fix-puppy-dbs: fix checking of pkgs on remote site

diff --git a/woof-code/support/fix-puppy-dbs b/woof-code/support/fix-puppy-dbs
--- a/woof-code/support/fix-puppy-dbs
+++ b/woof-code/support/fix-puppy-dbs
@@ -130,14 +130,26 @@ else
   do
    REMOTEURL="`echo "$PKG_DOCS_PET_REPOS" | tr ' ' '\n' | grep "$ONEREPO" | head -n 1 | cut -f 2 -d '|' | rev | cut -f 2-9 -d '/' | rev`"
    LOCALPKGS="`cat $ONEREPO`"
+   # http://distro.ibiblio.org/puppylinux/pet_packages-noarch/Pup-SysInfo-2.6.4.pet
+   SUBDIR=${ONEREPO//Packages-puppy/pet_packages} #pet_packages-noarch-official
+   SUBDIR=${SUBDIR%-official}                     #pet_packages-noarch
    echo "$LOCALPKGS" |
    while read ONELOCALPKG
    do
     SUBDIRECTORY="`echo -n "$ONELOCALPKG" | cut -f 7 -d '|'`"
+    if [ "$SUBDIRECTORY" ] ; then
+     SUBDIRECTORY=pet_packages-${SUBDIRECTORY}
+    else
+     SUBDIRECTORY=${SUBDIR}
+    fi
+    echo -n "${FULLPKGNAME}... "
     FULLPKGNAME="`echo -n "$ONELOCALPKG" | cut -f 8 -d '|'`"
-    wget -t 2 -T 20 --waitretry=20 --spider ${REMOTEURL}/${SUBDIRECTORY}/${FULLPKGNAME}
-    if [ $? -ne 0 ];then
-     echo; echo #clear #echo
+    wget -t 2 -T 20 --waitretry=20 --spider ${REMOTEURL}/${SUBDIRECTORY}/${FULLPKGNAME} 2>/dev/null
+    if [ $? -eq 0 ];then
+     echo "ok"
+    else
+     echo "error"
+     echo
      echo -e -n "\\033[1;31m" #red
      echo "WARNING, $FULLPKGNAME does not exist at $REMOTEURL"
      echo -e -n "\\033[0;39m" #back to black.
