support/fix-puppy-dbs: minor cleanup

diff --git a/woof-code/support/fix-puppy-dbs b/woof-code/support/fix-puppy-dbs
--- a/woof-code/support/fix-puppy-dbs
+++ b/woof-code/support/fix-puppy-dbs
@@ -1,15 +1,9 @@
 #!/bin/bash
 #(c) Copyright Barry Kauler June 2009
-#Woof has various Puppy db files, Packages-puppy-[2345]-official and one that is
-#for a specific compat-distro build -- for example, a compat-distro build based
-#on the Puppy 4.x series has file Packages-puppy-4xx-official (defined in DISTRO_PKGS_SPECS-puppy-4).
+#Woof has various Puppy db files, Packages-puppy-*-official
 #this script synchronises them all, including with the files at ibiblio.org...
-#111124 fix finding Packages-puppy-*-official.
 #111129 recommend not update db files with online entries.
-#120315 ignore if repo db file not wanted.
-#121102 file DISTRO_SPECS has new variable DISTRO_DB_SUBNAME. ex: for 14.0-based slacko, DISTRO_DB_SUBNAME=slacko14
 #121102 pet db file not only, use local file only.
-#130306 fix arch linux build.
 #-- this script executed in the main woof dir... --
 
 #db entry format: pkgname|nameonly|version|pkgrelease|category|size|path|fullfilename|dependencies|description|
@@ -25,29 +19,25 @@ export LANG=C
 . ./_00func
 . ./DISTRO_SPECS #has DISTRO_BINARY_COMPAT, DISTRO_COMPAT_VERSION
 . ./DISTRO_PET_REPOS
-[ ! "$DISTRO_DB_SUBNAME" ] && DISTRO_DB_SUBNAME="$DISTRO_COMPAT_VERSION" #121102 fallback if DISTRO_DB_SUBNAME not defined in file DISTRO_SPECS.
 source_compat_repos  # ./DISTRO_COMPAT_REPOS-
 source_pkgs_specs    # ./DISTRO_PKGS_SPECS-
 
 #find out if internet working...
-INTERNETWKG="no"
-PETREPO="`echo "$PKG_DOCS_PET_REPOS" | tr ' ' '\n' | head -n 1`"
-ONE_PET_SITE="`echo -n "$PETREPO" | cut -f 2 -d '|' | cut -f 3 -d '/'`"
-[ "`wget -t 2 -T 20 --waitretry=20 --spider -S $ONE_PET_SITE -o /dev/stdout 2>/dev/null | grep '200 OK'`" != "" ] && INTERNETWKG="yes"
+PKG_DOCS_PET_REPOS=$(echo "$PKG_DOCS_PET_REPOS" | tr ' ' '\n')
+ONE_PET_REPO="`echo "$PKG_DOCS_PET_REPOS" | head -n 1`"
+ONE_PET_SITE="`echo -n "$ONE_PET_REPO" | cut -f 2 -d '|' | cut -f 3 -d '/'`"
 
-if [ "$INTERNETWKG" = "no" ];then
- echo -e "\nInternet not working, so cannot check the Packages-puppy-* files with files at $REPOSITE"
+if ! ping -4 -c 1 $ONE_PET_SITE &>/dev/null ; then
+ echo -e "\nCannot check the Packages-puppy-* files with files at $REPOSITE"
  echo "Continuing with local checking only..."
+ exit
 fi
 
 #internet connected, check each of Packages-puppy-[2345]-official local against same file at ibiblio...
-#111124 fix...
-for ONEREPO in `find . -mindepth 1 -maxdepth 1 -name 'Packages-puppy-*-official' | rev | cut -f 1 -d '/' | rev | tr '\n' ' '`
+for ONEREPO in `find . -mindepth 1 -maxdepth 1 -name 'Packages-puppy-*-official' | sed 's|.*/||'`
 do
-  REMOTEREPO="`echo "$PKG_DOCS_PET_REPOS" | tr ' ' '\n' | grep "$ONEREPO" | head -n 1 | cut -f 2 -d '|'`"
-  if [ "$REMOTEREPO" = "" ];then
-   continue #120315 not an error. just not interested in this db file.
-  else
+   REMOTEREPO="`echo "$PKG_DOCS_PET_REPOS" | grep "/${ONEREPO}|" | head -n 1 | cut -f 2 -d '|'`"
+   [ "$REMOTEREPO" = "" ] && continue #not an error. just not interested in this db file.
    echo
    echo "Downloading ${ONEREPO}..."
    rm -f remotedbfile
@@ -106,7 +96,6 @@ do
     fi
    fi
    rm -f remotedbfile
-  fi
 done
 
-###END###
+### END ###
