probedisk: fix for optical/floppy usb devices + misc edits

diff --git a/woof-code/rootfs-skeleton/sbin/probedisk b/woof-code/rootfs-skeleton/sbin/probedisk
--- a/woof-code/rootfs-skeleton/sbin/probedisk
+++ b/woof-code/rootfs-skeleton/sbin/probedisk
@@ -14,18 +14,10 @@ case $1 in
 	-size) output=5 ; shift ;; # print only SIZE
 esac
 
-[ -e /proc/ide ] && PROCIDE=1
-
 device=${1##*/}
 
 if [ "$device" ] ; then
-	# process cli argument
-	if [ -b "/dev/$device" ] ; then
-		ALLDRVS=${device}
-	else
-		echo "${device}: invalid device" 1>&2
-		exit 1
-	fi
+	ALLDRVS=${device} #process cli argument
 else
 	if [ -f $HOME/.usb-drive-log-probedisk ] ; then #force /proc upate mechanism
 		while read ONEUSBDRV ; do
@@ -45,26 +37,39 @@ fi
 
 for DRV in ${ALLDRVS} ; do
 
+	if [ ! -b "/dev/$DRV" ] ; then
+		echo "${device}: invalid device" 1>&2
+		exit 1
+	fi
+
 	DRV=${DRV:0:3}
 	vendor=""
 	model=""
-	type="drive"
 	[ -f /sys/block/${DRV}/device/vendor ] && read -r vendor < /sys/block/${DRV}/device/vendor
 	[ -f /sys/block/${DRV}/device/model ] && read -r model < /sys/block/${DRV}/device/model
 	[ -f /sys/block/${DRV}/size ] && read -r size < /sys/block/${DRV}/size
 	info="$vendor $model"
+
 	case ${DRV} in
 		hd*) ## ide device, look in /proc/ide for info
 			[ -f /proc/ide/${DRV}/media ] && read -r media < /proc/ide/${DRV}/media
 			[ "$media" = "cdrom" ] && type="optical"
 			[ -f /proc/ide/${DRV}/model ] && read -r info < /proc/ide/${DRV}/model
 			;;
-		sd*) [ "$PROCIDE" ] && type=usbdrv ;; ## /proc/ide: usb drives appear as sdX)
+		sd*)
+			type=drive
+			[ -e /proc/ide ] && type=usbdrv ## /proc/ide: usb drives appear as sdX)
+			;;
+		mmc*) type=card    ; info="MMC/SD: $info" ;;
+		*)    type=unknown ;;
+	esac
+
+	readlink /sys/block/${DRV} | grep -q usb && type=usbdrv
+
+	case ${DRV} in
 		fd*)      type=floppy  ;;
 		scd*|sr*) type=optical ;; #scd*: probably old stuff
-		mmc*)     type=card ; info="MMC/SD: $info" ;;
 	esac
-	readlink /sys/block/${DRV} | grep -q usb && type=usbdrv
 
 	## Legacy stuff
 	if [ "$type" = "usbdrv" ] ; then
