probedisk: improvements

diff --git a/woof-code/rootfs-skeleton/sbin/probedisk b/woof-code/rootfs-skeleton/sbin/probedisk
--- a/woof-code/rootfs-skeleton/sbin/probedisk
+++ b/woof-code/rootfs-skeleton/sbin/probedisk
@@ -14,12 +14,18 @@ case $1 in
 	-size) output=5 ; shift ;; # print only SIZE
 esac
 
-device=${1##*/}
 [ -e /proc/ide ] && PROCIDE=1
 
-if [ -b "/dev/$device"  ] ; then
+device=${1##*/}
+
+if [ "$device" ] ; then
 	# process cli argument
-	ALLDRVS=${device}
+	if [ -b "/dev/$device" ] ; then
+		ALLDRVS=${device}
+	else
+		echo "${device}: invalid device" 1>&2
+		exit 1
+	fi
 else
 	if [ -f $HOME/.usb-drive-log-probedisk ] ; then #force /proc upate mechanism
 		while read ONEUSBDRV ; do
@@ -39,6 +45,7 @@ fi
 
 for DRV in ${ALLDRVS} ; do
 
+	DRV=${DRV:0:3}
 	vendor=""
 	model=""
 	type="drive"
