probedisk: proper drive validation
 @woodenshoe-wi might want to this and pmount as well...

diff --git a/woof-code/rootfs-skeleton/sbin/probedisk b/woof-code/rootfs-skeleton/sbin/probedisk
--- a/woof-code/rootfs-skeleton/sbin/probedisk
+++ b/woof-code/rootfs-skeleton/sbin/probedisk
@@ -5,6 +5,13 @@
 #v3.93 10 dec 2007 BK: updated for 2.6.24 kernel, no /dev/hd*.
 #v406 support for old kernel, /proc/ide, /dev/hd*.
 
+## MMC - SD cards
+#  Some laptops with built in SD card readers report SD cards as /dev/sd* and usb
+#    /sys/block/sdb -> ../devices/pci0000:00/0000:00:1d.7/usb1/1-8/1-8:1.0/host6/target6:0:0/6:0:0:0/block/sdb
+#  Raspberry Pi
+#    /sys/block/mmcblk0 -> ../devices/platform/soc/3f202000.sdhost/mmc_host/mmc0/mmc0:aaaa/block/mmcblk0
+
+
 usage() {
 	echo "probedisk - show information about drives
 
@@ -87,12 +94,11 @@ fi
 
 for DRV in ${ALLDRVS} ; do
 
-	if [ ! -b "/dev/$DRV" ] ; then
-		echo "${device}: invalid device" 1>&2
+	if [ ! -e /sys/block/${DRV} -a ! -e /proc/ide/${DRV} ] ; then
+		echo "${DRV}: invalid drive" 1>&2
 		continue
 	fi
 
-	DRV=${DRV:0:3}
 	UUID_STR=""
 	PTABLE_STR=""
 
