improve 9fcb3c63965f1ab8c3063dc17206cd150c8ff01a

diff --git a/woof-code/rootfs-skeleton/sbin/probedisk b/woof-code/rootfs-skeleton/sbin/probedisk
--- a/woof-code/rootfs-skeleton/sbin/probedisk
+++ b/woof-code/rootfs-skeleton/sbin/probedisk
@@ -94,9 +94,11 @@ fi
 
 for DRV in ${ALLDRVS} ; do
 
-	if [ ! -e /sys/block/${DRV} -a ! -e /proc/ide/${DRV} ] ; then
-		echo "${DRV}: invalid drive" 1>&2
-		continue
+	if [ "$CLI_ARG" != "" ] ; then
+		if [ ! -e /sys/block/${DRV} -a ! -e /proc/ide/${DRV} ] ; then
+			echo "${DRV}: invalid drive" 1>&2
+			continue
+		fi
 	fi
 
 	UUID_STR=""
