mount: (ntfs) don't override '-o ...'

diff --git a/woof-code/rootfs-skeleton/bin/mount b/woof-code/rootfs-skeleton/bin/mount
--- a/woof-code/rootfs-skeleton/bin/mount
+++ b/woof-code/rootfs-skeleton/bin/mount
@@ -77,53 +77,61 @@ elif [ "$LUKS_FLAG" = "yes" ] ; then
   exec mount.crypto_LUKS "$@" #mount.crypto_LUKS has specific rox code
 
 elif [ "$NTFS_FLAG" = "yes" ];then
- #screen out all the options...
- CMDPRMS="`echo -n "$*" | tr '\t' ' ' | tr -s ' ' | tr ' ' '\n' | grep '^/' | tr '\n' ' '`"
- #kirk advised these options so Rox will not complain about file
- #permissions when copy a file to a ntfs partition...
- [ -f /tmp/ntfsmnterr${MYPID}.txt ] && rm -f /tmp/ntfsmnterr${MYPID}.txt
- ntfs-3g $CMDPRMS -o ${USER_OTPS}silent 2>/tmp/ntfsmnterr${MYPID}.txt
- RETVAL=$?
- #v2.16 ntfs-3g v1.417, part. scheduled for check, failed with value 10...
- #v4.00 ntfs-3g v1.2412 does not have 4,10, has 15 for dirty f.s., 14 hiberneted...
- case $RETVAL in 4|10|15) #14 = must mount read-only
-   ntfs-3g $CMDPRMS -o ${USER_OTPS}force,silent 2>/tmp/ntfsmnterr${MYPID}.txt
-   RETVAL=$?
-   ERRMSG1="`cat /tmp/ntfsmnterr${MYPID}.txt`"
-   echo "$ERRMSG1"
-   if [ $RETVAL -eq 0 ];then
-    echo "WARNING: NTFS f.s. mounted read/write but corrupted."
-    [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
+  case "$@" in
+    *"-o "*) #don't override -o
+      ntfs-3g "${@}" || busybox mount "${@}"
+      RETVAL=$?
+      ;;
+    *)
+      #screen out all the options...
+      CMDPRMS="`echo -n "$*" | tr '\t' ' ' | tr -s ' ' | tr ' ' '\n' | grep '^/' | tr '\n' ' '`"
+      #kirk advised these options so Rox will not complain about file
+      #permissions when copy a file to a ntfs partition...
+      [ -f /tmp/ntfsmnterr${MYPID}.txt ] && rm -f /tmp/ntfsmnterr${MYPID}.txt
+      ntfs-3g $CMDPRMS -o ${USER_OTPS}silent 2>/tmp/ntfsmnterr${MYPID}.txt
+      RETVAL=$?
+      #v2.16 ntfs-3g v1.417, part. scheduled for check, failed with value 10...
+      #v4.00 ntfs-3g v1.2412 does not have 4,10, has 15 for dirty f.s., 14 hiberneted...
+      case $RETVAL in 4|10|15) #14 = must mount read-only
+        ntfs-3g $CMDPRMS -o ${USER_OTPS}force,silent 2>/tmp/ntfsmnterr${MYPID}.txt
+        RETVAL=$?
+        ERRMSG1="`cat /tmp/ntfsmnterr${MYPID}.txt`"
+        echo "$ERRMSG1"
+        if [ $RETVAL -eq 0 ];then
+         echo "WARNING: NTFS f.s. mounted read/write but corrupted."
+         [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was able to mount the NTFS
 partition but returned this error message:
 $ERRMSG1
 
 It is mounted read/write, but advice is only write
 to it in emergency situation. Recommendation is
 boot Windows and fix the filesystem first!!!" &
-   fi
-  [ ! -s /tmp/ntfsmnterr${MYPID}.txt ] && rm -f /tmp/ntfsmnterr${MYPID}.txt
-  ;;
- esac
+        fi
+       [ ! -s /tmp/ntfsmnterr${MYPID}.txt ] && rm -f /tmp/ntfsmnterr${MYPID}.txt
+       ;;
+      esac
  
- #ntfs-3g plays very safe and will not mount if thinks anything
- #wrong with ntfs f.s. But, we may want to recover files from a
- #damaged windows. So, fall back to the kernel ntfs driver...
- if [ ! $RETVAL -eq 0 ];then
-  #mount read-only...
-  busybox mount -r -t ntfs $CMDPRMS
-  RETVAL=$?
-  ERRMSG1="`cat /tmp/ntfsmnterr${MYPID}.txt`"
-  echo "$ERRMSG1"
-  if [ $RETVAL -eq 0 ];then
-   echo "WARNING: NTFS f.s. mounted read-only."
-   [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
+      #ntfs-3g plays very safe and will not mount if thinks anything
+      #wrong with ntfs f.s. But, we may want to recover files from a
+      #damaged windows. So, fall back to the kernel ntfs driver...
+      if [ ! $RETVAL -eq 0 ];then
+       #mount read-only...
+       busybox mount -r -t ntfs $CMDPRMS
+       RETVAL=$?
+       ERRMSG1="`cat /tmp/ntfsmnterr${MYPID}.txt`"
+       echo "$ERRMSG1"
+       if [ $RETVAL -eq 0 ];then
+        echo "WARNING: NTFS f.s. mounted read-only."
+        [ ! "`pidof X`" = "" ] && nohup gxmessage -bg red -center -title "NTFS WARNING" "The ntfs-3g driver was unable to mount the NTFS
 partition and returned this error message:
 $ERRMSG1
 
 So, the inbuilt kernel NTFS driver has been used
 to mount the partition read-only." &
-  fi
- fi
+       fi
+      fi
+      ;;
+  esac
 
 ### everything else ###
 else
