Exfat support for older mount versions

diff --git a/woof-code/rootfs-skeleton/bin/mount b/woof-code/rootfs-skeleton/bin/mount
--- a/woof-code/rootfs-skeleton/bin/mount
+++ b/woof-code/rootfs-skeleton/bin/mount
@@ -28,8 +28,12 @@ MYPID=${$}
 #v3.93 eliminate ' -- ' and all past it...
 DASHOPTS="`echo "$*" | tr '\t' ' '  | sed -e 's/ -- .*//' | tr ' ' '\n' | grep '^\-'`"
 
+#exfat systems fail with mount-FULL -n
+if [ "`echo "$*" | grep 'exfat'`" != "" ];then
+  mount-FULL "${@}"
+  RETVAL=$?
 #needs an explicit '-t ntfs', does not work with /etc/fstab...
-if [ "`echo "$*" | grep 'ntfs'`" = "" ];then
+elif [ "`echo "$*" | grep 'ntfs'`" = "" ];then
 
  # #busybox mount does not support '--bind'
  # #as have mtab file (see below), can now use full mount...
