Suppress spinning in github actions when the answers to questions are unsatisfactory.

diff --git a/merge2out b/merge2out
--- a/merge2out
+++ b/merge2out
@@ -1,6 +1,9 @@
 #!/bin/bash
 #BK nov. 2011
 
+# spun for 6 hours in git actions, asking for an architecture
+# https://github.com/JamesC1/woof-CE/runs/3454321862?check_suite_focus=true
+
 WOOF_VERSION=9
 
 [ -n "$GITPOD_WORKSPACE_ID" -a "`id -u`" -ne 0 ] && exec fakeroot $0 "$@"
@@ -44,6 +47,17 @@ echo 'This script merges woof-arch, woof-code
 woof-distro, kernel-kit and initrd-progs to ../woof-out_*.
 See README.md
 '
+
+testToGiveUp() {
+	# Presumes a global variable TRIES, which is reset to 0 by a surrounding loop
+	TRIES=$(($TRIES + 1))
+	if [ $TRIES -gt 10 ]]; then
+		echo "Error: asked the question too many times; giving up; exiting ..."
+		exit 1
+        fi
+}
+
+
 # autodetect HOSTARCH - how hard can it be?
 case `uname -m` in
 	i?86)HOSTARCH=x86 ;;
@@ -57,7 +71,9 @@ echo "-----------------"
 echo
 echo "Please choose the target architecture.. (the target
 is the machine in which the Puppy that you build is going to run):"
+TRIES=0
 while [ "$TARGETARCH" = "" ] ; do
+	testToGiveUp
 	echo
 	CNT=1
 	for ONEARCH in `find woof-distro -mindepth 1 -maxdepth 1 -type d | sed -e 's%^woof-distro/%%' | sort | tr '\n' ' '`
@@ -74,7 +90,9 @@ echo
 
 echo 'Woof builds a Puppy based on the binary packages from another distro.
 We sometimes refer to this as the "compat-distro".'
+TRIES=0
 while [ "$COMPATDISTRO" = "" ] ; do
+	testToGiveUp
 	echo
 	CNT=1
 	taPTN="s%^woof-distro/${TARGETARCH}/%%"
@@ -92,7 +110,9 @@ echo
 
 echo 'The compat-distro usually has release versions
 Choose which release you want to obtain the binary packages from.'
+TRIES=0
 while [ "$COMPATVERSION" = "" ] ; do
+	testToGiveUp
 	echo
 	CNT=1
 	for ONECOMPAT in `find woof-distro/${TARGETARCH}/${COMPATDISTRO} -maxdepth 1 -mindepth 1 -type d | rev | cut -f 1 -d '/' | rev | sort | tr '\n' ' '`
