merge2out: reduce some text

diff --git a/merge2out b/merge2out
--- a/merge2out
+++ b/merge2out
@@ -6,32 +6,24 @@
 CURDIR="`pwd`"
 
 echo
-echo 'This script merges woof-arch, woof-code and woof-distro, to ../woof-out_*.
+echo 'This script merges woof-arch, woof-code
+woof-distro, kernel-kit and initrd-progs to ../woof-out_*.
 
-woof-arch:  architecture-dependent (x86, arm) files, mostly binary executables.
-woof-code:  the core of Woof. Mostly scripts.
-woof-distro: distro-configuration (Debian, Slackware, etc.) files.
-kernel-kit: puppy-kernel build script and configuration files
-initrd-progs: script to generate the initial ramdisk
-
-Important: the host architecture is distinct from the target architecture.
-The host is the machine you are running Woof on, the target is the machine
-in which the Puppy that you build is going to run. Typically, you will build
-on a x86 machine, and the target may be x86 or arm.'
-echo
+See README
+'
 # autodetect HOSTARCH - how hard can it be?
-preHOSTARCH=`uname -m`
-case $preHOSTARCH in
+case `uname -m` in
 	i?86)HOSTARCH=x86 ;;
 	x86_64|amd64)HOSTARCH=x86_64 ;;
 	arm*)HOSTARCH=arm ;;
+	*) echo "Error detecting host architecture, exiting..." ; exit 1 ;;
 esac
-echo --------------------------------------------------------------------------
-echo "***     We have determined that your host architecture is $HOSTARCH    ***"
-echo --------------------------------------------------------------------------
+echo "-----------------"
+echo "Host arch: $HOSTARCH     (The host is the machine you are running Woof on)"
+echo "-----------------"
 echo
-
-echo "Please choose the target target architecture.."
+echo "Please choose the target target architecture..
+(the target is the machine in which the Puppy that you build is going to run):"
 while [ "$TARGETARCH" = "" ] ; do
 	echo
 	CNT=1
