askpass: improvements
- exit silently if 'sudo -A' is not found in `busybox ps`
- title: 'sudo <app>'
- text: 'Enter password for user: xxx'

diff --git a/woof-code/rootfs-skeleton/usr/sbin/askpass b/woof-code/rootfs-skeleton/usr/sbin/askpass
--- a/woof-code/rootfs-skeleton/usr/sbin/askpass
+++ b/woof-code/rootfs-skeleton/usr/sbin/askpass
@@ -8,16 +8,20 @@ export OUTPUT_CHARSET=UTF-8
 PS="`busybox ps`"
 APP=`echo "$PS" | grep 'sudo -A' | tail -n 1 | sed 's%.*sudo -A %%'`
 
-INSERTMSG="$(gettext 'Enter the administrator password:')"
+if ! [ "$APP" ] ; then
+	exit
+fi
 
-if [ $,DISPLAY ];then
- ADMINPASSWORD=$(/usr/lib/gtkdialog/box_passwd "${APP%% *}" "Run: $(echo "$APP" | cut -f1-2 -d ' ')" "$INSERTMSG")
+INSERTMSG="$(gettext 'Enter password for user ')'$(whoami)':"
+
+if [ $DISPLAY ];then
+	ADMINPASSWORD=$(/usr/lib/gtkdialog/box_passwd "sudo: ${APP%% *}" "Run: $(echo "$APP" | cut -f1-2 -d ' ')" "$INSERTMSG")
 else
- echo >/dev/console
- echo "App to run: $(echo "$APP" | cut -f1-4 -d ' ')" >/dev/console
- echo -n "$INSERTMSG " >/dev/console
- read -t 30 ADMINPASSWORD
- [ "$ADMINPASSWORD" = "" ] && echo '...failed' >/dev/console
+	echo >/dev/console
+	echo "App to run: $(echo "$APP" | cut -f1-4 -d ' ')" >/dev/console
+	echo -n "$INSERTMSG " >/dev/console
+	read -t 30 ADMINPASSWORD
+	[ "$ADMINPASSWORD" = "" ] && echo '...failed' >/dev/console
 fi
 
 echo "$ADMINPASSWORD" #return password to sudo.
