bootflash: misc fixes (it's still broken)

diff --git a/woof-code/rootfs-skeleton/usr/sbin/bootflash b/woof-code/rootfs-skeleton/usr/sbin/bootflash
--- a/woof-code/rootfs-skeleton/usr/sbin/bootflash
+++ b/woof-code/rootfs-skeleton/usr/sbin/bootflash
@@ -8,11 +8,21 @@
 #110130 fix for ldlinux.sys deleted, see jinx100 http://murga-linux.com/puppy/viewtopic.php?t=63719&start=165
 #110505 support sudo for non-root user.
 #120201 rodin.s: internationalized.
-#120311 ComboFormat, 128M first partition not big enough for some puppies, change to 256M.
-#120323 replace 'xmessage' with 'pupmessage'.
+#120311 ComboFormat, 128M first partition not big enough for some puppies, change to 512M.
 #130722 new method to update desktop drive icons. see also /usr/sbin/gparted_shell, puppyinstaller.
 
+#
+# interesting values for fdisk:
+#    https://www.win.tue.nl/~aeb/partitions/partition_types-1.html
+#
+
 [ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505
+
+#exec &>/tmp/${0##*/}.log ; set -x ; env #debug
+
+if ! which makebootfat 2>/dev/null ; then
+	exit 1
+fi
 
 export TEXTDOMAIN=bootflash
 export OUTPUT_CHARSET=UTF-8
@@ -48,7 +58,7 @@ BootFlash will format the USB drive so that it is bootable, then will offer to i
 You could use the Puppy Universal Installer, however it is a piece of cake to do it manually. When a new version of Puppy is released, download the live-CD iso file, then just click on it to open it. Drag the files vmlinuz, initrd.gz and puppy.sfs (and ardv, ydrf, fdrv and zdrv.sfs if they  exist) (some builds of Puppy have different names for these files, for example: wary_092.sfs and zw092345.sfs) to the USB drive, and that is it, you have upgraded!
 It is super-simple, but just a warning: if there are files of an old installation, for example wary_091.2fs and zw091346.sfs, just delete those.
 
-WARNING: There is one caveat to the above. Be careful before deleting the old puppy.sfs that it is not in use by Puppy. If the PC has 256MB or more of RAM, Puppy will normally copy puppy.sfs into RAM, so the original is not being used and can be deleted. To find out, open a terminal and type <i>losetup</i> -- if you see something like /mnt/tmpfs/puppy.sfs then it is in RAM. If not, or uncertain, boot another Puppy from a different drive/CD.
+WARNING: There is one caveat to the above. Be careful before deleting the old puppy.sfs that it is not in use by Puppy. If the PC has 512MB or more of RAM, Puppy will normally copy puppy.sfs into RAM, so the original is not being used and can be deleted. To find out, open a terminal and type <i>losetup</i> -- if you see something like /mnt/tmpfs/puppy.sfs then it is in RAM. If not, or uncertain, boot another Puppy from a different drive/CD.
 
 <b>Puppy Universal Installer</b>
 This is a tool for installing Puppy to any media, including USB. BootFlash is an alternative tool specific to USB and for new installations only. You might want to try the Universal Installer first, and if you cannot get the drive to boot then try BootFlash.
@@ -163,48 +173,46 @@ esac
 
 #decide what drive...
 if [ "$USBDRV" = "" ];then
- /usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'OK')" --no-label "$(gettext 'Cancel')" "BootFlash" \
-  "$(gettext '<b>Please plugin the USB drive right now. If it is already plugged in, make absolutely sure that it is unmounted before continuing</b>')" \
-  "$(gettext 'Note, it does not matter if you have other USB drives or devices plugged in, as the next dialog window will present them all and ask you to choose one.')" \
-  "$(gettext 'Click 'OK' to continue, 'Cancel' to quit:')"
- [ $? -ne 0 ] && exit
- sleep 2
- probedisk -extended-usb -plus-size | grep usbflash | sed 's|/dev/||' | while read USBINFO
- do
-   IFS="|" read -r ONEUSB USBTYPE USBINFO USBSIZE <<< "$USBINFO"
-   USBSIZE=$(filesize -bytes=512 -2 $USBSIZE)
-   echo "$ONEUSB \"Flash memory, ${USBINFO}, ${USBSIZE}\""
- done > /tmp/xselections$$
- xSELECTIONS="`cat /tmp/xselections$$ | tr '\n' ' ' | tr -s ' '`"
- rm -f /tmp/xselections$$
- if [ "(echo $SELECTIONS)" = "" ];then
-  /usr/lib/gtkdialog/box_ok "Bootflash" error "$(gettext 'No USB drive plugged in')"
-  exit
- fi
- CHOOSEDLG="Xdialog --wmclass \"gtkdialog2\" --title \"$(gettext 'BootFlash: choose drive')\" --no-cancel --stdout --menubox \"$(gettext 'Choose which drive to format:')\" 10 60 0 ${xSELECTIONS}"
- DRVSEL="`eval "$CHOOSEDLG"`"
- [ $? -ne 0 ] && exit
- [ "$DRVSEL" = "" ] && exit #precaution.
- [ "`echo -n "$DRVSEL" | cut -c 1,2`" != "sd" ] && exit #precaution.
- USBDRV="$DRVSEL"
- #reconfirm correct drv choice...
- MYSELECTION="`echo "$SELECTIONS" | grep "^${USBDRV} " | tr '"' ' ' | tr -s ' '`" #'geany
- /usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'OK')" --no-label "$(gettext 'Cancel')" "BootFlash" \
-  "$(gettext 'Please reconfirm that this is the USB drive that you want to format:')" \
-  "<b>${MYSELECTION}</b>" \
-  "`gettext "Please also reconfirm that you want to use BootFlash to reformat the drive (and install Puppy). If you have a new USB drive, it is normally recommended that you use the Puppy Universal Installer first, as that will attempt to make the drive bootable as-is, that is, without reformatting it. If you haven't tried the Universal Installer yet, recommend that you hit Cancel here, and run the Universal Installer from the Setup menu."`" \
-  "`gettext "Click 'OK' to continue, 'Cancel' to quit:"`"
- [ $? -ne 0 ] && exit
+	/usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'OK')" --no-label "$(gettext 'Cancel')" "BootFlash" \
+	"$(gettext '<b>Please plugin the USB drive right now. If it is already plugged in, make absolutely sure that it is unmounted before continuing</b>')" \
+	"$(gettext 'Note, it does not matter if you have other USB drives or devices plugged in, as the next dialog window will present them all and ask you to choose one.')" \
+	"$(gettext 'Click 'OK' to continue, 'Cancel' to quit:')"
+	[ $? -ne 0 ] && exit
+	probedisk -extended-usb -plus-size | grep usbflash | sed 's|/dev/||' | \
+	while read USBINFO
+	do
+		IFS="|" read -r ONEUSB USBTYPE USBINFO USBSIZE <<< "$USBINFO"
+		USBSIZE=$(filesize -bytes=512 -2 $USBSIZE)
+		echo "$ONEUSB \"Flash memory, ${USBINFO}, ${USBSIZE}\""
+	done > /tmp/xselections$$
+	xSELECTIONS="`cat /tmp/xselections$$ | tr '\n' ' ' | tr -s ' '`"
+	rm -f /tmp/xselections$$
+	if [ "(echo $SELECTIONS)" = "" ];then
+		/usr/lib/gtkdialog/box_ok "Bootflash" error "$(gettext 'No USB drive plugged in')"
+		exit
+	fi
+	CHOOSEDLG="Xdialog --wmclass \"gtkdialog2\" --title \"$(gettext 'BootFlash: choose drive')\" --no-cancel --stdout --menubox \"$(gettext 'Choose which drive to format:')\" 10 60 0 ${xSELECTIONS}"
+	DRVSEL="`eval "$CHOOSEDLG"`"
+	[ $? -ne 0 ] && exit
+	USBDRV="$DRVSEL"
+	#reconfirm correct drv choice...
+	MYSELECTION="`echo "$SELECTIONS" | grep "^${USBDRV} " | tr '"' ' ' | tr -s ' '`" #'geany
+	/usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'OK')" --no-label "$(gettext 'Cancel')" "BootFlash" \
+	"$(gettext 'Please reconfirm that this is the USB drive that you want to format:')" \
+	"<b>${MYSELECTION}</b>" \
+	"`gettext "Please also reconfirm that you want to use BootFlash to reformat the drive (and install Puppy). If you have a new USB drive, it is normally recommended that you use the Puppy Universal Installer first, as that will attempt to make the drive bootable as-is, that is, without reformatting it. If you haven't tried the Universal Installer yet, recommend that you hit Cancel here, and run the Universal Installer from the Setup menu."`" \
+	"`gettext "Click 'OK' to continue, 'Cancel' to quit:"`"
+	[ $? -ne 0 ] && exit
 fi
 
 #make sure not mounted...
 while [ "`mount | grep "^/dev/$DRVSEL "`" != "" ];do
- /usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'OK')" --no-label "$(gettext 'Cancel')" "BootFlash" \
-  "$(printf "$(gettext '<b>Drive %s is still mounted. Please unmount it before continuing. If the drive has multiple partitions, are they all unmounted?</b>')" "${DRVSEL}")" \
-  "$(gettext 'Note: click on the appropriate mounted desktop drive icon, and you will receive an offer to unmount it.')" \
-  "$(gettext 'Click 'OK' to continue, 'Cancel' to quit:')"
- [ $? -ne 0 ] && exit
- sleep 1
+	/usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'OK')" --no-label "$(gettext 'Cancel')" "BootFlash" \
+	"$(printf "$(gettext '<b>Drive %s is still mounted. Please unmount it before continuing. If the drive has multiple partitions, are they all unmounted?</b>')" "${DRVSEL}")" \
+	"$(gettext 'Note: click on the appropriate mounted desktop drive icon, and you will receive an offer to unmount it.')" \
+	"$(gettext 'Click 'OK' to continue, 'Cancel' to quit:')"
+	[ $? -ne 0 ] && exit
+	sleep 1
 done
 
 #======================================================================
@@ -215,10 +223,12 @@ done
 rm -rf /tmp/makebootfat 2>/dev/null
 mkdir /tmp/makebootfat
 cd /tmp/makebootfat
-cp -a /usr/lib/syslinux/ldlinux.bss ./
-cp -a /usr/lib/syslinux/mbrfat.bin ./
-cp -a /usr/lib/syslinux/mbr.bin ./
-cp -a /usr/lib/syslinux/ldlinux.sys ./
+dir=/usr/share/syslinux
+[ -f /usr/lib/syslinux/mbrfat.bin ] && dir=/usr/lib/syslinux
+cp -a ${dir}/ldlinux.bss ./
+cp -a ${dir}/mbrfat.bin ./
+cp -a ${dir}/mbr.bin ./
+cp -a ${dir}/ldlinux.sys ./
 mkdir tempdir
 
 /usr/lib/gtkdialog/box_splash -close never -text "$(printf "$(gettext 'Please wait, formatting %s drive...')" "${USBDRV}")" &
@@ -235,22 +245,31 @@ if [ "$RADIO_HDD" = "true" ];then #hard drive.
 	makebootfat -v --output /dev/$USBDRV --syslinux3 --boot ldlinux.bss \
 		--mbr mbr.bin --copy ldlinux.sys tempdir
 	#...but drive broken, fix as follows...
-
 	#zeroise first 512 bytes of partition. some apps need this.
 	dd if=/dev/zero of=/dev/${USBDRV}1 bs=512 count=1
-
-	DRVSIZEB=`fdisk -l /dev/${USBDRV} | grep '^Disk /dev/' | cut -f 5 -d ' '` #in bytes.
+	sync
+	DRVSIZEB=$(probedisk -size ${USBDRV} | cut -f 2 -d '|')
+	DRVSIZEB=$(($DRVSIZEB * 512))
 	DRVSIZEK=$(($DRVSIZEB / 1024))
 	DRVSIZEM=$(($DRVSIZEK / 1024))
 	sync
+#	mkdosfs /dev/${USBDRV}1 || mkdosfs -S 2048 /dev/${USBDRV}1 #FAT32.  -n puppysave
 	if [ $DRVSIZEM -gt 1024 ];then #1GB
-	  #set partition-id to fat32 (0b=fat32, oc=fat32-lba)...
-	  echo -e 't\n0b\nw' | fdisk /dev/$USBDRV
-	  mkdosfs -F 32 /dev/${USBDRV}1 || mkdosfs -F 32 -S 2048 /dev/${USBDRV}1 #FAT32.  -n puppysave
+		#set partition-id to fat32 (0b=fat32, oc=fat32-lba)...
+		(
+		echo t  # change a partition type
+		echo 0b # 0b WIN95 OSR2 FAT32
+		echo w  # write
+		) | fdisk /dev/$USBDRV
+		mkdosfs -F 32 /dev/${USBDRV}1 || mkdosfs -F 32 -S 2048 /dev/${USBDRV}1 #FAT32.  -n puppysave
 	else
-	  #set partition-id to fat16 (06=fat16, 0e=fat16-lba)...
-	  echo -e 't\n06\nw' | fdisk /dev/$USBDRV
-	  mkdosfs -F 16 /dev/${USBDRV}1 || mkdosfs -F 16 -S 2048 /dev/${USBDRV}1 #FAT16.  -n puppysave
+		#set partition-id to fat16 (06=fat16, 0e=fat16-lba)...
+		(
+		echo t  # change a partition type
+		echo 06 # DOS 3.31+ 16-bit FAT (over 32M)
+		echo w  # write
+		) | fdisk /dev/$USBDRV
+		mkdosfs -F 16 /dev/${USBDRV}1 || mkdosfs -F 16 -S 2048 /dev/${USBDRV}1 #FAT16.  -n puppysave
 	fi
 	sync
 	#110130 fix for ldlinux.sys wiped... note, i am uncertain how this hack makes any difference...
@@ -258,7 +277,13 @@ if [ "$RADIO_HDD" = "true" ];then #hard drive.
 	sync
 	syslinux /dev/${USBDRV}1
 	#um, it may still need to have the boot flag set...
-	[ "`fdisk -l /dev/$USBDRV | grep '/dev/.* \\* '`" = "" ] && echo -e 'a\n1\nw' | fdisk /dev/$USBDRV
+	if [ "`fdisk -l /dev/$USBDRV | grep '/dev/.* \\* '`" = "" ] ; then
+		(
+		echo a # toggle bootable flag
+		echo 1 # set flag
+		echo w # write
+		) | fdisk /dev/$USBDRV
+	fi
 	#one big fat partition, pup_save will be in it too...
 	PUPSAVEPART="${USBDRV}1"
 	PUPBOOTPART="${USBDRV}1"
@@ -275,87 +300,111 @@ elif [ "$RADIO_FDD" = "true" ];then #only choose this for drives no greater than
 
 else
 
-	#need space for 256MB image...
+	#need space for 512MB image...
 	WKGPATH="/tmp"
 	FREEM=`df -m | grep ' /tmp$' | tr -s ' ' | cut -f 4 -d ' '`
 	[ ! $FREEM ] && FREEM=0
-	if [ $FREEM -lt 300 ];then
-	  WKGPATH="/root"
-	  FREEM=`df -m | grep ' /$' | tr -s ' ' | cut -f 4 -d ' '`
-	  if [ $FREEM -lt 300 ];then
-	    WKGPATH="`readlink /mnt/home`"
-	    mhPATTERN=' '"$WKGPATH"'$'
-	    FREEM=`df -m | grep "$mhPATTERN" | tr -s ' ' | cut -f 4 -d ' '`
-	  fi
+	if [ $FREEM -lt 550 ];then
+		WKGPATH="/root"
+		FREEM=`df -m | grep ' /$' | tr -s ' ' | cut -f 4 -d ' '`
+		if [ $FREEM -lt 550 ];then
+			WKGPATH="`readlink /mnt/home`"
+			mhPATTERN=' '"$WKGPATH"'$'
+			FREEM=`df -m | grep "$mhPATTERN" | tr -s ' ' | cut -f 4 -d ' '`
+		fi
 	fi
-	if [ $FREEM -lt 300 ];then
-	  kill $X1PID
-	  /usr/lib/gtkdialog/box_ok "Bootflash" error "$(gettext "Can't find 256MB free working space")"
-	  exit
+	if [ $FREEM -lt 550 ];then
+		kill $X1PID
+		/usr/lib/gtkdialog/box_ok "Bootflash" error "$(gettext "Can't find 512MB free working space")"
+		exit
 	fi
 
 	if [ "$RADIO_ISO" = "true" ];then
-	  #need puppy.iso to copy to usb drive...
-	  kill $X1PID
-	  SRCFPATH="`Xdialog --wrap --wmclass "gtkdialog2" --left --backtitle "$(gettext "The 'ISO9660' choice requires the Puppy .iso file to be written directly into the USB drive. Please select it then click 'OK':")" --title "BootFlash: ISO9660 format" --stdout --no-buttons --no-cancel --fselect "*.iso" 0 0`"
-	  [ $? -ne 0 ] && exit
-	  /usr/lib/gtkdialog/box_splash -close never -text "$(gettext 'Please wait, copying .iso file...')" &
-	  X1PID=$!
-	  rm -f $WKGPATH/image256m 2>/dev/null
-	  cp -f "$SRCFPATH" $WKGPATH/image256m
-	  sync
-	  isohybrid $WKGPATH/image256m
-	  sync
-	  PUPSAVEPART="${USBDRV}2"
-	  PUPBOOTPART="${USBDRV}1"
+		#need puppy.iso to copy to usb drive...
+		kill $X1PID
+		SRCFPATH="`Xdialog --wrap --wmclass "gtkdialog2" --left --backtitle "$(gettext "The 'ISO9660' choice requires the Puppy .iso file to be written directly into the USB drive. Please select it then click 'OK':")" --title "BootFlash: ISO9660 format" --stdout --no-buttons --no-cancel --fselect "*.iso" 0 0`"
+		[ $? -ne 0 ] && exit
+		/usr/lib/gtkdialog/box_splash -close never -text "$(gettext 'Please wait, copying .iso file...')" &
+		X1PID=$!
+		rm -f $WKGPATH/image512m 2>/dev/null
+		cp -f "$SRCFPATH" $WKGPATH/image512m
+		sync
+		isohybrid $WKGPATH/image512m
+		sync
+		PUPSAVEPART="${USBDRV}2"
+		PUPBOOTPART="${USBDRV}1"
 	else
-	  #create 256M empty file...
-	  dd if=/dev/zero of=${WKGPATH}/image256m bs=1024 count=524288 #256MB 131072=128MB
-	  sync
-	  LOOPDEV="`losetup -f`"
-	  losetup $LOOPDEV ${WKGPATH}/image256m
-	  if [ "$RADIO_ALL" = "true" ];then #ComboFormat
-	    makebootfat --output $LOOPDEV --syslinux3 --zip --boot ldlinux.bss --mbr mbrfat.bin --mbrfat --copy ldlinux.sys tempdir
-	    #'--zip' sets partition-4 as bootable, so pup_save will go into partition-1...
-	    PUPSAVEPART="${USBDRV}1"
-	    PUPBOOTPART="${USBDRV}4"
-	  fi
-	  if [ "$RADIO_ZIP" = "true" ];then
-	    #take out '--mbrfat' has partition but makes look like floppy drive.
-	    makebootfat --output $LOOPDEV --syslinux3 --zip --boot ldlinux.bss --mbr mbrfat.bin --copy ldlinux.sys tempdir
-	    #'--zip' sets partition-4 as bootable, so pup_save will go into partition-1...
-	    PUPSAVEPART="${USBDRV}1"
-	    PUPBOOTPART="${USBDRV}4"
-	  fi
-	  sync
-	  losetup -d $LOOPDEV
+		#create 512M empty file...
+		dd if=/dev/zero of=${WKGPATH}/image512m bs=1024 count=524288 #512MB 131072=128MB
+		sync
+		LOOPDEV="`losetup -f`"
+		losetup $LOOPDEV ${WKGPATH}/image512m
+		if [ "$RADIO_ALL" = "true" ];then #ComboFormat
+			makebootfat --output $LOOPDEV --syslinux3 --zip --boot ldlinux.bss --mbr mbrfat.bin --mbrfat --copy ldlinux.sys tempdir
+			#'--zip' sets partition-4 as bootable, so pup_save will go into partition-1...
+			PUPSAVEPART="${USBDRV}1"
+			PUPBOOTPART="${USBDRV}4"
+		fi
+		if [ "$RADIO_ZIP" = "true" ];then
+			#take out '--mbrfat' has partition but makes look like floppy drive.
+			makebootfat --output $LOOPDEV --syslinux3 --zip --boot ldlinux.bss --mbr mbrfat.bin --copy ldlinux.sys tempdir
+			#'--zip' sets partition-4 as bootable, so pup_save will go into partition-1...
+			PUPSAVEPART="${USBDRV}1"
+			PUPBOOTPART="${USBDRV}4"
+		fi
+		sync
+		losetup -d $LOOPDEV
 	fi
 
 	#write bootable f.s. to drive...
-	dd if=${WKGPATH}/image256m of=/dev/$USBDRV
+	dd if=${WKGPATH}/image512m of=/dev/$USBDRV
 	sync
-	rm -f ${WKGPATH}/image256m
-
+	rm -f ${WKGPATH}/image512m
+	
 	#now create partition to fill remaining space on usb drive...
 	if [ "$RADIO_ISO" = "true" ];then
-	   echo -e 'n\np\n2\n\n\nw' | fdisk /dev/$USBDRV #create partition-2
-	   PARTNUM="2"
+		(
+		echo n # Add a new partition
+		echo p # Primary partition
+		echo 2 # Partition number
+		echo   # First sector (Accept default: 1)
+		echo   # Last sector (Accept default: varies)
+		echo w # Write changes
+		) | fdisk /dev/$USBDRV #create partition-2
 	else
-	   echo -e 'n\np\n1\n\n\nw' | fdisk /dev/$USBDRV #create partition-1
-	   PARTNUM="1"
+		(
+		echo n # Add a new partition
+		echo p # Primary partition
+		echo 1 # Partition number
+		echo   # First sector (Accept default: 1)
+		echo   # Last sector (Accept default: varies)
+		echo w # Write changes
+		) | fdisk /dev/$USBDRV #create partition-1
 	fi
-	DRVSIZEB=`fdisk -l /dev/${USBDRV} | grep '^Disk /dev/' | cut -f 5 -d ' '` #in bytes.
+	DRVSIZEB=$(probedisk -size ${USBDRV} | cut -f 2 -d '|')
+	DRVSIZEB=$(($DRVSIZEB * 512)) #bytes
 	DRVSIZEK=`expr $DRVSIZEB \/ 1024`
 	DRVSIZEM=`expr $DRVSIZEK \/ 1024`
+	sync
 	if [ $DRVSIZEM -gt 1024 ];then #1GB
-	  #set partition-id to fat32 (0b=fat32, oc=fat32-lba)...
-	  echo -e "t\n${PARTNUM}\n0b\nw" | fdisk /dev/${USBDRV}
-	  sync
-	  mkdosfs -F 32 -n puppysave /dev/${PUPSAVEPART} #FAT32.
+		#set partition-id to fat32 (0b=fat32, oc=fat32-lba)...
+		(
+		echo t   # change partition type
+		echo ${PARTNUM}
+		echo 0b  # WIN95 OSR2 FAT32
+		echo w   # write
+		) | fdisk /dev/${USBDRV}
+		sync
+		mkdosfs -F 32 -n puppysave /dev/${PUPSAVEPART} #FAT32.
 	else
-	  #set partition-id to fat16 (06=fat16, 0e=fat16-lba)...
-	  echo -e "t\n${PARTNUM}\n06\nw" | fdisk /dev/${USBDRV}
-	  mkdosfs -n puppysave /dev/${PUPSAVEPART} #FAT16.
+		#set partition-id to fat16 (06=fat16, 0e=fat16-lba)...
+		(
+		echo t   # change partition type
+		echo ${PARTNUM}
+		echo 06  # DOS 3.31+ 16-bit FAT (over 32M)
+		echo w   # write
+		) | fdisk /dev/${USBDRV}
+		mkdosfs -n puppysave /dev/${PUPSAVEPART} #FAT16.
 	fi
 
 fi
@@ -371,10 +420,10 @@ kill $X1PID
 
 #announce finished, offer to install Puppy...
 if [ "$RADIO_ISO" = "true" ];then
- /usr/lib/gtkdialog/box_ok "$(gettext 'BootFlash: ISO9660 format finished')" complete \
+	/usr/lib/gtkdialog/box_ok "$(gettext 'BootFlash: ISO9660 format finished')" complete \
   "<b>$(gettext 'All done!')</b>" \
   "$(gettext 'The drive now has two partitions, ISO9660 and the rest of the drive a FAT partition. Puppy will offer to create a pup-save file in the latter, at the first shutdown after successfully booting from the USB drive.')"
- exit
+	exit
 fi
 
 /usr/lib/gtkdialog/box_yesno --yes-first --yes-label "$(gettext 'Install Puppy')" --no-label "$(gettext 'Exit - finished')" \
@@ -398,7 +447,6 @@ fi
 mkdir -p /mnt/${PUPBOOTPART}
 mount -t vfat /dev/${PUPBOOTPART} /mnt/${PUPBOOTPART}
 if [ "`mount | grep "/dev/${PUPBOOTPART}"`" = "" ];then
-	umount /tmp/bootflash_iso 2>/dev/null
 	/usr/lib/gtkdialog/box_ok "Bootflash" error "$(gettext 'Error mounting USB drive')"
 	exit
 fi
