bootflash [iso]: (cli) secretly accept any iso file

diff --git a/woof-code/rootfs-skeleton/usr/sbin/bootflash b/woof-code/rootfs-skeleton/usr/sbin/bootflash
--- a/woof-code/rootfs-skeleton/usr/sbin/bootflash
+++ b/woof-code/rootfs-skeleton/usr/sbin/bootflash
@@ -20,7 +20,26 @@ fi
 
 if [ "$1" = "debug" ] ; then
 	exec &>/tmp/${0##*/}.log ; set -x ; env #debug
+	shift
 fi
+
+. /etc/rc.d/PUPSTATE
+. /etc/DISTRO_SPECS
+
+case $1 in *.iso|*.ISO)
+	ISO_MP=/mnt/isofile #unmountcdfunc
+	SRCPATH=${ISO_MP}
+	mkdir -p ${ISO_MP}
+	umount ${ISO_MP} 2>/dev/null
+	mount -o loop "$1" ${ISO_MP} || {
+		echo "Cannot mount $1"
+		umount ${ISO_MP}
+		exit 1
+	}
+	ANY_ISO=1
+	shift
+	;;
+esac
 
 PARAM1=""
 if [ $1 ] ; then
@@ -28,9 +47,6 @@ if [ $1 ] ; then
 	PARAM1="$1"
 	USBDRV="$PARAM1"
 fi
-
-. /etc/rc.d/PUPSTATE
-. /etc/DISTRO_SPECS
 
 #======================================================================
 #                             FUNCTIONS
@@ -184,8 +200,6 @@ locate_puppy_src_files() {
 		exit
 	fi
 } #end locate_puppy_src_files function.
-
-locate_puppy_src_files
 
 #======================================================================
 #							MAIN DIALOG
@@ -386,7 +400,9 @@ kill $X1PID
 
 #=======================================================================
 
-locate_puppy_src_files
+if [ -z "$SRCPATH" ] ; then
+	locate_puppy_src_files
+fi
 
 PUPBOOTPART=${USBDRV}1
 mkdir -p /mnt/${PUPBOOTPART}
@@ -412,12 +428,20 @@ else #g4dos
 	copy_g4dos_cd /mnt/${PUPBOOTPART} auto ${PMEDIA}
 fi
 
-for i in vmlinuz initrd.gz ${DISTRO_PUPPYSFS} ${DISTRO_ZDRVSFS} ${DISTRO_FDRVSFS} ${DISTRO_ADRVSFS} ${DISTRO_YDRVSFS}; do
-	if ! [ -f ${SRCPATH}/${i} ] ; then
-		continue
-	fi
-	cp -fv ${SRCPATH}/${i} /mnt/${PUPBOOTPART}/
-done
+if [ "$ANY_ISO" ] ; then
+	# just copy the sfs files, initrd.gz and vmlinuz
+	cp -fv ${SRCPATH}/*.sfs /mnt/${PUPBOOTPART}/
+	cp -fv ${SRCPATH}/initrd* /mnt/${PUPBOOTPART}/
+	cp -fv ${SRCPATH}/vmlinuz /mnt/${PUPBOOTPART}/
+else
+	for i in vmlinuz initrd.gz ${DISTRO_PUPPYSFS} ${DISTRO_ZDRVSFS} ${DISTRO_FDRVSFS} ${DISTRO_ADRVSFS} ${DISTRO_YDRVSFS}; do
+		if ! [ -f ${SRCPATH}/${i} ] ; then
+			continue
+		fi
+		cp -fv ${SRCPATH}/${i} /mnt/${PUPBOOTPART}/
+	done
+fi
+
 sync
 
 umount /mnt/${PUPBOOTPART}
