checkdeps fix
checkdeps -system was not working

diff --git a/woof-code/rootfs-skeleton/usr/sbin/checkdeps b/woof-code/rootfs-skeleton/usr/sbin/checkdeps
--- a/woof-code/rootfs-skeleton/usr/sbin/checkdeps
+++ b/woof-code/rootfs-skeleton/usr/sbin/checkdeps
@@ -58,12 +58,14 @@ if [ "$SYSTEM" = "TRUE" ] ; then
 
 	echo "SYSTEM CHECK" >&2
 	ROOTDIR=$1
-	if [ "$ROOTDIR" = "/" ] ; then
-		ROOTDIR=''
-	else
-		[ -d "$ROOTDIR" ] || { echo "ERROR: $ROOTDIR no such directory" >&2 ; exit 1; }
-		[[ $ROOTDIR != /* ]] && ROOTDIR=${PWD}/${ROOTDIR}
-		[[ $ROOTDIR == */ ]] && ROOTDIR=${ROOTDIR%\/}
+	if [ $ROOTDIR ] ; then
+		if [ "$ROOTDIR" = "/" ] ; then
+			ROOTDIR=''
+		else
+			[ -d "$ROOTDIR" ] || { echo "ERROR: $ROOTDIR no such directory" >&2 ; exit 1; }
+			[[ $ROOTDIR != /* ]] && ROOTDIR=${PWD}/${ROOTDIR}
+			[[ $ROOTDIR == */ ]] && ROOTDIR=${ROOTDIR%\/}
+		fi
 	fi
 
 	outputresult="/tmp/checkdeps_system.txt"
