connectwizard_crd: abort if iw app is missing

diff --git a/woof-code/rootfs-skeleton/usr/sbin/connectwizard_crd b/woof-code/rootfs-skeleton/usr/sbin/connectwizard_crd
--- a/woof-code/rootfs-skeleton/usr/sbin/connectwizard_crd
+++ b/woof-code/rootfs-skeleton/usr/sbin/connectwizard_crd
@@ -5,8 +5,11 @@
 
 #160922 fix so scan can see all channels allowed in my country... 160926
 #160926 ###NOTICE### this wait might not be needed, as module knows country code directly.
-if [ -s /etc/modprobe.d/crdw.conf ] \
-  && which crda &>/dev/null;then #set in quicksetup 170609
+if [ -s /etc/modprobe.d/crdw.conf ] && which crda &>/dev/null;then #set in quicksetup 170609
+ if ! which iw &>/dev/null ; then
+  echo "${0}: ERROR: iw is missing" >&2
+  exit 1
+ fi
  CRDW="$(cat /etc/modprobe.d/crdw.conf | grep '^options cfg80211' | cut -f 2 -d '=')" #created by quicksetup
  [ ! "$CRDW" ] && CRDW='00'
  if [ "$CRDW" != "00" ];then
