PPM2; Support for multiple package installation/removal and console operation
Merged without history of the ppm_auto git repo at commit
c21c8731ffbcf9b0a588e4b0a9600ac455960f16 (version 1.9.999)
See https://github.com/puppylinux-woof-CE/ppm_auto
for full history and changes.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/download_file b/woof-code/rootfs-skeleton/usr/sbin/download_file
--- a/woof-code/rootfs-skeleton/usr/sbin/download_file
+++ b/woof-code/rootfs-skeleton/usr/sbin/download_file
@@ -16,6 +16,10 @@
 #120908 revert 120220.
 #121019 extra msg if missing-url, when called from ppm (refer /usr/local/petget/downloadpkgs.sh).
 
+[ "$(cat /var/local/petget/nt_category 2>/dev/null)" != "true" ] && \
+ [ -f /tmp/install_quietly ] && set -x
+ #; mkdir -p /tmp/PPM_LOGs ; NAME=$(basename "$0"); exec 1>> /tmp/PPM_LOGs/"$NAME".log 2>&1
+
 BG='#2F2F2F'
 FG='#E3DB8B'
 # adding gettext
@@ -56,18 +60,20 @@ fi
 #test url... -t 2 means try 2 times, -T 20 means timeout in 20 seconds
 while [ 1 ];do
  echo -n "" > /tmp/download_file_spider.log1
- rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Testing file exists:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log1 & #120908 restored.
- PID1=$!
+ if [ ! -f /tmp/install_quietly ]; then
+  rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Testing file exists:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log1 & #120908 restored.
+  PID1=$!
+ fi
  LANG=C wget -4 -t 2 -T 20 --waitretry=20 --spider -S "${URLSPEC}" > /tmp/download_file_spider.log1 2>&1 #
  if [ $? -ne 0 ];then
-  Xdialog --wmclass "gtkdialog2" --left --wrap --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TEST AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/local/lib/X11/pixmaps/error.xpm" --yesno "$(gettext 'Tested if remote file exists, but failed, see log top-left of screen.
+  Xdialog --wmclass "gtkdialog2" --left --wrap --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TEST AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "$(gettext 'Tested if remote file exists, but failed, see log top-left of screen.
 Do you want to test again, or give up?')${PPM_NO_URL_MSG}" 0 0
   REPLY1=$?
   kill $PID1
   [ $REPLY1 -eq 0 ] && continue
   exit 1
  fi
- kill $PID1
+ [ ! -f /tmp/install_quietly ] && kill $PID1 || echo
  break
 done
 #LANG=C # i18n
@@ -105,7 +111,7 @@ on it.') "
  esac
 fi
 if [ "$URL_BROKEN" != "0" ];then
- Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/local/lib/X11/pixmaps/error.xpm" --msgbox "${MSG_NO1}
+ Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --msgbox "${MSG_NO1}
 
 $(gettext 'Click button to abort download...')" 0 0
  exit 3
@@ -113,9 +119,9 @@ fi
 #101117 check enough free space...
 #FREEK=`df -k | grep ' /$' | tr -s ' ' | cut -f 4 -d ' '`
 #no, need to know free space in whatever is current dir...
-PWD="`pwd`"
-FREEblocks=`stat -f --format=%a ${PWD}`
-BLOCKsize=`stat -f --format=%S ${PWD}`
+#PWD="`pwd`"
+FREEblocks=`stat -f --format=%a .`
+BLOCKsize=`stat -f --format=%S .`
 FREEbytes=`expr $FREEblocks \* $BLOCKsize`
 FREEK=`expr $FREEbytes \/ 1024`
 
@@ -148,7 +154,7 @@ or swap partition (or it needs to be bigger)')"
 See menu Utility -> Resize personal storage file')"
   ;;
  esac
- Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/local/lib/X11/pixmaps/error.xpm" --msgbox "
+ Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --msgbox "
 `eval_gettext \"Sorry, but there is not enough free space to download to.
 Attempted download directory: \\\${PWD}
 The online file is \\\${SIZEK_ONLINE}KB, but your free space is \\\${FREEK}KB.
@@ -165,9 +171,14 @@ while [ 1 ];do
 
  CONTPARAM=''
  if [ -f $FILENAME ];then
+  echo ${FILENAME} > /tmp/pkg_preexists
+  if [ "$(cat /var/local/petget/rd_category)" = "true" ]; then
+   rm -f "$FILENAME"
+  else
+
   SIZEB_LOCAL=`stat --format=%s "${FILENAME}"`
   if [ $SIZEB_LOCAL -lt $SIZEB_ONLINE ];then
-   Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'CONTINUE')" --cancel-label "$(gettext 'START AGAIN')"  --icon "/usr/local/lib/X11/pixmaps/question.xpm" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}partly downloaded (although there is
+   Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'CONTINUE')" --cancel-label "$(gettext 'START AGAIN')"  --icon "/usr/share/pixmaps/puppy/dialog-question.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}partly downloaded (although there is
 no guarantee it is uncorrupted), do you want to continue downloading it,
 or erase it and download entire file again?\"`" 0 0
    if [ $? -eq 0 ];then
@@ -177,7 +188,7 @@ or erase it and download entire file again?\"`" 0 0
    fi
   else
    if [ $SIZEB_LOCAL -gt $SIZEB_ONLINE ];then #101117
-    Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/local/lib/X11/pixmaps/error.xpm" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}downloaded but is larger
+    Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}downloaded but is larger
 than the online file. Hmmm... this probably means that the online
 file is a more recent version, so it is recommended that you erase
 the local file and download it again...
@@ -185,28 +196,37 @@ Do you want to erase it and download entire file again?\"`" 0 0
     if [ $? -eq 0 ];then
      rm -f "$FILENAME"
     else
+     [ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" \
+      >> /tmp/overall_package_status_log
      exit 0
     fi
    else
-    Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/local/lib/X11/pixmaps/question.xpm" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}fully downloaded (although there is
+    Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/share/pixmaps/puppy/dialog-question.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}fully downloaded (although there is
 no guarantee it is uncorrupted), do you want to erase it and download
 entire file again?\"`" 0 0
     if [ $? -eq 0 ];then
      rm -f "$FILENAME"
     else
+     [ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" \
+      >> /tmp/overall_package_status_log
      exit 0
     fi
    fi
   fi
+  fi
  fi
 
  echo -n "" > /tmp/download_file_spider.log2
- rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Downloading file:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log2 & #120908 restored.
+ if [ ! -f /tmp/install_quietly ]; then
+  rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Downloading file:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log2 & #120908 restored.
   PID1=$!
+ fi
  #-t 5 means retry 5 times, -w 5 means wait 5 seconds between retries...
+ [ -f /tmp/install_quietly -a "$(cat /var/local/petget/nt_category 2>/dev/null)" != "true" ]\
+  && tail -f /tmp/download_file_spider.log2 &
  wget -4 ${CONTPARAM} -t 5 -w 5 "${URLSPEC}" > /tmp/download_file_spider.log2 2>&1
  if [ $? -ne 0 ];then
-  Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TRY AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/local/lib/X11/pixmaps/error.xpm" --yesno "$(gettext 'Download failed, see log top-left of screen.
+  Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TRY AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "$(gettext 'Download failed, see log top-left of screen.
 Do you want to try again, or give up?')" 0 0
   REPLY1=$?
   kill $PID1
@@ -214,7 +234,7 @@ Do you want to try again, or give up?')" 0 0
   rm -f "$FILENAME"
   exit 2
  fi
- kill $PID1
+ [ ! -f /tmp/install_quietly ] && kill $PID1 || echo
  
  #paranoid, check size of downloaded file...
  SIZEB_LOCAL=`stat --format=%s "${FILENAME}"`
@@ -225,6 +245,9 @@ Do you want to try again, or give up?')" 0 0
  
  break
 done
+
+[ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" \
+ >> /tmp/overall_package_status_log
 
 exit 0
 ###END###
