download_file: w indent style

diff --git a/woof-code/rootfs-skeleton/usr/sbin/download_file b/woof-code/rootfs-skeleton/usr/sbin/download_file
--- a/woof-code/rootfs-skeleton/usr/sbin/download_file
+++ b/woof-code/rootfs-skeleton/usr/sbin/download_file
@@ -51,7 +51,7 @@ URLDIR="`dirname "$@"`" #121019
 #put up this info in downloadpkgs.sh. then no need for exported DL_F_CALLED_FROM.
 PPM_NO_URL_MSG=""
 if [ "$DL_F_CALLED_FROM" = "ppm" ];then #see /usr/local/petget/downloadpkgs.sh
- PPM_NO_URL_MSG="
+	PPM_NO_URL_MSG="
 
 $(gettext "NOTE:")
 $(gettext "It may be that the local package database needs to be updated. In some cases, the packages in the online package repository change, so you may be trying to download a package that no longer exists. One way to check this is to go to the URL with your web browser:")
@@ -61,22 +61,22 @@ fi
 
 #test url... -t 2 means try 2 times, -T 20 means timeout in 20 seconds
 while [ 1 ];do
- echo -n "" > /tmp/download_file_spider.log1
- if [ ! -f /tmp/install_quietly ]; then
-  rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Testing file exists:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log1 & #120908 restored.
-  PID1=$!
- fi
- LANG=C wget -4 -t 2 -T 20 --waitretry=20 --spider -S "${URLSPEC}" > /tmp/download_file_spider.log1 2>&1 #
- if [ $? -ne 0 ];then
-  Xdialog --wmclass "gtkdialog2" --left --wrap --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TEST AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "$(gettext 'Tested if remote file exists, but failed, see log top-left of screen.
+	echo -n "" > /tmp/download_file_spider.log1
+	if [ ! -f /tmp/install_quietly ]; then
+		rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Testing file exists:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log1 & #120908 restored.
+		PID1=$!
+	fi
+	LANG=C wget -4 -t 2 -T 20 --waitretry=20 --spider -S "${URLSPEC}" > /tmp/download_file_spider.log1 2>&1 #
+	if [ $? -ne 0 ];then
+		Xdialog --wmclass "gtkdialog2" --left --wrap --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TEST AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "$(gettext 'Tested if remote file exists, but failed, see log top-left of screen.
 Do you want to test again, or give up?')${PPM_NO_URL_MSG}" 0 0
-  REPLY1=$?
-  kill $PID1
-  [ $REPLY1 -eq 0 ] && continue
-  exit 1
- fi
- [ ! -f /tmp/install_quietly ] && kill $PID1 || echo
- break
+		REPLY1=$?
+		kill $PID1
+		[ $REPLY1 -eq 0 ] && continue
+		exit 1
+	fi
+	[ ! -f /tmp/install_quietly ] && kill $PID1 || echo
+	break
 done
 
 if grep -q 'file is already fully retrieved' /tmp/download_file_spider.log1 ; then
@@ -97,19 +97,19 @@ SIZEB_ONLINE=`grep '^Length: ' /tmp/download_file_spider.log1 | tr -s ' ' | cut 
 
 #101117 sanity check...
 case $SIZEB_ONLINE in
-  "") #could not get size of remote file.. continue anyway
-    echo -n
-  ;;
-  *[a-zA-Z]*)
-    Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/share/pixmaps/puppy/dialog-error.svg" \
-     --msgbox "$(gettext 'Oh dear, something seems to be wrong with the URL:')
+	"") #could not get size of remote file.. continue anyway
+		echo -n
+		;;
+	*[a-zA-Z]*)
+		Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/share/pixmaps/puppy/dialog-error.svg" \
+		--msgbox "$(gettext 'Oh dear, something seems to be wrong with the URL:')
 ${URLSPEC}
 $(gettext 'A probe of the remote file could not retrieve correct information
 on it.')
 
 $(gettext 'Click button to abort download...')" 0 0
-    exit 3
-  ;;
+		exit 3
+		;;
 esac
 
 #==========================================================
@@ -118,39 +118,39 @@ if [ "$SIZEB_ONLINE" != "" ] ; then
 	#need to know free space in whatever is current dir...
 	FREEblocks=`stat -f -c %a .`
 	BLOCKsize=`stat -f -c %S .`
-	FREEbytes=`expr $FREEblocks \* $BLOCKsize`
-	FREEK=`expr $FREEbytes \/ 1024`
+	FREEbytes=$(( $FREEblocks * $BLOCKsize))
+	FREEK=$(( $FREEbytes / 1024 ))
 
-	SIZEK_ONLINE=`expr $SIZEB_ONLINE \/ 1024`
+	SIZEK_ONLINE=$(( $SIZEB_ONLINE / 1024 ))
 	case $PUPMODE in
-	 3|7|13|77) #tmpfs on top
-	  #when install pkg, it writes direct to save-layer.
-	  SIZEK_REQUEST=`expr $SIZEK_ONLINE + 6000` #6MB slack.
-	 ;;
-	 *)
-	  SIZEK_REQUEST=`expr $SIZEK_ONLINE \* 3` #3MB slack, no, need install space too.
-	 ;;
+		3|7|13|77) #tmpfs on top
+			#when install pkg, it writes direct to save-layer.
+			SIZEK_REQUEST=$(( $SIZEK_ONLINE + 6000 )) #6MB slack.
+			;;
+		*)
+			SIZEK_REQUEST=$(( $SIZEK_ONLINE * 3 )) #3MB slack, no, need install space too.
+			;;
 	esac
 	#LANG=$LANG_USER
 	if [ $SIZEK_REQUEST -gt $FREEK ];then
-	 case $PUPMODE in
-	  5)
-	   MSGs="$(gettext 'You need to shutdown and create a save-file, then you will have more space.
+		case $PUPMODE in
+		5)
+			MSGs="$(gettext 'You need to shutdown and create a save-file, then you will have more space.
 See menu Shutdown -> Reboot')"
-	  ;;
-	  2|6)
-	   MSGs="$(gettext 'The partition is full, you will have to delete something.')"
-	  ;;
-	  3|7|77) #tmpfs on top, full partition underneath
-	   MSGs="$(gettext 'Do not have enough space in the RAM. Maybe you need a swap file
+			;;
+		2|6)
+			MSGs="$(gettext 'The partition is full, you will have to delete something.')"
+			;;
+		3|7|77) #tmpfs on top, full partition underneath
+			MSGs="$(gettext 'Do not have enough space in the RAM. Maybe you need a swap file
 or swap partition (or it needs to be bigger)')"
-	  ;;
-	  *)
-	   MSGs="$(gettext 'You need to increase the size of the save-file.
+			;;
+		*)
+			MSGs="$(gettext 'You need to increase the size of the save-file.
 See menu Utility -> Resize personal storage file')"
-	  ;;
-	 esac
-	 Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --msgbox "
+			;;
+		esac
+		Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --msgbox "
 `eval_gettext \"Sorry, but there is not enough free space to download to.
 Attempted download directory: \\\${PWD}
 The online file is \\\${SIZEK_ONLINE}KB, but your free space is \\\${FREEK}KB.
@@ -158,7 +158,7 @@ The online file is \\\${SIZEK_ONLINE}KB, but your free space is \\\${FREEK}KB.
 \\\${MSGs}
 
 Click button to abort download...\"`" 0 0
-	 exit 1
+		exit 1
 	fi
 fi
 
@@ -169,89 +169,91 @@ INSERT1="$(gettext 'already ')"
 while [ 1 ]
 do
 
- CONTPARAM=''
- if [ -f $FILENAME ];then
-  echo ${FILENAME} > /tmp/pkg_preexists
-  if [ "$(cat /var/local/petget/rd_category 2>/dev/null)" = "true" ]; then
-   rm -f "$FILENAME"
-  else
+	CONTPARAM=''
+	if [ -f $FILENAME ];then
+		echo ${FILENAME} > /tmp/pkg_preexists
+		if [ "$(cat /var/local/petget/rd_category 2>/dev/null)" = "true" ]; then
+			rm -f "$FILENAME"
+		else
 
-   if [ "$SIZEB_ONLINE" != "" ] ; then
-	  SIZEB_LOCAL=`stat -c %s "${FILENAME}"`
-	  if [ $SIZEB_LOCAL -lt $SIZEB_ONLINE ];then
-	   Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'CONTINUE')" --cancel-label "$(gettext 'START AGAIN')"  --icon "/usr/share/pixmaps/puppy/dialog-question.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}partly downloaded (although there is
+			if [ "$SIZEB_ONLINE" != "" ] ; then
+				SIZEB_LOCAL=`stat -c %s "${FILENAME}"`
+				if [ $SIZEB_LOCAL -lt $SIZEB_ONLINE ];then
+					Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'CONTINUE')" --cancel-label "$(gettext 'START AGAIN')"  --icon "/usr/share/pixmaps/puppy/dialog-question.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}partly downloaded (although there is
 no guarantee it is uncorrupted), do you want to continue downloading it,
 or erase it and download entire file again?\"`" 0 0
-	   if [ $? -eq 0 ];then
-	    CONTPARAM='-c'
-	   else
-	    rm -f "$FILENAME"
-	   fi
-	  else
-	   if [ $SIZEB_LOCAL -gt $SIZEB_ONLINE ];then #101117
-	    Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}downloaded but is larger
+					if [ $? -eq 0 ];then
+						CONTPARAM='-c'
+					else
+						rm -f "$FILENAME"
+					fi
+				else
+					if [ $SIZEB_LOCAL -gt $SIZEB_ONLINE ];then #101117
+						Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}downloaded but is larger
 than the online file. Hmmm... this probably means that the online
 file is a more recent version, so it is recommended that you erase
 the local file and download it again...
 Do you want to erase it and download entire file again?\"`" 0 0
-		if [ $? -eq 0 ];then
-		 rm -f "$FILENAME"
-		else
-		 [ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" >> /tmp/overall_package_status_log
-		 exit 0
-		fi
-	   else
-		Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/share/pixmaps/puppy/dialog-question.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}fully downloaded (although there is
+						if [ $? -eq 0 ];then
+							rm -f "$FILENAME"
+						else
+							[ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" >> /tmp/overall_package_status_log
+							exit 0
+						fi
+					else
+						Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'DOWNLOAD AGAIN')" --cancel-label "$(gettext 'NO')"  --icon "/usr/share/pixmaps/puppy/dialog-question.svg" --yesno "`eval_gettext \"File '\\\${FILENAME}' is \\\${INSERT1}fully downloaded (although there is
 no guarantee it is uncorrupted), do you want to erase it and download
 entire file again?\"`" 0 0
-		if [ $? -eq 0 ];then
-		 rm -f "$FILENAME"
-		else
-		 [ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" >> /tmp/overall_package_status_log
-		 exit 0
+						if [ $? -eq 0 ];then
+							rm -f "$FILENAME"
+						else
+							[ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" >> /tmp/overall_package_status_log
+							exit 0
+						fi
+					fi
+				fi
+			fi
 		fi
-	   fi
-	  fi
-   fi
+	fi
 
-  fi
- fi
-
- echo -n "" > /tmp/download_file_spider.log2
- if [ ! -f /tmp/install_quietly ]; then
-  rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Downloading file:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log2 & #120908 restored.
-  PID1=$!
- fi
- #-t 5 means retry 5 times, -w 5 means wait 5 seconds between retries...
- [ -f /tmp/install_quietly -a "$(cat /var/local/petget/nt_category 2>/dev/null)" != "true" ]\
-  && tail -f /tmp/download_file_spider.log2 &
- wget -4 ${CONTPARAM} -t 5 -w 5 "${URLSPEC}" > /tmp/download_file_spider.log2 2>&1
- if [ $? -ne 0 ];then
-  Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TRY AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "$(gettext 'Download failed, see log top-left of screen.
+	echo -n "" > /tmp/download_file_spider.log2
+	if [ ! -f /tmp/install_quietly ]; then
+		rxvt -geometry 130x10+0+0 -bg "$BG" -fg "$FG" -title "$(gettext 'Downloading file:') ${URLSPEC}" -e tail -f /tmp/download_file_spider.log2 & #120908 restored.
+		PID1=$!
+	fi
+	#-t 5 means retry 5 times, -w 5 means wait 5 seconds between retries...
+	if [ -f /tmp/install_quietly -a "$(cat /var/local/petget/nt_category 2>/dev/null)" != "true" ] ; then
+		tail -f /tmp/download_file_spider.log2 &
+	fi
+	wget -4 ${CONTPARAM} -t 5 -w 5 "${URLSPEC}" > /tmp/download_file_spider.log2 2>&1
+	if [ $? -ne 0 ];then
+		Xdialog --wmclass "gtkdialog2" --title "$(gettext 'Puppy File Downloader')" --screen-center --cr-wrap --ok-label "$(gettext 'TRY AGAIN')" --cancel-label "$(gettext 'GIVE UP')" --icon "/usr/share/pixmaps/puppy/dialog-error.svg" --yesno "$(gettext 'Download failed, see log top-left of screen.
 Do you want to try again, or give up?')" 0 0
-  REPLY1=$?
-  kill $PID1
-  [ $REPLY1 -eq 0 ] && continue
-  rm -f "$FILENAME"
-  exit 2
- fi
- [ ! -f /tmp/install_quietly ] && kill $PID1 || echo
+		REPLY1=$?
+		kill $PID1
+		[ $REPLY1 -eq 0 ] && continue
+		rm -f "$FILENAME"
+		exit 2
+	fi
+	[ ! -f /tmp/install_quietly ] && kill $PID1 || echo
  
- if [ "$SIZEB_ONLINE" != "" ] ; then
-	 #paranoid, check size of downloaded file...
-	 SIZEB_LOCAL=`stat -c %s "${FILENAME}"`
-	 if [ $SIZEB_LOCAL -ne $SIZEB_ONLINE ];then
-	  INSERT1=''
-	  continue
-	 fi
- fi
+	if [ "$SIZEB_ONLINE" != "" ] ; then
+		#paranoid, check size of downloaded file...
+		SIZEB_LOCAL=`stat -c %s "${FILENAME}"`
+		if [ $SIZEB_LOCAL -ne $SIZEB_ONLINE ];then
+			INSERT1=''
+			continue
+		fi
+	fi
  
- break
+	break
  
 done
 
-[ -f /tmp/install_quietly ] && echo "PACKAGE: $FILENAME" \
- >> /tmp/overall_package_status_log
+if [ -f /tmp/install_quietly ] ; then
+	echo "PACKAGE: $FILENAME" >> /tmp/overall_package_status_log
+fi
 
 exit 0
-###END###
+
+### END ###
