make 'edit-initramfs -c initrd-expanded' possible..

diff --git a/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs b/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
--- a/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
+++ b/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
@@ -55,8 +55,18 @@ function initrd_proc() { #<extract|compress> [-home] <initrd.gz/xz>
 	[ "$1" = "-home" ] && { TOHOME=1; shift; }
 
 	INFILE="$@"
-	[ -f "$INFILE" ] || { echo "ERROR: file does not exist: $INFILE"; exit 1; }
-	[[ $INFILE != /* ]] && INFILE=$PWD/$INFILE
+	case $INFILE in
+		*'initrd-expanded')
+			INITRD_DIR=1
+			[ -e "$INFILE" ] || { echo "ERROR: file does not exist: $INFILE"; exit 1; }
+			[[ $INFILE != /* ]] && INFILE=$PWD/initrd.gz
+			UNCOMPREXE=gunzip ; EXT=gz ; COMPREXE=gzip
+			;;
+		*)
+			[ -f "$INFILE" ] || { echo "ERROR: file does not exist: $INFILE"; exit 1; }
+			[[ $INFILE != /* ]] && INFILE=$PWD/$INFILE
+			;;
+	esac
 	DIR="`dirname "$INFILE"`"
 	FILE_NAME=${INFILE##*/}
 
@@ -67,11 +77,14 @@ function initrd_proc() { #<extract|compress> [-home] <initrd.gz/xz>
 	fi
 
 	cd "$DIR"
-	[ $TOHOME ] && cp -fv "$INFILE" ${HOME}
-	[ -f initrd.gz -o -f initrd.xz ] || { echo "initrd.gz/xz not found in $DIR" ; exit 1 ; }
 
 	## now proceed
-	compr_func ${FILE_NAME} || { echo "ERROR getting compression type for ${FILE_NAME}" >&2 ; return 1 ; }
+	if [ ! "$INITRD_DIR" ] ; then
+		[ $TOHOME ] && cp -fv "$INFILE" ${HOME}
+		[ -f initrd.gz -o -f initrd.xz ] || { echo "initrd.gz/xz not found in $DIR" ; exit 1 ; }
+		compr_func ${FILE_NAME} || { echo "ERROR getting compression type for ${FILE_NAME}" >&2 ; return 1 ; }
+	fi
+
 	if [ "$OPTION" = "extract" ] ; then
 		echo "Expanding at $DIR"
 		[ "initrd.${EXT}" != "${FILE_NAME}" ] && cp -f "${FILE_NAME}" initrd.${EXT}
