edit-initramfs: support extracting fd64's initrd
I was looking for a DOTconfig but didn't find any hehe..

diff --git a/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs b/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
--- a/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
+++ b/woof-code/rootfs-skeleton/usr/sbin/edit-initramfs
@@ -21,6 +21,7 @@ function compr_func() {
 	case "$comp" in
 		gz*|GZ*) UNCOMPREXE=gunzip ; EXT=gz ; COMPREXE=gzip ;;
 		xz*|XZ*) UNCOMPREXE=unxz   ; EXT=xz ; COMPREXE='xz --check=crc32 --lzma2' ;;
+		*cpio*|*CPIO*) CPIO=1 ;; #fd64
 		*) echo "Unsupported compression/format for initrd."
 			exit 1 ;;
 	esac
@@ -79,14 +80,20 @@ function initrd_proc() { #<extract|compress> [-home] <initrd.gz/xz>
 	cd "$DIR"
 
 	## now proceed
-	if [ ! "$INITRD_DIR" ] ; then
+	if [ ! "$INITRD_DIR" -o "$CPIO" != "" ] ; then
 		[ $TOHOME ] && cp -fv "$INFILE" ${HOME}
-		[ -f initrd.gz -o -f initrd.xz ] || { echo "initrd.gz/xz not found in $DIR" ; exit 1 ; }
+		[ -f initrd -o -f initrd.gz -o -f initrd.xz ] || { echo "initrd.gz/xz not found in $DIR" ; exit 1 ; }
 		compr_func ${FILE_NAME} || { echo "ERROR getting compression type for ${FILE_NAME}" >&2 ; return 1 ; }
 	fi
 
 	if [ "$OPTION" = "extract" ] ; then
 		echo "Expanding at $DIR"
+		if [ "$CPIO" != "" ] ; then #to extract fd64's initrd ...
+			mkdir -p initrd-expanded
+			cd initrd-expanded
+			cat ../initrd | cpio -i -d -m
+			return
+		fi
 		[ "initrd.${EXT}" != "${FILE_NAME}" ] && cp -f "${FILE_NAME}" initrd.${EXT}
 		#-f and -k are options in gunzip, and unxz
 		zout="$(${UNCOMPREXE} -f -k initrd.${EXT} 2>&1)"
@@ -137,7 +144,7 @@ DIRX="`dirname "$zfile"`"
 BASEFILE="`basename "$zfile"`"
 
 case "${BASEFILE}" in
-	*"initrd.gz"|*"initrd.xz") ok=1 ;;
+	*initrd|*"initrd.gz"|*"initrd.xz") ok=1 ;;
 	*) exit 1 ;;
 esac
 
