filesize: final adjustments

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filesize b/woof-code/rootfs-skeleton/usr/sbin/filesize
--- a/woof-code/rootfs-skeleton/usr/sbin/filesize
+++ b/woof-code/rootfs-skeleton/usr/sbin/filesize
@@ -68,28 +68,30 @@ done
 #############################################################
 
 function formatbytes() { #args: bytes
-	local bytes=$1 suf suf2 res
-	if [[ $bytes -ge 1099511627776 ]] ; then #terabytes
-		res=$(bc <<< "scale = 2; $bytes/1099511627776")
-		suf=T ; suf2=TB
-	elif [[ $bytes -ge 1073741824 ]] ; then #gigabytes
-		res=$(bc <<< "scale = 2; $bytes/1073741824")
-		suf=G ; suf2=GB
-	elif [[ $bytes -ge 1048576 ]] ; then #megabytes
-		res=$(bc <<< "scale = 2; $bytes/1048576")
-		suf=M ; suf2=MB
-	elif [[ $bytes -ge 1024 ]] ; then #kilobyes
-		res=$(bc <<< "scale = 0; $bytes/1024")
+	local bytes=$1 suf="" suf2="" res="" bc=""
+	if [[ ${bytes} -ge 1099511627776 ]] ; then #terabytes
+		res=$(bc <<< "scale = 2; ${bytes}/1099511627776")
+		suf=T ; suf2=TB ; bc=1
+	elif [[ ${bytes} -ge 1073741824 ]] ; then #gigabytes
+		res=$(bc <<< "scale = 2; ${bytes}/1073741824")
+		suf=G ; suf2=GB ; bc=1
+	elif [[ ${bytes} -ge 1048576 ]] ; then #megabytes
+		res=$(bc <<< "scale = 2; ${bytes}/1048576")
+		suf=M ; suf2=MB ; bc=1
+	elif [[ ${bytes} -ge 1024 ]] ; then #kilobyes
+		res=$((${bytes}/1024))
 		suf=K ; suf2=KB
-	elif [[ $bytes -lt 1024 ]] ; then #bytes
-    	res=$(bc <<< "scale = 0; $bytes ")
+	elif [[ ${bytes} -lt 1024 ]] ; then #bytes
+    	res=${bytes}
 		suf=B ; suf2=B
 	else
-		suf=N/A
+		suf='?'
 	fi
-	[[ $res == \.* ]] && res="0${res}"
-	res=${res%.00}
-	res=${res%,00}
+	if [ "$bc" ] ; then
+		[[ $res == \.* ]] && res="0${res}"
+		res=${res%.00}
+		res=${res%,00}
+	fi
 	if [ $suffix -eq 2 ] ; then
 		echo "$res $suf2"
 	else
@@ -107,21 +109,23 @@ function filesizex() { #args: filename
 }
 
 function results() {
-	local bytes=$1 s s2 res
+	local bytes=$1 s="" s2="" res="" bc=""
 	if [ "$funit" ] ; then
 		bytes=$((bytes*funit))
 	fi
 	case $type in
-		b) res=$bytes ; s=B ; s2=B ;;
-		k) res=$(bc <<< "scale = 0; $bytes/1024 ") ; s=K ; s2=KB ;;
-		m) res=$(bc <<< "scale = 2; $bytes/1048576") ; s=M ; s2=MB ;;
-		g) res=$(bc <<< "scale = 2; $bytes/1073741824") ; s=G ; s2=GB ;;
-		t) res=$(bc <<< "scale = 2; $bytes/1099511627776") ; s=T ; s2=TB ;;
-		*) res=$(formatbytes $bytes) ;;
+		b) res=${bytes} ; s=B ; s2=B ;;
+		k) res=$((${bytes}/1024)) ; s=K ; s2=KB ;;
+		m) res=$(bc <<< "scale = 2; ${bytes}/1048576")       ; s=M ; s2=MB ; bc=1 ;;
+		g) res=$(bc <<< "scale = 2; ${bytes}/1073741824")    ; s=G ; s2=GB ; bc=1 ;;
+		t) res=$(bc <<< "scale = 2; ${bytes}/1099511627776") ; s=T ; s2=TB ; bc=1 ;;
+		*) res=$(formatbytes ${bytes}) ;;
 	esac
-	[[ $res == \.* ]] && res="0${res}"
-	res=${res%.00}
-	res=${res%,00}
+	if [ "$bc" ] ; then
+		[[ $res == \.* ]] && res="0${res}"
+		res=${res%.00}
+		res=${res%,00}
+	fi
 	if [ "$VERBOSE" ] ; then
 		if [ $suffix -eq 2 ] ; then
 			echo $res $s2
@@ -138,7 +142,7 @@ function results() {
 if [ "$FORMATONLY" ] ; then
 	[ ! "$1" ] && echo "* Need bytes" >&2 && exit 1
 	case "$1" in
-		''|*[!0-9]*) echo "$1: invalid number" >&2 ; exit 1 ;; 
+		''|*[!0-9]*) echo "$1: invalid number" >&2 ; exit 1 ;;
 	esac
 	results $1
 	exit
