filemnt: better FS detection / better exfat support

diff --git a/woof-code/rootfs-skeleton/usr/sbin/filemnt b/woof-code/rootfs-skeleton/usr/sbin/filemnt
--- a/woof-code/rootfs-skeleton/usr/sbin/filemnt
+++ b/woof-code/rootfs-skeleton/usr/sbin/filemnt
@@ -33,27 +33,10 @@ if [ "$MNTEDLOOP" = "" ];then #not mounted on $MntPt
     4fs) Type='ext4'     ;;
     sfs) Type='squashfs' ;;
     iso) Type='iso'      ;;
-    *)
-      info=$(file -b "$imgFile")
-      echo -en "\n${info}\n"
-      case $info in
-         *DOS*)  Type='msdos' ;;
-         *FAT*)  Type='vfat'  ;;
-         *NTFS*) Type='ntfs'  ;;
-         *9660*) Type='iso'   ;;
-         *UDF*)  Type='iso'   ;;
-         *ext2*) Type='ext2'  ;;
-         *ext3*) Type='ext3'  ;;
-         *ext4*) Type='ext4'  ;;
-         *Squashfs*) Type='squashfs' ;;
-         *)
-            Type=$(blkid "$imgFile" | grep -o ' TYPE=.*' | cut -f 2 -d '"')
-            [ "$Type" = "" ] && { echo "Unrecognized format" ; exit 1 ; }
-            echo -e "\nType=${Type}\n"
-            ;;
-      esac
-      ;;
+    *) Type=$(blkid "$imgFile" | grep -o ' TYPE=.*' | cut -f 2 -d '"') ;;
   esac
+  [ "$Type" = "" ] && { echo "Unrecognized format" ; exit 1 ; }
+  echo -e "\nType=${Type}\n"
 
   if [ "$Type" = "squashfs" ];then
       . /etc/rc.d/BOOTCONFIG # 140609 add contextual Install/Uninstall button
@@ -108,8 +91,18 @@ if [ "$MNTEDLOOP" = "" ];then #not mounted on $MntPt
     fi
   else #normal, no encryption... 130204 mavrothal: fix spaces in imgFile...
     case $Type in 
-      iso) mount -t udf -o loop "$imgFile" "$MntPt" || mount -t iso9660 -o loop "$imgFile" "$MntPt" ;;
-      *)   mount -t $Type -o loop "$imgFile" "$MntPt" ;;
+      iso|udf|iso9660) #iso img might have more than 1 fs. prefer udf..
+         mount -t udf -o loop "$imgFile" "$MntPt" || mount -t iso9660 -o loop "$imgFile" "$MntPt"
+         ;;
+      exfat)
+         mount -t exfat -o loop "$imgFile" "$MntPt" || {
+            # musl static mount.exfat fails
+            # have to set loop device manually...
+            losetup $DEVLOOP "$imgFile"
+            mount.exfat-fuse $DEVLOOP "$MntPt"
+         }
+         ;;
+      *) mount -t $Type -o loop "$imgFile" "$MntPt" ;;
     esac
     Err=$?
   fi
