3builddistro-Z: ./usr/sbin/icon_switcher -sysroot . -a ${NEWTHEME}

diff --git a/woof-code/rootfs-skeleton/usr/sbin/icon_switcher b/woof-code/rootfs-skeleton/usr/sbin/icon_switcher
--- a/woof-code/rootfs-skeleton/usr/sbin/icon_switcher
+++ b/woof-code/rootfs-skeleton/usr/sbin/icon_switcher
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #(c) Copyright Nov 2007 Barry Kauler www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #written dec 2007 for Puppy Linux.
@@ -10,64 +10,91 @@
 #110912 modify jwm to use menu icon 'start-button.png' if present.
 #120201 rodin.s: internationalized
 
-[ -z $ROX_DESKTOP ] && pidof ROX-Filer &>/dev/null && export ROX_DESKTOP=yes
-if [ ! "$ROX_DESKTOP" ] ; then
-	exit
-fi
-
 export TEXTDOMAIN=icon_switcher
 export OUTPUT_CHARSET=UTF-8
 
 func_switch (){
+
+	echo
+	echo "Setting Desktop Icon Theme..."
+
 	NEWTHEME="$1"
 	[ "$NEWTHEME" = "" ] && exit
-	[ ! -d /usr/local/lib/X11/themes/${NEWTHEME} ] && exit
+	if [ ! -d ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME} ] ; then
+		echo "ERROR: ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME} does not exist"
+		exit 1
+	fi
+
+	echo "Theme: $NEWTHEME"
+
+
 	#show splash if running in gui mode
 	if [ "$UPDATE" = "true" ]; then
 		/usr/lib/gtkdialog/box_splash -close never -fontsize large -icon_width 60 -icon /usr/share/pixmaps/puppy/puppy_config.svg -text "$(gettext 'Changing theme')" &
 		XPID=$!
 	fi
 	#---
-	for ONESVG in `find /usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -name \*.svg | tr '\n' ' '`; do
+	for ONESVG in `find ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -name \*.svg | tr '\n' ' '`; do
 		ONEBASENAME="`basename $ONESVG .svg`"
-		rm -f /usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png
-		rsvg-convert -w 48 -h 48 -o /usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png $ONESVG
-		rm -f /usr/local/lib/X11/pixmaps/${ONEBASENAME}24.png
+		rm -f ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png
+		rsvg-convert -w 48 -h 48 -o ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png $ONESVG
+		rm -f ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}24.png
 	done
-	for ONEPNG in `find /usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -type f -name \*.png | tr '\n' ' '`; do
+	for ONEPNG in `find ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -type f -name \*.png | tr '\n' ' '`; do
 		ONEBASENAME="`basename $ONEPNG .png`"
-		cp -f $ONEPNG /usr/local/lib/X11/pixmaps/
-		touch -m /usr/local/lib/X11/pixmaps/${ONEBASENAME}.png #v3.98
+		cp -f $ONEPNG ${SYSROOT}/usr/local/lib/X11/pixmaps/
+		touch -m ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}.png #v3.98
 	done
+
+	if [ "${SYSROOT}" -a "${NEWTHEME}" != "StandardSvg" ] ; then
+		# fill in the gaps with the StandardSvg icons...
+		for ONESVG in `find ${SYSROOT}/usr/local/lib/X11/themes/StandardSvg/ -maxdepth 1 -name \*.svg | tr '\n' ' '`; do
+			ONEBASENAME="`basename $ONESVG .svg`"
+			if [ -f ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png ] ; then
+				continue
+			fi
+			echo "[StandardSvg] ${ONEBASENAME}.svg -> ${ONEBASENAME}48.png"
+			rsvg-convert -w 48 -h 48 -o ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png $ONESVG
+		done
+	fi
  
 	#new standardised icons to show when mounted...
-	if [ "`which pngoverlay`" -a -e /usr/local/lib/X11/pixmaps/closebox_outline48.png ];then #overlay app created by vovchik (see source /usr/sbin/pngoverlay.bac)
-	rm -f /usr/local/lib/X11/pixmaps/*_mntd*.png
-	cd /usr/local/lib/X11/pixmaps
-	cp -f /usr/sbin/pngoverlay /usr/local/lib/X11/pixmaps/ #dumb, but needs to be in same folder.
-	for ONEDRV in card drive floppy optical usbdrv; do
-		./pngoverlay ${ONEDRV}48.png closebox_outline48.png ${ONEDRV}_mntd48.png #background foreground output.
-		./pngoverlay ${ONEDRV}48.png locked_outline48.png ${ONEDRV}_mntd_boot48.png
-	done
-	rm -f /usr/local/lib/X11/pixmaps/pngoverlay
+	if [ "`which pngoverlay`" -a -e ${SYSROOT}/usr/local/lib/X11/pixmaps/closebox_outline48.png ];then
+		rm -f ${SYSROOT}/usr/local/lib/X11/pixmaps/*_mntd*.png
+		(
+			cd ${SYSROOT}/usr/local/lib/X11/pixmaps
+			cp -fv `which pngoverlay` ./pngoverlay #dumb, but needs to be in same folder.
+			for ONEDRV in card drive floppy optical usbdrv; do
+				./pngoverlay ${ONEDRV}48.png closebox_outline48.png ${ONEDRV}_mntd48.png #background foreground output.
+				./pngoverlay ${ONEDRV}48.png locked_outline48.png ${ONEDRV}_mntd_boot48.png
+			done
+			rm -fv ./pngoverlay
+		)
 	fi
  
 	#modify jwm to use menu icon 'start-button.png' if present...
 	#note, similar code also in 3builddistro in Woof.
-	if [ -f /root/.jwmrc-tray ] && [ -f /usr/local/lib/X11/${NEWTHEME}/start-button.png ]; then #chosen theme has menu icon.
-		if [ -f /usr/local/lib/X11/pixmaps/start-button.png ];then #precaution.
-			if [ ! "`grep -F 'start-button.png' /root/.jwmrc-tray`" ]; then
+	if [ -f ${SYSROOT}/root/.jwmrc-tray ] && [ -f ${SYSROOT}/usr/local/lib/X11/${NEWTHEME}/start-button.png ]; then #chosen theme has menu icon.
+		if [ -f ${SYSROOT}/usr/local/lib/X11/pixmaps/start-button.png ];then #precaution.
+			if [ ! "`grep -F 'start-button.png' ${SYSROOT}/root/.jwmrc-tray`" ]; then
 				#the default is to use 'mini-dog.xpm' with text "Menu"...
-				sed -i 's%label="Menu" icon="puppy.svg"%icon="start-button.png"%' $HOME/.jwmrc-tray
+				sed -i 's%label="Menu" icon="puppy.svg"%icon="start-button.png"%' ${SYSROOT}$HOME/.jwmrc-tray
 			fi
 		else
 			#chosen theme does not have start-button.png, so go back to the mini-dog.xpm...
-			sed -i 's%icon="start-button.png"%label="Menu" icon="puppy.svg"%' $HOME/.jwmrc-tray
+			sed -i 's%icon="start-button.png"%label="Menu" icon="puppy.svg"%' ${SYSROOT}$HOME/.jwmrc-tray
 		fi
 	fi
 
+	echo -n "$NEWTHEME" > ${SYSROOT}/etc/desktop_icon_theme
+
+	if [ "${SYSROOT}" ] ; then
+		echo
+		return
+	fi
+
 	#record current theme...
-	echo -n "$NEWTHEME" > /etc/desktop_icon_theme
+	[ -z $ROX_DESKTOP ] && pidof ROX-Filer &>/dev/null && export ROX_DESKTOP=yes
 	if [ "$UPDATE" = "true" ]; then
 		#restart rox and jwm immediately...
 		roxfiler -p $HOME/Choices/ROX-Filer/PuppyPin
@@ -82,15 +109,19 @@ while [ $# != 0 ]; do
 	I=1
 	while [ $I -le `echo $# | wc -c` ]; do 
 		case $1 in
+			-sysroot) SYSROOT="$2" ; shift;;
 			-a) NEWTHEME="$2"; shift;;
 			-u) UPDATE=true;;
 			-h|--help)
-echo 'Usage: icon_switcher [OPTION]
+				echo '
+Usage: icon_switcher [OPTION]
 
 Options
   -a THEME    Activate theme
   -h          Show this help message
-  -u          Update desktop'; exit;;
+  -u          Update desktop
+  -sysroot R  Set system root (use with -a THEME)'
+				exit;;
 		esac
 		shift
 		I=$[$I+1]
