javaif: skip web demo test if no javaws executable

diff --git a/woof-code/rootfs-skeleton/usr/sbin/javaiftest b/woof-code/rootfs-skeleton/usr/sbin/javaiftest
--- a/woof-code/rootfs-skeleton/usr/sbin/javaiftest
+++ b/woof-code/rootfs-skeleton/usr/sbin/javaiftest
@@ -50,15 +50,17 @@ fi
 echo -e "\njava HelloWorldApp (expect Hello World!):"
 java HelloWorldApp
 
-echo -en "\nEnter any character to run an interactive JNLP example,\nand/or <Enter>: "
-read REPLY
-if [ -n "$REPLY" ]; then
- cd /usr/lib/javaif
- echo -e "\njavaws InputVerificationDemo.jnlp:"
- javaws InputVerificationDemo.jnlp 2>/dev/null
- if [ $? -eq 0 ]; then
-  echo 'Demonstration Completed'
- else
-  echo 'Demonstration Aborted'
+if which javaws &>/dev/null; then
+ echo -en "\nEnter any character to run an interactive JNLP example,\nand/or <Enter>: "
+ read REPLY
+ if [ -n "$REPLY" ]; then
+  cd /usr/lib/javaif
+  echo -e "\njavaws InputVerificationDemo.jnlp:"
+  javaws InputVerificationDemo.jnlp 2>/dev/null
+  if [ $? -eq 0 ]; then
+   echo 'Demonstration Completed'
+  else
+   echo 'Demonstration Aborted'
+  fi
  fi
 fi
