javaif: upgrade for openJDK support & new Java packaging structure

diff --git a/woof-code/rootfs-skeleton/usr/sbin/javaiftest b/woof-code/rootfs-skeleton/usr/sbin/javaiftest
--- a/woof-code/rootfs-skeleton/usr/sbin/javaiftest
+++ b/woof-code/rootfs-skeleton/usr/sbin/javaiftest
@@ -1,19 +1,36 @@
 #!/bin/ash
 #javaiftest - To be run from command line, to see results.
 echo -e "\nEnvironment:"
-echo -e "JAVA_HOME=$JAVA_HOME\nJRE_HOME=$JRE_HOME"
-echo -e "\nwhich java:"
-which java 2>/dev/null
-echo -e "\njava -version:"
-java -version
-JAVARC=$?
-grep -E '^JAVAHOME=|^JREHOME=|^JAVAVERSION=' /etc/javaif.conf > /tmp/javaifconf
-echo ''
-cat /tmp/javaifconf
-. /tmp/javaifconf
-[ $JAVARC -ne 0 ] && echo "Java is not installed." && exit
+echo -e "JAVA_HOME=$JAVA_HOME"
+if [ ! -s /root/.javaifrc ] \
+  || ! grep -qx "JAVAHOME=$JAVA_HOME" /root/.javaifrc; then
+  javaifchange
+ fi
+echo -e "\n.javaifrc:"
+if [ -f /root/.javaifrc ]; then
+ cat /root/.javaifrc
+ echo
+fi
+echo -en "\nwhich java:   "
+if which java 2>/dev/null; then
+ echo -n "which javaws: "
+ which javaws 2>/dev/null
+ echo -e "\njava -version:"
+ java -version
+ if which javaws &>/dev/null \
+   && javaws --help | grep -q '-version'; then
+  echo -e "\njavaws -version:"
+  javaws -version
+ fi
+else
+ echo "Java is not installed."
+ exit
+fi
 
-if [ "$JREHOME" != "$JAVAHOME" ] && echo "$JREHOME" | grep -q '/jre$' /etc/javaif.conf; then #JDK installed
+echo -e "\nPATH=$PATH"
+echo -e "\nLD_LIBRARY_PATH=$LD_LIBRARY_PATH"
+
+if which javac >/dev/null; then #JDK installed
  echo '/**
  * The HelloWorldApp class implements an application that
  * simply prints "Hello World!" to standard output.
@@ -29,5 +46,19 @@ class HelloWorldApp {
 else
  cd /usr/lib/javaif
 fi
+
 echo -e "\njava HelloWorldApp (expect Hello World!):"
 java HelloWorldApp
+
+echo -en "\nEnter any character to run an interactive JNLP example,\nand/or <Enter>: "
+read REPLY
+if [ -n "$REPLY" ]; then
+ cd /usr/lib/javaif
+ echo -e "\njavaws InputVerificationDemo.jnlp:"
+ javaws InputVerificationDemo.jnlp 2>/dev/null
+ if [ $? -eq 0 ]; then
+  echo 'Demonstration Completed'
+ else
+  echo 'Demonstration Aborted'
+ fi
+fi
