pupcamera: show error msg if gphotofs is missing

diff --git a/woof-code/rootfs-skeleton/usr/sbin/pupcamera b/woof-code/rootfs-skeleton/usr/sbin/pupcamera
--- a/woof-code/rootfs-skeleton/usr/sbin/pupcamera
+++ b/woof-code/rootfs-skeleton/usr/sbin/pupcamera
@@ -7,6 +7,14 @@
 # -- it detects if gphoto (and deps) not installed and informs the user.
 #pupcamera rewritten by mistfire. Interface and behavior based from pmount for Puppy 4.0
 
+if ! [ "`which gphoto2`" ];then
+	/usr/lib/gtkdialog/box_ok "PupCamera" error "<b>$(gettext "The 'gphoto2' application is not installed.")</b>" "$(gettext "That means PupCamera cannot access the photos on a digital camera. Please run the Package Manager to install 'gphoto2'.")"
+	exit 1
+elif ! [ "`which gphotofs`" ]; then
+	/usr/lib/gtkdialog/box_ok "PupCamera" error "<b>$(gettext "The 'gphotofs' application is not installed.")</b>" "$(gettext "That means PupCamera cannot access the photos on a digital camera. Please run the Package Manager to install 'gphotofs'.")"
+	exit 1
+fi
+
 PIDOFMTP=`pidof mtpdevice`
 [ "$PIDOFMTP" ] && exit # exits if mtpdevice process starts to tame udev rule 88-puppy-autodetect.rules
 
@@ -78,13 +86,7 @@ xPID=$!
 sleep 3s
 kill $xPID
 
-if [ "`which gphoto2`" ];then
-	gphoto2 --auto-detect | tr -s ' ' | tail -n +3 > /tmp/pcamera_ports
-else
-	/usr/lib/gtkdialog/box_ok "PupCamera" error "<b>$(gettext "The 'gphoto' application is not installed.")</b>" "$(gettext "That means PupCamera cannot access the photos on a digital camera. Please run the Puppy Package Manager (see 'install' icon on desktop) to install 'gphotofs' and it's dependencies.")"
-	exit
-fi
-
+gphoto2 --auto-detect | tr -s ' ' | tail -n +3 > /tmp/pcamera_ports
 content=`cat /tmp/pcamera_ports`
 
 cp /tmp/pcamera_ports /tmp/pcamera_port_name
@@ -120,7 +122,6 @@ do
   </button>
 </hbox>"
 	else
-		#<input file>${DRIVEXPM}</input>
 		PARTSGUI="${PARTSGUI}
 <hbox>
   <text space-expand=\"true\" space-fill=\"true\">
