puppyinstaller: simplify locate_puppy_src_files() a bit

diff --git a/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller b/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
--- a/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
+++ b/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
@@ -351,82 +351,37 @@ unmountcdfunc() {
 locate_puppy_src_files() {
 	SRCPATH=""
 	CDDRIVE=""
-	rm -f /tmp/srcpath.txt
-	mount | tr -s " " | cut -f 3 -d " " |
-	while read ONEDIR
-	do
-	 INCYES=0
-	 [ -f ${ONEDIR}/${DISTRO_PUPPYSFS} ] && INCYES=`expr $INCYES + 1` #v3.01 v424 100913
-	 [ -f $ONEDIR/vmlinuz ] && INCYES=`expr $INCYES + 1`
-	 [ -f $ONEDIR/initrd.gz ] && INCYES=`expr $INCYES + 1`
-	 if [ $INCYES -eq 3 ];then
-	  echo -n "$ONEDIR" > /tmp/srcpath.txt
-	  break
-	 fi
-	done
-	[ -f /tmp/srcpath.txt ] && SRCPATH="`cat /tmp/srcpath.txt`"
-	if [ "$SRCPATH" = "" ];then
-	 Xdialog --wmclass "gtkdialog2" --left --buttons-style text \
-	 --title "$L_PUPPY_INSTALLER" \
-	 --ok-label "CD" --cancel-label "$(gettext 'DIRECTORY')" \
-	 --yesno "$(eval_gettext "Puppy consists of 2 to 4 files:\
-\nvmlinuz      The Linux kernel\ninitrd.gz    The initial ramdisk.\
-\n${DISTRO_PUPPYSFS}  This has all the Puppy files (sometimes inside initrd.gz).\
-\n             (if built inside initrd.gz then only initrd.gz is required)\
-\n${DISTRO_ZDRVSFS} Extra kernel drivers and firmware (optional).\
-\n             (most builds have a usable selection of drivers in \
-${DISTRO_PUPPYSFS})\
-\nIf you booted Puppy from a live-CD, those files will be on it.\
-\nOtherwise, they are in the .iso file and can be extracted -- in that\
-\ncase, just click on the .iso file and it will be mounted (opened) in\
-\na directory (do not forget to click on the file later to unmount it!)\
-\n\nWhere are the Puppy files?...")" 0 0
-	 RETVAL=$?
-	 if [ $RETVAL -eq 0 ];then #CD
-	  CDDRIVE="`readlink /dev/cdrom`"
-	  CDDRIVE="`basename $CDDRIVE`"
-	  CDDRVINFO="`probedisk "/dev/$CDDRIVE" | cut -f 3 -d '|'`"
-	  Xdialog --wmclass "gtkdialog2" --left \
-	  --title "$L_PUPPY_INSTALLER" \
+	CDDRV=$(probedisk | grep optical | head -1)
+	if [ -d /initrd/${PUP_HOME}${PSUBDIR} ] ; then
+	    SRCPATH=/initrd/${PUP_HOME}${PSUBDIR}
+	elif [ "$PDEV1" ] ; then
+	    PDEV1_MP=$(LANG=C mount | grep "^/dev/${PDEV1} " | awk '{print $3}')
+	    SRCPATH=${PDEV1_MP}${PSUBDIR}
+	    if [ ! -d $SRCPATH -a $PUPMODE -eq 5 ] ; then
+			FS=$(blkid /dev/${PDEV1} | grep -o ' TYPE=.*' | cut -f 2 -d '"')
+			mkdir -p /mnt/$PDEV1
+			mount -t $FS /dev/$PDEV1 /mnt/$PDEV1
+			[ $? -eq 0 ] && SRCPATH=/mnt/${PDEV1}${PSUBDIR}
+	    fi
+	elif [ "$CDDRV" ] ; then
+        CDDRIVE=$(echo "$CDDRV" | cut -f 1 -d '|')
+        CDDRIVE=$(basename $CDDRIVE)
+        CDDRVINFO=$(echo "$CDDRV" | cut -f 3 -d '|')
+	    Xdialog --wmclass "gtkdialog2" --left --title "$L_PUPPY_INSTALLER" \
 	  --msgbox "$(eval_gettext "Please insert the Puppy live-CD (if not already) \
   into the drive.\nNote, in case your PC has two CD/DVD drives, \
   Puppy is expecting\nthe live-CD to be inserted into $CDDRIVE, which is \
   described as:\n $CDDRVINFO \n\nAfter inserting live-CD, \
   click OK button...")" 0 0
-	  mkdir /mnt/$CDDRIVE 2> /dev/null
-	  mount -t iso9660 /dev/$CDDRIVE /mnt/$CDDRIVE
-	  if [ -f /mnt/$CDDRIVE/initrd.gz ];then
-	   SRCPATH="/mnt/$CDDRIVE"
-	  else
-	   Xdialog --wmclass "gtkdialog2" --left \
-	   --title "$(gettext 'Puppy universal installer: ERROR')" \
-	   --msgbox "$(gettext 'Sorry, Puppy is not on the CD.\nPlease mount the CD \
-using one of the mount programs\n(see File Managers menu) \
-then click OK button...')" 0 0
-	   RETVAL=1
-	  fi 
-	 fi
-	 if [ ! $RETVAL -eq 0 ];then #DIRECTORY
-	  if [ -d /initrd/${PUP_HOME}${PSUBDIR} ] ; then
-	    HOMEDIR=/initrd/${PUP_HOME}${PSUBDIR}
-	  else
-	    PDEV1_MP=$(LANG=C mount | grep "^/dev/${PDEV1} " | awk '{print $3}')
-	    HOMEDIR=${PDEV1_MP}${PSUBDIR}
-	    if [ ! -d "$HOMEDIR" -a $PUPMODE -eq 5 -a "$PDEV1" != "" ] ; then
-	      mkdir -p /mnt/$PDEV1
-	      mount /dev/$PDEV1 /mnt/$PDEV1
-	      [ $? -eq 0 ] && HOMEDIR=/mnt/${PDEV1}${PSUBDIR}
+	    mkdir /mnt/$CDDRIVE 2> /dev/null
+	    mount -t iso9660 /dev/$CDDRIVE /mnt/$CDDRIVE
+	    if [ -f /mnt/$CDDRIVE/initrd.gz -o -f /mnt/$CDDRIVE/initrd.xz ];then
+	      SRCPATH="/mnt/$CDDRIVE"
 	    fi
-	  fi
-	  [ ! -d "$HOMEDIR" ] && HOMEDIR=$CWD
-	  cd "$HOMEDIR"
-	  SRCFPATH="`/usr/lib/gtkdialog/file_chooser "$L_PUPPY_INSTALLER" "$(eval_gettext "Please find the latest Puppy files - vmlinuz, initrd.gz and ${DISTRO_PUPPYSFS} - THEN HIGHLIGHT ANY ONE OF THEM and click the OK button")"`"
-	  [ ! $? -eq 0 ] && exit
-	  SRCPATH="`dirname $SRCFPATH`"
-	  cd "$CWD"
-	 fi
+	else
+        /usr/lib/gtkdialog/box_ok "$(gettext 'Puppy Installer')" error "$(gettext 'ERROR: Need a CD drive with with the installation disc inserted...')"
+        exit 1
 	fi
-	SRCPATH=`echo "${SRCPATH}" | head -n 1`
 	#sanity check...
 	if [ ! -f ${SRCPATH}/${DISTRO_PUPPYSFS} ];then #v3.01 v424 100913
 	 [ "$SRCPATH" = "/mnt/$CDDRIVE" ] && eject /dev/$CDDRIVE
