puppyinstaller: improve locate_puppy_src_files() and unmountcdfunc()

diff --git a/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller b/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
--- a/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
+++ b/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller
@@ -291,17 +291,28 @@ read yesgo
 }
 
 unmountcdfunc() {
-	if [ "$CDDRIVE" -a "`mount | grep "/dev/$CDDRIVE"`" ];then
-		rox -D "`mount | grep "/dev/$CDDRIVE" | tr -s " " | cut -f 3 -d " "`"
-		umount /dev/$CDDRIVE && eject /dev/$CDDRIVE
+	if [ "$CDDRIVE" -a "`mount | grep "^/dev/$CDDRIVE " | cut -f 3 -d ' '`" ];then
+		rox -D /dev/$CDDRIVE 2>/dev/null
+		umount /dev/$CDDRIVE "`mount | grep "^/dev/$CDDRIVE " | cut -f 3 -d ' '`"
+	fi
+	if [ "$ISO_MP" -a "`mount | grep " $ISO_MP "`" ] ; then
+		umount $ISO_MP 2>/dev/null #iso mountpoint
 	fi
 }
 
 locate_puppy_src_files() {
-	SRCPATH=""
-	CDDRIVE=""
+	SRCPATH="" CDDRIVE="" ISO_MP=""
 	CDDRV=$(probedisk | grep optical | head -1)
-	if [ -d /initrd/${PUP_HOME}${PSUBDIR} ] ; then
+	if [ $PUPMODE -eq 2 ] ; then #full install
+		SRCPATH=/mnt/iso_file
+		cd $HOME
+		ISO_FILE=$(/usr/lib/gtkdialog/file_chooser "ISO File" "$(gettext "Please select a Puppy live-CD .iso file for $DISTRO_NAME $DISTRO_VERSION ")")
+		[ $? -ne 0 ] && exit 1
+		umount ${SRCPATH} 2>/dev/null
+		mkdir -p ${SRCPATH}
+		mount -t iso9660 -o loop ${ISO_FILE} ${SRCPATH}
+		ISO_MP=${SRCPATH}
+	elif [ -d /initrd/${PUP_HOME}${PSUBDIR} ] ; then
 		SRCPATH=/initrd/${PUP_HOME}${PSUBDIR}
 	elif [ "$PDEV1" ] ; then
 		PDEV1_MP=$(LANG=C mount | grep "^/dev/${PDEV1} " | awk '{print $3}')
@@ -324,19 +335,13 @@ locate_puppy_src_files() {
   click OK button...")" 0 0
 		mkdir /mnt/$CDDRIVE 2> /dev/null
 		mount -t iso9660 /dev/$CDDRIVE /mnt/$CDDRIVE
-		if [ -f /mnt/$CDDRIVE/initrd.gz -o -f /mnt/$CDDRIVE/initrd.xz ];then
-			SRCPATH="/mnt/$CDDRIVE"
-		fi
-	else
-		/usr/lib/gtkdialog/box_ok "$(gettext 'Puppy Installer')" error "$(gettext 'ERROR: Need a CD drive with with the installation disc inserted...')"
-		exit 1
+		SRCPATH="/mnt/$CDDRIVE"
 	fi
 	#sanity check...
 	if [ ! -f ${SRCPATH}/${DISTRO_PUPPYSFS} ];then #v3.01 v424 100913
-		[ "$SRCPATH" = "/mnt/$CDDRIVE" ] && eject /dev/$CDDRIVE
+		unmountcdfunc
 		Xdialog --wmclass "gtkdialog2" --left \
-			--title "$(gettext 'Puppy universal installer: ERROR')" \
-			--msgbox "`eval_gettext \"Oh dear, a 'sanity check' has failed.\
+			--title "$(gettext 'ERROR')" --msgbox "`eval_gettext \"Oh dear, a 'sanity check' has failed.\
  \nThis file: \\\$SRCPATH/\\\${DISTRO_PUPPYSFS}\ndoes not exist.\nThe above \
  is supposed to be path-to-where-puppy-files-are/\\\${DISTRO_PUPPYSFS}\
  \nClick OK button to quit...\"`" 0 0
