puppyapps: implement -sort option for the gui puppyapps -sort 0..2 0 dont sort 1 sort by internal category name 2 sort by category description [default]
requested by mavrothal

diff --git a/woof-code/rootfs-skeleton/usr/sbin/puppyapps b/woof-code/rootfs-skeleton/usr/sbin/puppyapps
--- a/woof-code/rootfs-skeleton/usr/sbin/puppyapps
+++ b/woof-code/rootfs-skeleton/usr/sbin/puppyapps
@@ -7,6 +7,7 @@ export TEXTDOMAIN=puppyapps
 export OUTPUT_CHARSET=UTF-8
 DEFAULTAPPS=""
 IGNORE_ALREADY_SET=""
+SORT=2
 APPS_DEFAULT_EXEC="$(gettext 'Autodetect')"
 [ ! -d /tmp/puppyapps ] && mkdir -p /tmp/puppyapps
 
@@ -383,7 +384,7 @@ for arg in "$@" ; do
 			done
 			exit
 			;;
-		-m)
+		-m) ###gui###
 			shift
 			DEFAULTAPPS=$(
 				while [ "$1" ]; do
@@ -441,6 +442,14 @@ for arg in "$@" ; do
 			done
 			exit
 			;;
+		-sort) ###gui###
+			shift
+			case $1 in
+				0|1|2) SORT=$1 ;;
+				*) echo "ERROR: -sort only accepts 0,1,2" >&2 ; exit 1;;
+			esac
+			shift
+			;;
 		-h|--help)
 			echo 'Usage: puppyapps [OPTION(S)]
 
@@ -477,6 +486,10 @@ for arg in "$@" ; do
                  and choose one of them and will write it to the defaultapp.
                  If no program is found for a specific default app,
                  then puppyapps will manage it.
+  -sort 0..2     For the GUI
+                 0) Dont sort
+                 1) Sort by internal category name
+                 2) Sort by category description [default]
   -h, --help     Show this help message
   
   
@@ -533,10 +546,11 @@ make_item() {
 }
 
 make_box() {
-	LABEL=$1
-	VARIABLE=$2
+	VARIABLE=$1
+	ICON=$2
+	shift 2
+	LABEL="$@"
 	APP="${VARIABLE,,}" ##lowercase #APP="`echo $2 | tr [A-Z] [a-z]`"
-	ICON=$3
 	#find default executable
 	DEFAULT_EXEC=$(get_default $APP)
 	retval=$?
@@ -579,6 +593,93 @@ list_active (){
 	defaulttextviewer /tmp/puppyapps/puppyapps_tmp &
 }
 
+#TRANSLATIONS
+__WORDPROCESSOR="$(gettext "Word processor")"
+__TEXTEDITOR="$(gettext  "Text editor")"
+__TEXTVIEWER="$(gettext  "Text viewer")"
+__PDFVIEWER="$(gettext  "PDF viewer")"
+__CHMVIEWER="$(gettext  "CHM viewer")"
+__SPREADSHEET="$(gettext  "Spreadsheet")"
+__CALENDAR="$(gettext  "Calendar")"
+__CONTACT="$(gettext  "Contact")"
+__MEDIAPLAYER="$(gettext  "Media player")"
+__MUSICPLAYER="$(gettext  "Music player")"
+__AUDIOPLAYER="$(gettext  "Audio Player")"
+__AUDIOEDITOR="$(gettext  "Audio Editor")"
+__AUDIOMIXER="$(gettext  "Audio Mixer")"
+__CDPLAYER="$(gettext  "CD player")"
+__CDRECORDER="$(gettext  "CD recorder")"
+__PAINT="$(gettext  "Paint")"
+__DRAW="$(gettext  "Draw")"
+__IMAGEEDITOR="$(gettext  "Image editor")"
+__IMAGEVIEWER="$(gettext  "Image viewer")"
+__SCREENSHOT="$(gettext  "Screenshot")"
+__FILEMANAGER="$(gettext  "File manager")"
+__ARCHIVER="$(gettext  "Archiver")"
+__SEARCH="$(gettext  "Search")"
+__TERMINAL="$(gettext  "Terminal")"
+__PROCESSMANAGER="$(gettext  "Process manager")"
+__RUN="$(gettext  "App runner")"
+__BROWSER="$(gettext  "Web browser")"
+__EMAIL="$(gettext  "Mail")"
+__HTMLEDITOR="$(gettext  "HTML editor")"
+__HTMLVIEWER="$(gettext  "HTML viewer")"
+__CONNECT="$(gettext  "Connect")"
+__CHAT="$(gettext  "Chat")"
+__BAREHTMLVIEWER="$(gettext  "Bare HTML Viewer")"
+
+APPDATA="WORDPROCESSOR document $__WORDPROCESSOR
+TEXTEDITOR edit $__TEXTEDITOR
+TEXTVIEWER document_viewer $__TEXTVIEWER
+PDFVIEWER pdf $__PDFVIEWER
+CHMVIEWER document_viewer $__CHMVIEWER
+SPREADSHEET spreadsheet $__SPREADSHEET
+CALENDAR calendar $__CALENDAR
+CONTACT user $__CONTACT
+MEDIAPLAYER multimedia $__MEDIAPLAYER
+MUSICPLAYER audio $__MUSICPLAYER
+AUDIOPLAYER audio $__AUDIOPLAYER
+AUDIOEDITOR edit_sound $__AUDIOEDITOR
+AUDIOMIXER sound_mixer $__AUDIOMIXER
+CDPLAYER cd_audio $__CDPLAYER
+CDRECORDER cd_burn $__CDRECORDER
+PAINT draw $__PAINT
+DRAW draw_vector $__DRAW
+IMAGEEDITOR edit_image $__IMAGEEDITOR
+IMAGEVIEWER image_viewer $__IMAGEVIEWER
+SCREENSHOT photocamera $__SCREENSHOT
+FILEMANAGER directory $__FILEMANAGER
+ARCHIVER package_compressed $__ARCHIVER
+SEARCH find $__SEARCH
+TERMINAL terminal $__TERMINAL
+PROCESSMANAGER execute $__PROCESSMANAGER
+RUN execute $__RUN
+BROWSER internet $__BROWSER
+EMAIL mail $__EMAIL
+HTMLEDITOR edit_html $__HTMLEDITOR
+HTMLVIEWER document_viewer $__HTMLVIEWER
+CONNECT internet_connect $__CONNECT
+CHAT chat $__CHAT
+BAREHTMLVIEWER internet $__BAREHTMLVIEWER"
+
+case $SORT in
+	0)
+		echo "$APPDATA" | while read adata ; do
+			make_box $adata
+		done > /tmp/puppyapps/gui_boxes
+		;;
+	1)
+		echo "$APPDATA" | sort | while read adata ; do
+			make_box $adata
+		done > /tmp/puppyapps/gui_boxes
+		;;
+	2)
+		echo "$APPDATA" | sort -k3 | while read adata ; do
+			make_box $adata
+		done > /tmp/puppyapps/gui_boxes
+		;;
+esac
+
 #build help GUI
 gettext "<b>Helpful Tips</b>
 You can add custom commands, parameters and options by typing the desired command in the chosen field and clicking the apply button. To load apps through the terminal, simply add 'rxvt -e ' before the command you wish to execute in the terminal.
@@ -593,39 +694,7 @@ export GUI='
   <vbox space-expand="true" space-fill="true">
     <hbox shadow-type="0" scrollable="true" space-expand="true" space-fill="true">
       <frame>
-        '$(make_box "$(gettext  "Word processor")" WORDPROCESSOR document)'
-        '$(make_box "$(gettext  "Text editor")" TEXTEDITOR edit)'
-        '$(make_box "$(gettext  "Text viewer")" TEXTVIEWER document_viewer)'
-        '$(make_box "$(gettext  "PDF viewer")" PDFVIEWER pdf)'
-        '$(make_box "$(gettext  "CHM viewer")" CHMVIEWER document_viewer)'
-        '$(make_box "$(gettext  "Spreadsheet")" SPREADSHEET spreadsheet)'
-        '$(make_box "$(gettext  "Calendar")" CALENDAR calendar)'
-        '$(make_box "$(gettext  "Contact")" CONTACT user)'
-        '$(make_box "$(gettext  "Media player")" MEDIAPLAYER multimedia)'
-        '$(make_box "$(gettext  "Music player")" MUSICPLAYER audio)'
-        '$(make_box "$(gettext  "Audio Player")" AUDIOPLAYER audio)'
-        '$(make_box "$(gettext  "Audio Editor")" AUDIOEDITOR edit_sound)'
-        '$(make_box "$(gettext  "Audio Mixer")" AUDIOMIXER sound_mixer)'
-        '$(make_box "$(gettext  "CD player")" CDPLAYER cd_audio)'
-        '$(make_box "$(gettext  "CD recorder")" CDRECORDER cd_burn)'
-        '$(make_box "$(gettext  "Paint")" PAINT draw)'
-        '$(make_box "$(gettext  "Draw")" DRAW draw_vector)'
-        '$(make_box "$(gettext  "Image editor")" IMAGEEDITOR edit_image)'
-        '$(make_box "$(gettext  "Image viewer")" IMAGEVIEWER image_viewer)'
-        '$(make_box "$(gettext  "Screenshot")" SCREENSHOT photocamera)'
-        '$(make_box "$(gettext  "File manager")" FILEMANAGER directory)'
-        '$(make_box "$(gettext  "Archiver")" ARCHIVER package_compressed)'
-        '$(make_box "$(gettext  "Search")" SEARCH find)'
-        '$(make_box "$(gettext  "Terminal")" TERMINAL terminal)'
-        '$(make_box "$(gettext  "Process manager")" PROCESSMANAGER execute)'
-        '$(make_box "$(gettext  "App runner")" RUN execute)'
-        '$(make_box "$(gettext  "Web browser")" BROWSER internet)'
-        '$(make_box "$(gettext  "Mail")" EMAIL mail)'
-        '$(make_box "$(gettext  "HTML editor")" HTMLEDITOR edit_html)'
-        '$(make_box "$(gettext  "HTML viewer")" HTMLVIEWER document_viewer)'
-        '$(make_box "$(gettext  "Connect")" CONNECT internet_connect)'
-        '$(make_box "$(gettext  "Chat")" CHAT chat)'
-        '$(make_box "$(gettext  "Bare HTML Viewer")" BAREHTMLVIEWER internet)'
+        '$(< /tmp/puppyapps/gui_boxes)'
         <vbox space-expand="true" space-fill="true">
           <text space-expand="true" space-fill="true"><label>""</label></text>
         </vbox>
