puppyapps: implement -rows option for the gui For this I had to rework some things.
    -rows N (gui) max number of rows per column [default: '${GUI_MAXROWS}']

There are two new important variables:
GUI_MAXROWS=11
GUI_COUNT=0 (to replace /tmp/puppyapps/puppyapps_count)

You can combine -sort, -rows and -m

    puppyapps -rows 8 -sort 1 -m mediaplayer htmleditor audioeditor #etc

diff --git a/woof-code/rootfs-skeleton/usr/sbin/puppyapps b/woof-code/rootfs-skeleton/usr/sbin/puppyapps
--- a/woof-code/rootfs-skeleton/usr/sbin/puppyapps
+++ b/woof-code/rootfs-skeleton/usr/sbin/puppyapps
@@ -7,9 +7,13 @@ export TEXTDOMAIN=puppyapps
 export OUTPUT_CHARSET=UTF-8
 DEFAULTAPPS=""
 IGNORE_ALREADY_SET=""
-SORT=2
 APPS_DEFAULT_EXEC="$(gettext 'Autodetect')"
 [ ! -d /tmp/puppyapps ] && mkdir -p /tmp/puppyapps
+
+GUI_SORT=2
+GUI_MAXROWS=11
+GUI_COUNT=0 #count available default* - for columns in gui
+   #for this to work, we must avoid creating a subshell or pipe | (*)
 
 
     ############################
@@ -445,9 +449,17 @@ for arg in "$@" ; do
 		-sort) ###gui###
 			shift
 			case $1 in
-				0|1|2) SORT=$1 ;;
+				0|1|2) GUI_SORT=$1 ;;
 				*) echo "ERROR: -sort only accepts 0,1,2" >&2 ; exit 1;;
 			esac
+			;;
+		-rows) ###gui###
+			shift
+			if [[ "$1" -gt 0 && "$1" -lt 101 ]] ; then
+				GUI_MAXROWS=$1
+			else
+				echo "ERROR: -rows only accepts 1-100" >&2 ; exit 1
+			fi
 			;;
 		-h|--help)
 			echo 'Usage: puppyapps [OPTION(S)]
@@ -489,6 +501,7 @@ for arg in "$@" ; do
                  0) Dont sort
                  1) Sort by internal category name
                  2) Sort by category label [default]
+  -rows N        (gui) max number of rows per column [default: '${GUI_MAXROWS}']
   -h, --help     Show this help message
   
   
@@ -507,7 +520,6 @@ done
     ############################
 
 desktop_output
-echo 0 > /tmp/puppyapps/puppyapps_count #count available default* - for columns in gui
 
 #check if -m switch has been used
 if [ -z "$DEFAULTAPPS" -a -z "$1" ]; then
@@ -559,13 +571,11 @@ make_box() {
 	esac
 	[ ! "$DEFAULT_EXEC" ] && return #do not allow empty $DEFAULT_EXEC
 	#new frame
-	N="$(</tmp/puppyapps/puppyapps_count)"
-	if [ "$N" -gt 10 ]; then
-		N=0
+	if [ ${GUI_COUNT} -ge ${GUI_MAXROWS} ]; then #ge = greater or equal
+		GUI_COUNT=0
 		echo '</frame><frame>'
 	fi
-	N=$(($N + 1))
-	echo -n $N > /tmp/puppyapps/puppyapps_count
+	GUI_COUNT=$(($GUI_COUNT + 1))
 	#---
 	echo '
 	<vbox space-expand="false" space-fill="false">
@@ -625,23 +635,16 @@ CONNECT internet_connect $(gettext 'Connect')
 CHAT chat $(gettext 'Chat')
 BAREHTMLVIEWER internet $(gettext 'Bare HTML Viewer')"
 
-case $SORT in
-	0)
-		echo "$APPDATA" | while read adata ; do
-			make_box $adata
-		done > /tmp/puppyapps/gui_boxes
-		;;
-	1)
-		echo "$APPDATA" | sort | while read adata ; do
-			make_box $adata
-		done > /tmp/puppyapps/gui_boxes
-		;;
-	2)
-		echo "$APPDATA" | sort -k3 | while read adata ; do
-			make_box $adata
-		done > /tmp/puppyapps/gui_boxes
-		;;
+case $GUI_SORT in
+	0) APPDATA2="$APPDATA" ;; 						#dont sort
+	1) APPDATA2="$(echo "$APPDATA" | sort)" ;;		#sort by category name
+	2) APPDATA2="$(echo "$APPDATA" | sort -k3)" ;;	#sort by label
+	*) echo "ERROR: invalid value for \$GUI_SORT" >&2 ; exit 1;;
 esac
+
+while read adata ; do
+	make_box $adata
+done <<< "$APPDATA2" > /tmp/puppyapps/gui_boxes #(*)
 
 #build help GUI
 gettext "<b>Helpful Tips</b>
