Major clean up of the xrandr code fixing at least six errors where break downs were occuring. Request for KRG to test.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/quicksetup b/woof-code/rootfs-skeleton/usr/sbin/quicksetup
--- a/woof-code/rootfs-skeleton/usr/sbin/quicksetup
+++ b/woof-code/rootfs-skeleton/usr/sbin/quicksetup
@@ -1049,22 +1049,28 @@ This resolution selection box uses the <b>xrandr</b> utility to set the resoluti
    echo $p | awk '{print $1,$2}'
    e=`echo $p | awk '{print $3}'`
    if [ "$e" != "" ];then
+   [ "$e" = "+" ] && continue
    echo $p | awk '{print $1,$3}'
    fi
    f=`echo $p | awk '{print $4}'`
    if [ "$f" != "" ];then
+   [ "$f" = "+" ] && continue
    echo $p | awk '{print $1,$4}'
    fi
    g=`echo $p | awk '{print $5}'`
    if [ "$g" != "" ];then
+   [ "$g" = "+" ] && continue
    echo $p | awk '{print $1,$5}'
    fi
-  done)" #131121
+  done)" #131121 #131124 sort out "+" ..is it necessary to go beyond $5?
   LIST_XYRESES=""
   [ "$xXYRESES" ] && LIST_XYRESES="$(echo "$xXYRESES" | sed -e 's%$% "" off%')"
   echo "$LIST_XYRESES" > /var/local/quickset-xrandr-list
-  onPTN="s%^${DEF_XYRES} \"(.*)\" off$%${DEF_XYRES} \"\1\" on%"
-  sed -i -e 's% on$% off%' -r -e "$onPTN" /var/local/quickset-xrandr-list
+  #onPTN="s%^${DEF_XYRES} .\+ off$%${DEF_XYRES} \"\1\" on%"
+  #sed -i -e 's% on$% off%' -r -e "$onPTN" /var/local/quickset-xrandr-list #not working here
+  RESLINE=`grep -n ${DEF_XYRES} /var/local/quickset-xrandr-list|grep "\*"` #get the line number of default
+  RESLINE=${RESLINE%%:*}
+  sed -i -e 's% on$% off%' -e ""$RESLINE"s%off$%on%" /var/local/quickset-xrandr-list
 
   DEFAULTXML=""
   DEFAULT=`grep ' on$' /var/local/quickset-xrandr-list | sed -e 's% on$%%' -e 's%"%%g' -e "s% % ${TABCHAR}%"`
@@ -1645,12 +1651,26 @@ if [ "$SET_XRES" ];then
   if [ $? -eq 0 ];then
    echo "ICONWIPE" > /var/local/pup_event_icon_change_flag #120226 .xinitrc -> clean_desk_icons will read this, and redraw drive icons.
    sync
-   xrandr -s $NEW_XYRES -r $NEW_VFREQ #this changes the screen resolution. #130202 add freq.
+   xrandr -s $NEW_XYRES -r $NEW_VFREQ 2>/tmp/xrandr_error #this changes the screen resolution. #130202 add freq.
+   if [ "$?" -ne "0" ];then
+     # try without frequency
+     xrandr -s $NEW_XYRES 2>/dev/null
+     bFLG=1 #flag so correct entry entered to /etc/xrandrindex
+     if [ "$?" -ne "0" ];then
+       BMSG=`cat /tmp/xrandr_error`
+       gtkdialog-splash -bg red -close box -timeout 5 -text "$BMSG" & #put out the old error, maybe it will work anyway, does here
+       rm /tmp/xrandr_error
+       unset bFLG
+       exit
+     fi
+   fi
    XRANDR="`xrandr -q`"
    TESTLINE="$(echo "$XRANDR" | tr -s " " | grep "^ [0-9]" | grep '\*' | head -n 1)" #130202 'head -n 1' workaround for dual monitors (see also .xinitrc).
+   
    TESTX="`echo -n "$TESTLINE" | cut -f 2 -d " " | cut -f 1 -d 'x'`"
    TESTY="`echo -n "$TESTLINE" | cut -f 2 -d " " | cut -f 2 -d 'x'`"
-   TESTVR="`echo -n "$TESTLINE" | cut -f 3 -d ' ' | cut -f 1 -d '*'`"
+   #TESTVR="`echo -n "$TESTLINE" | cut -f 3 -d ' ' | cut -f 1 -d '*'`" # this fails because its plain wrong!
+   TESTVR="`echo -n "$TESTLINE" |tr ' ' '\n' | grep "\*" | cut -f 1 -d '*'`" 
 
    M_y0=$(gettext 'Can you see this?')
    M_y1=$(gettext "Click <b>Permanent</b> button to keep this resolution permanently.
@@ -1678,7 +1698,10 @@ It is NOT recommended to choose <b>Permanent</b> here, as the default resolution
    eval $(${GTKDIALOGEXE} --program=XY_DIALOG --center)
    case $EXIT in
     permanent)
-     echo -n "${TESTX}x${TESTY}@${TESTVR}" > /etc/xrandrindex #so will be set in .xinitrc at next X start. #130202 added freq.
+     case $bFLG in
+      1)echo -n "${TESTX}x${TESTY}" > /etc/xrandrindex ;;
+      *)echo -n "${TESTX}x${TESTY}@${TESTVR}" > /etc/xrandrindex ;; #so will be set in .xinitrc at next X start. #130202 added freq.
+     esac
     ;;
     session)
      rm -f /etc/xrandrindex
