report-video:  show error msg on invalid option

diff --git a/woof-code/rootfs-skeleton/usr/sbin/report-video b/woof-code/rootfs-skeleton/usr/sbin/report-video
--- a/woof-code/rootfs-skeleton/usr/sbin/report-video
+++ b/woof-code/rootfs-skeleton/usr/sbin/report-video
@@ -122,7 +122,7 @@ function XorgConf() {
       sPTN='/^Section "Device"/,/^$/p' #this is a multi-line block find expression.
       echo "$(sed -n "$sPTN" /etc/X11/xorg.conf | tr '\t' ' ' | tr -s ' ' | grep '^[^#][ \t]*Driver ' | cut -f 2 -d '"' | tr '\n' ' ')"
       ;;
-    *) return 1 ;;
+    *) echo "Valid parameters for xorgconf: videodepth videores reqmods disabledmods reqdriver" >&2 ; return 1 ;;
   esac
 }
 
@@ -157,6 +157,8 @@ case $1 in
   actualres)ActualResolution  ; exit $? ;;
   actualdepth)ActualDepth     ; exit $? ;;
   -h|--help|-help) help ; exit ;;
+  "") continue=1 ;;
+  *) echo "Invalid option: $1" >&2 ; exit 1 ;;
 esac
 
 ##############################################
