sfs_load: another minor cleanup
another harry's bar

diff --git a/woof-code/rootfs-skeleton/usr/sbin/sfs_load b/woof-code/rootfs-skeleton/usr/sbin/sfs_load
--- a/woof-code/rootfs-skeleton/usr/sbin/sfs_load
+++ b/woof-code/rootfs-skeleton/usr/sbin/sfs_load
@@ -106,8 +106,6 @@ JWMRC="$HOME/.jwmrc"
 mkdir -p "$MYTMPDIR"
 
 export DEBUGFLAG=""
-[ "$(echo $VERSION|cut -b1)" = "0" ] && DEBUGFLAG="y"
-echo $MYNAME | grep -q 'debug' && DEBUGFLAG="y"
 tty | grep -q '^/dev/[^c]' && DEBUGFLAG="y"
 case "$1" in
 	-d|--debug) DEBUGFLAG="y";;
@@ -430,33 +428,29 @@ afterwork() {
 	[ "$HAS_GLIB_SCHEMA" ] && /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/ 
 	[ "$HAS_PINS" ] && mergepin
 	[ "$HAS_PINS_REMOVED" ] && removepin
-	if [ "$HAS_PINS" -o "$HAS_PINS_REMOVED" ] && which restartjwm &>/dev/null; then
-		[ "$DISPLAY" ] && restartjwm
-	else
-		[ "$HAS_PINS" -o "$HAS_PINS_REMOVED" ] && restart_rox
-		if [ "$HAS_DESKTOPS" -a -z "$SKIP_FIXMENUS" ]; then
-			waitsplash $(gettext "Updating menu...")
-			#v2.0: refresh default applications
-			if [ "$ACTION" != "load" ] && which defaults-chooser &>/dev/null; then
-				for F in $(ls /usr/local/bin/default* | grep -v 'defaults-changer') ; do
-					P=$(head "$F" | grep '^[^#]*exec '| grep -vw 'defaults-chooser' | head -n 1 | sed -e 's/^.*exec[ ]//' -e 's/.\$@.*$//')
-					[ "$P" ] || continue
-					X=$(echo $P| sed -e 's/rxvt [ ]*-e //'| cut -d' ' -f1)
-					[ "$X" ] && [ "$(echo $X| cut -c1)" != "/" ] && X=$(which "$X")
-					[ -x "$X" ] && continue
-					echo '#!/bin/sh
+	[ "$HAS_PINS" -o "$HAS_PINS_REMOVED" ] && restart_rox
+	if [ "$HAS_DESKTOPS" -a -z "$SKIP_FIXMENUS" ]; then
+		waitsplash $(gettext "Updating menu...")
+		#v2.0: refresh default applications
+		if [ "$ACTION" != "load" ] && which defaults-chooser &>/dev/null; then
+			for F in $(ls /usr/local/bin/default* | grep -v 'defaults-changer') ; do
+				P=$(head "$F" | grep '^[^#]*exec '| grep -vw 'defaults-chooser' | head -n 1 | sed -e 's/^.*exec[ ]//' -e 's/.\$@.*$//')
+				[ "$P" ] || continue
+				X=$(echo $P| sed -e 's/rxvt [ ]*-e //'| cut -d' ' -f1)
+				[ "$X" ] && [ "$(echo $X| cut -c1)" != "/" ] && X=$(which "$X")
+				[ -x "$X" ] && continue
+				echo '#!/bin/sh
 defaults-chooser' > $F
-					chmod +x $F
-					log "'$(basename $F)' is reset."
-				done
-			fi
-			fixmenus
-			if [ "$DISPLAY" ] && pidof jwm &>/dev/null; then
-				#v1.9.3: jwm -reload without flicker (01mico)
-				jwm -reload &>/dev/null || jwm -restart
-			fi
-			waitsplash --stop
+				chmod +x $F
+				log "'$(basename $F)' is reset."
+			done
 		fi
+		fixmenus
+		if [ "$DISPLAY" ] && pidof jwm &>/dev/null; then
+			#v1.9.3: jwm -reload without flicker (01mico)
+			jwm -reload &>/dev/null || jwm -restart
+		fi
+		waitsplash --stop
 	fi
 	if [ "$ACTION" = "load" ]; then
 		if [ "$HAS_PROFILE" != "" ]; then # 28 Oct 2011
@@ -657,22 +651,9 @@ loadable_sfs_list() {
 	debug "loadable_sfs_list $@"
 	# puppy system file names
 	[ "$MYTMPDIR" != "" ] && mkdir -p "$MYTMPDIR"
-	rm -f "$WRONGVERSION"
 	[ "$DISTRO_PUPPYSFS" = "" ] && DISTRO_PUPPYSFS=$SFSBASE
 	[ "$DISTRO_VERSION" = "" ] && DISTRO_VERSION=$(basename $DISTRO_PUPPYSFS .sfs| tr '_' '-'| cut -s -d'-' -f2)
 	[ "$DISTRO_FILE_PREFIX" = "" ] && DISTRO_FILE_PREFIX=$(echo $DISTRO_PUPPYSFS| tr '_' '-'| cut -d'-' -f1)
-	if [ "${DISTRO_ZDRVSFS}" = "" ]; then
-		[ "$ZDRBASE" != "" ] && DISTRO_ZDRVSFS=$ZDRBASE || DISTRO_ZDRVSFS="zdrv"
-	fi
-	if [ "${DISTRO_ADRVSFS}" = "" ]; then	#v1.9.2
-		[ "$ADRBASE" != "" ] && DISTRO_ADRVSFS=$ADRBASE || DISTRO_ADRVSFS="adrv"
-	fi
-	if [ "${DISTRO_YDRVSFS}" = "" ]; then	#v2.0.11
-		[ "$YDRBASE" != "" ] && DISTRO_YDRVSFS=$YDRBASE || DISTRO_YDRVSFS="ydrv"
-	fi
-	if [ "${DISTRO_FDRVSFS}" = "" ]; then
-		[ "$FDRBASE" != "" ] && DISTRO_FDRVSFS=$FDRBASE || DISTRO_FDRVSFS="fdrv"
-	fi
 	ALLSFSLIST=""
 	#if [ "$PUPHOME" != "" -a  "$PUPHOME" != "/" ]; then
 	if [ "$PUPHOME" != "" ]; then
@@ -746,12 +727,6 @@ main_dialog() {
       </button></hbox>'
 		ENABLEBROWS='<action>enable:FILE_BROWSE</action>'
 	fi
-	WRONGTEXT=""
-	if [ -s "$WRONGVERSION" ]; then
-		WRONGVERSION=$(sort -u "$WRONGVERSION")
-		WRONGVERSION=$(echo $WRONGVERSION | sed -e 's/ /\\n/g')
-		WRONGTEXT='<text><input>echo -en "'$(gettext "The followings are the different version"):'\n'$WRONGVERSION'"</input><visible>disabled</visible></text>'
-	fi
 	UNLOADCOMBO=""
 	if [ "$ALREADY_SFS_LIST" != "" ]; then
 		UNLOADABLE="enabled"
@@ -771,8 +746,7 @@ main_dialog() {
    </hbox>
 	<hbox width-request="'$BOXWIDTH'"><frame '$(gettext "Load SFS")'>
 	<vbox height-request="'$BOXHEIGHT1'">
-   '"$LOADCOMBO
-	$WRONGTEXT"'
+   '"$LOADCOMBO"'
 	</vbox>
 	<button tooltip-text="'$(gettext "Which SFS do you want to load?")' '$(gettext "Click here after you choose the extra sfs file.")'">
 	<input file stock="gtk-add"></input><label>'$(gettext 'Load')'</label>
@@ -789,7 +763,7 @@ main_dialog() {
     </frame></hbox>
     <hbox>
      <button tooltip-text="'$(gettext "Refresh list of loaded sfs.")'"><input file stock="gtk-refresh"></input><action>sfs_load &</action><action>EXIT:Abort</action></button>
-     <button tooltip-text="'$(eval_gettext "Quit $TITLE v$VERSION.")'"><input file stock="gtk-quit"></input><action>EXIT:Abort</action></button>
+     <button tooltip-text="'$(gettext "$(printf "Quit %s v%s." "$TITLE" "$VERSION")")'"><input file stock="gtk-quit"></input><action>EXIT:Abort</action></button>
     </hbox>
 	</vbox></window>'
 	waitsplash --stop
@@ -906,14 +880,6 @@ mountpart(){
 
 download_file() {
 	URLSPEC="$1"
-	#v1.9.4: never use external
-	# has extra program?
-	#EXTPROG=$(which download_file)
-	#if [ "$EXTPROG" ]; then
-	#  $EXTPROG "$@"
-	#  return
-	#fi
-	# internal func
 	for P in urxvt rxvt xterm; do
 		which $P &>/dev/null && RXVT="$P" && break
 	done
@@ -1280,7 +1246,7 @@ append_sfs() {
 		echo $PERM| grep -qw 'drwxr.xr.x' || STATUS=888
 		if [ $STATUS -ne 0 ]; then
 			debug "PERMISSION: $PERM"
-			PERMINFO=$(eval_gettext "'\$EXTRASFS' has the wrong permissions.")"\n'$PERM'"
+			PERMINFO=$(gettext "$(printf "%s has wrong permissions." "$EXTRASFS")")"\n'$PERM'"
 			busybox unmount "$MNTPNT"
 			free_loopdev "$LOOPDEV"
 		fi
@@ -1696,7 +1662,6 @@ esac
 
 [ -d "$MYTMPDIR" ] || mkdir -p "$MYTMPDIR"
 LOOPLIST="$MYTMPDIR/loop_device_list"
-WRONGVERSION="$MYTMPDIR/wrong_sfs_version"
 PUPMODE_dummy=$PUPMODE                          ############ for debugging
 #savefile_dummy=savefile
 DISTRO_NAME="Puppy"
@@ -1920,7 +1885,7 @@ if [ "$STARTSCRIPT" ]; then
 		afterwork
 		#v2.0: fix menu icons
 		if [ "$HAS_DESKTOPS" ] && pidof jwm &>/dev/null; then
-			[ "$NEED_FIXMENUS" ] && { jwm -reload &>/dev/null || jwm -restart ; }
+			[ "$NEED_FIXMENUS" ] && { jwm -reload || jwm -restart ; }
 			log "jwm restarted."
 		fi
 		PRINTDONE=1
