shutdownconfig: fix encrypted savefile creation on ext4, ntfs, exfat partitions
as it was failing to create working encrypted savefiles.

diff --git a/woof-code/rootfs-skeleton/usr/sbin/shutdownconfig b/woof-code/rootfs-skeleton/usr/sbin/shutdownconfig
--- a/woof-code/rootfs-skeleton/usr/sbin/shutdownconfig
+++ b/woof-code/rootfs-skeleton/usr/sbin/shutdownconfig
@@ -597,18 +597,18 @@ If anything looks wrong, choose \Zb\\\${T_notsave}\ZB...\"`"
   pupkill $w1PID #130525 moved down.
  else
   #note: loop2 is kept available for scripts to use. but, find which is free...
-  DEVLOOP="`losetup-222 -f`"
-  if [ "$DEVLOOP" = "" ];then
-   pupkill $w1PID #130525 moved down.
-   return 1
-  fi
+  echo -e "Save this log somewhere and close this window to continue...\n" >/tmp/mk2fs.log
+  DEVLOOP="$(losetup-222 -f)"
   #'-p 0' means read password from stdin...
-  echo "$MYPASSWORD" | losetup-222 -p 0 $CRYPTO $DEVLOOP ${SMNTPT}$SAVEFILE
-  if [ $? -ne 0 ];then
-   pupkill $w1PID #130525 moved down.
-   return 1
+  echo "losetup-222 -v -p 0 $CRYPTO $DEVLOOP ${SMNTPT}$SAVEFILE" >>/tmp/mk2fs.log
+  echo "$MYPASSWORD" | losetup-222 -v -p 0 $CRYPTO $DEVLOOP ${SMNTPT}$SAVEFILE &>>/tmp/mk2fs.log
+  mke2fs -v -t ext2 -m 0 -E nodiscard -F $DEVLOOP &>>/tmp/mk2fs.log && \
+  e2fsck -v -f -y -E discard $DEVLOOP &>>/tmp/mk2fs.log || e2fsck -v -f -y $DEVLOOP &>>/tmp/mk2fs.log
+  if [ $? -ne 0 ] ; then
+    pupkill $w1PID
+    /usr/lib/gtkdialog/box_ok "$(gettext 'Error')" error "$(gettext 'Unable to create ext2 filesystem')"
+    defaulttextviewer /tmp/mk2fs.log
   fi
-  mke2fs -q -m 0 $DEVLOOP #REMOVEDv3.98 added '-O none', fix mntg fail at boot.
   sync
   pupkill $w1PID #130525 moved down.
   losetup -d $DEVLOOP
