pupzip: cleanup

diff --git a/woof-code/rootfs-skeleton/usr/local/bin/pupzip b/woof-code/rootfs-skeleton/usr/local/bin/pupzip
--- a/woof-code/rootfs-skeleton/usr/local/bin/pupzip
+++ b/woof-code/rootfs-skeleton/usr/local/bin/pupzip
@@ -2,12 +2,6 @@
 #Barry Kauler 2005 www.puppylinux.com
 #frontend for XArchive.
 #well, i want this to be a universal archiver frontend for puppy.
-#v4.00 25apr2008 BK: now have full dpkg-deb in Puppy.
-#w474 support .delta, .bfe files.
-#100616 support .xz files. support slackware and arch pkgs.
-#120203 rodin.s: internationalized.
-#120512 added support for .rar (needs unrar or rar pkg installed).
-#131224 SFR: huge rewrite + added support for a few more common formats/extensions
 
 export TEXTDOMAIN=pupzip
 export TEXTDOMAINDIR=/usr/share/locale
@@ -16,31 +10,20 @@ export OUTPUT_CHARSET=UTF-8
 # -----------------------------------------------------------------------------
 
 eval_gettext () {
-  local myMESSAGE=$(gettext "$1")
-  eval echo \"$myMESSAGE\"
-}
-
-error_msg () {
-  xmessage -bg red -center -title "$(gettext 'PupZip: ERROR')" "$1"
+	local myMESSAGE=$(gettext "$1")
+	eval echo \"$myMESSAGE\"
 }
 
 request_msg () {
-  xmessage -bg yellow -buttons "$(gettext 'Yes'):100,$(gettext 'No'):101" -center -title "PupZip" "$1"
+	xmessage -bg yellow -buttons "$(gettext 'Yes'):100,$(gettext 'No'):101" -center -title "PupZip" "$1"
 }
 
 check_xarchive () {
-if [ ! "$XARCHIVE" ]; then
-  xmessage -bg "orange red" -center -title "$(gettext 'PupZip: ERROR')" "$(gettext 'No archive GUI program found.
+	if [ ! "$XARCHIVE" ]; then
+		xmessage -bg "orange red" -center -title "$(gettext 'PupZip: ERROR')" "$(gettext 'No archive GUI program found.
 Please install XArchive.')"
-  exit 1
-fi
-}
-
-add_to_xarchive () {
-  check_xarchive
-  if [ "$XARCHIVE" = "xarchive" ];then
-    exec $XARCHIVE --add=ask "$@"
-  fi
+		exit 1
+	fi
 }
 
 # -----------------------------------------------------------------------------
@@ -51,100 +34,44 @@ UNPACK_CMD=
 
 XARCHIVE=
 for i in engrampa file-roller xarchiver xarchive ; do
-  [ "`which $i 2>/dev/null`" ] && { XARCHIVE="$i"; break; }
+	[ "`which $i 2>/dev/null`" ] && { XARCHIVE="$i"; break; }
 done
 
-# -----------------------------------------------------------------------------
-
-if [ "$1" = "" ];then
-  #just start xarchive...
-  check_xarchive
-  exec $XARCHIVE
-
-elif [ "$1" = "--help" ];then
-
-  if [ "$XARCHIVE" = "xarchive" ];then
-    MSGE="$(gettext 'Drag and drop invocation of XArchive is achieved by dragging any file or
-directory to the "pupzip" icon on the desktop. If you drag one of the
-recognised archived files, such as .tar.gz, .rpm, .deb, .zip, .tar.bz2,
-it will open in XArchive and you will be given the opportunity to extract
-it. If you drag an ordinary file to the desktop icon, such as for example
-"myfile.txt", a XArchive will popup a dialog asking if you want to add
-it to an existing archive or create a new one.')"
-  else
-    MSGE="$(gettext 'There is support for drag-and-drop of archive files to the desktop icon,
-however not for files and directories -- for that you need to have 
-XArchive installed, the preferred archiver program for Puppy.')"
-  fi
-
-  xmessage -bg "orange" -center -title "$(gettext 'PupZip: help')" "
-`eval_gettext \"This is a frontend to \\\$XARCHIVE, which in turn is a frontend to the\"`
-$(gettext 'archiver utilities in Puppy (such as gzip, bzip2, dpkg, rpm, zip).')
-
-`eval_gettext \"Note: \\\$XARCHIVE can be started in the conventional way via the menu.\"`
-
-$MSGE
-
-$(gettext 'PupZip can also be invoked from Rox by the "Open With..." menu,
-by right-clicking on a file or directory.')"
-  exit
+if [ "$1" = "" ];then #just start xarchive...
+	check_xarchive
+	exec $XARCHIVE
 fi
-
-# -----------------------------------------------------------------------------
 
 # if multiple input files/dirs or directory itself - always add to xarchive!
 if [ "$#" -gt 1 ] || [ -d "$1" ]; then
-  add_to_xarchive "$@"
+	exec $XARCHIVE "$@"
 fi
 
 # -----------------------------------------------------------------------------
 
 case "$EXTENSION" in
-  *.bfe)   exec bcrypt_gui "$1" ;;
-  # -----------
-  *.delta) exec xdelta_gui "$1" ;;
-  # -----------
-  *.rpm)
-    #busybox applets are not adequate for handling rpm, deb...
-    #get absolute path of file...
-    FULLSPEC="$(realpath "$1")"
-    TMPARCH=/tmp/temprpm_${RANDOM}_${$}
-    mkdir $TMPARCH
-    cd $TMPARCH
-    exploderpm -x "$FULLSPEC"
-    if [ $? -ne 0 ];then
-      error_msg "$(gettext 'An error has occurred opening the RPM file.')"
-      exit 1
-    fi
-    sync
-    tar -c -f $TMPARCH.tar .
-    rm -rf $TMPARCH
-    cd /
-    $XARCHIVE $TMPARCH.tar
-    rm -f $TMPARCH.tar
-    cd $CDIR
-    exit
-  ;;
-  # -----------
-  *.7z|*.arj|*.deb|*.rar|*.tar|*.tar.bz|*.tar.bz2|*.tar.gz|*.tar.lzma|*.tar.xz|*.tbz|*.tbz2|*.tgz|*.tlz|*.txz|*.zip)
-    #ask if this is a slackware or arch binary pkg...
-    case "$EXTENSION" in
-      *.tgz|*.txz|*.pkg.tar.gz)
-      request_msg "$(gettext 'Is this a Slackware or Arch package, that you want to install?')
+	*.bfe)   exec bcrypt_gui "$1" ;;
+	# -----------
+	*.delta) exec xdelta_gui "$1" ;;
+	# -----------
+	*.rpm|*.7z|*.arj|*.deb|*.rar|*.tar|*.tar.bz|*.tar.bz2|*.tar.gz|*.tar.lzma|*.tar.xz|*.tbz|*.tbz2|*.tgz|*.tlz|*.txz|*.zip)
+		#ask if this is a slackware or arch binary pkg...
+		case "$EXTENSION" in *.tgz|*.txz|*.pkg.tar.gz)
+			request_msg "$(gettext 'Is this a Slackware or Arch package, that you want to install?')
 $(gettext 'If you answer Yes, the Package Manager application will run...')
 $(printf "$(gettext 'If you answer No, the %s application will run...')" "$XARCHIVE")"
-    [ $? -eq 100 ] && exec petget "$1"
-    ;;
-    esac
-    check_xarchive
-    exec $XARCHIVE "$1"
-  ;;
-  # -----------
-  *.gz)			UNPACK_CMD=gzip ;;
-  *.bz|*.bz2)	UNPACK_CMD=bzip2 ;;
-  *.lzma|*.xz)	UNPACK_CMD=xz ;;
-  # -----------
-  *) add_to_xarchive "$1" ;;
+			[ $? -eq 100 ] && exec petget "$1"
+			;;
+		esac
+		check_xarchive
+		exec $XARCHIVE "$1"
+		;;
+		# -----------
+	*.gz)			UNPACK_CMD=gzip ;;
+	*.bz|*.bz2)		UNPACK_CMD=bzip2 ;;
+	*.lzma|*.xz)	UNPACK_CMD=xz ;;
+	# -----------
+	*) exec $XARCHIVE "$1" ;;
 esac
 
 if [ "$XARCHIVE" != "xarchive" ];then
@@ -152,7 +79,10 @@ if [ "$XARCHIVE" != "xarchive" ];then
 fi
 
 # handle gz|bz(2)|lzma|xz internally
-[ "`which $UNPACK_CMD 2>/dev/null`" ] || { error_msg "`gettext \"ERROR: '$UNPACK_CMD' utility not installed\"`"; exit 1; }
+if ! [ "`which $UNPACK_CMD 2>/dev/null`" ] ; then
+	xmessage -bg red -center -title "$(gettext 'PupZip: ERROR')" "`gettext \"ERROR: '$UNPACK_CMD' utility not installed\"`"
+	exit 1
+fi
 
 request_msg "$(gettext 'Do you want to decompress') ${1}?
 ($(gettext 'it will decompress in current location
@@ -162,12 +92,7 @@ request_msg "$(gettext 'Do you want to decompress') ${1}?
 yaf-splash -bg orange -text "$(gettext 'Uncompressing, please wait...')" &
 UPID=$!
 
-# busybox applets, as well as full bzip2, don't support '--suffix' option
-if [ "$UNPACK_CMD" = "bzip2" ] || [ "`readlink -e \`which $UNPACK_CMD\` | grep 'busybox'`" ]; then
-  $UNPACK_CMD -d "$1"
-else
-  $UNPACK_CMD --suffix=".${1##*.}" -d "$1"	# in case if extension is in upper-case
-fi
+$UNPACK_CMD -d "$1"
   
 sync
 kill $UPID
