10alsa: misc edits

diff --git a/woof-code/rootfs-skeleton/etc/init.d/10alsa b/woof-code/rootfs-skeleton/etc/init.d/10alsa
--- a/woof-code/rootfs-skeleton/etc/init.d/10alsa
+++ b/woof-code/rootfs-skeleton/etc/init.d/10alsa
@@ -2,24 +2,13 @@
 #Barry Kauler april 2009, puppylinux.com
 #called from /etc/rc.d/rc.services at bootup, with 'start' param.
 #called from /etc/rc.d/rc.shutdown at shutdown, with 'stop' param.
-#101120, 101121 simplification.
-#110111 shinobar: for reliable sound detection on HP Compac nc4010.
-#110113 tweak delay. 110216 tweak delay.
-#110506 /usr/sbin/alsaconf has 'restart' option, might need to reprobe modules. for now, just 'start|restart'.
-#111229 add test file /etc/asound.state exists.
-#120103 karl godt: fix unloading modules. refer: http://www.murga-linux.com/puppy/viewtopic.php?t=71767&start=390
-#120222 revert 111229. 120223 shinobar: better fix.
-#120226 01micko: added 'Master Front' entries. 120318 bumped it up, 75% to 100%.
 
 function set_volume_levels() { #card
-	[ ! "$1" ] && return
+	[ $1 ] || return
 	local card="$1"
-	echo
-	echo "For card $1"
+	echo -e "\nFor card $1"
 	#try and set all levels workable...
-	#101015 BK had to add ,0 after Front...
-	#110823 pemasu: add this set Speaker 75 % unmute
-	#120226 01micko: added 'Master Front' entries...
+	#BK: had to add ,0 after Front...
 	amixer -c $card -d -s <<EOF
 set Master 75% unmute
 set Master -12dB
@@ -58,7 +47,7 @@ EOF
 	if [ $? -eq 0 ] ; then
 		echo "Successfully set volume levels"
 		echo "# alsactl -d -f /etc/asound.state store $card"
-		alsactl -d -f /etc/asound.state store $card #120223 shinobar
+		alsactl -d -f /etc/asound.state store $card #shinobar
 		echo "alsactl: exit code $?"
 	else
 		echo "Failed to set volume levels"
@@ -67,19 +56,17 @@ EOF
 
 ###################################################################
 
-LOG=1 #1 = use logfile
+logfile='/dev/null'
+LOG=1 #1 = log to file, 0 = /dev/null
 
 case "$1" in
- start|restart)
 
+ start|restart)
 	if [ "$LOG" = "1" ] ; then
 		mkdir -p /tmp/services
 		logfile='/tmp/services/10alsa.start.log'
 		[ "$1" = "restart" ] && logfile='/tmp/services/10alsa.restart.log'
-	else
-		logfile='/dev/null'
 	fi
-
 	(
 	rm -f /var/lock/subsys/alsasound 2> /dev/null #or alsa will not start.
 	#sometimes these don't all load... oss-compat
@@ -88,17 +75,15 @@ case "$1" in
 	modprobe snd-pcm-oss   #/dev/dsp /dev/audio http://alsa.opensrc.org/Snd-pcm-oss
 
 	if [ "$LOG" = "1" ] ; then
-		. /etc/DISTRO_SPECS
-		echo "$DISTRO_NAME $DISTRO_VERSION"
+		. /etc/DISTRO_SPECS && echo "$DISTRO_NAME $DISTRO_VERSION"
 		uname -a ; echo
 	fi
 
 	if [ "$1" = "start" ] ; then #only done at boot
-		wt=0.5
-		for I in $(seq 10); do #110111 shinobar: for reliable sound detection on HP Compac nc4010.
+		for I in $(seq 10); do # shinobar: for reliable sound detection
 			[ -c /dev/mixer ] && break #note, /dev/mixer is deleted in /etc/rc.d/rc.sysinit.
-			echo "Waiting $wt seconds"
-			sleep $wt
+			echo "Waiting 0.5 seconds"
+			sleep 0.5
 			WAITING=1
 		done
 		[ "$WAITING" ] && echo
@@ -107,9 +92,8 @@ case "$1" in
 	#https://forum.openwrt.org/viewtopic.php?id=10132
 	if [ -c /dev/controlC0 ] ; then #controlC0 in /dev like the one found in puppy431
 		cd /dev ; mkdir -p /dev/snd #/dev/snd/* is deleted in /etc/rc.d/rc.sysinit
-		for file in controlC* pcmC* ; do
-			ln -sv /dev/$file /dev/snd/$file #place symlinks in /dev/snd, the alsa tools want file(s) from there..
-		done
+		#place symlinks in /dev/snd, the alsa tools want file(s) from there..
+		for f in controlC* pcmC* ; do ln -sv /dev/$f /dev/snd/$f ; done
 		echo
 	fi
 
@@ -117,22 +101,15 @@ case "$1" in
 		#/dev/snd/controlC0 [ /dev/mixer associates with this ]
 		#/dev/snd/pcmC0D0p is a play back device
 		#/dev/snd/pcmC0D0c is a recording device
-		if [ ! -c /dev/mixer ] ; then
-			echo "Warning: /dev/mixer is missing" ; echo
-		fi
-		if [ ! -c /dev/snd/controlC0 ] ; then
-			echo "ERROR: /dev/snd/controlC0 is missing" ; echo
-		fi
+		[ -c /dev/mixer ] || { echo "Warning: /dev/mixer is missing"; echo; }
+		[ -c /dev/snd/controlC0 ] || { echo "ERROR: /dev/snd/controlC0 is missing"; echo; }
 		cat /proc/asound/modules
-		echo
-		echo "###################################################"
+		echo -e "\n###################################################"
 		cat /proc/asound/cards
-		echo "###################################################"
-		echo
+		echo -e "###################################################\n"
 		echo "###################################################"
 		lsmod | grep snd
-		echo "###################################################"
-		echo
+		echo -e "###################################################\n"
 	fi
 
 	if [ ! -f /etc/asound.state ];then
@@ -163,11 +140,9 @@ case "$1" in
 	if [ "$LOG" = "1" ] ; then
 		mkdir -p /tmp/services
 		logfile=/tmp/services/10alsa.stop.log
-	else
-		logfile=/dev/null
 	fi
 	(
-	[ -f /etc/asound.state ] && alsactl -d -f /etc/asound.state store #saves to /etc/asound.state. 111229 add test file exists. 120222 revert. 120223 restore.
+	[ -f /etc/asound.state ] && alsactl -d -f /etc/asound.state store #saves to /etc/asound.state
 	# Kill processes holding open sound devices...
 	fuser -kv /dev/admmidi? /dev/adsp? /dev/amidi? /dev/audio* /dev/dmfm* /dev/dmmidi? /dev/dsp* /dev/dspW* /dev/midi0? /dev/mixer? /dev/music /dev/patmgr? /dev/sequencer* /dev/sndstat >/dev/null 2>&1
 	[ -d /proc/asound/dev ] && fuser -kv /proc/asound/dev/*
@@ -176,7 +151,8 @@ case "$1" in
 	[ -f /proc/asound/seq/clients -a -x aconnect ] && aconnect --removeall
 	# mute master to avoid clicks at unload
 	amixer set Master mute
-	# remove all sound modules... 120103...
+	# remove all sound modules...
+	# karl godt: refer: http://www.murga-linux.com/puppy/viewtopic.php?t=71767&start=390
 	c=0
 	while [ "`lsmod | grep 'snd_'`" ];do
 		lsmod | grep "^snd" | grep -E '0 $|0$' | grep -Ev "(snd-page-alloc|snd_page_alloc)" |
