10alsa: fix previous commit

diff --git a/woof-code/rootfs-skeleton/etc/init.d/10alsa b/woof-code/rootfs-skeleton/etc/init.d/10alsa
--- a/woof-code/rootfs-skeleton/etc/init.d/10alsa
+++ b/woof-code/rootfs-skeleton/etc/init.d/10alsa
@@ -12,16 +12,14 @@
 #120226 01micko: added 'Master Front' entries. 120318 bumped it up, 75% to 100%.
 
 function set_volume_levels() { #card
-		if [ "$1" ] ; then
-			local card="$1"
-			echo
-			echo "For card $1"
-		fi
-		#try and set all levels workable...
-		#101015 BK had to add ,0 after Front...
-		#110823 pemasu: add this set Speaker 75 % unmute
-		#120226 01micko: added 'Master Front' entries...
-		amixer -c $card -d -s <<EOF
+	local card="$1"
+	echo
+	echo "For card $1"
+	#try and set all levels workable...
+	#101015 BK had to add ,0 after Front...
+	#110823 pemasu: add this set Speaker 75 % unmute
+	#120226 01micko: added 'Master Front' entries...
+	amixer -c $card -d -s <<EOF
 set Master 75% unmute
 set Master -12dB
 set 'Master Mono' 75% unmute
@@ -56,14 +54,14 @@ set "SB Live Analog/Digital Output Jack" off
 set "Audigy Analog/Digital Output Jack" off
 set Speaker 75% unmute
 EOF
-		if [ $? -eq 0 ] ; then
-			echo "Successfully set volume levels"
-			echo "# alsactl -d -f /etc/asound.state store $card"
-			alsactl -d -f /etc/asound.state store $card #120223 shinobar
-			echo "alsactl: exit code $?"
-		else
-			echo "Failed to set volume levels"
-		fi
+	if [ $? -eq 0 ] ; then
+		echo "Successfully set volume levels"
+		echo "# alsactl -d -f /etc/asound.state store $card"
+		alsactl -d -f /etc/asound.state store $card #120223 shinobar
+		echo "alsactl: exit code $?"
+	else
+		echo "Failed to set volume levels"
+	fi
 }
 
 case "$1" in
