10alsa: fixes for backward compatbility
tested in wary5.5 - the same behavior
tested in puppy431 - differences, generates files in /dev instead of /dev/snd
a lot of permanent devices in /dev/snd/ (in the current woof there is a 'rm -f /dev/snd/*')

These changes make 10alsa universal and timeless again..

The verbose/debug option has been added to several commands to get more
info to report in case someone is having sound problems..

diff --git a/woof-code/rootfs-skeleton/etc/init.d/10alsa b/woof-code/rootfs-skeleton/etc/init.d/10alsa
--- a/woof-code/rootfs-skeleton/etc/init.d/10alsa
+++ b/woof-code/rootfs-skeleton/etc/init.d/10alsa
@@ -24,20 +24,27 @@ case "$1" in
 
 	wt=0.5
 	for I in $(seq 10); do #110111 shinobar: for reliable sound detection on HP Compac nc4010.
-		[ -c /dev/snd/controlC0 ] && break #alsa sound interface
-		[ -c /dev/snd/pcmC0D0p ] && break #alsa sound interface
-		#[ -c /dev/mixer ] && break #oss-compat
-		#note, /dev/mixer is deleted in /etc/rc.d/rc.sysinit.
+		[ -c /dev/mixer ] && break #note, /dev/mixer is deleted in /etc/rc.d/rc.sysinit.
 		echo "Waiting $wt seconds"
 		sleep $wt
 	done
 
-	[ ! -c /dev/mixer ] && echo "/dev/mixer is missing"
-	[ ! -c /dev/snd/controlC0 ] && echo "/dev/snd/controlC0 is missing [alsa interface]" && err1=1
-	[ ! -c /dev/snd/pcmC0D0p ] && echo "/dev/snd/pcmC0D0p is missing [alsa interface]" && err2=2
+	#https://forum.openwrt.org/viewtopic.php?id=10132
+	if [ -c /dev/controlC0 ] ; then #controlC0 in /dev like the one found in puppy431
+		cd /dev ; mkdir -p /dev/snd #/dev/snd/* is deleted in /etc/rc.d/rc.sysinit
+		for file in controlC* pcmC* ; do
+			ln -s /dev/$file /dev/snd/$file #place symlinks in /dev/snd, the alsa tools want file(s) from there..
+		done
+	fi
 
-	if [ "$err1" -o "$err2" ] ; then
-		echo "ERROR: alsa is not usable"
+	#/dev/snd/controlC0 [ /dev/mixer associates with this ]
+	#/dev/snd/pcmC0D0p is a play back device
+	#/dev/snd/pcmC0D0c is a recording device
+
+	[ ! -c /dev/mixer ] && echo "/dev/mixer is missing"
+	if [ ! -c /dev/snd/controlC0 ] ; then
+		echo "/dev/snd/controlC0 is missing"
+		echo "ERROR: alsa is not usable.."
 	fi
 
 	if [ ! -f /etc/asound.state ];then
@@ -49,7 +56,7 @@ case "$1" in
 		#110823 pemasu: add this set Speaker 75 % unmute
 		#120226 01micko: added 'Master Front' entries...
 		echo "Try and set all levels workable..."
-		amixer -s <<EOF
+		amixer -d -s <<EOF
 set Master 75% unmute
 set Master -12dB
 set 'Master Mono' 75% unmute
@@ -86,34 +93,29 @@ set Speaker 75% unmute
 EOF
 		if [ $? -eq 0 ] ; then
 			echo "Successfully set volume levels"
-			alsactl -f /etc/asound.state store #120223 shinobar
-			if [ $? -eq 0 ] ; then
-				echo "Saved current driver setup to /etc/asound.state (1st time)"
-			else
-				echo "Failed to save current driver setup to /etc/asound.state"
-			fi
+			echo '# alsactl -d -f /etc/asound.state store'
+			alsactl -d -f /etc/asound.state store #120223 shinobar
+			echo "alsactl: exit code $?"
 		else
 			echo "Failed to set volume levels"
 		fi
 		echo "=================================="
 	else
-		alsactl -f /etc/asound.state restore #from /etc/asound.state.
-		if [ $? -eq 0 ] ; then
-			echo "Loaded current driver setup from /etc/asound.state"
-		else
-			echo "Failed to load current driver setup from /etc/asound.state"
-		fi
+		echo '# alsactl -d -f /etc/asound.state restore'
+		alsactl -d -f /etc/asound.state restore #from /etc/asound.state.
+		echo "alsactl: exit code $?"
 	fi
 	) &> /tmp/services/10alsa.start.log
- ;;
+	;;
+
  stop)
 	mkdir -p /tmp/services
 	(
-	[ -f /etc/asound.state ] && alsactl -f /etc/asound.state store #saves to /etc/asound.state. 111229 add test file exists. 120222 revert. 120223 restore.
+	[ -f /etc/asound.state ] && alsactl -d -f /etc/asound.state store #saves to /etc/asound.state. 111229 add test file exists. 120222 revert. 120223 restore.
 	# Kill processes holding open sound devices...
-	fuser -k /dev/admmidi? /dev/adsp? /dev/amidi? /dev/audio* /dev/dmfm* /dev/dmmidi? /dev/dsp* /dev/dspW* /dev/midi0? /dev/mixer? /dev/music /dev/patmgr? /dev/sequencer* /dev/sndstat >/dev/null 2>&1
-	[ -d /proc/asound/dev ] && fuser -k /proc/asound/dev/*
-	[ -d /dev/snd ] && fuser -k /dev/snd/*
+	fuser -kv /dev/admmidi? /dev/adsp? /dev/amidi? /dev/audio* /dev/dmfm* /dev/dmmidi? /dev/dsp* /dev/dspW* /dev/midi0? /dev/mixer? /dev/music /dev/patmgr? /dev/sequencer* /dev/sndstat >/dev/null 2>&1
+	[ -d /proc/asound/dev ] && fuser -kv /proc/asound/dev/*
+	[ -d /dev/snd ] && fuser -kv /dev/snd/*
 	# remove all sequencer connections if any
 	[ -f /proc/asound/seq/clients -a -x aconnect ] && aconnect --removeall
 	# mute master to avoid clicks at unload
@@ -133,7 +135,7 @@ EOF
 	# remove lockfile if lockdir exists
 	[ -d /var/lock/subsys ] && rm -fv /var/lock/subsys/alsasound
 	) &> /tmp/services/10alsa.stop.log
- ;;
+	;;
 esac
 
 ### END ###
