initrd mountpartition: send debug msgs to stderr

diff --git a/initrd-progs/0initrd/sbin/mountpartition b/initrd-progs/0initrd/sbin/mountpartition
--- a/initrd-progs/0initrd/sbin/mountpartition
+++ b/initrd-progs/0initrd/sbin/mountpartition
@@ -13,7 +13,7 @@ mntfunc() {
    ntfsRETVAL=$?
    [ $ntfsRETVAL -eq 0 ] && return 0
    if [ $ntfsRETVAL -eq 14 ];then
-    echo -n "ERROR: Windows NTFS hibernated partition, cannot mount"
+    echo "ERROR: Windows NTFS hibernated partition, cannot mount" >&2
     return 14
    else
     ntfs-3g $MNT_DEV $MNT_DIR -o umask=0,no_def_opts,noatime,rw,force,silent 2>/dev/null
@@ -43,7 +43,7 @@ if [ "$MP" = "" ] ; then
   echo "* Mounting $xpart" >&2
   mkdir -p ${MP}
   fs=$(blkid /dev/$xpart 2>/dev/null | grep -o ' TYPE=".*"' | cut -f 2 -d '"')
-  echo "fs=${fs}"
+  echo "fs=${fs}" >&2
   mntfunc $fs /dev/$xpart ${MP}
   if [ $? -ne 0 ] ; then
     echo "Coult not mount $xpart... sorry" >&2
