mountpartition: Added NTFS3 support
ntfs3  is new native linux driver written by paragon software
It will use ntfs3 as primary for mounting ntfs formatted disk if detected otherwise use ntfs-3g as fallback

diff --git a/initrd-progs/0initrd/sbin/mountpartition b/initrd-progs/0initrd/sbin/mountpartition
--- a/initrd-progs/0initrd/sbin/mountpartition
+++ b/initrd-progs/0initrd/sbin/mountpartition
@@ -40,12 +40,59 @@ fi
 
 case $MNT_FS in
   ntfs)
-    ntfs-3g $MNT_DEV $MNT_DIR -o umask=0,no_def_opts,noatime,rw,silent 2>/dev/null #default is rw. 130211 add silent.
-    case $? in
-      0)  RET=0 ;;
-      14) echo "\\033[1;31m_WINDOWS_HIBERNATED_\\033[0;39m" >/dev/console ;; #31=red
-      *)  ntfs-3g $MNT_DEV $MNT_DIR -o umask=0,no_def_opts,noatime,rw,force,silent 2>/dev/null ;; #130211 add silent.
-    esac
+  
+    #Use ntfs3 if available otherwise use ntfs-3g
+    
+    #Check for ntfs3 modules
+    NTFS3_FOUND="$(zcat /proc/config.gz 2>/dev/null | grep "CONFIG_NTFS3_FS=y")"
+    NTFS_3G="y"
+   
+    if [ "$NTFS3_FOUND" != "" ]; then
+     USE_NTFS3="y"
+    elif [ -e /sys/modules/ntfs3 ]; then
+     USE_NTFS3="y"
+    elif [ "$(cat /proc/filesystems | grep ntfs3)" != "" ]; then
+     USE_NTFS3="y"
+    elif [ -e /sys/fs/ntfs3 ]; then
+     USE_NTFS3="y" 
+    else
+     USE_NTFS3=""
+    fi
+    
+    if [ "$USE_NTFS3" != "" ];  then
+      echo "Mounting $MNT_DEV using ntfs3 driver..."
+      mount -t ntfs3 -o umask=0,noatime,$perm $MNT_DEV $MNT_DIR
+      retvalm=$?
+      if [ $retvalm -eq 0 ]; then
+       if [ "$(mount | grep "$MNT_DIR")" != "" ]; then
+        echo "Mounting ntfs successful!"
+        NTFS_3G=""
+       fi
+      else
+       echo "Mount failed. Force mounting $MNT_DEV using ntfs3 driver..."
+       mount -t ntfs3 -o umask=0,noatime,force,$perm $MNT_DEV $MNT_DIR
+       retvalm=$?
+       if [ $retvalm -eq 0 ]; then
+        if [ "$(mount | grep "$MNT_DIR")" != "" ]; then
+         echo "Mounting ntfs successful!"
+         NTFS_3G=""
+        fi
+       else
+        echo "Mounting failed. Mounting ntfs using ntfs-3g"  
+       fi
+      fi
+    fi
+   
+  
+    if [ "$NTFS_3G" != "" ]; then
+     ntfs-3g $MNT_DEV $MNT_DIR -o umask=0,no_def_opts,noatime,rw,silent 2>/dev/null #default is rw. 130211 add silent.
+     case $? in
+       0)  RET=0 ;;
+       14) echo "\\033[1;31m_WINDOWS_HIBERNATED_\\033[0;39m" >/dev/console ;; #31=red
+       *)  ntfs-3g $MNT_DEV $MNT_DIR -o umask=0,no_def_opts,noatime,rw,force,silent 2>/dev/null ;; #130211 add silent.
+     esac
+    fi 
+    
     ;;
   vfat)
     VFAT_OUT_PARAM='noatime,shortname=mixed,quiet,utf8' 
