probedisk/probepart: don't write to logfile, just #force /proc upate mechanism
this is the mechanism to update usb drives info
i think it might not be needed nowadays, but who knows

it's not a good idea to keep a log file and use it blindly the next time
probepart/probedisk is called... the devices may no longer exist

diff --git a/initrd-progs/0initrd/sbin/probedisk b/initrd-progs/0initrd/sbin/probedisk
--- a/initrd-progs/0initrd/sbin/probedisk
+++ b/initrd-progs/0initrd/sbin/probedisk
@@ -99,11 +99,9 @@ do_probedisk() {
 	[ "$1" ] || return 1
 	DRV=${1##*/} #basename
 
-	if [ "$CLI_ARG" != "" ] ; then #specifial flag
-		if [ ! -e /sys/block/${DRV} ] ; then
-			echo "${DRV}: invalid drive" 1>&2
-			continue
-		fi
+	if [ ! -e /sys/block/${DRV} ] ; then
+		echo "${DRV}: invalid drive" 1>&2
+		continue
 	fi
 
 	vendor=""
@@ -113,6 +111,16 @@ do_probedisk() {
 	usb=""
 	xtype=""
 
+	blockdev=/dev/${DRV}
+	[ -e /dev/block/${DRV} ] && blockdev=/dev/block/${DRV} #android
+
+	case $(readlink /sys/block/${DRV}) in */usb*)
+		usb=yes
+		#force /proc upate mechanism
+		dd if=${blockdev} of=/dev/null bs=512 count=1 1>/dev/null 2>&1
+		;;
+	esac
+
 	[ -f /sys/block/${DRV}/device/vendor ] && read -r vendor < /sys/block/${DRV}/device/vendor
 	[ -f /sys/block/${DRV}/device/model ] && read -r model < /sys/block/${DRV}/device/model
 	[ -f /sys/block/${DRV}/size ] && read -r size < /sys/block/${DRV}/size
@@ -121,7 +129,6 @@ do_probedisk() {
 	#Android
 	[ -f /sys/block/${DRV}/device/name ] && read -r name < /sys/block/${DRV}/device/name
 	[ -f /sys/block/${DRV}/device/date ] && read -r date < /sys/block/${DRV}/device/date
-	[ -e /dev/block/${DRV} ] && blockdev=/dev/block/${DRV}
 
 	info="$vendor"
 	[ -n "$model" ] && info="$info $model"
@@ -129,8 +136,6 @@ do_probedisk() {
 	[ -n "$date" ] && info="$info $date"
 
 	type=drive #default
-
-	case $(readlink /sys/block/${DRV}) in *usb*) usb=yes ;; esac
 
 	if [ -e /sys/block/${DRV}/device/type ] ; then
 		# http://lxr.free-electrons.com/source/include/scsi/scsi.h?v=3.12
@@ -169,15 +174,6 @@ do_probedisk() {
 		fi
 	fi
 	# --
-
-	if [ "$type" = "usbdrv" -a "$CLI_ARG" = "" ] ; then
-		if [ "$HOME" != "" -a "$HOME" != "/" ] ; then
-			#keep record of usb drives, for forced updating of /proc...
-			echo "${DRV}" >> $HOME/.usb-drive-log-probedisk
-			sorted="$(sort -u $HOME/.usb-drive-log-probedisk)"
-			echo "$sorted" > $HOME/.usb-drive-log-probedisk
-		fi
-	fi
 
 	## -- legacy: properly identify a floppy
 	if [ "$type" = "usbdrv" ] ; then
@@ -240,15 +236,8 @@ do_probedisk_all() {
 #==============================================================
 
 if [ "$device" ] ; then
-	CLI_ARG=1
 	do_probedisk ${device} #process cli argument
 else
-	if [ -f $HOME/.usb-drive-log-probedisk ] ; then #force /proc upate mechanism
-		while read ONEUSBDRV ; do
-			dd if=/dev/$ONEUSBDRV of=/dev/null bs=512 count=1 1>/dev/null 2>&1
-		done < $HOME/.usb-drive-log-probedisk
-	fi
-	#--
 	do_probedisk_all
 fi
 
