0setup: support only debdb2pupdb (to process debian db files)

diff --git a/woof-code/0setup b/woof-code/0setup
--- a/woof-code/0setup
+++ b/woof-code/0setup
@@ -393,13 +393,10 @@ do
  echo -n "" > /tmp/${ONE_PKGLISTS_COMPAT}temp #130126
  case ${DISTRO_BINARY_COMPAT} in
   ubuntu|trisquel|debian|devuan|raspbian)
-  
-   if [ -f $DEBDB2PUPDB ];then #121111
     #new fast compiled app...
+    [ ! -f $DEBDB2PUPDB ] && { echo "FATAL: Could not find $DEBDB2PUPDB" ; exit 1 ; }
     #create an intermediate-converted file...
-    LANG=${LANGORG} echo " please wait..."
-    #121113 added "Section"...
-    #121113 insert STARTMARKER...
+    #121113 added "Section"... 121113 insert STARTMARKER...
     MANIPULATED1="$(grep -E '^Package:|^Installed\-Size:|^Architecture:|^Version:|^Depends:|^Filename:|^Description:|^Homepage:|^Section:' ${ONE_PKGLISTS_COMPAT}pre | tr '[\t"|`]' ' ' | tr -s ' ' | sed -e 's%^Installed\-Size%InstalledSize%' -e 's%^Package:%STARTMARKER|PKG\nPackage:%' -e 's%: %|%' -e 's% $%%')" #`geany
     #call new app. note, this in turn calls /usr/local/petget/find_pkgs...
     if [ -n "$MANIPULATED1" ];then
@@ -410,11 +407,9 @@ do
      touch $ONE_PKGLISTS_COMPAT
     fi
     #homepages also get logged...
-    if [ -f /tmp/woof-homepages.acc ];then
-     if [ -f ./PKGS_HOMEPAGES ];then #running in woof.
+    if [ -f /tmp/woof-homepages.acc -a -f ./PKGS_HOMEPAGES ];then #running in woof.
       cat  ./PKGS_HOMEPAGES >> /tmp/woof-homepages.acc
       sort --key=1,1 --field-separator=" " --unique /tmp/woof-homepages.acc > ./PKGS_HOMEPAGES #121113
-     fi
     fi
     #130316 /tmp/0setupnewinvaliddeps is created by debdb2pupdb, when run in woof.
     # 3builddistro will have to copy this file 'invaliddepslist' into rootfs-complete/usr/local/petget/ ...
@@ -424,44 +419,6 @@ do
      NIDL1="$(sort -u /tmp/0setupnewinvaliddeps | tr '\n' ' ')"
      echo -n "$NIDL1" >> invaliddepslist
     fi
-   else
-    DB_category="" #130126
-    #120719 debian squeeze and earlier has Description field last, wheezy has Filename field last...
-    Description=''; Filename=''; Package=''; InstalledSize=''; Architecture=''; Version=''
-    endflag=''
-    while read DB_ONELINE
-    do
-     eval $DB_ONELINE
-     case $DB_ONELINE in
-      Description*)
-      [ "$Filename" ] && endflag='yes'
-      ;;
-      Filename*)
-       [ "$Description" ] && endflag='yes' #wheezy and later.
-      ;;
-     esac
-     if [ "$endflag" = "yes" ];then
-      DB_fullfilename="`echo -n "$Filename" | rev | cut -f 1 -d '/' | rev`"
-      DB_path="`echo -n "$Filename" | rev | cut -f 2-9 -d '/' | rev`"
-      DB_version="`echo -n "$Version" | sed -e 's%^[0-9]:%%' -e "$v1PATTERN" -e "$v2PATTERN"`"
-      DB_pkgrelease="`echo -n "$Version" | sed -e 's%^[0-9]:%%' -e "s%${DB_version}%%" -e 's%^\\-%%' -e 's%^\\+%%'`"
-      DB_pkgname="${Package}_${DB_version}"
-      #120815 for debian, ubuntu, use the generic name provided in the $DB_path, instead of $Package, for find_cat... 130126...
-      #xPackage="$Package"
-      #[ "$DB_path" ] && xPackage="$(basename "$DB_path")"
-      #DB_category="`${FIND_CAT} $xPackage "$Description"`" #120812 find_cat now returns category[;subcategory], ex: Document;edit
-      DB_dependencies="`echo -n "$Depends" | sed -e 's%, %\n%g' | cut -f 1 -d ' ' | tr '\n' ' ' | sed -e 's% $%%' -e 's% %,+%g' -e 's%,$%%'`"
-      [ "$DB_dependencies" != "" ] && DB_dependencies='+'"$DB_dependencies"
-      echo "$DB_pkgname|$Package|$DB_version|$DB_pkgrelease|$DB_category|${InstalledSize}K|$DB_path|$DB_fullfilename|$DB_dependencies|$Description|$DISTRO_BINARY_COMPAT|$DISTRO_COMPAT_VERSION|" >> /tmp/${ONE_PKGLISTS_COMPAT}temp #130126 $ONE_PKGLISTS_COMPAT
-      echo -n "$Package "
-      Description=''; Filename=''; Package=''; InstalledSize=''; Architecture=''; Version=''
-      endflag=''
-     fi
-    done<<_END1
-$(grep -E '^Package:|^Installed\-Size:|^Architecture:|^Version:|^Depends:|^Filename:|^Description:' ${ONE_PKGLISTS_COMPAT}pre | tr '[\t"|`]' ' ' | tr -s ' ' | grep -v '\\-dbg$' | sed -e 's%^Installed\-Size%InstalledSize%' -e 's%: %="%' -e 's% $%%' -e 's%$%"%')
-_END1
-    ${FIND_CAT} /tmp/${ONE_PKGLISTS_COMPAT}temp > $ONE_PKGLISTS_COMPAT #130126
-   fi
   ;;
   slackware*)
    DB_category="" #130126 #151221 rewrote this case to use mostly shell - 150% speed improvement
