0setup: wget's exit code 0 = successful download

diff --git a/woof-code/0setup b/woof-code/0setup
--- a/woof-code/0setup
+++ b/woof-code/0setup
@@ -65,6 +65,12 @@ PKGS_SPECS_TABLE="`echo "$PKGS_SPECS_TABLE" | grep -v '^#'`"
 
 #======================================================================
 
+if wget --help | grep -q '\-\-show\-progress' ; then
+	WGET='wget --no-check-certificate -q --show-progress'
+else
+	WGET='wget --no-check-certificate -q'
+fi
+
 #w008 convert pkg database ${PKGLISTFILE}pre to a standard format...
 #120812 subcategory...
 #each line: pkgname|nameonly|version|pkgrelease|category[;subcategory]|size|path|fullfilename|dependencies|description|
@@ -223,11 +229,11 @@ function download_compat_pkg_dbs() {
 	 if [ "$skipdl" = "" ];then 
 	  if pkg_db_confirm_download ; then
 	   DLFILE="`basename $PKGLISTURI`"
-	   [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
-	   [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
-	   sync
 	   xDLFILE="$DLFILE"
-	   if [ -f $DLFILE ];then
+	   [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
+	   echo "+ Downloading..."
+	   $WGET $PKGLISTURI
+	   if [ $? -eq 0 ];then
 		case ${DISTRO_BINARY_COMPAT} in
 		 ubuntu|trisquel|debian|devuan|raspbian)
 		  xDLFILE="`basename $DLFILE`"
@@ -287,13 +293,13 @@ do
  if pkg_db_confirm_download ; then
    DLFILE=${PKGLISTFILE}
    [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1 111129 prevent error msg.
-   [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
-   sync
-   if [ -f $DLFILE ] ; then
+   echo "+ Downloading..."
+   $WGET $PKGLISTURI
+   if [ $? -eq 0 ];then
       LANG=${LANGORG} echo "...success"
    else
-      LANG=${LANGORG} echo "*** ERROR"
-      [ "$RUNNINGPUP" = "no" ] && exit 1
+      rm -f $DLFILE
+      LANG=${LANGORG} echo "*** ERROR" && sleep 3
    fi
  else #120126
    LANG=${LANGORG} echo "...skipped"
