0setup: download_compat_pkg_dbs()

diff --git a/woof-code/0setup b/woof-code/0setup
--- a/woof-code/0setup
+++ b/woof-code/0setup
@@ -129,9 +129,10 @@ function pkg_db_confirm_download() {
   downloadit=""
   if [ "$DBmethod" = "true" ];then
    echo
-   LANG=${LANGORG} echo "A package information database file needs to be downloaded."
+   LANG=${LANGORG} echo "A package information database file needs to be downloaded:"
+   echo "> $PKGLISTFILE"
    LANG=${LANGORG} echo "This will be downloaded from:"
-   echo "$PKGLISTURI"
+   echo "> $PKGLISTURI"
    if [ "$RUNNINGPUP" = "yes" ];then
      LANG=${LANGORG} echo "and will be processed and named: ${PKGLISTFILE}"
      LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
@@ -142,164 +143,94 @@ function pkg_db_confirm_download() {
 }
 
 #download docs on compatible-distro pkgs...
-for PKGLISTSPEC in $PKG_DOCS_DISTRO_COMPAT  #see file DISTRO_PKGS_SPECS-ubuntu
-do
- PKGLISTFILE="`echo -n "$PKGLISTSPEC" | cut -f 3 -d '|'`"
- PKGLISTURI="`echo -n "$PKGLISTSPEC" | cut -f 2 -d '|'`"
- [ "$PKGLISTURI" = "" ] && continue #w478 no url, pkg db file only kept in woof.
- skipdl=""
- if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE -a "$DBmethod" = "true" ];then
-  echo
-  echo "Local db file '${PKGLISTFILE}' already exists."
-  echo "Press ENTER key only to upgrade it,"
-  echo -n "or any other printable char to skip: "
-  read skipdl
- fi
- if [ "$skipdl" = "" ];then 
-  if pkg_db_confirm_download ; then
-   DLFILE="`basename $PKGLISTURI`"
-   [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
-   [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
-   sync
-   xDLFILE="$DLFILE"
-   if [ -f $DLFILE ];then
-    case ${DISTRO_BINARY_COMPAT} in
-     ubuntu|trisquel|debian|devuan|raspbian)
-      case "$DLFILE" in
-       *.bz2)
-        xDLFILE="`basename $DLFILE .bz2`"
-        bunzip2 $DLFILE
-        RETSTAT=$?
-        ;;
-       *.xz)
-        xDLFILE="`basename $DLFILE .xz`"
-        unxz $DLFILE
-        RETSTAT=$?
-        ;;
-      esac
-      [ $RETSTAT -eq 0 ] && mv -f $xDLFILE ${PKGLISTFILE}pre
-     ;;
-     slackware*)
-      RETSTAT=0
-      mv -f $xDLFILE ${PKGLISTFILE}pre
-     ;;
-     puppy)
-      RETSTAT=0
-     ;;
-    esac
-    if [ $RETSTAT -eq 0 ];then
-     LANG=${LANGORG} echo "...success."
-    else
-     LANG=${LANGORG} echo "Downloaded file is corrupted. Deleting file and aborting."
-     rm -f $xDLFILE 2>/dev/null
-     rm -f $DLFILE 2>/dev/null
-     if [ "$DBmethod" = "false" ];then
-      kill $XPID
-      Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-     fi
-     unset OSETUP_CALLED_FROM
-     exit
-    fi
-   else
-    LANG=${LANGORG} echo "Failed to download, aborting."
-    LANG=${LANGORG} echo "
-Failed to download db file: 
- ${PKGLISTURI}
-...exited from 0setup script." >> /var/woof/0setup_fail_report_$RUNNINGPUP
-    if [ "$DBmethod" = "false" ];then
-     kill $XPID
-     Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-    fi
-    unset OSETUP_CALLED_FROM
-    exit
-   fi
-  else #120126
-   LANG=${LANGORG} echo "...skipped"
-  fi
- fi
-done
+function download_compat_pkg_dbs() {
+	for PKGLISTSPEC in "$@" #see file DISTRO_PKGS_SPECS-ubuntu
+	do
+	 PKGLISTFILE="`echo -n "$PKGLISTSPEC" | cut -f 3 -d '|'`"
+	 PKGLISTURI="`echo -n "$PKGLISTSPEC" | cut -f 2 -d '|'`"
+	 [ "$PKGLISTURI" = "" ] && continue #w478 no url, pkg db file only kept in woof.
+	 skipdl=""
+	 if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE -a "$DBmethod" = "true" ];then
+	  echo
+	  echo "Local db file '${PKGLISTFILE}' already exists."
+	  echo "Press ENTER key only to upgrade it,"
+	  echo -n "or any other printable char to skip: "
+	  read skipdl
+	 fi
+	 if [ "$skipdl" = "" ];then 
+	  if pkg_db_confirm_download ; then
+	   DLFILE="`basename $PKGLISTURI`"
+	   [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
+	   [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
+	   sync
+	   xDLFILE="$DLFILE"
+	   if [ -f $DLFILE ];then
+		case ${DISTRO_BINARY_COMPAT} in
+		 ubuntu|trisquel|debian|devuan|raspbian)
+		  xDLFILE="`basename $DLFILE`"
+		  xDLFILE=${xDLFILE%.*}
+		  rm -f $xDLFILE
+		  case "$DLFILE" in
+		   *.bz2) bunzip2 $DLFILE ; RETSTAT=$? ;;
+		   *.xz)  unxz $DLFILE    ; RETSTAT=$? ;;
+		  esac
+		  [ $RETSTAT -eq 0 ] && mv -f $xDLFILE ${PKGLISTFILE}pre
+		 ;;
+		 slackware*)
+		  RETSTAT=0
+		  mv -f $xDLFILE ${PKGLISTFILE}pre
+		 ;;
+		 puppy)
+		  RETSTAT=0
+		 ;;
+		esac
+		if [ $RETSTAT -eq 0 ];then
+		 LANG=${LANGORG} echo "...success."
+		else
+		 LANG=${LANGORG} echo "Downloaded file is corrupted. Deleting file and aborting."
+		 rm -f $DLFILE $xDLFILE 2>/dev/null
+		 if [ "$DBmethod" = "false" ];then
+		  kill $XPID
+		  Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
+		 fi
+		 unset OSETUP_CALLED_FROM
+		 exit
+		fi
+	   else
+		LANG=${LANGORG} echo "Failed to download, aborting."
+		LANG=${LANGORG} echo "
+	Failed to download db file: 
+	 ${PKGLISTURI}
+	...exited from 0setup script." >> /var/woof/0setup_fail_report_$RUNNINGPUP
+		if [ "$DBmethod" = "false" ];then
+		 kill $XPID
+		 Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
+		fi
+		unset OSETUP_CALLED_FROM
+		exit
+	   fi
+	  else #120126
+	   LANG=${LANGORG} echo "...skipped"
+	  fi
+	 fi
+	done
+}
 
-#120825 -update dbs... #${DISTRO_BINARY_COMPAT}-updates package databases
+download_compat_pkg_dbs $PKG_DOCS_DISTRO_COMPAT
+
+# -update dbs... #${DISTRO_BINARY_COMPAT}-updates package databases
 PKGLISTS_COMPAT_UPDATES=""
-case $DISTRO_BINARY_COMPAT in
- ubuntu|trisquel|debian|devuan) #130319 removed |raspbian
+case $DISTRO_BINARY_COMPAT in ubuntu|trisquel|debian|devuan) #130319 removed |raspbian
    DBUPDATEFLAG='yes'
-   #basically same code as above, slight mods...
-   for PKGLISTSPEC in $PKG_DOCS_DISTRO_COMPAT
-   do
-    updPTN1="s%${DISTRO_COMPAT_VERSION}%${DISTRO_COMPAT_VERSION}_updates%" #ex: 'precise' becomes 'precise_updates' (underscore because - is delimiter)
-    updPTN2="s%${DISTRO_COMPAT_VERSION}%${DISTRO_COMPAT_VERSION}-updates%" #ex: 'precise' becomes 'precise-updates'
-    PKGLISTFILE="`echo -n "$PKGLISTSPEC" | cut -f 3 -d '|' | sed "$updPTN1"`"
-    PKGLISTURI="`echo -n "$PKGLISTSPEC" | grep -v 'deb-multimedia' | cut -f 2 -d '|' | sed "$updPTN2"`"
-    [ "$PKGLISTURI" = "" ] && continue #w478 no url, pkg db file only kept in woof.
-    PKGLISTS_COMPAT_UPDATES="${PKGLISTS_COMPAT_UPDATES} ${PKGLISTFILE}" #see further down.
-    skipdl=""
-    if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE -a "$DBmethod" = "true" ];then
-     echo
-     echo "Local db file '${PKGLISTFILE}' already exists."
-     echo "Press ENTER key only to upgrade it,"
-     echo -n "or any other printable char to skip: "
-     read skipdl
-    fi
-    if [ "$skipdl" = "" ]; then
-     if pkg_db_confirm_download ; then
-      DLFILE="`basename $PKGLISTURI`"
-      [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
-      [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
-      sync
-      xDLFILE="$DLFILE"
-      if [ -f $DLFILE ];then
-       case ${DISTRO_BINARY_COMPAT} in
-        ubuntu|trisquel|debian|devuan) #130319 removed |raspbian
-         case "$DLFILE" in
-          *.bz2)
-           xDLFILE="`basename $DLFILE .bz2`"
-           bunzip2 $DLFILE
-           RETSTAT=$?
-           ;;
-          *.xz)
-           xDLFILE="`basename $DLFILE .xz`"
-           unxz $DLFILE
-           RETSTAT=$?
-           ;;
-         esac
-         [ $RETSTAT -eq 0 ] && mv -f $xDLFILE ${PKGLISTFILE}pre
-        ;;
-       esac
-       if [ $RETSTAT -eq 0 ];then
-        LANG=${LANGORG} echo "...success."
-       else
-        LANG=${LANGORG} echo "Downloaded file is corrupted. Deleting file and aborting."
-        rm -f $xDLFILE 2>/dev/null
-        rm -f $DLFILE 2>/dev/null
-        if [ "$DBmethod" = "false" ];then
-         kill $XPID
-         Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-        fi
-        unset OSETUP_CALLED_FROM
-        exit
-       fi
-      else
-       LANG=${LANGORG} echo "Failed to download, aborting."
-       LANG=${LANGORG} echo "
-Failed to download db file: 
- $PKGLISTURI
-...exited from 0setup script." >> /var/woof/0setup_fail_report_$RUNNINGPUP
-       if [ "$DBmethod" = "false" ];then
-        kill $XPID
-        Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-       fi
-       unset OSETUP_CALLED_FROM
-       exit
-      fi
-     else #120126
-      LANG=${LANGORG} echo "...skipped"
-     fi
-    fi
-   done
- ;;
+   #Packages-ubuntu-precise-main -> Packages-ubuntu-precise_updates-main
+   #http://archive.ubuntu.com/ubuntu/dists/precise/main/binary-i386/Packages.bz2 -> http://archive.ubuntu.com/ubuntu/dists/precise-updates/main/binary-i386/Packages.bz2
+   PKGLISTS_COMPAT_U=$(echo "$PKG_DOCS_DISTRO_COMPAT" | tr ' ' '\n' | \
+     sed -e "s|-${DISTRO_COMPAT_VERSION}-|-${DISTRO_COMPAT_VERSION}_updates-|" \
+         -e "s|/${DISTRO_COMPAT_VERSION}/|/${DISTRO_COMPAT_VERSION}-updates/|")
+   download_compat_pkg_dbs $PKGLISTS_COMPAT_U
+   #see further down
+   PKGLISTS_COMPAT_UPDATES=$(echo "$PKGLISTS_COMPAT_U" | cut -f 3 -d "|" | tr '\n' ' ')
 esac
-
 
 ###download pet pkg databases...
 for PKGLISTSPEC in $PKG_DOCS_PET_REPOS  #see file DISTRO_PET_REPOS
