Revert "Merge branch 'testing' of https://github.com/puppylinux-woof-CE/woof-CE into testing"
This reverts commit 1ca88b00070bda9ef58977c326d81cbd5159cfe5, reversing
changes made to d8f9d843ee0d05dd704f96a71a747f181823816f.

Conflicts:
	woof-code/3builddistro
	woof-distro/x86/slackware/14.1/DISTRO_PKGS_SPECS-slackware-14.1
	woof-distro/x86/slackware/14.1/DISTRO_SPECS

diff --git a/woof-code/0setup b/woof-code/0setup
--- a/woof-code/0setup
+++ b/woof-code/0setup
@@ -35,18 +35,6 @@
 LANGORG="$(locale | grep '^LANG=' | cut -d '=' -f 2)" #121116
 export LANG=C #faster.
 
-if [ "$SETUPCALLEDFROM" = "ppm" ];then
- DBmethod="$(cat /var/local/petget/db_verbose 2>/dev/null)"
- [ "$DBmethod" = "" ] && DBmethod=true
- if [ "$DBmethod" = "false" ]; then
-  LANG=${LANGORG} . yaf-splash -icon gtk-info -bg white -placement top -close never -text "$(gettext 'Updating package databases.
-Please wait...')" &
-  XPID=$!
- fi
-else
- DBmethod=true
-fi
-
 if [ -f ./DISTRO_SPECS ];then
 . ./DISTRO_SPECS
 [ ! "$DISTRO_DB_SUBNAME" ] && DISTRO_DB_SUBNAME="$DISTRO_COMPAT_VERSION" #121102 fallback if DISTRO_DB_SUBNAME not defined in file DISTRO_SPECS.
@@ -67,7 +55,7 @@ fi
  RUNNINGPUP='no'
 # 140109 64 bit support #140116 improve
 . ./WOOFMERGEVARS
-if [ "${COMPATDISTRO}" = "slackware" -a "${TARGETARCH}" = "x86_64" ];then
+if [ "$WOOF_TARGETARCH" = "x86_64" ];then
 # see if it's been done
 LIB64DONE=`find packages-templates -type d -name 'lib64'`
  if [ "$LIB64DONE" ];then
@@ -156,48 +144,33 @@ do
  PKGLISTURI="`echo -n "$PKGLISTSPEC" | cut -f 2 -d '|'`"
  [ "$PKGLISTURI" = "" ] && continue #w478 no url, pkg db file only kept in woof.
  skipdl=""
- if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE -a "$DBmethod" = "true" ];then
+ if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE ];then
   echo
   echo "Local db file '${PKGLISTFILE}' already exists."
   echo "Press ENTER key only to upgrade it,"
   echo -n "or any other printable char to skip: "
   read skipdl
- else
-  skipdl=""
  fi
- if [ "$skipdl" = "" ];then 
-  if [ "$DBmethod" = "true" ];then
-   echo
-   LANG=${LANGORG} echo "A package information database file needs to be downloaded."
-   LANG=${LANGORG} echo "This will be downloaded from:"
-   echo "$PKGLISTURI"
-   LANG=${LANGORG} echo "and will be processed and named: ${PKGLISTFILE}"
-   LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
-   read downloadit
-  else
-   downloadit=""
-  fi
+ if [ "$skipdl" = "" ];then
+  echo
+  LANG=${LANGORG} echo "A package information database file needs to be downloaded."
+  LANG=${LANGORG} echo "This will be downloaded from:"
+  echo "$PKGLISTURI"
+  LANG=${LANGORG} echo "and will be processed and named: ${PKGLISTFILE}"
+  LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
+  read downloadit
   if [ "$downloadit" = "" ] ; then #120126
    DLFILE="`basename $PKGLISTURI`"
    [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
-   [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
+   rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI
    sync
    xDLFILE="$DLFILE"
    if [ -f $DLFILE ];then
     case ${DISTRO_BINARY_COMPAT} in
-     ubuntu|trisquel|debian|devuan|raspbian)
-      case "$DLFILE" in
-       *.bz2)
-        xDLFILE="`basename $DLFILE .bz2`"
-        bunzip2 $DLFILE
-        RETSTAT=$?
-        ;;
-       *.xz)
-        xDLFILE="`basename $DLFILE .xz`"
-        unxz $DLFILE
-        RETSTAT=$?
-        ;;
-      esac
+     ubuntu|debian|raspbian)
+      xDLFILE="`basename $DLFILE .bz2`"
+      bunzip2 $DLFILE
+      RETSTAT=$?
       [ $RETSTAT -eq 0 ] && mv -f $xDLFILE ${PKGLISTFILE}pre
      ;;
      slackware*)
@@ -306,11 +279,6 @@ do
      LANG=${LANGORG} echo "Downloaded file is corrupted. Deleting file and aborting."
      rm -f $xDLFILE 2>/dev/null
      rm -f $DLFILE 2>/dev/null
-     if [ "$DBmethod" = "false" ];then
-      kill $XPID
-      Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-     fi
-     unset OSETUP_CALLED_FROM
      exit
     fi
    else
@@ -319,11 +287,6 @@ do
 Failed to download db file: 
  ${PKGLISTURI}
 ...exited from 0setup script." >> /var/woof/0setup_fail_report_$RUNNINGPUP
-    if [ "$DBmethod" = "false" ];then
-     kill $XPID
-     Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-    fi
-    unset OSETUP_CALLED_FROM
     exit
    fi
   else #120126
@@ -336,20 +299,16 @@ done
 DBUPDATEFLAG='invalid' #121130
 PKGLISTS_COMPAT_UPDATES=""
 case $DISTRO_BINARY_COMPAT in
- ubuntu|trisquel|debian|devuan) #130319 removed |raspbian
-  if [ "$DBmethod" = "true" ]; then
-   echo
-   LANG=${LANGORG} echo "Do you want to download the ${DISTRO_BINARY_COMPAT}-updates package databases?"
-   LANG=${LANGORG} echo "Accept, they will be downloaded and merged,"
-   LANG=${LANGORG} echo "such that only the updated pkg db entries are kept."
-   LANG=${LANGORG} echo "Example: as at August 31, 2012, Ubuntu Precise Pangolin 12.04 has the first
+ ubuntu|debian) #130319 removed |raspbian
+  echo
+  LANG=${LANGORG} echo "Do you want to download the ${DISTRO_BINARY_COMPAT}-updates package databases?"
+  LANG=${LANGORG} echo "Accept, they will be downloaded and merged,"
+  LANG=${LANGORG} echo "such that only the updated pkg db entries are kept."
+  LANG=${LANGORG} echo "Example: as at August 31, 2012, Ubuntu Precise Pangolin 12.04 has the first
 'Service Pack' which is version 12.04.1 -- accepting here will obtain the
 package lists for 12.04.1 -- it is generally recommended to accept."
-   LANG=${LANGORG} echo -n "ENTER key only to accept, any other printable char then ENTER to decline: "
-   read DBUPDATEFLAG
-  else
-   DBUPDATEFLAG=""
-  fi
+  LANG=${LANGORG} echo -n "ENTER key only to accept, any other printable char then ENTER to decline: "
+  read DBUPDATEFLAG
   if [ "$DBUPDATEFLAG" = "" ];then #121113
    #basically same code as above, slight mods...
    for PKGLISTSPEC in $PKG_DOCS_DISTRO_COMPAT
@@ -357,52 +316,37 @@ package lists for 12.04.1 -- it is generally recommended to accept."
     updPTN1="s%${DISTRO_COMPAT_VERSION}%${DISTRO_COMPAT_VERSION}_updates%" #ex: 'precise' becomes 'precise_updates' (underscore because - is delimiter)
     updPTN2="s%${DISTRO_COMPAT_VERSION}%${DISTRO_COMPAT_VERSION}-updates%" #ex: 'precise' becomes 'precise-updates'
     PKGLISTFILE="`echo -n "$PKGLISTSPEC" | cut -f 3 -d '|' | sed "$updPTN1"`"
-    PKGLISTURI="`echo -n "$PKGLISTSPEC" | grep -v 'deb-multimedia' | cut -f 2 -d '|' | sed "$updPTN2"`"
+    PKGLISTURI="`echo -n "$PKGLISTSPEC" | cut -f 2 -d '|' | sed "$updPTN2"`"
     [ "$PKGLISTURI" = "" ] && continue #w478 no url, pkg db file only kept in woof.
     PKGLISTS_COMPAT_UPDATES="${PKGLISTS_COMPAT_UPDATES} ${PKGLISTFILE}" #see further down.
     skipdl=""
-    if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE -a "$DBmethod" = "true" ];then
+    if [ "$RUNNINGPUP" = "no" -a -f $PKGLISTFILE ];then
      echo
      echo "Local db file '${PKGLISTFILE}' already exists."
      echo "Press ENTER key only to upgrade it,"
      echo -n "or any other printable char to skip: "
      read skipdl
-    else
-     skipdl=""
     fi
-    if [ "$skipdl" = "" ]; then
-     if [ "$DBmethod" = "true" ];then
-      echo
-      LANG=${LANGORG} echo "A package information database file needs to be downloaded."
-      LANG=${LANGORG} echo "This will be downloaded from:"
-      echo "$PKGLISTURI"
-      LANG=${LANGORG} echo "and will be processed and named: ${PKGLISTFILE}"
-      LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
-      read downloadit
-     else
-      downloadit=""
-     fi
+    if [ "$skipdl" = "" ];then
+     echo
+     LANG=${LANGORG} echo "A package information database file needs to be downloaded."
+     LANG=${LANGORG} echo "This will be downloaded from:"
+     echo "$PKGLISTURI"
+     LANG=${LANGORG} echo "and will be processed and named: ${PKGLISTFILE}"
+     LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
+     read downloadit
      if [ "$downloadit" = "" ] ; then #120126
       DLFILE="`basename $PKGLISTURI`"
       [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1
-      [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
+      rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI
       sync
       xDLFILE="$DLFILE"
       if [ -f $DLFILE ];then
        case ${DISTRO_BINARY_COMPAT} in
-        ubuntu|trisquel|debian|devuan) #130319 removed |raspbian
-         case "$DLFILE" in
-          *.bz2)
-           xDLFILE="`basename $DLFILE .bz2`"
-           bunzip2 $DLFILE
-           RETSTAT=$?
-           ;;
-          *.xz)
-           xDLFILE="`basename $DLFILE .xz`"
-           unxz $DLFILE
-           RETSTAT=$?
-           ;;
-         esac
+        ubuntu|debian) #130319 removed |raspbian
+         xDLFILE="`basename $DLFILE .bz2`"
+         bunzip2 $DLFILE
+         RETSTAT=$?
          [ $RETSTAT -eq 0 ] && mv -f $xDLFILE ${PKGLISTFILE}pre
         ;;
        esac
@@ -412,11 +356,6 @@ package lists for 12.04.1 -- it is generally recommended to accept."
         LANG=${LANGORG} echo "Downloaded file is corrupted. Deleting file and aborting."
         rm -f $xDLFILE 2>/dev/null
         rm -f $DLFILE 2>/dev/null
-        if [ "$DBmethod" = "false" ];then
-         kill $XPID
-         Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-        fi
-        unset OSETUP_CALLED_FROM
         exit
        fi
       else
@@ -425,11 +364,6 @@ package lists for 12.04.1 -- it is generally recommended to accept."
 Failed to download db file: 
  $PKGLISTURI
 ...exited from 0setup script." >> /var/woof/0setup_fail_report_$RUNNINGPUP
-       if [ "$DBmethod" = "false" ];then
-        kill $XPID
-        Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
-       fi
-       unset OSETUP_CALLED_FROM
        exit
       fi
      else #120126
@@ -448,21 +382,17 @@ do
  PKGLISTFILE="`echo -n "$PKGLISTSPEC" | cut -f 3 -d '|'`"
  PKGLISTURI="`echo -n "$PKGLISTSPEC" | cut -f 2 -d '|'`"
  if [ "$RUNNINGPUP" = "yes" -o ! -f $PKGLISTFILE ];then
-  if [ "$DBmethod" = "true" ];then
-   echo
-   LANG=${LANGORG} echo "A package information database file needs to be downloaded."
-   LANG=${LANGORG} echo "This will be downloaded from:"
-   echo "$PKGLISTURI"
-   LANG=${LANGORG} echo "and will be named: ${PKGLISTFILE}"
-   LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
-   read downloadit
-  else
-   downloadit=""
-  fi
+  echo
+  LANG=${LANGORG} echo "A package information database file needs to be downloaded."
+  LANG=${LANGORG} echo "This will be downloaded from:"
+  echo "$PKGLISTURI"
+  LANG=${LANGORG} echo "and will be named: ${PKGLISTFILE}"
+  LANG=${LANGORG} echo -n "Press ENTER key to download, any other to skip it: " #120126
+  read downloadit
   if [ "$downloadit" = "" ] ; then #120126
    DLFILE="`basename $PKGLISTURI`"
    [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1 111129 prevent error msg.
-   [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
+   rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI
    sync
    [ -f $DLFILE ] && LANG=${LANGORG} echo "...success"
   else #120126
@@ -477,7 +407,7 @@ v2PATTERN="s%\\+[0-9.]*${DISTRO_BINARY_COMPAT}[0-9.]*$%%"
 #130305 debdb2pupdb.bac now also check that deps exist, need this list of pkgs...
 if [ "$RUNNINGPUP" = "no" ];then #130316 debdb2pupdb does not read this file in a running pup.
  case ${DISTRO_BINARY_COMPAT} in
-  ubuntu|trisquel|debian|devuan|raspbian)
+  ubuntu|debian|raspbian)
    echo -n " " > /tmp/0setupcompletelistpkgs
    COMPLETELISTPKGS="$(grep '^Package: ' Packages*pre | cut -f 2 -d ' ' | tr '\n' ' ')"
    echo "$COMPLETELISTPKGS" >> /tmp/0setupcompletelistpkgs
@@ -502,7 +432,7 @@ do
  echo -n "" > $ONE_PKGLISTS_COMPAT
  echo -n "" > /tmp/${ONE_PKGLISTS_COMPAT}temp #130126
  case ${DISTRO_BINARY_COMPAT} in
-  ubuntu|trisquel|debian|devuan|raspbian)
+  ubuntu|debian|raspbian)
   
    if [ -f /usr/local/petget/debdb2pupdb ];then #121111
     #new fast compiled app...
@@ -666,23 +596,13 @@ fi
 sync
 
 #120909 moved down...
-if [ "$RUNNINGPUP" = "yes" -a "$DBmethod" = "true" ];then
+if [ "$RUNNINGPUP" = "yes" ];then
  echo
  LANG=${LANGORG} echo "FINISHED"
  LANG=${LANGORG} echo "After restarting Puppy Package Manager (PPM),"
  LANG=${LANGORG} echo "it will be reading the updated database files."
  LANG=${LANGORG} echo -n "Press ENTER key to exit: "
  read enditnow
- DATE="`date +%Y%m%d `"
- echo "$DATE" > /root/.packages/db-date
- unset OSETUP_CALLED_FROM
- exit
-elif [ "$RUNNINGPUP" = "yes" ];then
- kill $XPID
- Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database was successfully completed.')" 0 100
- DATE="`date +%Y%m%d `"
- echo "$DATE" > /root/.packages/db-date
- unset OSETUP_CALLED_FROM
  exit
 fi
 
@@ -766,34 +686,17 @@ Search for suitable packages in these files:
 Or, search online. In the case of Debian or Ubuntu, you can search
 at packages.debian.org or packages.ubuntu.com.
 After you have fixed PKGS_SPECS_TABLE, run this script again."  >> /var/woof/0setup_fail_report_$RUNNINGPUP
- if [ "$DBmethod" = "false" ];then
-  kill $XPID
-  Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM database failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
- fi
- unset OSETUP_CALLED_FROM
 else
  echo
  echo "Finished, successful."
  echo "...finished, successful."  >> /var/woof/0setup_fail_report_$RUNNINGPUP
- DATE="`date +%Y%m%d `"
- echo "$DATE" > /root/.packages/db-date
 fi
 
-if [ "$DBmethod" = "true" ]; then
- echo
- echo "The log of '0setup', as reported above, is saved for future reference."
- echo "(In file /var/woof/0setup_fail_report_${RUNNINGPUP})"
- echo "In the Woof GUI, tab 'Download dbs', click the 'REPORT' button to"
- echo "retrieve this log."
- echo -n "Press ENTER key to finish '0setup' script: "
- read yepgetout
-else
- kill $XPID
- if [ "$(grep -e 'FAIL|exited|failures' /var/woof/0setup_fail_report_$RUNNINGPUP)" = "" ]; then
-  Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM databases update was successfully completed.')" 0 100
- else
-  Xdialog --title "$(gettext 'PPM database')" --left --msgbox "$(gettext 'PPM databases update failed. Chech /var/woof/0setup_fail_report_')$RUNNINGPUP $(gettext 'for details.')" 0 100
- fi
-fi
-unset OSETUP_CALLED_FROM
+echo
+echo "The log of '0setup', as reported above, is saved for future reference."
+echo "(In file /var/woof/0setup_fail_report_${RUNNINGPUP})"
+echo "In the Woof GUI, tab 'Download dbs', click the 'REPORT' button to"
+echo "retrieve this log."
+echo -n "Press ENTER key to finish '0setup' script: "
+read yepgetout
 ###END###
diff --git a/woof-code/huge_extras/init b/woof-code/huge_extras/init
--- a/woof-code/huge_extras/init
+++ b/woof-code/huge_extras/init
@@ -219,10 +219,9 @@ fsckme_func() { #passed params: partition filesystem [pupsavefile]
   echo -e -n "\\033[1;31m SORRY, cannot check filesystem \\033[0;39m" > /dev/console #31=red
   return
  fi
- [ "$DEEPFSCK" = "yes" ] && FCK="-f" || FCK=""
  case $2 in
   ext2|ext3|ext4)
-   e2fsck -y ${FCK} /dev/$1 >/tmp/chkret &
+   e2fsck -y -f /dev/$1 >/tmp/chkret &
    echo -e "\\033[1;35m" >/dev/console #35=purple
    if [ "${1}" = "loop1" ];then
     echo -n " 'save file' filesystem check, please wait..." >/dev/console
@@ -369,9 +368,7 @@ search_func() { #110425
   if [ "$IGNORE" = "optical" ];then #110126 ignore optical if boot partition found.
    [ "`echo -n "$ONEDRV" | grep -f /tmp/OPTICALDRIVES0`" != "" ] && continue #110205
   fi
-
-  [ "$PFSCK" = "yes" ] && [ "$pdev1" = "$ONEDEV" ] && \
-   [ "$(echo $ONEFS| cut -c 1-3)" = "ext" ] && fsckme_func $ONEDEV $ONEFS
+  
   #v403 nasty bug: usb optical drive showing as /sys/block/sr0, but won't mount, needs more delay...
   mntfunc $ONEFS /dev/$ONEDEV /mnt/data #-t $ONEFS /dev/$ONEDEV /mnt/data
   if [ $? -ne 0 ];then
@@ -555,8 +552,7 @@ search_func() { #110425
   
   #fix any improper shutdowns... fsckme.flg format: sda7,ext3,[/pupsave.2fs] (see rc.shutdown)
   FSCKME=""
-  [ -f /mnt/data/fsckme.flg ] && FSCKME="`cat /mnt/data/fsckme.flg | tr ',' ' ' | tr '\n' ' '`" \
-   && DEEPFSCK="yes"
+  [ -f /mnt/data/fsckme.flg ] && FSCKME="`cat /mnt/data/fsckme.flg | tr ',' ' ' | tr '\n' ' '`"
   rm -f /mnt/data/fsckme.flg
   umntfunc /mnt/data
   [ "$FSCKME" ] && fsckme_func $FSCKME
@@ -585,12 +581,12 @@ mnt_enc_pupsave_func() {
     echo -e "\\033[1;36m" >/dev/console #aqua-blue
     echo -n "Password: " >/dev/console
     echo -en "\\033[0;39m" >/dev/console
-    read -s MYPASS
     if [ "$CRYPTO" = "-e aes" ];then #v3.98
+     read -s MYPASS #< /dev/console v403
      echo "$MYPASS" | losetup -p 0 -e aes /dev/loop1 /mnt/dev_save$PUPSAVEFILE
     else
      #losetup does not accept -p param for xor encryption... may not work...
-     echo "$MYPASS" | losetup -p 0 $CRYPTO /dev/loop1 /mnt/dev_save$PUPSAVEFILE
+     losetup $CRYPTO /dev/loop1 /mnt/dev_save$PUPSAVEFILE
     fi
 }
 
@@ -693,11 +689,14 @@ if [ "$PKEYS" ];then
   zcat /lib/keymaps/${PKEYS}.gz | loadkmap ; STATUS=$(($STATUS + $?))
   case $PKEYS in #note, same code in /etc/rc.d/rc.country, /usr/sbin/input-wizard and init.
    de*|be*|br*|dk*|es*|fi*|fr*|it*|no*|se*|pt*)
+    modprobe nls_cp850
     [ ! "$PLANG" ] && FONTMAP="lat1-12.psfu" #120216
     CODEPAGE="850"
     VFAT_OUT_PARAM="$OUT_PARAM"',codepage=850'
    ;;
    cz*|hu*|pl*|ro*|sk*|croat*|slovene*)
+    modprobe nls_cp852
+    modprobe nls_iso8859-2
     [ ! "$PLANG" ] && FONTMAP="lat2-12.psfu" #120216
     CODEPAGE="852"
     VFAT_OUT_PARAM="$OUT_PARAM"',codepage=852,iocharset=iso8859-2'
@@ -719,6 +718,53 @@ fi
 
 ###################LOAD MODULES TO ACCESS DRIVES#####################
 echo -n "Loading drivers needed to access disk drives" > /dev/console #STEP ONE
+
+#100214 one config of 2.6.33 has base floppy and ps/2 mouse support not builtin...
+[ "`modinfo floppy 2>/dev/null`" != "" ] && modprobe floppy > /dev/null 2>&1
+[ "`modinfo psmouse 2>/dev/null`" != "" ] && modprobe psmouse
+
+#w462 if present, load it. enables recognition of drives attached to parallel port.
+[ "`modinfo ppa 2>/dev/null`" != "" ] && modprobe ppa #also loads parport.ko
+
+ELSPCI="`elspci -l`" #jesses great little utility.
+#v403 pcmcia drive support. i think this may need extra delay though...
+if [ "`echo "$ELSPCI" | grep '060700'`" != "" ];then
+ modprobe yenta_socket
+ #...may have to add on a couple of seconds, need to test with a pcmcia drive.
+ #v412 yeah, my pccard-usb adaptor needs delay before elspci recognises 0C0310 (ohci-hcd) interface...
+ echo -n "." > /dev/console
+ sleep 2
+fi
+#v423 k2.6.29.6 dmesg has warning that ehci-hcd should load before uhci-hcd and ohci-hid...
+[ "`echo "$ELSPCI" | grep '0C0320'`" != "" ] && modprobe ehci-hcd 2>/dev/null
+
+#121227 extra f.s. drivers may be modules (quirky6)... 130216 add f2fs...
+for ONEFSMOD in ext2 ext3 ext4 fat msdos vfat ntfs reiserfs udf f2fs
+do
+ [ "`modinfo $ONEFSMOD 2>/dev/null`" != "" ] && modprobe $ONEFSMOD
+done
+
+echo -n "." > /dev/console
+MODALIASES="`cat /sys/bus/pci/devices/*/modalias`" #important, save to variable before loop.
+for ONEMODALIAS in $MODALIASES
+do
+  modprobe $ONEMODALIAS 2>/dev/null #-v means verbose.
+  #[ $? -eq 0 ] && echo -n "." > /dev/console
+done
+
+#091222 some mmc/sd interfaces need this...
+#(above code loop may have loaded sdhci/sdhci_pci or tifm_core/tifm_7xx1)
+[ "`lsmod | grep '^sdhci'`" != "" ] && modprobe mmc_core && modprobe mmc_block
+[ "`lsmod | grep '^tifm'`" != "" ] && modprobe mmc_core && modprobe mmc_block && modprobe tifm_sd
+
+modprobe squashfs
+modprobe sr_mod > /dev/null 2>&1 #v3.93 now built-in to kernel.
+
+#filesystems...
+modprobe nls_cp437 2>/dev/null    #needed by windows filesystems.
+modprobe nls_iso8859-1 2>/dev/null #needed by linux filesystems.
+modprobe $LAYERFS #unionfs or aufs.
+modprobe fuse #for ntfs-3g driver.
 
 #110126 define ATADRIVES as all internal ide/pata/sata (and mmc) drives (not usb), except optical...
 #110710 rewritten to handle kernel with usb driver built-in...
@@ -995,10 +1041,6 @@ if [ "$CREATEPDEV1" != "" ];then
   FS="$DEV1FS"
  fi
  [ "`echo "$FS" | grep 'ext[234]'`" != "" ] && echo "/dev/$DEV $CREATEPDEV1 $FS defaults  1 1" >> /etc/fstab #v2.21
- if [ "$PFSCK" = "yes" -a "$pdev1" = "" ]; then
-  FSCKME="$DEV $FS"
-  fsckme_func $FSCKME
- fi
  mount -t $FS /dev/$DEV $CREATEPDEV1
  check_status $?
  #save is not a ${DISTRO_FILE_PREFIX}save file, but a partition on a layered-fs layer...
@@ -1023,27 +1065,20 @@ if [ "$CREATEPUPSAVE2FS" != "" ];then
    case $PUPSAVEFILE in 
     *cryptx*) #see /etc/rc.d/rc.shutdown.
      CRYPTO='-E 1' #v2.16final '-e xor' --bug, loads xor.ko which is something else.
+     modprobe cryptoloop
      ;;
     *)
      CRYPTO='-e aes'
+     modprobe cryptoloop
+     modprobe aes_generic 2>/dev/null #v407 aes name change.
+     modprobe aes 2>/dev/null #for older kernel <2.6.25
+     modprobe crypto_blkcipher 2>/dev/null #v407 blkcipher name change.
+     modprobe blkcipher 2>/dev/null #old kernel.
+     modprobe cbc
      ;;
    esac
   fi
-  if [ -d /mnt/dev_save${PUPSAVEFILE} ]; then
-   # Check partition if user calls for savefile check
-   if [ "$PFSCK" = "yes" -a "$pdev1" = "" ]; then
-    umount /mnt/dev_save
-    MOUNTED=$(cat /proc/mounts | grep $PUPSAVEDEV |cut -f 2 -d ' ')
-    MNTOPT=$(cat /proc/mounts | grep $PUPSAVEDEV |cut -f 4 -d ' ')
-    umount  $MOUNTED
-    FSCKME="$(echo $PUPSAVE | tr ',' ' ')"
-    fsckme_func $FSCKME
-    mntfunc $PUPSAVEFS /dev/$PUPSAVEDEV $MOUNTED $MNTOPT
-    mntfunc $PUPSAVEFS /dev/$PUPSAVEDEV /mnt/dev_save noatime
-   fi
-   rm -r -f "$CREATEPUPSAVE2FS"
-   ln -s /mnt/dev_save${PUPSAVEFILE} $CREATEPUPSAVE2FS
-  elif [ "$CRYPTO" != "" ] ; then
+  if [ "$CRYPTO" != "" ] ; then
    echo "" >/dev/console
    echo "Mounting encrypted $PUPSAVEFILE..." > /dev/console
    while true; do
@@ -1089,6 +1124,8 @@ if [ "$CREATEPUPSAVE2FS" != "" ];then
      losetup -d /dev/loop1
     fi
    done
+  elif [ -d /mnt/dev_save$PUPSAVEFILE ]; then
+   mount -o bind /mnt/dev_save${PUPSAVEFILE} $CREATEPUPSAVE2FS
   else #pupsave not encrypted.
    # if pupsave increase requested
    if [ -f /mnt/dev_save/pupsaveresizenew.txt ];then #131225 changed to function
@@ -1137,12 +1174,7 @@ if [ "$CREATEPUPSAVE2FS" != "" ];then
       echo "Backing off, not using save-file, booting in RAM only, PUPMODE=5..." >/dev/console
       echo -en "\\033[0;39m" >/dev/console
       sync
-      if [ -L "$CREATEPUPSAVE2FS" ]; then
-       rm -f "$CREATEPUPSAVE2FS" #get rid of save-folder
-       mkdir $CREATEPUPSAVE2FS
-      else
-       umount $CREATEPUPSAVE2FS #unmount the save-file.
-      fi
+      umount $CREATEPUPSAVE2FS #unmount the save-file.
       PUPMODE=5
       CREATETMPFS="";CREATEPDEV1="";CREATEPUPXXXSFS="";CREATEPUPSAVE2FS="";CREATEFOLDERS=""
       CREATETMPFS="/pup_rw";CREATEPUPXXXSFS="/pup_ro2"
@@ -1169,7 +1201,7 @@ if [ "$CREATEPUPSAVE2FS" != "" ];then
         echo "'${basepupsfs}' now copying to hard drive (but only available next boot)..." >/dev/console
         echo -en "\\033[0;39m" >/dev/console
         PPATTERN="/dev/$xPUPSFSDEV "
-        PUPSFSDEVMNTPT="`mount | grep -m1 "$PPATTERN" | cut -f 3 -d ' '`"
+        PUPSFSDEVMNTPT="`grep "$PPATTERN" /proc/self/mountinfo | grep '/ ' | cut -f 5 -d ' '`"
         if [ "$PUPSFSDEVMNTPT" = "" ];then
          mntfunc $xPUPSFSFS /dev/$xPUPSFSDEV /mnt/dev_ro2 #-t $PUPSFSFS /dev/$PUPSFSDEV /mnt/dev_ro2
          PUPSFSDEVMNTPT="/mnt/dev_ro2"
@@ -1381,7 +1413,7 @@ if [ "$CREATEPUPXXXSFS" != "" ];then
   COPY2RAM='yes' #actually it is already in ram, but code below puts it in a tmpfs.
  else
   PPATTERN="/dev/$PUPSFSDEV "
-  PUPSFSDEVMNTPT="`mount | grep -m1 "$PPATTERN" | cut -f 3 -d ' '`"
+  PUPSFSDEVMNTPT="`grep "$PPATTERN" /proc/self/mountinfo | grep '/ ' | cut -f 5 -d ' '`"
   if [ "$PUPSFSDEVMNTPT" = "" ];then
    mntfunc $PUPSFSFS /dev/$PUPSFSDEV /mnt/dev_ro2 #-t $PUPSFSFS /dev/$PUPSFSDEV /mnt/dev_ro2
    PUPSFSDEVMNTPT="/mnt/dev_ro2"
@@ -1442,7 +1474,7 @@ if [ "$ZDRVINIT" != "yes" ];then
    COPY2RAM='yes' #actually it is already in ram, but code below puts it in a tmpfs.
   else
    zPATTERN="/dev/$ZDEV "
-   MNT_ZFILE="`mount | grep -m1 "$zPATTERN" | cut -f 3 -d ' '`"
+   MNT_ZFILE="`grep "$zPATTERN" /proc/self/mountinfo | grep '/ ' | cut -f 5 -d ' '`"
   fi
   ZBASENAME="`basename $ZFILE`" #v426 moved up.
   if [ "$MNT_ZFILE" != "" ];then
@@ -1506,7 +1538,7 @@ if [ "$ADRV" != "" ];then
   AFILE="`echo "$ADRV" | cut -f 3 -d ','`"
   MNT_AFILE=""
   aPATTERN="/dev/$ADEV "
-  MNT_AFILE="`mount | grep -m1 "$aPATTERN" | cut -f 3 -d ' '`"
+  MNT_AFILE="`grep "$aPATTERN" /proc/self/mountinfo | grep '/ ' | cut -f 5 -d ' '`"
   ABASENAME="`basename $AFILE`" #v426 moved up.
   if [ "$MNT_AFILE" != "" ];then
    if [ "$COPY2RAM" = "yes" ];then
@@ -1535,7 +1567,7 @@ if [ "$YDRV" != "" ];then
   YFILE="`echo "$YDRV" | cut -f 3 -d ','`"
   MNT_YFILE=""
   yPATTERN="/dev/$YDEV "
-  MNT_YFILE="`mount | grep -m1 "$yPATTERN" | cut -f 3 -d ' '`"
+  MNT_YFILE="`grep "$yPATTERN" /proc/self/mountinfo | grep '/ ' | cut -f 5 -d ' '`"
   YBASENAME="`basename $YFILE`" #v426 moved up.
   if [ "$MNT_YFILE" != "" ];then
    if [ "$COPY2RAM" = "yes" ];then
@@ -1662,7 +1694,7 @@ if [ "$PUPSAVE" != "" ];then
   SAVEFILENAMEONLY="`basename $SAVEFILE`"
   SFSFILE="`echo -n "$PUPSFS" | cut -f 3 -d ','`"
   SFSFILENAMEONLY="`basename $SFSFILE`"
-  RECORDLIST="$SAVEFILENAMEONLY $AFACTOR $YFACTOR $SFSFILENAMEONLY $ZFACTOR $EXTRASFSLIST" #v426
+  RECORDLIST="$SAVEFILENAMEONLY $AFACTOR $YFACTOR $SFSFILENAMEONLY $EXTRASFSLIST $ZFACTOR" #v426
   NEWUNIONRECORD="`echo "$RECORDLIST" | tr -s ' '  | sed -e 's/ $//'`"
 
   #120130 bring back Underdog Linux...
@@ -1678,7 +1710,7 @@ if [ "$UNDERDOG" ];then #note, 'underdog' can also be specified on kernel comman
  FNDPART="`echo "$PCPARTS0" | grep "$udPTN1"`" #ex: sda1|ext3
  if [ "$FNDPART" ];then
   udPTN2="/dev/${UNDERDOG} "
-  UDMNTPT="`mount | grep -m1 "$udPTN2" | cut -f 3 -d ' '`"
+  UDMNTPT="`grep "$udPTN2" /proc/self/mountinfo | grep '/ ' | cut -f 5 -d ' '`"
   if [ ! "$UDMNTPT" ];then #must not be mounted.
    udFS="`echo -n "$FNDPART" | cut -f 2 -d '|'`"
    mount -r -t $udFS /dev/$UNDERDOG /pup_ro${CNTLOOP}
@@ -1935,12 +1967,6 @@ for ONEMNT in `mount | cut -f 3 -d ' ' | grep '^/mnt/' | tr '\n' ' '`
 do
  mount -o move $ONEMNT /pup_new/initrd${ONEMNT}
 done
-if [ "${PUPSAVEFILE}" -a -d /pup_new/initrd/mnt/dev_save${PUPSAVEFILE} ]; then
- if [ "${CREATEPUPSAVE2FS}" -a -L "${CREATEPUPSAVE2FS}" ]; then
-  rm -r -f "/pup_new/initrd${CREATEPUPSAVE2FS}"
-  ln -s /initrd/mnt/dev_save${PUPSAVEFILE} /pup_new/initrd${CREATEPUPSAVE2FS} #for after the switch root
- fi
-fi
 
 #v4.02 bring back, but allocate more space (/4 instead of /8)....
 #v3.97 a problem can run out of /tmp space, remove...
@@ -1985,6 +2011,13 @@ if [ "$PLANG" ];then
  sed -i -e "$langPTN" /pup_new/etc/profile
 fi
 
+#v3.01 a bit untidy, but cd may still be mounted when it doesn't have to be...
+case $PMEDIA in
+ *cd)
+  [ "$PDEV1" ] && umount /dev/$PDEV1 2>/dev/null #okay if it fails.
+  ;;
+esac
+
 #110114 if a drive unplugged in previous boot, but plugged in at bootup, device-nodes will be missing in main f.s...
 #james: moves /dev management last, before switch root
 if [ $DEVTMPFSFLG -eq 0 ];then #130612
@@ -1997,13 +2030,6 @@ if [ "$RDSH" = "yes" ];then
  echo "Dropped to initramfs shell. Type 'exec switch' to continue booting Puppy." > /dev/console
  exec /bin/sh >/dev/console 2>&1
 fi
-
-#v3.01 a bit untidy, but cd may still be mounted when it doesn't have to be...
-case $PMEDIA in
- *cd)
-  [ "$PDEV1" ] && umount /dev/$PDEV1 2>/dev/null #okay if it fails.
-  ;;
-esac
 
 sync
 #killall -USR1 hotplug2 #v423
