0setup: download pet DB's (delete fix-puppy-dbs)

diff --git a/woof-code/0setup b/woof-code/0setup
--- a/woof-code/0setup
+++ b/woof-code/0setup
@@ -177,13 +177,6 @@ esac
 
 #======================================================================
 
-#w480 check puppy pkg db files...
-if [ "$RUNNINGPUP" = "no" ];then
- ./support/fix-puppy-dbs
- [ $? -eq 1 ] && exit
-fi
-rm -f remotedbfile #created by fix-puppy-dbs
-
 #w091018 now logging errors for future recall...
 mkdir -p /var/woof
 RUNDATE="`date`"
@@ -287,16 +280,23 @@ for PKGLISTSPEC in $PKG_DOCS_PET_REPOS  #see file DISTRO_PET_REPOS
 do
  PKGLISTURI="`echo -n "$PKGLISTSPEC" | cut -f 2 -d '|'`"
  PKGLISTFILE="${PKGLISTURI##*/}" #basename
- if [ "$RUNNINGPUP" = "yes" -o ! -f $PKGLISTFILE ];then
-  if pkg_db_confirm_download ; then
+ if echo "$PKGS_DOCS_PET_REPOS_LOCAL_ONLY" | grep -q "^${PKGLISTFILE}$" ; then
+   echo -e "\n- Keeping local ${PKGLISTFILE}\n-"
+   continue
+ fi
+ if pkg_db_confirm_download ; then
    DLFILE=${PKGLISTFILE}
    [ -f $DLFILE ] && mv -f $DLFILE /tmp/${DLFILE}-backup1 #v431 otherwise wget creates a new file ${DLFILE}.1 111129 prevent error msg.
    [ "$DBmethod" = "true" ] && rxvt -name pet -bg orange -geometry 80x10 -e wget $PKGLISTURI || wget $PKGLISTURI
    sync
-   [ -f $DLFILE ] && LANG=${LANGORG} echo "...success"
-  else #120126
+   if [ -f $DLFILE ] ; then
+      LANG=${LANGORG} echo "...success"
+   else
+      LANG=${LANGORG} echo "*** ERROR"
+      [ "$RUNNINGPUP" = "no" ] && exit 1
+   fi
+ else #120126
    LANG=${LANGORG} echo "...skipped"
-  fi
  fi
 done
 
@@ -509,7 +509,6 @@ elif [ "$RUNNINGPUP" = "yes" ];then
  exit
 fi
 
-echo "`date +%Y%m%d `" > /root/.packages/db-date
 check_compat_distro_pkgs
 
 ### END ###
