1download: better show what's happening / add -c to wget

diff --git a/woof-code/1download b/woof-code/1download
--- a/woof-code/1download
+++ b/woof-code/1download
@@ -199,7 +199,9 @@ do_echo_file() { #$1: file
   fi
 }
 do_download() { #$1: url
-  wget -q --show-progress --timeout=20 $1
+  echo "  - from ${1%/*}"
+  #wget -S --spider $1  2>&1 | grep -q '200 OK' || { echo "  not found" ; continue ; }
+  wget -c -q --show-progress --timeout=15 $1
   #check file downloaded correctly...
   if [ -f $DB_fullfilename ];then
     case $DB_fullfilename in
@@ -275,7 +277,8 @@ do
     cd packages-${BINARIES}
     do_download ${ONE_BIN_URL}/${DB_path}/${DB_fullfilename}
     cd ..
-    [ "$SUCCESS" = "yes" ] && break
+    [ "$SUCCESS" = "yes" ] && { echo "  success" ; break ; }
+    echo "  failed (not found or corrupted file)"
   done
  fi #end if PETorCOMPAT
 
