1download: fix and improve download/verification process

diff --git a/woof-code/1download b/woof-code/1download
--- a/woof-code/1download
+++ b/woof-code/1download
@@ -193,18 +193,27 @@ fi
 #--- called within the loop...
 do_echo_file() { #$1: file
   if [ -f "$1" ] ; then
-     echo -n " ${DB_fullfilename}" ; continue #already downloaded
+     echo -n " ${DB_fullfilename}"
+     SUCCESS='yes'
+     continue
   else
      echo -e "\n* Downloading ${DB_fullfilename}"
   fi
 }
 do_download() { #$1: url
+  if [ -f $DB_fullfilename ] ; then
+     SUCCESS='yes'
+     return #already downloaded
+  fi
   echo "  - from ${1%/*}"
   #wget -S --spider $1  2>&1 | grep -q '200 OK' || { echo "  not found" ; continue ; }
-  wget -c -q --show-progress --timeout=15 $1
+  wget -c -q --show-progress --timeout=15 $1 || {
+     echo "  failed (file not found on server or could not finish download)"
+     rm -f ${DB_fullfilename}
+     return
+  }
   #check file downloaded correctly...
-  if [ -f $DB_fullfilename ];then
-    case $DB_fullfilename in
+  case $DB_fullfilename in
      *.deb) # ubuntu|trisquel|debian|devuan|raspbian
       dpkg-deb --extract $DB_fullfilename tempdironly && SUCCESS='yes'
      ;;
@@ -222,10 +231,12 @@ do_download() { #$1: url
      *.tar.bz2) # gentoo
       bzip2 --test $DB_fullfilename &>/dev/null && SUCCESS='yes'
      ;;
-    esac
-  fi
+  esac
   rm -rf tempdironly 2>/dev/null
-  [ "$SUCCESS" = "no" ] && rm -f ${DB_fullfilename} 2>/dev/null
+  if [ "$SUCCESS" = "no" ] ; then
+     echo "  failed (file not found or corrupted file)"
+     rm -f ${DB_fullfilename} 2>/dev/null
+  fi
 }
 #---
 
@@ -278,7 +289,6 @@ do
     do_download ${ONE_BIN_URL}/${DB_path}/${DB_fullfilename}
     cd ..
     [ "$SUCCESS" = "yes" ] && { echo "  success" ; break ; }
-    echo "  failed (not found or corrupted file)"
   done
  fi #end if PETorCOMPAT
 
