2createpackages: "unify" processing of pet & compat distro pkgs

diff --git a/woof-code/2createpackages b/woof-code/2createpackages
--- a/woof-code/2createpackages
+++ b/woof-code/2createpackages
@@ -264,8 +264,6 @@ do
   DBFILE="$F3"           #ex: Packages-puppy-5-official
   DB_pkgname="$F4"       #ex: abiword-2.3.4-w5
   DB_fullfilename="$F11" #ex: abiword-2.3.4-w5.pet
-  petFLG=""
-  case "$DB_fullfilename" in *.pet) petFLG=pet ;; esac
 
   #---- check if need to stop here
   if [ "$EXE" = "_NULL" -a "$DEV" = "_NULL" -a "$NLS" = "_NULL" ] ; then
@@ -285,60 +283,7 @@ do
   case "$DB_fullfilename" in *"_NLS"*) continue ;; esac
   #--
 
-  if [ "$petFLG" = "pet" ];then #do not test PETorCOMPAT only.
-   PETPKG=${DB_fullfilename%.pet} #remove trailing ".pet"
-   PETSUB="pet" #fix finding compat PETs in wary.
-   [ "$PETorCOMPAT" = "compat" ] && PETSUB="$BINARIES" #110823
-
-   echo "${GENERICNAME}|${PETPKG}.pet" >> status/2createpackages_history_builds-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
-   #now expand $PETPKG.pet in packages-${DISTRO_FILE_PREFIX}...
-   echo " processing ${PETPKG}.pet"
-   #PKGS_SPECS_TABLE may specify redirections...
-   case "$DB_pkgname" in
-     *"_DEV"*) xxPETTYPE="$DEV" ;;
-     *"_DOC"*) xxPETTYPE="$DOC" ;;
-     *"_NLS"*) xxPETTYPE="$NLS" ;;
-     *)        xxPETTYPE="$EXE" ;;
-   esac
-   if [ -f packages-${PETSUB}/${PETPKG}.pet ];then #110823
-    PKGDIR="packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}"
-    head -c -32 packages-${PETSUB}/${PETPKG}.pet > packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
-    #mkdir -p ${PKGDIR}
-    # need tar 1.26+ (slacko 14.0)
-    #tar --strip=2 --directory=${PKGDIR} -a -x -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar || {
-    tar --directory=packages-${DISTRO_FILE_PREFIX} -a -x -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar || {
-      echo "ERROR: failed to unpack ${PETPKG}.pet"
-      rm -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
-      continue
-    }
-    sync
-    # xdg_puppy.pet already has the correct PKG_DIR
-    if [ "$MWD/packages-${DISTRO_FILE_PREFIX}/${PETPKG}" != "${PKG_DIR}" ] ; then
-      mv packages-${DISTRO_FILE_PREFIX}/${PETPKG} ${PKG_DIR}
-    fi
-    rm -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
-    if [ -d packages-templates/${PETPKG}.pet ] ; then
-      echo " postprocessing with packages-templates/${PETPKG}.pet"
-      cp -a --remove-destination packages-templates/${PETPKG}.pet/* ${PKGDIR}/
-      if [ -f ${PKGDIR}/FIXUPHACK ] ; then
-        ( cd ${PKGDIR}/ ; sh ./FIXUPHACK ; rm -f FIXUPHACK )
-      fi
-    fi
-    if [ -d ${PKGDIR}/usr/share/applications/ ] ; then
-      sed -i 's| %u|| ; s| %U|| ; s| %f|| ; s| %F||' ${PKGDIR}/usr/share/applications/*.desktop
-	fi
-   else
-	( echo
-	echo "ERROR: packages-${PETSUB}/${PETPKG}.pet does not exist."
-	echo "(Generic name: ${GENERICNAME})"
-	echo "You will need to find this PET package and place in packages-${PETSUB}."
-	echo "Do it, then rerun this script and choose to build ${GENERICNAME}." ) >> ERROR-2CREATEPACKAGES
-   fi
-   continue
-  fi 
-  
   #--------------------------------
-  #anything other than .pet pkgs...
   ONEBINARYPKG="./packages-${BINARIES}/${DB_fullfilename}"
   [ ! -f $ONEBINARYPKG ] && ONEBINARYPKG="./packages-pet/${DB_fullfilename}"
   if [ ! -f $ONEBINARYPKG ];then
@@ -348,41 +293,48 @@ do
     echo "then run this script again and choose to build ${GENERICNAME}." ) >> ERROR-2CREATEPACKAGES
    continue 2 #skip this pkg.
   fi
-  zPKGNAME="$DB_fullfilename"
   
-  echo "${GENERICNAME}|${zPKGNAME}" >> status/2createpackages_history_builds-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
+  echo "${GENERICNAME}|${DB_fullfilename}" >> status/2createpackages_history_builds-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
 
-  if [ -f packages-templates/${GENERICNAME}/FIXUPHACK ] ; then
-    FIXUPHACK_FILE="packages-templates/${GENERICNAME}/FIXUPHACK"
-  elif [ -f packages-templates/${GENERICNAME}_FIXUPHACK ] ; then
-    FIXUPHACK_FILE="packages-templates/${GENERICNAME}_FIXUPHACK"
-  else
-    FIXUPHACK_FILE=""
-  fi
- 
-  DISABLE_POST_INSTALL_SCRIPT=
-  if [ -f "$FIXUPHACK_FILE" ];then
-    DISABLE_POST_INSTALL_SCRIPT="`grep '^DISABLE_POST_INSTALL_SCRIPT' "$FIXUPHACK_FILE"`"
-  fi
-
-  echo " processing $zPKGNAME"
-  PKGNAME="${ONEBINARYPKG##*/}" #basename "$ONEBINARYPKG"
+  echo " processing $DB_fullfilename"
+  PKGNAME=${DB_fullfilename}
 
   TARGET_DIR=${PKG_DIR}
   case "$PKGNAME" in
     *"-dev_"*|*"_DEV"*) TARGET_DIR=${DEV_DIR} ;;
     *"-doc_"*|*"_DOC"*) TARGET_DIR=${DOC_DIR} ;;
+    *"-nls_"*|*"_NLS"*) TARGET_DIR=${NLS_DIR} ;;
   esac
-  mkdir -p ${TARGET_DIR}/
 
   case $DB_fullfilename in
+   *.pet) # need tar 1.26+ (slacko 14.0)
+     PETPKG=${DB_fullfilename%.pet} #remove trailing ".pet"
+     head -c -32 packages-pet/${PETPKG}.pet > packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
+     tar --directory=packages-${DISTRO_FILE_PREFIX} -xaf packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar || {
+       echo "ERROR: failed to unpack ${PETPKG}.pet"
+       rm -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
+       continue
+     }
+     sync
+     # xdg_puppy.pet already has the correct TARGET_DIR
+     if [ "$MWD/packages-${DISTRO_FILE_PREFIX}/${PETPKG}" != "${TARGET_DIR}" ] ; then
+       mv packages-${DISTRO_FILE_PREFIX}/${PETPKG} ${TARGET_DIR}
+     fi
+     rm -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
+     if [ -d ${TARGET_DIR}/usr/share/applications/ ] ; then
+       sed -i 's| %u|| ; s| %U|| ; s| %f|| ; s| %F||' ${TARGET_DIR}/usr/share/applications/*.desktop
+     fi
+     continue
+   ;;
    *.deb) #ubuntu|trisquel|debian|devuan|raspbian etc
+    mkdir -p ${TARGET_DIR}/
     PKGNAME="${PKGNAME%.deb}" #ex: bash_3.2-4ububtu1_i386
     dpkg-deb -x $ONEBINARYPKG ${TARGET_DIR}/
     [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
     pre_process_pkg
    ;;
    *.tgz|*.txz) #slackware*
+    mkdir -p ${TARGET_DIR}/
     PKGNAME="${PKGNAME%.*}" #no extension
     tar --directory=${TARGET_DIR}/ -ixaf ${ONEBINARYPKG}
     [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
@@ -398,12 +350,14 @@ do
     fi
    ;;
    *.tar.*) #gentoo and others 120515
+    mkdir -p ${TARGET_DIR}/
     PKGNAME="${PKGNAME%.tar.bz2}" #ex: bash-3.2
     tar --directory=${TARGET_DIR}/ -xaf ${ONEBINARYPKG}
     [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
     pre_process_pkg
    ;;
   esac
+  #...get next pkg in same GENERICNAME
  done <<< "${FNDIT}"
  #==== fishined extracting packages =====
 
@@ -411,9 +365,21 @@ do
  ./support/2createpackages.fix.desktop.files.sh "${PKG_DIR}" "$ONEDBENTRY"
  #====================================================================
 
- #...get next pkg in same GENERICNAME
- [ "$petFLG" = "pet" ] && continue #do not do post-processing.
+ case "$DB_fullfilename" in *.pet) continue ;; esac
  ###POST-PROCESSING FOR NON-PET PKGS###  
+
+ if [ -f packages-templates/${GENERICNAME}/FIXUPHACK ] ; then
+    FIXUPHACK_FILE="packages-templates/${GENERICNAME}/FIXUPHACK"
+ elif [ -f packages-templates/${GENERICNAME}_FIXUPHACK ] ; then
+    FIXUPHACK_FILE="packages-templates/${GENERICNAME}_FIXUPHACK"
+ else
+    FIXUPHACK_FILE=""
+ fi
+ 
+ DISABLE_POST_INSTALL_SCRIPT=
+ if [ -f "$FIXUPHACK_FILE" ];then
+    DISABLE_POST_INSTALL_SCRIPT="`grep '^DISABLE_POST_INSTALL_SCRIPT' "$FIXUPHACK_FILE"`"
+ fi
 
  # NLS_DIRS='usr/share/locale'
  # DOC_DIRS='usr/share/doc usr/share/info usr/share/man usr/share/gtk-doc usr/doc usr/info usr/man usr/share/gnome/help'
