speed up Checking syntax of PKGS_SPECS_TABLE...
use shell code only

diff --git a/woof-code/2createpackages b/woof-code/2createpackages
--- a/woof-code/2createpackages
+++ b/woof-code/2createpackages
@@ -238,19 +238,23 @@ echo "Checking syntax of PKGS_SPECS_TABLE..."
 CNT=1
 for ONECHK in $PKGS_SPECS_TABLE
 do
- BADFLAG='no'
- NUMDELS=`echo "$ONECHK"  | sed -e 's/[^|]//g' | wc -c`
- [  $NUMDELS -lt 4 -o $NUMDELS -gt 6 ] && BADFLAG='yes'
- YESNO="`echo "$ONECHK" | cut -f 1 -d '|' | grep -E 'yes|no'`"
- [ "YESNO" = "" ] && BADFLAG='yes'
- GENPKG="`echo "$ONECHK" | cut -f 2 -d '|'`"
- [ "$GENPKG" = "" ]  && BADFLAG='yes'
- if [ "$BADFLAG" = "yes"  ];then
-  echo "SYNTAX ERROR LINE ${CNT}: '$ONECHK'"
-  echo "$PKGS_SPECS_TABLE" > /tmp/pst-dump
-  exit 1
- fi
- CNT=$(($CNT + 1))
+	BADFLAG='no'
+	DELS="${ONECHK//[^|]}" # remove all chars but "|"
+	NUMDELS="${#DELS}"     # count chars / delimiters
+	[  $NUMDELS -lt 4 -o $NUMDELS -gt 6 ] && BADFLAG='yes'
+	# delim         yes  |cairo |cairo|exe,dev,doc,nls|
+	IFS="|" read -r YESNO GENPKG ETC <<< "$ONECHK"
+	case $YESNO in
+		yes|no) ok=1 ;;
+		*) BADFLAG='yes' ;;
+	esac
+	[ "$GENPKG" = "" ]  && BADFLAG='yes'
+	if [ "$BADFLAG" = "yes"  ];then
+		echo "SYNTAX ERROR LINE ${CNT}: '$ONECHK'"
+		echo "$PKGS_SPECS_TABLE" > /tmp/pst-dump
+		exit 1
+	fi
+	CNT=$(($CNT + 1))
 done
 
 COMMANDLINE_CHOICE=""
