on a 2createpackages error, exit with a non-zero exit code

diff --git a/woof-code/2createpackages b/woof-code/2createpackages
--- a/woof-code/2createpackages
+++ b/woof-code/2createpackages
@@ -490,6 +490,8 @@ do
 done #process next GENERICNAME.
 
 echo -e "\nScript finished."
-[ ! -s ERROR-2CREATEPACKAGES ] || echo "WARNING: Errors were logged to file ERROR-2CREATEPACKAGES"
+[ -s ERROR-2CREATEPACKAGES ] || exit 0
+echo "WARNING: Errors were logged to file ERROR-2CREATEPACKAGES"
+exit 1
 
 ###END###
