2createpackages: remove code that already is in findpkgs..

diff --git a/woof-code/2createpackages b/woof-code/2createpackages
--- a/woof-code/2createpackages
+++ b/woof-code/2createpackages
@@ -145,31 +145,23 @@ CURRDIR="`pwd`"
 #remove comments from PKGS_SPECS_TABLE... make sure '|' on end... get rid of old |+udev,+whatever on end...
 PKGS_SPECS_TABLE="`echo "$PKGS_SPECS_TABLE" | grep -v '^#' | grep -v '^$' | tr '\t' ' ' | tr -s ' ' | tr '+' '&' | sed -e 's%|&.*%%' | tr '&' '+' | sed -e 's% #.*%%' -e 's% $%%' -e 's%$%|%' -e 's%||$%|%'`"
 
-echo
-echo "Checking syntax of PKGS_SPECS_TABLE..."
-CNT=1
-for ONECHK in $PKGS_SPECS_TABLE
-do
-	BADFLAG='no'
-	DELS="${ONECHK//[^|]}" # remove all chars but "|"
-	NUMDELS="${#DELS}"     # count chars / delimiters
-	[  $NUMDELS -lt 3 -o $NUMDELS -gt 6 ] && BADFLAG='yes'
-	# delim         yes  |cairo |cairo|exe,dev,doc,nls|
-	IFS="|" read -r YESNO GENPKG ETC <<< "$ONECHK"
-	case $YESNO in
-		yes|no) ok=1 ;;
-		*) BADFLAG='yes' ;;
-	esac
-	[ "$GENPKG" = "" ]  && BADFLAG='yes'
-	if [ "$BADFLAG" = "yes"  ];then
-		echo "NUMDELS=$NUMDELS"
-		echo "YESNO=$YESNO"
-		echo "SYNTAX ERROR LINE ${CNT}: '$ONECHK'"
-		echo "$PKGS_SPECS_TABLE" > /tmp/pst-dump
-		exit 1
-	fi
-	CNT=$(($CNT + 1))
-done
+#find all packages that will be used in the Puppy build...
+#new script to find all pkgs for build...
+./support/findpkgs
+#...returns file status/findpkgs_FINAL_PKGS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
+# each line is full db entry for pkg, prefixed with :generic-name:, pet/compat and repo-filename.
+# ex: :a52dec:|compat|Packages-puppy-wary5-official|a52dec-0.7.4-w5|a52dec|0.7.4-w5||BuildingBlock|68K||a52dec-0.7.4-w5.pet||A free ATSC A52 stream decoder|puppy|wary5||
+if [ $? -ne 0 ];then
+ echo
+ echo "ERROR: Script support/findpkgs aborted with an error, exiting."
+ exit 1
+fi
+if [ ! -f status/findpkgs_FINAL_PKGS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION} ];then
+ echo
+ echo "ERROR: Something went wrong with support/findpkgs, exiting."
+ exit 1
+fi
+#------
 
 COMMANDLINE_CHOICE=""
 [ $1 ] && COMMANDLINE_CHOICE="$1"
@@ -229,25 +221,6 @@ done
 
 #121120 further down, wants this in the host system...
 [ -f rootfs-skeleton/usr/local/petget/categories.dat ] && cp -f rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/
-
-############################################################################
-#find all packages that will be used in the Puppy build...
-
-#new script to find all pkgs for build...
-./support/findpkgs
-#...returns file status/findpkgs_FINAL_PKGS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
-# each line is full db entry for pkg, prefixed with :generic-name:, pet/compat and repo-filename.
-# ex: :a52dec:|compat|Packages-puppy-wary5-official|a52dec-0.7.4-w5|a52dec|0.7.4-w5||BuildingBlock|68K||a52dec-0.7.4-w5.pet||A free ATSC A52 stream decoder|puppy|wary5||
-if [ $? -ne 0 ];then
- echo
- echo "ERROR: Script support/findpkgs aborted with an error, exiting."
- exit 1
-fi
-if [ ! -f status/findpkgs_FINAL_PKGS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION} ];then
- echo
- echo "ERROR: Something went wrong with support/findpkgs, exiting."
- exit 1
-fi
 
 ############################################################################
 #read through PKGS_SPECS_TABLE, find matching pkg(s) in 'packages-${BINARIES}',
