2createpackages: reduce code

diff --git a/woof-code/2createpackages b/woof-code/2createpackages
--- a/woof-code/2createpackages
+++ b/woof-code/2createpackages
@@ -411,47 +411,24 @@ then run this script again and choose to build ${GENERICNAME}." >> ERROR-2CREATE
    continue 2 #process next GENERICNAME
   fi
   echo "${GENERICNAME}|${zPKGNAME}" >> status/2createpackages_history_builds-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
+
   echo " processing $zPKGNAME"
   PKGNAME="${ONEBINARYPKG##*/}" #basename "$ONEBINARYPKG"
+  rm -rf sandbox2
+  mkdir sandbox2
   case $DISTRO_BINARY_COMPAT in
    ubuntu|trisquel|debian|devuan|raspbian)
     PKGNAME="${PKGNAME%.deb}" #ex: bash_3.2-4ububtu1_i386
-    rm -rf sandbox2
-    mkdir sandbox2
     dpkg-deb -x $ONEBINARYPKG sandbox2/
-    if [ $? -ne 0 ];then
-     echo "ERROR: failed to unpack $PKGNAME"
-     continue
-    fi
+    [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
    ;;
    slackware*) #140716 64 bit
-    #100617 add support for .txz...
-    SLACKEXT=${ONEBINARYPKG##*\.} #exs: tgz, txz
-    rm -rf sandbox2
-    mkdir sandbox2
-    cp -a $ONEBINARYPKG sandbox2/
-    cd sandbox2
-    if [ "$SLACKEXT" == "tgz" ];then
-     PKGNAME="${PKGNAME%.tgz}" #ex: bash-3.2
-     tar -izxf ${PKGNAME}.tgz
-     RETVAL=$?
-     rm -f ${PKGNAME}.tgz
-    else
-     PKGNAME="${PKGNAME%.txz}" #ex: bash-3.2
-     tar -iJxf ${PKGNAME}.txz
-     RETVAL=$?
-     rm -f ${PKGNAME}.txz
-    fi
-    cd ..
-    if [ $RETVAL -ne 0 ];then
-     echo "ERROR: failed to unpack $PKGNAME"
-     continue
-    fi
+    PKGNAME="${PKGNAME%.*}" #no extension
+    tar --directory=sandbox2/ -ixaf ${ONEBINARYPKG}
+    [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
     #complication, may have a post-install script...
     if [ -f sandbox2/install/doinst.sh ];then
      chmod +x sandbox2/install/doinst.sh
-     #move it to here...
-     #cat sandbox2/install/doinst.sh > sandbox2/hack-install.sh
      #accumulate post-install scripts here, run later...
      cat sandbox2/install/doinst.sh >> /tmp/2createpackages-hack-install.sh
      #...note, could have created FIXUPHACK which executes later in this script,
@@ -460,20 +437,9 @@ then run this script again and choose to build ${GENERICNAME}." >> ERROR-2CREATE
     fi
    ;;
    gentoo) #120515
-    FULLPKGNAME="$PKGNAME"
     PKGNAME="${PKGNAME%.tar.bz2}" #ex: bash-3.2
-    rm -rf sandbox2
-    mkdir sandbox2
-    cp -a $ONEBINARYPKG sandbox2/
-    cd sandbox2
-    tar -jxf $FULLPKGNAME
-    RETVAL=$?
-    rm -f $FULLPKGNAME
-    cd ..
-    if [ $RETVAL -ne 0 ];then
-     echo "ERROR: failed to unpack $PKGNAME"
-     continue
-    fi
+    tar --directory=sandbox2/ -xaf ${ONEBINARYPKG}
+    [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
    ;;
   esac
   
