2createpackages: don't use sandbox2, extract directly to PKG_DIR
faster processing of packages

it's a significant change

diff --git a/woof-code/2createpackages b/woof-code/2createpackages
--- a/woof-code/2createpackages
+++ b/woof-code/2createpackages
@@ -1,7 +1,6 @@
 #!/bin/bash
 #(c) Copyright Barry Kauler 2009.
 # grab binary ubuntu/debian/slackware packages and build puppy packages.
-# each binary package is expanded in sandbox2/ then copied as split pkgs
 # to packages-$DISTRO_FILE_PREFIX/, into the "generic name". Note that one generic
 # name can have one or more binary pkgs.
 # Note, DISTRO_FILE_PREFIX is specified in DISTRO_SPECS file.
@@ -141,7 +140,6 @@ while [ 1 ];do
   rm -rf packages-${DISTRO_FILE_PREFIX}
   mkdir packages-${DISTRO_FILE_PREFIX}
   CHOICE_PKGS_SPECS_TABLE="$PKGS_SPECS_TABLE"
-  rm -rf sandbox2c 2>/dev/null
  else
   CHOICE_PKGS_SPECS_TABLE="`echo "$PKGS_SPECS_TABLE" | grep "^yes|${USERINPUT}|"`"
   if [ "$CHOICE_PKGS_SPECS_TABLE" = "" ];then
@@ -168,12 +166,12 @@ rm -f ERROR-2CREATEPACKAGES 2>/dev/null
 pre_process_pkg() {
   # before processing the whole package, check if there is a _PRE file
   # which contains code to fix/trim dowm stuff to speed up processing...
-  if [ -f packages-templates/${GENERICNAME}/_PRE ] ; then
+  if [ -f ${MWD}/packages-templates/${GENERICNAME}/_PRE ] ; then
     echo " executing packages-templates/${GENERICNAME}/_PRE"
-    ( cd sandbox2 ; sh ../packages-templates/${GENERICNAME}/_PRE )
+    ( cd ${PKG_DIR} ; sh ${MWD}/packages-templates/${GENERICNAME}/_PRE )
   elif [ -f packages-templates/${GENERICNAME}_PRE ] ; then
     echo " executing packages-templates/${GENERICNAME}_PRE"
-    ( cd sandbox2 ; sh ../packages-templates/${GENERICNAME}_PRE )
+    ( cd ${PKG_DIR} ; sh ${MWD}/packages-templates/${GENERICNAME}_PRE )
   fi
 }
 
@@ -203,13 +201,12 @@ do
    continue
  fi
 
- PKG_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}
- [ -d ${PKG_DIR} ] && rm -rf ${PKG_DIR}
- [ -d ${PKG_DIR}_DEV ] && rm -rf ${PKG_DIR}_DEV
- [ -d ${PKG_DIR}_DOC ] && rm -rf ${PKG_DIR}_DOC
- [ -d ${PKG_DIR}_NLS ] && rm -rf ${PKG_DIR}_NLS
- [ -d ${PKG_DIR}_NULL ] && rm -rf ${PKG_DIR}_NULL
- [ -d sandbox2c/${GENERICNAME} ] && rm -rf sandbox2c/${GENERICNAME}
+ PDIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}
+ [ -d ${PDIR} ] && rm -rf ${PDIR}
+ [ -d ${PDIR}_DEV ] && rm -rf ${PDIR}_DEV
+ [ -d ${PDIR}_DOC ] && rm -rf ${PDIR}_DOC
+ [ -d ${PDIR}_NLS ] && rm -rf ${PDIR}_NLS
+ [ -d ${PDIR}_NULL ] && rm -rf ${PDIR}_NULL
  
  # rootfs-packages override pet pkgs
  if [ -d ${PWD}/rootfs-packages/${GENERICNAME} ] ; then
@@ -221,8 +218,44 @@ do
    cp -a ${PWD}/rootfs-packages/${GENERICNAME} ${PWD}/packages-${DISTRO_FILE_PREFIX}
    continue
  fi
- 
+
+ #PKGS_SPECS_TABLE may specify redirections...
+ EXE=""
+ DEV="_DEV"
+ DOC="_DOC"
+ NLS="_NLS"
+ #exe>dev,dev>exe,etc
+ #exe,dev,doc>exe,nls>null
+ for TOK in ${SPLITRULE//,/ } ; do #convert "," to " "
+	case $TOK in
+		exe*) EXE="${TOK#*>}" ; EXE="_${EXE^^}" ;;
+		dev*) DEV="${TOK#*>}" ; DEV="_${DEV^^}" ;;
+		doc*) DOC="${TOK#*>}" ; DOC="_${DOC^^}" ;;
+		nls*) NLS="${TOK#*>}" ; NLS="_${NLS^^}" ;;
+	esac
+ done
+ #the "packagename_EXE" is just named "packagename"...
+ [ "$EXE" = "_EXE" ] && EXE=""
+ [ "$DEV" = "_EXE" ] && DEV=""
+ [ "$DOC" = "_EXE" ] && DOC=""
+ [ "$NLS" = "_EXE" ] && NLS=""
+
+ if [ "$EXE" = "_DEV" ] ; then
+    DEVX=1
+ else
+    DEVX=
+ fi
+
+ #------------------------------------------------------------------------
+ EXE_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${EXE%_NULL}
+ DEV_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${DEV}
+ DOC_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${DOC}
+ NLS_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${NLS}
+ PKG_DIR=${EXE_DIR}
+ #------------------------------------------------------------------------
+
  #inject $FNDIT at end of do-done, runs faster...
+ #==== extract packages ======
  while read ONEDBENTRY
  do
   #120812 category now allows optional subcategory...
@@ -243,24 +276,6 @@ do
   petFLG=""
   case "$DB_fullfilename" in *.pet) petFLG=pet ;; esac
 
-  #PKGS_SPECS_TABLE may specify redirections...
-  EXE="" ; DEV="" ; DOC="" ; NLS=""
-  #exe>dev,dev>exe,etc
-  #exe,dev,doc>exe,nls>null
-  for TOK in ${SPLITRULE//,/ } ; do #convert "," to " "
-	case $TOK in
-		exe*) EXE="${TOK#*>}" ; EXE="_${EXE^^}" ;;
-		dev*) DEV="${TOK#*>}" ; DEV="_${DEV^^}" ;;
-		doc*) DOC="${TOK#*>}" ; DOC="_${DOC^^}" ;;
-		nls*) NLS="${TOK#*>}" ; NLS="_${NLS^^}" ;;
-	esac
-  done
-  #the "packagename_EXE" is just named "packagename"...
-  [ "$EXE" = "_EXE" ] && EXE=""
-  [ "$DEV" = "_EXE" ] && DEV=""
-  [ "$DOC" = "_EXE" ] && DOC=""
-  [ "$NLS" = "_EXE" ] && NLS=""
-
   #---- check if need to stop here
   if [ "$EXE" = "_NULL" -a "$DEV" = "_NULL" -a "$NLS" = "_NULL" ] ; then
     # don't want anything fromt this pkg... a 'fake install'
@@ -278,14 +293,6 @@ do
   esac
   case "$DB_fullfilename" in *"_NLS"*) continue ;; esac
   #--
-
-  #------------------------------------------------------------------------
-  PKG_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}
-  EXE_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${EXE%_NULL}
-  DEV_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${DEV}
-  DOC_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${DOC}
-  NLS_DIR=${PWD}/packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${NLS}
-  #------------------------------------------------------------------------
 
   if [ "$petFLG" = "pet" ];then #do not test PETorCOMPAT only.
    PETPKG=${DB_fullfilename%.pet} #remove trailing ".pet"
@@ -309,34 +316,37 @@ do
    echo " processing ${PETPKG}.pet"
    #PKGS_SPECS_TABLE may specify redirections...
    case "$DB_pkgname" in
-     *"_DEV"*) xPETTYPE="$DEV" ;;
-     *"_DOC"*) xPETTYPE="$DOC" ;;
-     *"_NLS"*) xPETTYPE="$NLS" ;;
-     *)        xPETTYPE="$EXE" ;;
+     *"_DEV"*) xxPETTYPE="$DEV" ;;
+     *"_DOC"*) xxPETTYPE="$DOC" ;;
+     *"_NLS"*) xxPETTYPE="$NLS" ;;
+     *)        xxPETTYPE="$EXE" ;;
    esac
-   xxPETTYPE=${xPETTYPE}
-   rm -rf sandbox2e 2>/dev/null #110830
-   mkdir sandbox2e #110830
    if [ -f packages-${PETSUB}/${PETPKG}.pet ];then #110823
-    cp -f packages-${PETSUB}/${PETPKG}.pet sandbox2e/ #110830
-    cd sandbox2e
-    pet2tgz ${PETPKG}.pet
-    tar -a -x -f ${PETPKG}.tar.[gx]z
-    mkdir -p ../packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE} #110830
-    cp -a -f --remove-destination $PETPKG/* ../packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}/ #110830
+    PKGDIR="packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}"
+    head -c -32 packages-${PETSUB}/${PETPKG}.pet > packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
+    #mkdir -p ${PKGDIR}
+    # need tar 1.26+ (slacko 14.0)
+    #tar --strip=2 --directory=${PKGDIR} -a -x -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar || {
+    tar --directory=packages-${DISTRO_FILE_PREFIX} -a -x -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar || {
+      echo "ERROR: failed to unpack ${PETPKG}.pet"
+      rm -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
+      continue
+    }
     sync
-    rm -f ${PETPKG}.tar.[gx]z
-    rm -rf $PETPKG
-    cd $MWD
+    # xdg_puppy.pet already has the correct PKG_DIR
+    if [ "$MWD/packages-${DISTRO_FILE_PREFIX}/${PETPKG}" != "${PKG_DIR}" ] ; then
+      mv packages-${DISTRO_FILE_PREFIX}/${PETPKG} ${PKG_DIR}
+    fi
+    rm -f packages-${DISTRO_FILE_PREFIX}/${PETPKG}.tar
     if [ -d packages-templates/${PETPKG}.pet ] ; then
       echo " postprocessing with packages-templates/${PETPKG}.pet"
-      cp -a --remove-destination packages-templates/${PETPKG}.pet/* packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}/
-      if [ -f packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}/FIXUPHACK ] ; then
-        ( cd packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}/ ; sh ./FIXUPHACK ; rm -f FIXUPHACK )
+      cp -a --remove-destination packages-templates/${PETPKG}.pet/* ${PKGDIR}/
+      if [ -f ${PKGDIR}/FIXUPHACK ] ; then
+        ( cd ${PKGDIR}/ ; sh ./FIXUPHACK ; rm -f FIXUPHACK )
       fi
     fi
-    if [ -d packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}/usr/share/applications/ ] ; then
-      sed -i 's| %u|| ; s| %U|| ; s| %f|| ; s| %F||' packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${xxPETTYPE}/usr/share/applications/*.desktop
+    if [ -d ${PKGDIR}/usr/share/applications/ ] ; then
+      sed -i 's| %u|| ; s| %U|| ; s| %f|| ; s| %F||' ${PKGDIR}/usr/share/applications/*.desktop
 	fi
    else
 	( echo
@@ -345,7 +355,6 @@ do
 	echo "You will need to find this PET package and place in packages-${PETSUB}."
 	echo "Do it, then rerun this script and choose to build ${GENERICNAME}." ) >> ERROR-2CREATEPACKAGES
    fi
-   rm -rf sandbox2e 2>/dev/null #110830
    continue
   fi 
   
@@ -394,82 +403,60 @@ do
 
   echo " processing $zPKGNAME"
   PKGNAME="${ONEBINARYPKG##*/}" #basename "$ONEBINARYPKG"
-  rm -rf sandbox2
-  mkdir sandbox2
+
+  TARGET_DIR=${PKG_DIR}
+  case "$PKGNAME" in
+    *"-dev_"*|*"_DEV"*) TARGET_DIR=${DEV_DIR} ;;
+    *"-doc_"*|*"_DOC"*) TARGET_DIR=${DOC_DIR} ;;
+  esac
+  mkdir -p ${TARGET_DIR}/
+
   case $DB_fullfilename in
    *.deb) #ubuntu|trisquel|debian|devuan|raspbian etc
     PKGNAME="${PKGNAME%.deb}" #ex: bash_3.2-4ububtu1_i386
-    dpkg-deb -x $ONEBINARYPKG sandbox2/
+    dpkg-deb -x $ONEBINARYPKG ${TARGET_DIR}/
     [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
     pre_process_pkg
    ;;
    *.tgz|*.txz) #slackware*
     PKGNAME="${PKGNAME%.*}" #no extension
-    tar --directory=sandbox2/ -ixaf ${ONEBINARYPKG}
+    tar --directory=${TARGET_DIR}/ -ixaf ${ONEBINARYPKG}
     [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
     pre_process_pkg
-    if [ -f sandbox2/install/doinst.sh ];then
+    if [ -f ${TARGET_DIR}/install/doinst.sh ];then
       # slackware post-install script
       if [ ! "$DISABLE_POST_INSTALL_SCRIPT" ] ; then
 		echo " executing (Slackware) install script"
-		( cd sandbox2 ; sh ./install/doinst.sh )
+		( cd ${TARGET_DIR} ; sh ./install/doinst.sh )
 		sync
-		rm -rf sandbox2/install
+		rm -rf ${TARGET_DIR}/install
       fi
     fi
    ;;
    *.tar.*) #gentoo and others 120515
     PKGNAME="${PKGNAME%.tar.bz2}" #ex: bash-3.2
-    tar --directory=sandbox2/ -xaf ${ONEBINARYPKG}
+    tar --directory=${TARGET_DIR}/ -xaf ${ONEBINARYPKG}
     [ $? -ne 0 ] && { echo "ERROR: failed to unpack $PKGNAME"; continue; }
     pre_process_pkg
    ;;
   esac
+ done <<< "${FNDIT}"
+ #==== fishined extracting packages =====
 
-  #====================================================================
-  ./support/2createpackages.fix.desktop.files.sh sandbox2 "$ONEDBENTRY"
-  #====================================================================
-  
-  case "$PKGNAME" in
-    *"-dev_"*|*"_DEV"*) #if pkg has '-dev_' in name, copy all of it to $DEV... w018 add '_DEV'
-      #debian pkgs can have doc dirs and even nls dirs.
-      if [ "$NLS" = "_NULL" ] ; then
-        NLS_DIRS='usr/share/locale'
-        for i in $NLS_DIRS ; do [ -d sandbox2/${i} ] && rm -rf sandbox2/${i} ; done
-      fi
-      if [ "$DOC" = "_NULL" ] ; then
-        DOC_DIRS='usr/share/doc usr/share/info usr/share/man usr/share/gtk-doc usr/doc usr/info usr/man usr/share/gnome/help'
-        for i in $DOC_DIRS ; do [ -d sandbox2/${i} ] && rm -rf sandbox2/${i} ; done
-      fi
-      if [ ! -d ${DEV_DIR} ] ; then
-        mv -f sandbox2 ${DEV_DIR}
-      else
-        mkdir -p ${DEV_DIR}
-        cp -a --remove-destination sandbox2/* ${DEV_DIR}/
-      fi
-      continue
-      ;;
-    *"-doc_"*|*"_DOC"*)
-      if [ ! -d ${DOC_DIR} ] ; then
-        mv -f sandbox2 ${DOC_DIR}
-      else
-        mkdir -p ${DOC_DIR}
-        cp -a --remove-destination sandbox2/* ${DOC_DIR}/
-      fi
-      continue
-      ;;
-    *"_NLS"*)
-      if [ ! -d ${NLS_DIR} ] ; then
-        mv -f sandbox2 ${NLS_DIR}
-      else
-        mkdir -p ${NLS_DIR}
-        cp -a --remove-destination sandbox2/* ${NLS_DIR}/
-      fi
-      continue
-      ;;
-  esac
+ #====================================================================
+ ./support/2createpackages.fix.desktop.files.sh "${PKG_DIR}" "$ONEDBENTRY"
+ #====================================================================
 
-  cd sandbox2
+ #...get next pkg in same GENERICNAME
+ [ "$petFLG" = "pet" ] && continue #do not do post-processing.
+ [ "$MISSPOSTPROC" = "yes" ] && continue #091211
+ ###POST-PROCESSING FOR NON-PET PKGS###  
+
+ # NLS_DIRS='usr/share/locale'
+ # DOC_DIRS='usr/share/doc usr/share/info usr/share/man usr/share/gtk-doc usr/doc usr/info usr/man usr/share/gnome/help'
+
+ if [ -d ${PKG_DIR} ] ; then
+  cd ${PKG_DIR}
   # directories
   find . -mindepth 1 -type d | sed -e 's|^\.\/||' | sort | \
   while read ONEDIR
@@ -483,7 +470,10 @@ do
      #-- NLS -- international language
      *"/locale"|*"/nls"|*"/i18n")
        if [ "$NLS" = "_NULL" ] ; then
-         rm -rf ${ONEDIR}
+          rm -rf ${ONEDIR}
+          continue
+       fi
+       if [ "$NLS_DIR" = "$PKG_DIR" ] ; then
          continue
        fi
        if [ ! -d ${NLS_DIR}/${ONEDIR} ] ; then
@@ -502,6 +492,9 @@ do
          rm -rf ${ONEDIR}
          continue
        fi
+       if [ "$DOC_DIR" = "$PKG_DIR" ] ; then
+         continue
+       fi
        if [ ! -d ${DOC_DIR}/${ONEDIR} ] ; then
          mkdir -p ${DOC_DIR}/${PARENTDIR}
          mv -f ${ONEDIR} ${DOC_DIR}/${PARENTDIR}/
@@ -518,6 +511,9 @@ do
          rm -rf ${ONEDIR}
          continue
        fi
+       if [ "$DEVX" ] ; then
+         continue
+       fi
        if [ ! -d ${DEV_DIR}/${ONEDIR} ] ; then
          mkdir -p ${DEV_DIR}/${PARENTDIR}
          mv ${ONEDIR} ${DEV_DIR}/${PARENTDIR}/
@@ -530,25 +526,14 @@ do
        ;;
    esac
   done
-  
-  # will post-process this...
-  mkdir -p ${EXE_DIR}/
-  cp -a ./* ${EXE_DIR}/
   cd $MWD
+ fi
 
- done <<< "${FNDIT}" #################
-
-  #...get next pkg in same GENERICNAME
- [ "$petFLG" = "pet" ] && continue #do not do post-processing.
- [ "$MISSPOSTPROC" = "yes" ] && continue #091211
-
- if [ "$EXE" = "" ] ; then #EXE is not redirected to _DEV, _DOC, or _NLS
-  ###POST-PROCESSING FOR NON-PET PKGS### 
+ if [ "$EXE" = "" ] && [ -d ${EXE_DIR} ] ; then #EXE is not redirected to _DEV, _DOC, or _NLS
   # post-process $EXE_DIR...
-  mkdir -p ${EXE_DIR}
   cd ${EXE_DIR}
   #this will find all files and symlinks to files...
-  find -L ./ -noleaf -type f | sed -e 's|^\.\/||' |
+  find ./ -noleaf -type f -or -type l | sed -e 's|^\.\/||' |
   while read ONEFILE
   do
    ONEBASE="${ONEFILE##*/}" #basename "$ONEFILE"
@@ -564,8 +549,8 @@ do
      continue
     fi
    esac
-   #find various config files... all .a .la .m4a files
-   case "$ONEFILE" in *"-config"|*"config.sh"|*"Conf.sh"|*.a|*.la|*.m4)
+   #find various config files... all .a .la .m4 files
+   case "$ONEFILE" in *"-config"|*"config.sh"|*"Conf.sh"|*.a|*.la|*.m4|*.o|*.cmake)
     [ "$DEV" = "_NULL" ] && { rm -f "$ONEFILE" ; continue ; }
     [ ! -d "${DEV_DIR}/${ONEPATH}" ] && mkdir -p "${DEV_DIR}/${ONEPATH}"
     mv -f "$ONEFILE" "$ONEFILE" "${DEV_DIR}/${ONEPATH}/" 2>/dev/null
@@ -573,9 +558,10 @@ do
    esac
    [ "$EXE" = "_NULL" ] && { rm -f "$ONEFILE" ; continue ; }
    #anything left over goes into the main 'executable' package...
-   #strip the file... but not if a cross-build (see file WOOFMERGEVARS)
-   if [ "$STRIP_BINARIES" = "yes" ];then #build.conf
-    if [ "$STRIP_BIN" -a "$WOOF_HOSTARCH" = "$WOOF_TARGETARCH" ];then #needs devx.
+   case "$ONEFILE" in *"/bin"*|*"/sbin"*|*"/lib"*)
+    #strip the file... but not if a cross-build (see file WOOFMERGEVARS)
+    if [ "$STRIP_BINARIES" = "yes" ];then #build.conf
+     if [ "$STRIP_BIN" -a "$WOOF_HOSTARCH" = "$WOOF_TARGETARCH" ];then #needs devx.
       if [ ! -h "$ONEFILE" ];then #make sure it isn't a symlink
        FILE_INFO=$(file "$ONEFILE")
        case $FILE_INFO in *"ELF"*)
@@ -585,40 +571,33 @@ do
         esac
        esac
       fi
+     fi
     fi
-   fi
+    ;;
+   esac
   done
+  cd $MWD
  fi
 
- cd $MWD
  #end of splitting.
  #--------------------------------------------
 
  #now do some post-processing using "template" found in 'packages-templates'...
  if [ -d packages-templates/${GENERICNAME} ];then
-  echo " postprocessing with packages-templates/${GENERICNAME}"
-  mkdir -p packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}
-  find packages-templates/${GENERICNAME}/ -empty \( -type f -o -type l \) | \
-	while read file ; do rm -fv $file ; done
-  cp -a --remove-destination \
-	packages-templates/${GENERICNAME}/* packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}${EXE}/
-  [ -f packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}/_PRE ] && rm -f packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}/_PRE
-  [ -f packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}_DEV/_PRE ] && rm -f packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}_DEV/_PRE
+   echo " postprocessing with packages-templates/${GENERICNAME}"
+   find packages-templates/${GENERICNAME}/ -empty \( -type f -o -type l \) -delete #this line will removed
+   cp -a --remove-destination packages-templates/${GENERICNAME}/* ${PKG_DIR}/
+   [ -f ${PKG_DIR}/_PRE ] && rm -f ${PKG_DIR}/_PRE
  fi
 
  #a last resort fixup, if 'FIXUPHACK' exists, execute it... 111204 DISABLE_POST_INSTALL_SCRIPT code moved up.
- if [ -f "$FIXUPHACK_FILE" ];then #111210
-   if [ "$EXE" = "_DEV" ];then
-    cp -f "$FIXUPHACK_FILE" packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}_DEV/FIXUPHACK
-    cd packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}_DEV/
-   else
-    cp -f "$FIXUPHACK_FILE" packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}/FIXUPHACK
-    cd packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}/
-   fi
+ if [ -f "$FIXUPHACK_FILE" ];then
    echo " executing ${FIXUPHACK_FILE}"
-   sh ./FIXUPHACK
-   rm -f FIXUPHACK _PRE
-   cd $MWD
+   if [ -d $PKG_DIR ] ; then #python-dev
+     ( cd $PKG_DIR ; sh ${MWD}/${FIXUPHACK_FILE} )
+   elif [ -d $DEV_DIR ] ; then
+     ( cd $DEV_DIR ; sh ${MWD}/${FIXUPHACK_FILE} )
+   fi
  fi
 
  [ -d packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}_NULL ] && rm -rf packages-${DISTRO_FILE_PREFIX}/${GENERICNAME}_NULL
