3builddistro: g4dos = x86* arch..

diff --git a/woof-code/3builddistro-Z b/woof-code/3builddistro-Z
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -18,16 +18,6 @@ UEFI_ISO=${UFEI_ISO} #UFEI is a typo
 . ./_00func
 . ./_00build.conf
 
-if [ "$UFEI_ISO" != "yes" -a "$G4DOS_ISO" != "yes" ] ; then
-	if ! which giftopnm &>/dev/null ; then
-		# boot/boot-dialog/textongif.sh requires:
-		#   ppmquant, ppmlabel, giftopnm, ppmtogif from netpbm
-		echo "Warning: ppmtogif is missing ... building a grub4dos iso "
-		G4DOS_ISO=yes
-	fi
-	sleep 1
-fi
-
 export PTHEME #build.conf - woof-code/rootfs-packages/ptheme
 export XTRA_FLG # build.conf - extra naming for iso
 KERNEL_REPO_URL=${KERNEL_REPO_URL:-http://distro.ibiblio.org/puppylinux/huge_kernels} #can change var
@@ -52,6 +42,18 @@ PKGLISTS_COMPAT="`echo "$PKG_DOCS_DISTRO_COMPAT" | tr ' ' '\n' | cut -f 3 -d '|'
 #...format ex: 'Packages-ubuntu-intrepid-main Packages-ubuntu-intrepid-universe'
 
 export WKGDIR="`pwd`"
+
+case "$DISTRO_TARGETARCH" in x86*)
+	if [ "$UFEI_ISO" != "yes" -a "$G4DOS_ISO" != "yes" ] ; then
+		if ! which giftopnm &>/dev/null ; then
+			# boot/boot-dialog/textongif.sh requires:
+			#   ppmquant, ppmlabel, giftopnm, ppmtogif from netpbm
+			echo "Warning: ppmtogif is missing ... building a grub4dos iso "
+			G4DOS_ISO=yes
+		fi
+		sleep 1
+	fi
+esac
 
 if [ "$BUILD_ZIP" = "yes" ]; then
 	SDFLAG="zip"
