3builddistro: build a g4dos iso if giftopnm is missing
this is for non-uefi builds
a grub4dos iso is also an hybrid iso (includes isolinux)

diff --git a/woof-code/3builddistro-Z b/woof-code/3builddistro-Z
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -13,8 +13,21 @@ if [ "`which xorriso`" != "" ];then # use xorriso if it is installed
 fi
 export CDRECORD MKISOFS
 
+UEFI_ISO=${UFEI_ISO} #UFEI is a typo
+
 . ./_00func
 . ./_00build.conf
+
+if [ "$UFEI_ISO" != "yes" -a "$G4DOS_ISO" != "yes" ] ; then
+	if ! which giftopnm &>/dev/null ; then
+		# boot/boot-dialog/textongif.sh requires:
+		#   ppmquant, ppmlabel, giftopnm, ppmtogif from netpbm
+		echo "Warning: ppmtogif is missing ... building a grub4dos iso "
+		G4DOS_ISO=yes
+	fi
+	sleep 3
+fi
+
 export PTHEME #build.conf - woof-code/rootfs-packages/ptheme
 export XTRA_FLG # build.conf - extra naming for iso
 KERNEL_REPO_URL=${KERNEL_REPO_URL:-http://distro.ibiblio.org/puppylinux/huge_kernels} #can change var
