Add ability to make .img.xz without writing to SD card
Note: also changed
echo "/dev/${SDDEVICE}2 / ${SDFS2} defaults,noatime 0 1"
 >> /mnt/sdimagep2/etc/fstab
to
echo "/dev/mmcblk0p2 / ${SDFS2} defaults,noatime 0 1"
 >> /mnt/sdimagep2/etc/fstab

diff --git a/woof-code/3builddistro b/woof-code/3builddistro
--- a/woof-code/3builddistro
+++ b/woof-code/3builddistro
@@ -280,9 +280,7 @@ echo "Do you want to create a live-CD .iso file, which is the normal choice for 
 PC-compatible target, or is your target an SD-card for an ARM-based board?
 In the latter case, you would already have downloaded an SD-card skeleton image
 file into folder 'sd-skeleton-images' (done by script '1download') -- if there
-is no image file in that folder, you cannot choose the SD-card option.
-The latter choice will also require an SD card to write to, and you must have
-it available now."
+is no image file in that folder, you cannot choose the SD-card option."
 echo "WARNING: for the SD-card option, you must have enough free space in the
 current directory ${WKGDIR}/sandbox3
 to expand the SD image file, typically 4GB."
@@ -3325,35 +3323,6 @@ else #120506 sd image
   [ "$sdcorrect" = "" ] && break
  done
  echo
- echo "Please insert the SD card. Make sure that it is the same size or bigger than
-indicated on the filename of the skeleton image file that you chose."
- echo -n "Press ENTER after it is inserted: "
- read waitinsert
- sleep 2
- while [ 1 ];do
-  CNT=1
-  echo -n "" > /tmp/3builddistro-probedisk
-  probedisk | 
-  while read ONEPROBE
-  do
-   echo "${CNT} ${ONEPROBE}" >> /tmp/3builddistro-probedisk
-   CNT=`expr $CNT + 1`
-  done
-  echo
-  echo "Type number which is your SD card:"
-  cat /tmp/3builddistro-probedisk
-  read sdnumber
-  SDDEVICE="`cat /tmp/3builddistro-probedisk | head -n $sdnumber | tail -n 1 | cut -f 2 -d ' ' | cut -f 1 -d '|'`"
-  echo -n "You chose ${SDDEVICE} Press ENTER if correct: "
-  read sdcorrect
-  [ "$sdcorrect" = "" ] && break
- done
- echo
- echo "Sanity check: ../sd-skeleton-images/${SDIMAGE}
-is to be written to ${SDDEVICE}."
- echo -n "Press ENTER to continue: "
- read yepgo
- echo
  
  #need to know uncompressed size of image...
  echo "Uncompressing image, please wait..."
@@ -3369,17 +3338,6 @@ is to be written to ${SDDEVICE}."
   exit 1
  fi
  sync
-
- IMGBYTES=`stat --format=%s $SDBASE`
- SDCARDINFO="`disktype ${SDDEVICE}`"
- #120506b check that sd card big enough...
- SDCARDBYTES=`echo "$SDCARDINFO" | grep '^Block device' | cut -f 2 -d '(' | cut -f 1 -d ' '` #ex: 4023386112
- if [ $IMGBYTES -gt $SDCARDBYTES ];then
-  echo
-  echo "Sorry, the image file is ${IMGBYTES}bytes, however the
-SD card is only ${SDCARDBYTES}bytes. Cannot continue."
-  exit 1
- fi
 
  #120703 allow 2nd partition to be ext2, ext3 or ext4...
  SDIMGINFO="`disktype ${SDBASE}`"
@@ -3436,19 +3394,14 @@ SD card is only ${SDCARDBYTES}bytes. Cannot continue."
  cp -a rootfs-complete/* /mnt/sdimagep2/
  sync
  #120704 add to /etc/fstab...
- echo "/dev/${SDDEVICE}2     /     ${SDFS2}     defaults,noatime   0 1" >> /mnt/sdimagep2/etc/fstab #120707 change relatime to noatime.
+# echo "/dev/${SDDEVICE}2     /     ${SDFS2}     defaults,noatime   0 1" >> /mnt/sdimagep2/etc/fstab #120707 change relatime to noatime.
+ #not sure if the root partition is referred to as /dev/root or /dev/mmcblk0p2 on the raspi
+ echo "/dev/mmcblk0p2     /     ${SDFS2}     defaults,noatime   0 1" >> /mnt/sdimagep2/etc/fstab
  sync
  echo "...done"
  busybox umount /mnt/sdimagep2 2>/dev/null
  
- echo
- echo "Writing image file ${SDBASE} to SD card ${SDDEVICE}..."
- dd if=${SDBASE} of=${SDDEVICE} bs=4M #120704 added bs=4M
- if [ $? -ne 0 ];then
-  echo "Sorry, operation failure. Aborting script."
-  exit 1
- fi
- sync
+ IMGBYTES=`stat --format=%s $SDBASE`
  
  echo
  echo "Please type the name that you want to give the SD image file, or press ENTER"
@@ -3465,8 +3418,78 @@ SD card is only ${SDCARDBYTES}bytes. Cannot continue."
  [ -f ./${PUPIMG}.xz ] && rm -f ./${PUPIMG}.xz
  xz --stdout ${SDBASE} > ${PUPIMG}.xz
  sync
- rm -f ./${SDBASE}
  echo "...${PUPIMG}.xz created."
+ COMPRIMGBYTES=`stat --format=%s ${PUPIMG}.xz`
+ echo
+ echo "The image is now ${PUPIMG}.xz and is ${COMPRIMGBYTES}bytes."
+ COMPRIMGK=`expr $COMPRIMGBYTES \/ 1024`
+ echo "(${COMPRIMGK}KB)"
+ echo "Image file may be distributed to others!"
+ echo
+
+ echo
+ echo "Would you like to write it to a SD card?  ENTER only for no,"
+ echo -n "or any printable char then ENTER to write image to SD card: "
+ read writeSD
+ if [ "$writeSD" = "" ];then
+  WRITE_SD="no"
+ else
+  WRITE_SD="yes"
+ fi
+
+ if [ "$WRITE_SD" = "yes" ];then
+
+  echo
+  echo "Please insert the SD card. Make sure that it is the same size or bigger than
+ indicated on the filename of the skeleton image file that you chose."
+  echo -n "Press ENTER after it is inserted: "
+  read waitinsert
+  sleep 2
+  while [ 1 ];do
+   CNT=1
+   echo -n "" > /tmp/3builddistro-probedisk
+   probedisk |
+   while read ONEPROBE
+   do
+    echo "${CNT} ${ONEPROBE}" >> /tmp/3builddistro-probedisk
+    CNT=`expr $CNT + 1`
+   done
+   echo
+   echo "Type number which is your SD card:"
+   cat /tmp/3builddistro-probedisk
+   read sdnumber
+   SDDEVICE="`cat /tmp/3builddistro-probedisk | head -n $sdnumber | tail -n 1 | cut -f 2 -d ' ' | cut -f 1 -d '|'`"
+   echo -n "You chose ${SDDEVICE} Press ENTER if correct: "
+   read sdcorrect
+   [ "$sdcorrect" = "" ] && break
+  done
+  echo
+  echo "Sanity check: ../sd-skeleton-images/${SDIMAGE}
+ is to be written to ${SDDEVICE}."
+  echo -n "Press ENTER to continue: "
+  read yepgo
+
+  SDCARDINFO="`disktype ${SDDEVICE}`"
+  #120506b check that sd card big enough...
+  SDCARDBYTES=`echo "$SDCARDINFO" | grep '^Block device' | cut -f 2 -d '(' | cut -f 1 -d ' '` #ex: 4023386112
+  if [ $IMGBYTES -gt $SDCARDBYTES ];then
+   echo
+   echo "Sorry, the image file is ${IMGBYTES}bytes, however the
+SD card is only ${SDCARDBYTES}bytes. Cannot continue."
+   exit 1
+  fi
+
+  echo
+  echo "Writing image file ${SDBASE} to SD card ${SDDEVICE}..."
+  dd if=${SDBASE} of=${SDDEVICE} bs=4M #120704 added bs=4M
+  if [ $? -ne 0 ];then
+   echo "Sorry, operation failure. Aborting script."
+   exit 1
+  fi
+  sync
+ fi # if WRITE_SD
+
+ rm -f ./${SDBASE}
  
  
 #130530 this is old code...
@@ -3570,17 +3593,11 @@ SD card is only ${SDCARDBYTES}bytes. Cannot continue."
 # sync
 
 
+ if [ "$WRITE_SD" = "yes" ];then
  #update desktop drive icons. note, this is also done in /usr/sbin/bootflash, puppyinstaller, gparted_shell...
  #/tmp/pup_event_frontend_block_request is used in /sbin/pup_event_frontend_d to refresh drv...
  THEDRIVE="`echo -n "$SDDEVICE" | cut -f 3 -d '/'`"
  echo "$THEDRIVE" > /tmp/pup_event_frontend_block_request
- COMPRIMGBYTES=`stat --format=%s ${PUPIMG}.xz`
- echo
- echo "The image is now ${PUPIMG}.xz and is ${COMPRIMGBYTES}bytes."
- COMPRIMGK=`expr $COMPRIMGBYTES \/ 1024`
- echo "(${COMPRIMGK}KB)"
- echo "Image file may be distributed to others!"
- echo
 
  #120510...
  echo "If the SD card currently plugged in is bigger than the image, for example
@@ -3601,6 +3618,7 @@ ${SDFS2} partition to fill the remaining space -- this is for your own use."
    echo "$THEDRIVE" > /tmp/pup_event_frontend_block_request
   fi
  fi
+ fi # if WRITE_SD
 
 fi
 
