Fail 3builddistro if wget failed.

diff --git a/woof-code/3builddistro b/woof-code/3builddistro
--- a/woof-code/3builddistro
+++ b/woof-code/3builddistro
@@ -498,7 +498,14 @@ done
 if [ -n "$DOCS_URL" ]; then
 	echo "Overwriting current documentation with developer provided $DOCS_URL..."
 	rm -rf sandbox3/rootfs-complete/usr/share/doc
-	wget -t 3 -T 60 -O doc.zip "$DOCS_URL"
+
+	wget_output=$(wget -t 3 -T 60 -O doc.zip "$DOCS_URL")
+
+	if [ $wget_output -ne 0 ]; then
+		echo "ERROR: wget failed. Read above lines to see the error."
+		exit 1
+	fi
+
 	unzip doc.zip -d sandbox3/rootfs-complete/usr/share/
 	rm doc.zip
 fi
