Initial RK3288 support in 3builddistro

diff --git a/woof-code/3builddistro-Z b/woof-code/3builddistro-Z
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -121,11 +121,13 @@ if [ "$SDFLAG" != "" ];then
  echo "Type number of board that you are building for: 
 1 Raspberry Pi
 2 Mele A1000 or A2000 (or other A10 board)
-3 ODROID-X (or other Exynos 4412 board)"
+3 Rockchip RK3288
+4 ODROID-X (or other Exynos 4412 board)"
  read boardnum
  case $boardnum in
   1) BOOT_BOARD='raspi' ;;
   2) BOOT_BOARD='mele' ;;
+  3) BOOT_BOARD='rk3288' ;;
   *) BOOT_BOARD='odroidx' ;;
  esac
  echo "...you chose $BOOT_BOARD"
@@ -2669,26 +2671,32 @@ indicated on the filename of the skeleton image file that you chose."
  
  echo
  echo "Copying Linux kernel to SD image file..."
- mkdir -p /mnt/sdimagep1
- mkdir -p /mnt/sdimagep2
- mount-FULL -t vfat -o loop,offset=${P1STARTBYTES} ../${WOOF_OUTPUT}/${PUPIMG} /mnt/sdimagep1
- if [ $? -ne 0 ];then
-  echo "Sorry, mounting vfat partition 1 (at offset ${P1STARTBYTES}) of ${PUPIMG} failed. Aborting script."
-  exit 1
+ if [ "$BOOT_BOARD" = "rk3288" ];then
+  # depthcharge reads the kernel image directly from the "kernel" partition, without a file system
+  dd if=build/vmlinuz of=../${WOOF_OUTPUT}/${PUPIMG} obs=8192 seek=1
+  sync
+ else
+  mkdir -p /mnt/sdimagep1
+  mount-FULL -t vfat -o loop,offset=${P1STARTBYTES} ../${WOOF_OUTPUT}/${PUPIMG} /mnt/sdimagep1
+  if [ $? -ne 0 ];then
+   echo "Sorry, mounting vfat partition 1 (at offset ${P1STARTBYTES}) of ${PUPIMG} failed. Aborting script."
+   exit 1
+  fi
+  #120613 restore correct kernel image name...
+  case $REALKERNAME in
+   uImage)     cp -f build/vmlinuz /mnt/sdimagep1/uImage ;;
+   kernel.img) cp -f build/vmlinuz /mnt/sdimagep1/kernel.img ;;
+   *)          cp -f build/vmlinuz /mnt/sdimagep1/ ;;
+  esac
+  echo -n "$REALKERNAME" > /mnt/sdimagep1/REALKERNAME #just in case need to know, in a running puppy.
+  sync
+  busybox umount /mnt/sdimagep1 2>/dev/null
  fi
- #120613 restore correct kernel image name...
- case $REALKERNAME in
-  uImage)     cp -f build/vmlinuz /mnt/sdimagep1/uImage ;;
-  kernel.img) cp -f build/vmlinuz /mnt/sdimagep1/kernel.img ;;
-  *)          cp -f build/vmlinuz /mnt/sdimagep1/ ;;
- esac
- echo -n "$REALKERNAME" > /mnt/sdimagep1/REALKERNAME #just in case need to know, in a running puppy.
- sync
- busybox umount /mnt/sdimagep1 2>/dev/null
  echo "...done"
  
  echo
  echo "Copying Puppy filesystem to SD image file, please wait..."
+ mkdir -p /mnt/sdimagep2
  mount-FULL -t ${SDFS2} -o loop,offset=${P2STARTBYTES} ../${WOOF_OUTPUT}/${PUPIMG} /mnt/sdimagep2
  if [ $? -ne 0 ];then
   echo "Sorry, mounting ${SDFS2} partition 2 (at offset ${P2STARTBYTES}) of ${PUPIMG} failed. Aborting script."
