woof-output* now created in 3builddistro-Z #12dcada

diff --git a/woof-code/3builddistro-Z b/woof-code/3builddistro-Z
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -91,9 +91,7 @@ echo "Do you want to create a live-CD .iso file, which is the normal choice for 
 PC-compatible target, or is your target an SD-card for an ARM-based board?
 In the latter case, you would already have downloaded an SD-card skeleton image
 file into folder 'sd-skeleton-images' (done by script '1download') -- if there
-is no image file in that folder, you cannot choose the SD-card option.
-The latter choice will also require an SD card to write to, and you must have
-it available now."
+is no image file in that folder, you cannot choose the SD-card option."
 echo "WARNING: for the SD-card option, you must have enough free space in the
 current directory ${WKGDIR}/sandbox3
 to expand the SD image file, typically 4GB."
@@ -206,6 +204,7 @@ echo
  #fi
 #fi
 #140615
+MKSQUASHFS=mksquashfs #use running system's 140619
 COMPCHOICE='-comp xz -Xbcj x86 -b 512K'
 #110823
 echo
@@ -225,6 +224,8 @@ KERNEL3CHARS="`echo -n "$KERNELVER" | tr -d '.' | tr -d '\-' | tr -d '[a-z]' | r
 #110422 new traditional names...
 tradPUPPYSFS="puppy_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
 tradZDRVSFS="zdrv_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
+tradADRVSFS="adrv_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
+tradYDRVSFS="ydrv_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
 tradDEVXSFS="devx_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
 
 #if [ $7 ];then #passed in from woof_gui
@@ -252,11 +253,15 @@ if [ "$CHK_SIMPLE_FILENAMES" = "true" ];then
  echo '...simple chosen'
  PUPPYSFS='puppy.sfs'
  ZDRVSFS='zdrv.sfs'
+ ADRVSFS='adrv.sfs'
+ YDRVSFS='ydrv.sfs'
  DEVXSFS='devx.sfs'
 else
  echo '...traditional chosen'
  PUPPYSFS="$tradPUPPYSFS"
  ZDRVSFS="$tradZDRVSFS"
+ ADRVSFS="$tradADRVSFS"
+ YDRVSFS="$tradYDRVSFS" 
  DEVXSFS="$tradDEVXSFS"
 fi
 
@@ -763,7 +768,9 @@ DISTRO_IDSTRING='${IDSTRING}'
 #Note, the 'SFS' files below are what the 'init' script in initrd.gz searches for,
 #for the partition, path and actual files loaded, see PUPSFS and ZDRV in /etc/rc.d/PUPSTATE
 DISTRO_PUPPYSFS='${PUPPYSFS}'
-DISTRO_ZDRVSFS='${ZDRVSFS}'"
+DISTRO_ZDRVSFS='${ZDRVSFS}
+DISTRO_ADRVSFS='${ADRVSFS}
+DISTRO_YDRVSFS='${YDRVSFS}'"
 #DISTRO_DEVXSFS='${DEVXSFS}'"
 echo "$NEWVARIABLES" >> initrd-tree/DISTRO_SPECS
 echo "$NEWVARIABLES" >> rootfs-complete/etc/DISTRO_SPECS
@@ -1422,43 +1429,16 @@ if [ "$wantfont" != "" ];then
  echo '</Options>' >> rootfs-complete/root/.config/rox.sourceforge.net/ROX-Filer/Options
 fi
 
-#w464 maybe get rid of old mksquashfs... v424 fix
-#w091019 running puppy with older glibc, mksquashfs may not work, so must chroot...
-if [ "$WOOF_HOSTARCH" = "$WOOF_TARGETARCH" ];then #111123
- if [ -e rootfs-complete/usr/sbin/mksquashfs ];then
-  if [ "`chroot rootfs-complete /usr/sbin/mksquashfs -version | grep 'mksquashfs version 4'`" = "" ];then
-   mv -f rootfs-complete/usr/sbin/mksquashfs rootfs-complete/usr/sbin/mksquashfs3
-  else
-   [ ! -e rootfs-complete/usr/sbin/mksquashfs4 ] && mv -f rootfs-complete/usr/sbin/mksquashfs rootfs-complete/usr/sbin/mksquashfs4
-  fi
-  if [ "$SQUASHFSMAJOR" = "4" ];then #100607
-   [ -e rootfs-complete/usr/sbin/mksquashfs4 ] && ln -s mksquashfs4 rootfs-complete/usr/sbin/mksquashfs
-  else
-   ln -s mksquashfs3 rootfs-complete/usr/sbin/mksquashfs
-  fi
- fi
- #ditto for unsquashfs... v424 fix w091019 chroot fix...
- if [ -e rootfs-complete/usr/sbin/unsquashfs ];then
-  if [ "`chroot rootfs-complete /usr/sbin/unsquashfs -version | grep 'unsquashfs version 4'`" = "" ];then
-   mv -f rootfs-complete/usr/sbin/unsquashfs rootfs-complete/usr/sbin/unsquashfs3
-  else
-   [ ! -e rootfs-complete/usr/sbin/unsquashfs4 ] && mv -f rootfs-complete/usr/sbin/unsquashfs rootfs-complete/usr/sbin/unsquashfs4
-  fi
-  if [ "$SQUASHFSMAJOR" = "4" ];then #100607
-   [ -e rootfs-complete/usr/sbin/unsquashfs4 ] && ln -s unsquashfs4 rootfs-complete/usr/sbin/unsquashfs
-  else
-   ln -s unsquashfs3 rootfs-complete/usr/sbin/unsquashfs
-  fi
- fi
-else
- #cross-build, assume recent kernel and has squashfs v4...
- [ ! -e rootfs-complete/usr/sbin/mksquashfs4 ] && mv -f rootfs-complete/usr/sbin/mksquashfs rootfs-complete/usr/sbin/mksquashfs4
- [ -e rootfs-complete/usr/sbin/mksquashfs ] && [ ! -h rootfs-complete/usr/sbin/mksquashfs ] && mv -f rootfs-complete/usr/sbin/mksquashfs rootfs-complete/usr/sbin/mksquashfs3 #120502
- [ -e rootfs-complete/usr/sbin/mksquashfs4 ] && ln -s mksquashfs4 rootfs-complete/usr/sbin/mksquashfs
- [ ! -e rootfs-complete/usr/sbin/unsquashfs4 ] && mv -f rootfs-complete/usr/sbin/unsquashfs rootfs-complete/usr/sbin/unsquashfs4
- [ -e rootfs-complete/usr/sbin/unsquashfs ] && [ ! -h rootfs-complete/usr/sbin/unsquashfs ] && mv -f rootfs-complete/usr/sbin/unsquashfs rootfs-complete/usr/sbin/unsquashfs3 #120502
- [ -e rootfs-complete/usr/sbin/unsquashfs4 ] && ln -s unsquashfs4 rootfs-complete/usr/sbin/unsquashfs
-fi
+RK=`uname -r`
+[ ${RK%%*.} -lt 3 ] && echo "Running kernel too old, exiting" && exit 1
+
+#w464 maybe get rid of old mksquashfs... v424 fix #140619 assume 3 kernel
+[ ! -e rootfs-complete/usr/sbin/mksquashfs4 ] && mv -f rootfs-complete/usr/sbin/mksquashfs rootfs-complete/usr/sbin/mksquashfs4
+[ -e rootfs-complete/usr/sbin/mksquashfs ] && [ ! -h rootfs-complete/usr/sbin/mksquashfs ] && mv -f rootfs-complete/usr/sbin/mksquashfs rootfs-complete/usr/sbin/mksquashfs3 #120502
+[ -e rootfs-complete/usr/sbin/mksquashfs4 ] && ln -s mksquashfs4 rootfs-complete/usr/sbin/mksquashfs
+[ ! -e rootfs-complete/usr/sbin/unsquashfs4 ] && mv -f rootfs-complete/usr/sbin/unsquashfs rootfs-complete/usr/sbin/unsquashfs4
+[ -e rootfs-complete/usr/sbin/unsquashfs ] && [ ! -h rootfs-complete/usr/sbin/unsquashfs ] && mv -f rootfs-complete/usr/sbin/unsquashfs rootfs-complete/usr/sbin/unsquashfs3 #120502
+[ -e rootfs-complete/usr/sbin/unsquashfs4 ] && ln -s unsquashfs4 rootfs-complete/usr/sbin/unsquashfs
 
 #w470 create a table for dialog/Xdialog: /usr/share/i18n/dialog_table
 #'chooselocale' is called from /etc/rc.d/rc.country at first boot and
@@ -2274,18 +2254,30 @@ fi
 
 rm -rf rootfs-complete/tmp/* #121123 some above chroot operations may have left something behind in here.
 
-
+BUILD_SFS='yes'
+if [ "$SDFLAG" != "" ]; then
+ echo
+ echo "Since you are building a SD card image, it is not necessary"
+ echo "to build the main sfs file.  Press ENTER only to skip,"
+ echo "any other character then ENTER to build it anyway."
+ read buildanyway
+ if [ "$buildanyway" = '' ]; then
+  BUILD_SFS='no'
+ fi
+fi
+if [ "$BUILD_SFS" = 'yes' ]; then
 ###########
 #build the rootfs-complete sfs...
 echo
 echo "Now building the main f.s., ${PUPPYSFS}..."
 sync
 rm -f build/${PUPPYSFS} 2>/dev/null
-mksquashfs rootfs-complete build/${PUPPYSFS} ${COMPCHOICE} #100911 110713
+${MKSQUASHFS} rootfs-complete build/${PUPPYSFS} ${COMPCHOICE} #100911 110713
 sync
 echo -n "$IDSTRING" >> build/${PUPPYSFS} #100911 16-byte id-string appended to file.
 sync
 ###########
+fi # if BUILD_SFS
 
 #if separate 'zdrv' exists, copy that into live-cd also...
 if [ -f ${ZDRVSFS} ];then #100911
@@ -2312,9 +2304,12 @@ fi
 #timeout 50" > build/isolinux.cfg
 
 
+WOOF_OUTPUT="woof-output-${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}" #woodenshoe-wi idea. #140619
+[ -d ../$WOOF_OUTPUT ] || mkdir -p ../$WOOF_OUTPUT
+
 #build live-cd .iso file...
 echo "Now building ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso"
-rm -f ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso 2>/dev/null
+rm -f ../${WOOF_OUTPUT}/${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso 2>/dev/null
 if [ -f rootfs-complete/usr/lib/syslinux/isolinux.bin ];then
  cp -a rootfs-complete/usr/lib/syslinux/isolinux.bin build/
 else
@@ -2427,12 +2422,15 @@ sync
 
 
 if [ "$SDFLAG" = "" ];then #120506
- $MKISOFS -D -R -o ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table ./build/
+ $MKISOFS -D -R -o ../${WOOF_OUTPUT}/${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table ./build/
  sync
  # 131227 iguleder: made the generated ISO image hybrid, so it can be written to flash drives using dd
  isohybrid="$(which isohybrid)"
- [ -n "$isohybrid" ] && $isohybrid ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso
+ [ -n "$isohybrid" ] && $isohybrid ../${WOOF_OUTPUT}/${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso
+ CUR_DIR="$PWD"
+ cd ../${WOOF_OUTPUT}
  md5sum ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso > ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso.md5.txt
+ cd "$CUR_DIR"
  echo
  echo "Would you like to burn it to a CD? "
  echo -n "ENTER only for yes, or any printable char then ENTER not to: "
@@ -2455,7 +2453,7 @@ if [ "$SDFLAG" = "" ];then #120506
   echo -n "Then hit ENTER key: "
   read yayburn
 # $CDRECORD $BURNMULTI -data -eject -v speed=4 padsize=300k dev=ATAPI:$CDR ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso
-  $CDRECORD $BURNMULTI -data -eject -v speed=4 padsize=300k dev=$CDR ${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso
+  $CDRECORD $BURNMULTI -data -eject -v speed=4 padsize=300k dev=$CDR ../${WOOF_OUTPUT}/${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}${SCSIFLAG}.iso
   sync
   eject $CDR
   echo "...done"
@@ -2506,46 +2504,35 @@ indicated on the filename of the skeleton image file that you chose."
   read sdcorrect
   [ "$sdcorrect" = "" ] && break
  done
+ SDBASE="`basename ../sd-skeleton-images/${SDIMAGE} .xz`"
  echo
- echo "Sanity check: ../sd-skeleton-images/${SDIMAGE}
-is to be written to ${SDDEVICE}."
- echo -n "Press ENTER to continue: "
- read yepgo
+ echo "Please type the name that you want to give the SD image file, or press ENTER"
+ SDBASEBASE="`basename $SDBASE .img | sed -e 's%-201[0-9]*%-%' -e 's%-skeleton%-%' | cut -f 1,2,3 -d '-'`"
+ PUPIMG="${SDBASEBASE}-${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}.img"
+ echo -n "only for the default [${PUPIMG}]: "
+ read PUPIMG1
+ [ "$PUPIMG1" != "" ] && PUPIMG="`basename $PUPIMG1 .img`.img"
+ echo "...chosen $PUPIMG"
  echo
  
  #need to know uncompressed size of image...
  echo "Uncompressing image, please wait..."
- cp -f ../sd-skeleton-images/${SDIMAGE} ./${SDIMAGE}
- sync
- SDBASE="`basename $SDIMAGE .xz`"
- [ -f ./${SDBASE} ] && rm -f ./${SDBASE}
- unxz ${SDIMAGE}
+ [ -f ../${WOOF_OUTPUT}/${PUPIMG} ] && rm -f ../${WOOF_OUTPUT}/${PUPIMG}
+ unxz --stdout ../sd-skeleton-images/${SDIMAGE} > ../${WOOF_OUTPUT}/${PUPIMG}
  if [ $? -ne 0 ];then
-  [ -f ./$SDIMAGE ] && rm -f ./$SDIMAGE
-  [ -f ./$SDBASE ] && rm -f ./$SDBASE
+  [ -f ../${WOOF_OUTPUT}/${PUPIMG} ] && rm -f ../${WOOF_OUTPUT}/${PUPIMG}
   echo "Uncompress fail. Aborting."
   exit 1
  fi
  sync
 
- IMGBYTES=`stat --format=%s $SDBASE`
- SDCARDINFO="`disktype ${SDDEVICE}`"
- #120506b check that sd card big enough...
- SDCARDBYTES=`echo "$SDCARDINFO" | grep '^Block device' | cut -f 2 -d '(' | cut -f 1 -d ' '` #ex: 4023386112
- if [ $IMGBYTES -gt $SDCARDBYTES ];then
-  echo
-  echo "Sorry, the image file is ${IMGBYTES}bytes, however the
-SD card is only ${SDCARDBYTES}bytes. Cannot continue."
-  exit 1
- fi
-
  #120703 allow 2nd partition to be ext2, ext3 or ext4...
- SDIMGINFO="`disktype ${SDBASE}`"
+ SDIMGINFO="`disktype ../${WOOF_OUTPUT}/${PUPIMG}`"
  SDFS2="`echo "$SDIMGINFO" | grep -o 'Ext[0-9] file system' | cut -f 1 -d ' ' | tr '[A-Z]' '[a-z]'`"
  case $SDFS2 in
   ext2|ext3|ext4) SDFS2="ext4" ;; #120706 hack for now. disktype misreports ext4 without journal as ext2.
   *)
-   echo -n "wrong f.s. ${SDFS2} in ${SDBASE}, aborting. Press ENTER: "
+   echo -n "wrong f.s. ${SDFS2} in ${SDIMAGE}, aborting. Press ENTER: "
    read exitme
    exit
   ;;
@@ -2568,9 +2555,9 @@ SD card is only ${SDCARDBYTES}bytes. Cannot continue."
  echo "Copying Linux kernel to SD image file..."
  mkdir -p /mnt/sdimagep1
  mkdir -p /mnt/sdimagep2
- mount-FULL -t vfat -o loop,offset=${P1STARTBYTES} ${SDBASE} /mnt/sdimagep1
+ mount-FULL -t vfat -o loop,offset=${P1STARTBYTES} ../${WOOF_OUTPUT}/${PUPIMG} /mnt/sdimagep1
  if [ $? -ne 0 ];then
-  echo "Sorry, mounting vfat partition 1 (at offset ${P1STARTBYTES}) of ${SDBASE} failed. Aborting script."
+  echo "Sorry, mounting vfat partition 1 (at offset ${P1STARTBYTES}) of ${PUPIMG} failed. Aborting script."
   exit 1
  fi
  #120613 restore correct kernel image name...
@@ -2586,47 +2573,126 @@ SD card is only ${SDCARDBYTES}bytes. Cannot continue."
  
  echo
  echo "Copying Puppy filesystem to SD image file, please wait..."
- mount-FULL -t ${SDFS2} -o loop,offset=${P2STARTBYTES} ${SDBASE} /mnt/sdimagep2
+ mount-FULL -t ${SDFS2} -o loop,offset=${P2STARTBYTES} ../${WOOF_OUTPUT}/${PUPIMG} /mnt/sdimagep2
  if [ $? -ne 0 ];then
-  echo "Sorry, mounting ${SDFS2} partition 2 (at offset ${P2STARTBYTES}) of ${SDBASE} failed. Aborting script."
+  echo "Sorry, mounting ${SDFS2} partition 2 (at offset ${P2STARTBYTES}) of ${PUPIMG} failed. Aborting script."
   exit 1
  fi
  cp -a rootfs-complete/* /mnt/sdimagep2/
  sync
  #120704 add to /etc/fstab...
- echo "/dev/${SDDEVICE}2     /     ${SDFS2}     defaults,noatime   0 1" >> /mnt/sdimagep2/etc/fstab #120707 change relatime to noatime.
+# echo "/dev/${SDDEVICE}2     /     ${SDFS2}     defaults,noatime   0 1" >> /mnt/sdimagep2/etc/fstab #120707 change relatime to noatime.
+ #not sure if the root partition is referred to as /dev/root or /dev/mmcblk0p2 on the raspi
+ echo "/dev/mmcblk0p2     /     ${SDFS2}     defaults,noatime   0 1" >> /mnt/sdimagep2/etc/fstab
  sync
  echo "...done"
  busybox umount /mnt/sdimagep2 2>/dev/null
  
- echo
- echo "Writing image file ${SDBASE} to SD card ${SDDEVICE}..."
- dd if=${SDBASE} of=${SDDEVICE} bs=4M #120704 added bs=4M
- if [ $? -ne 0 ];then
-  echo "Sorry, operation failure. Aborting script."
-  exit 1
- fi
- sync
+ IMGBYTES=`stat --format=%s ../${WOOF_OUTPUT}/$PUPIMG`
  
- echo
- echo "Please type the name that you want to give the SD image file, or press ENTER"
- SDBASEBASE="`basename $SDBASE .img | sed -e 's%-201[0-9]*%-%' -e 's%-skeleton%-%' | cut -f 1,2,3 -d '-'`"
- PUPIMG="${SDBASEBASE}-${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}.img"
- echo -n "only for the default [${PUPIMG}]: "
- read PUPIMG1
- [ "$PUPIMG1" != "" ] && PUPIMG="$PUPIMG1"
- echo "...chosen $PUPIMG"
  echo
  IMGK=`expr $IMGBYTES \/ 1024`
  echo "The image file is ${IMGK}KB, so needs to be compressed for distribution."
+
+ echo "If you only want to write to SD card choose 'none' which is the fastest."
+ echo "You can also compress the image file yourself later."
+ echo "Choose compression type:
+1 xz   (smallest, slowest)
+2 gz   (larger, faster)
+3 none (huge, instant)"
+ read compresstype
+ case $compresstype in
+  1) COMPRESS='xz' ;;
+  2) COMPRESS='gz' ;;
+  *) COMPRESS='none' ;;
+ esac
+ echo "...you chose $COMPRESS"
+
+ if [ "$COMPRESS" != 'none' ]; then
  echo "Compressing, please wait..."
- [ -f ./${PUPIMG}.xz ] && rm -f ./${PUPIMG}.xz
- xz --stdout ${SDBASE} > ${PUPIMG}.xz
+ [ -f ../${WOOF_OUTPUT}/${PUPIMG}.${COMPRESS} ] && rm -f ../${WOOF_OUTPUT}/${PUPIMG}.${COMPRESS}
+ if [ "$COMPRESS" = 'xz' ]; then
+ xz --stdout ../${WOOF_OUTPUT}/${PUPIMG} > ../${WOOF_OUTPUT}/${PUPIMG}.xz
+ elif [ "$COMPRESS" = 'gz' ]; then
+ gzip --stdout ../${WOOF_OUTPUT}/${PUPIMG} > ../${WOOF_OUTPUT}/${PUPIMG}.gz
+ fi
  sync
- rm -f ./${SDBASE}
- echo "...${PUPIMG}.xz created."
- 
- 
+ echo "...${PUPIMG}.${COMPRESS} created."
+ COMPRIMGBYTES=`stat --format=%s ../${WOOF_OUTPUT}/${PUPIMG}.${COMPRESS}`
+ echo
+ echo "The image is now ${PUPIMG}.${COMPRESS} and is ${COMPRIMGBYTES}bytes."
+ COMPRIMGK=`expr $COMPRIMGBYTES \/ 1024`
+ echo "(${COMPRIMGK}KB)"
+ echo "Image file may be distributed to others!"
+ echo
+ fi # if COMPRESS
+
+ echo
+ echo "Would you like to write it to a SD card?  ENTER only for no,"
+ echo -n "or any printable char then ENTER to write image to SD card: "
+ read writeSD
+ if [ "$writeSD" = "" ];then
+  WRITE_SD="no"
+ else
+  WRITE_SD="yes"
+ fi
+
+ if [ "$WRITE_SD" = "yes" ];then
+
+  echo
+  echo "Please insert the SD card. Make sure that it is the same size or bigger than
+ indicated on the filename of the skeleton image file that you chose."
+  echo -n "Press ENTER after it is inserted: "
+  read waitinsert
+  sleep 2
+  while [ 1 ];do
+   CNT=1
+   echo -n "" > /tmp/3builddistro-probedisk
+   probedisk |
+   while read ONEPROBE
+   do
+    echo "${CNT} ${ONEPROBE}" >> /tmp/3builddistro-probedisk
+    CNT=`expr $CNT + 1`
+   done
+   echo
+   echo "Type number which is your SD card:"
+   cat /tmp/3builddistro-probedisk
+   read sdnumber
+   SDDEVICE="`cat /tmp/3builddistro-probedisk | head -n $sdnumber | tail -n 1 | cut -f 2 -d ' ' | cut -f 1 -d '|'`"
+   echo -n "You chose ${SDDEVICE} Press ENTER if correct: "
+   read sdcorrect
+   [ "$sdcorrect" = "" ] && break
+  done
+  echo
+  echo "Sanity check: ${PUPIMG}
+ is to be written to ${SDDEVICE}."
+  echo -n "Press ENTER to continue: "
+  read yepgo
+
+  SDCARDINFO="`disktype ${SDDEVICE}`"
+  #120506b check that sd card big enough...
+  SDCARDBYTES=`echo "$SDCARDINFO" | grep '^Block device' | cut -f 2 -d '(' | cut -f 1 -d ' '` #ex: 4023386112
+  if [ $IMGBYTES -gt $SDCARDBYTES ];then
+   echo
+   echo "Sorry, the image file is ${IMGBYTES}bytes, however the
+SD card is only ${SDCARDBYTES}bytes. Cannot continue."
+   exit 1
+  fi
+
+  echo
+  echo "Writing image file ${PUPIMG} to SD card ${SDDEVICE}..."
+  dd if=../${WOOF_OUTPUT}/${PUPIMG} of=${SDDEVICE} bs=4M #120704 added bs=4M
+  if [ $? -ne 0 ];then
+   echo "Sorry, operation failure. Aborting script."
+   exit 1
+  fi
+  sync
+ fi # if WRITE_SD
+
+ if [ "$COMPRESS" != 'none' ]; then
+ rm -f ../${WOOF_OUTPUT}/${PUPIMG}
+ fi
+
 #130530 this is old code...
 # echo "Writing skeleton image to ${SDDEVICE}, please wait very patiently..."
 # dd if=${SDBASE} of=${SDDEVICE} bs=4M #120704 added bs=4M
@@ -2728,17 +2794,11 @@ SD card is only ${SDCARDBYTES}bytes. Cannot continue."
 # sync
 
 
+ if [ "$WRITE_SD" = "yes" ];then
  #update desktop drive icons. note, this is also done in /usr/sbin/bootflash, puppyinstaller, gparted_shell...
  #/tmp/pup_event_frontend_block_request is used in /sbin/pup_event_frontend_d to refresh drv...
  THEDRIVE="`echo -n "$SDDEVICE" | cut -f 3 -d '/'`"
  echo "$THEDRIVE" > /tmp/pup_event_frontend_block_request
- COMPRIMGBYTES=`stat --format=%s ${PUPIMG}.xz`
- echo
- echo "The image is now ${PUPIMG}.xz and is ${COMPRIMGBYTES}bytes."
- COMPRIMGK=`expr $COMPRIMGBYTES \/ 1024`
- echo "(${COMPRIMGK}KB)"
- echo "Image file may be distributed to others!"
- echo
 
  #120510...
  echo "If the SD card currently plugged in is bigger than the image, for example
@@ -2759,6 +2819,7 @@ ${SDFS2} partition to fill the remaining space -- this is for your own use."
    echo "$THEDRIVE" > /tmp/pup_event_frontend_block_request
   fi
  fi
+ fi # if WRITE_SD
 
 fi
 
@@ -2777,7 +2838,7 @@ echo "Building ${DEVXSFS}..."
 echo " building sandbox3/devx ..."
 rm -f /tmp/3builddistro_removed_alt_dev #101013
 ALLGENNAMESD="`echo "$PKGS_SPECS_TABLE" | grep '^yes' | cut -f 2 -d '|' | sed -e 's%$%_DEV%'`"
-rm -f sandbox3/${DEVXSFS} 2>/dev/null #100911
+rm -f ./${WOOF_OUTPUT}/${DEVXSFS} 2>/dev/null #100911
 for ONEDEV in `ls -1 packages-${DISTRO_FILE_PREFIX} | grep '_DEV$' | tr '\n' ' '`
 do
 
@@ -2975,14 +3036,15 @@ rm -f sandbox3/devx/etc/profile.d/*.csh
 # rm -rf sandbox3/devx/usr/bin/multiarch-i386-linux
 #fi
 
-echo "Now creating sandbox3/${DEVXSFS} ..."
-mksquashfs sandbox3/devx sandbox3/${DEVXSFS} ${COMPCHOICE} #100911 110713
+echo "Now creating ${DEVXSFS} ..."
+${MKSQUASHFS} sandbox3/devx ./${WOOF_OUTPUT}/${DEVXSFS} ${COMPCHOICE} #100911 110713
 sync
-chmod 644 sandbox3/${DEVXSFS}
-cd sandbox3
+chmod 644 ./${WOOF_OUTPUT}/${DEVXSFS}
+CUR_DIR="$PWD"
+cd ./${WOOF_OUTPUT}
 echo -n "$IDSTRING" >> ${DEVXSFS} #100911 16-byte id-string appended to file.
 md5sum ${DEVXSFS} > ${DEVXSFS}.md5.txt #100911
-cd ..
+cd "$CUR_DIR"
 sync
 echo "...done"
 
