(grub4dos) support alternative kernel in the puppy cd

diff --git a/woof-code/3builddistro-Z b/woof-code/3builddistro-Z
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -1,8 +1,8 @@
 #!/bin/bash
 # new for fatdog style kernel
-# we need udev >= 176
 
 export LANG=C #faster.
+export BUILDSYS=yes
 
 CDRECORD='cdrecord'
 MKISOFS='mkisofs'
@@ -645,6 +645,28 @@ sync
 echo
 rm -rf build 2>/dev/null
 mkdir build
+
+if [ "$G4DOS_ISO" = "yes" -a ! -z "${ALT_KERNEL_TARBALL}" ] ; then
+	echo "Installing alternative kernel.."
+	akfile=$(basename ${ALT_KERNEL_TARBALL})
+	if [ ! -f ../../local-repositories/huge_kernels/${akfile} ] ; then
+		mkdir -p ../../local-repositories/huge_kernels
+		(
+			cd ../../local-repositories/huge_kernels 
+			wget -c --no-check-certificate ${ALT_KERNEL_TARBALL}
+		)
+	fi
+	cp ../../local-repositories/huge_kernels/${akfile} build/
+	cp ../boot/grub4dos/altkernel.sh build/
+	cd build
+	if ! ./altkernel.sh ${ALT_KERNEL_TARBALL} ; then
+		echo "*** ERROR: Will not include alternative kernel ***"
+		rm -f ../../local-repositories/huge_kernels/${akfile} &>/dev/null
+	fi
+	rm -f altkernel.sh
+	mv -f ${akfile} ../../../local-repositories/huge_kernels
+	cd ..
+fi
 
 case "$KERNEL_TARBALL_URL" in *.pet|*.deb|*.tgz|*.txz) KPKG=yes  ;; esac
 
