3builddistroZ: define SD_IMAGE in _00build.conf

diff --git a/woof-code/3builddistro-Z b/woof-code/3builddistro-Z
--- a/woof-code/3builddistro-Z
+++ b/woof-code/3builddistro-Z
@@ -1227,42 +1227,41 @@ if [ "$SDFLAG" = "zip" ];then
 	fi
 
 elif [ "$SDFLAG" ];then #120506 sd image
- 
-	echo
-	echo "Please choose the SD-card skeleton image file, to suit target board."
-	CNT=1
-	echo -n "" > /tmp/3builddistro-probeimage
-	ls -1 ../sd-skeleton-images | grep 'xz$' | grep "$BOOT_BOARD" | #120714 BOOT_BOARD is raspi, mele, or odroidx.
-	while read ONEIMAGE
-	do
-		echo "${CNT} ${ONEIMAGE}" >> /tmp/3builddistro-probeimage
-		CNT=`expr $CNT + 1`
+
+	# see http://distro.ibiblio.org/puppylinux/arm/sd-skeleton-images
+	if ! [ "$SD_IMAGE" ] ; then
+		echo "SD_IMAGE not defined (url/img.xz md5)"
+		exit 1
+	fi
+	URL=$(echo $SD_IMAGE | cut -f 1 -d ' ')
+	MD5=$(echo $SD_IMAGE | cut -f 2 -d ' ')
+	SDIMAGE=${URL##*/}
+	SDBASE=${SDIMAGE%.xz}
+
+	mkdir -p ../../local-repositories #precaution
+	for i in 1 2 ; do
+		if [ -f ../../local-repositories/${SDIMAGE} ] ; then
+			MD5Z=$(md5sum ../../local-repositories/${SDIMAGE} | cut -f 1 -d ' ')
+			[ "$MD5" != "$MD5Z" ] && rm -f ../../local-repositories/${SDIMAGE}
+		fi
+		if [ ! -f ../../local-repositories/${SDIMAGE} ] ; then
+			wget -P ../../local-repositories/ -c $URL
+			if [ $? -ne 0 ] ; then
+				echo "ERROR downloading $SDIMAGE"
+				rm -f ../../local-repositories/${SDIMAGE}
+				exit 1
+			fi
+		fi
 	done
-	while [ 1 ];do
-		echo
-		echo "Type number which is your choice of SD image:"
-		cat /tmp/3builddistro-probeimage
-		read sdnumber
-		SDIMAGE="`cat /tmp/3builddistro-probeimage | head -n $sdnumber | tail -n 1 | cut -f 2 -d ' '`"
-		echo -n "You chose '${SDIMAGE}' Press ENTER if correct: "
-		read sdcorrect
-		[ "$sdcorrect" = "" ] && break
-	done
-	SDBASE="`basename ../sd-skeleton-images/${SDIMAGE} .xz`"
+
 	echo
-	echo "Please type the name that you want to give the SD image file, or press ENTER"
 	SDBASEBASE="`basename $SDBASE .img | sed -e 's%-201[0-9]*%-%' -e 's%-skeleton%-%' | cut -f 1,2,3 -d '-'`"
 	PUPIMG="${SDBASEBASE}-${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}.img"
-	echo -n "only for the default [${PUPIMG}]: "
-	read PUPIMG1
-	[ "$PUPIMG1" != "" ] && PUPIMG="`basename $PUPIMG1 .img`.img"
-	echo "...chosen $PUPIMG"
-	echo
  
 	#need to know uncompressed size of image...
 	echo "Uncompressing image, please wait..."
 	[ -f ../${WOOF_OUTPUT}/${PUPIMG} ] && rm -f ../${WOOF_OUTPUT}/${PUPIMG}
-	unxz --stdout ../sd-skeleton-images/${SDIMAGE} > ../${WOOF_OUTPUT}/${PUPIMG}
+	unxz --stdout ../../local-repositories/${SDIMAGE} > ../${WOOF_OUTPUT}/${PUPIMG}
 	if [ $? -ne 0 ];then
 		[ -f ../${WOOF_OUTPUT}/${PUPIMG} ] && rm -f ../${WOOF_OUTPUT}/${PUPIMG}
 		echo "Uncompress fail. Aborting."
