Complete with extension type tar.{xz,gz,bz2}.

diff --git a/woof-code/3builddistro b/woof-code/3builddistro
--- a/woof-code/3builddistro
+++ b/woof-code/3builddistro
@@ -503,10 +503,11 @@ esac
 
 if [ -n "$DOCS_URL" ]; then
 	echo "Overwriting current documentation with developer provided $DOCS_URL..."
-	rm -rf sandbox3/rootfs-complete/usr/share/doc
+	
+	DOCS_EXT=$(echo -n $DOCS_URL | rev | cut -f1,2 -d'.' | rev)
 
 	if [ "$CACHE_PERSONAL_DOCS" = 'y' ]; then
-		DOWNLOADED_DOC_FILENAME="../../local-repositories/$(echo "$DOCS_URL" | sha256sum | cut -f 1 -d ' ').zip"
+		DOWNLOADED_DOC_FILENAME="../../local-repositories/$(echo "$DOCS_URL" | sha256sum | cut -f 1 -d ' ').$DOCS_EXT"
 
 		if [ ! -f $DOWNLOADED_DOC_FILENAME ]; then
 			wget -t 3 -T 60 -O $DOWNLOADED_DOC_FILENAME "$DOCS_URL"
@@ -515,9 +516,9 @@ if [ -n "$DOCS_URL" ]; then
 			wget_return_code=0
 		fi
 	else
-		wget -t 3 -T 60 -O "doc.zip" "$DOCS_URL"
+		wget -t 3 -T 60 -O "doc.$DOCS_EXT" "$DOCS_URL"
 		wget_return_code=$?
-		DOWNLOADED_DOC_FILENAME="doc.zip"
+		DOWNLOADED_DOC_FILENAME="doc.$DOCS_EXT"
 	fi
 
 	if [ $wget_output -ne 0 ]; then
@@ -526,9 +527,23 @@ if [ -n "$DOCS_URL" ]; then
 	fi
 
 	TEMP_DIR=".temp.personal_docs"
-	COMPLETED_DOCS_DIR="../sandbox3/rootfs-complete/usr/share" # used from $TEMP_DIR
+	COMPLETED_DOCS_DIR="../sandbox3/rootfs-complete/usr/share/doc" # used from $TEMP_DIR
 
-	unzip $DOWNLOADED_DOC_FILENAME -d $TEMP_DIR
+	case $DOCS_EXT in
+		tar.bz2)
+			tar -xjf $DOWNLOADED_DOC_FILENAME -C $TEMP_DIR
+			;;
+		tar.xz)
+			tar -xJf $DOWNLOADED_DOC_FILENAME -C $TEMP_DIR
+			;;
+		tar.gz)
+			tar -xzf $DOWNLOADED_DOC_FILENAME -C $TEMP_DIR
+    			;;
+ 		*)
+    			echo "ERROR: DOCS_URL's downloaded file matched no known extension (is $DOCS_EXT; supported are tar.{xz,gz,bz2})"
+			exit 1
+    			;;
+    	esac
 
 	cd $TEMP_DIR
 
@@ -537,9 +552,9 @@ if [ -n "$DOCS_URL" ]; then
 		rm -f "$COMPLETED_DOCS_DIR/$entry"
 
 		if [ ${entry:0:4} == ".wh." ]; then
-			rm -f "./$entry" ${entry:4}
+			rm -f "./$entry" "$COMPLETED_DOCS_DIR/"${entry:4}
 		elif [ ${entry:0:5} == ".whd." ]; then
-			rm -rf "./$entry" ${entry:5}
+			rm -rf "./$entry" "$COMPLETED_DOCS_DIR/"${entry:5}
 		else
 			mv "./$entry" "$COMPLETED_DOCS_DIR/"
 		fi
