rpi: allow 2 sdcard images to be created This is just a convenience for distro builders - the default is still a single image

diff --git a/woof-code/3builddistro b/woof-code/3builddistro
--- a/woof-code/3builddistro
+++ b/woof-code/3builddistro
@@ -926,6 +926,19 @@ fi
 
 #==================================================================================
 
+function create_image() {
+	FMT=$FMT TSIZE=$TSIZE SWAP=$SWAP ../support/mk_arm_img.sh ../${WOOF_OUTPUT}/${ZIPNAME}
+	[ $? -ne 0 ] && rm -rf tmp/ && echo "failed to create image" && exit 1
+	# we're in sandbox3
+	TGTIMG=''
+	cd tmp # can't run in subshell
+	SRCIMG=`find . -type f -name "${DISTRO_FILE_PREFIX}*.img"` 
+	TGTIMG=${SRCIMG##*/}
+	zip -9 ../../${WOOF_OUTPUT}/${TGTIMG}.zip ${SRCIMG}
+	cd - >/dev/null 2>&1
+	( cd ../${WOOF_OUTPUT} ; md5sum ${TGTIMG}.zip > ${TGTIMG}.zip.md5.txt )
+}
+
 if [ "$SDFLAG" = "zip" ];then
 	WOOF_OUTPUT="woof-output-${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}"
 	mkdir -p ../$WOOF_OUTPUT
@@ -948,18 +961,21 @@ if [ "$SDFLAG" = "zip" ];then
 	fi
 
 	if [ "$MKIMGFLAG" -a -e "../support/mk_arm_img.sh" ];then
-		FMT=$FMT TSIZE=$TSIZE SWAP=$SWAP ../support/mk_arm_img.sh ../${WOOF_OUTPUT}/${ZIPNAME}
-		[ $? -ne 0 ] && rm -rf tmp/ && echo "failed to create image" && exit 1
-		# we're in sandbox3
-		TGTIMG=''
-		cd tmp # can't run in subshell
-		SRCIMG=`find . -type f -name "${DISTRO_FILE_PREFIX}*.img"` 
-		TGTIMG=${SRCIMG##*/}
-		zip -9 ../../${WOOF_OUTPUT}/${TGTIMG}.zip ${SRCIMG}
-		cd - >/dev/null 2>&1
-		( cd ../${WOOF_OUTPUT} ; md5sum ${TGTIMG}.zip > ${TGTIMG}.zip.md5.txt )
-		rm -rf tmp/ # we're still in sandbox3
+		if [ -z "$IMG_NUM" ] ; then
+			create_image
+		else
+			for imgzip in 1 2
+			do
+				case $imgzip in
+					1)SWAP=y;;
+					2)SWAP=n;;
+				esac
+				create_image
+				rm -rf tmp/
+			done
+		fi
 	fi
+	rm -rf tmp/ # we're still in sandbox3
 
 elif [ "$SDFLAG" ]; then #120506 sd image
 
