Allow 'Pkg' to be integrated into woof-ce.
'Pkg' still has it's own github repository. All this commit does is clone
(or update) Pkg into ../local-repositories and installs it, configured for
your build based on etc/DISTRO_SPECS.
NOTE:
 * it is off by default (except for slacko and raspup)
 * to turn it on, in _00build.conf change the INCLUDE_PKG variable to y -
INCLUDE_PKG=y
 * or comment the INCLUDE_PKG variable and the question will be asked if you
want Pkg in 3builddistro

This has been tested working in slackoes, (32 and 64), raspup and dpup stretch

diff --git a/woof-code/3builddistro b/woof-code/3builddistro
--- a/woof-code/3builddistro
+++ b/woof-code/3builddistro
@@ -329,6 +329,31 @@ cp -a -f packages-${DISTRO_FILE_PREFIX}/busybox/bin/busybox* ./sandbox3/rootfs-c
 [ -f /tmp/rootfs_pkgs_pinstall.sh ] && cat /tmp/rootfs_pkgs_pinstall.sh >> sandbox3/pinstall.sh
 # -
 
+## pkg
+install_pkg() {
+		pkg_get || return 1
+		( cd ../local-repositories/pkg
+		SYSROOT=../../${MWD##*/}/sandbox3/rootfs-complete ./installer.sh
+		unset SYSROOT # precaution
+		)
+		return 0
+}
+if [ "$INCLUDE_PKG" = 'y' ] ; then
+	install_pkg || echo "can't install pkg"
+elif [ "$INCLUDE_PKG" = 'n' ] ; then
+	echo "not installing pkg"
+else
+	echo \
+"Do you want to include the 'pkg' cli package manager in the build? (y/n)"
+	read pkg_include
+	if [ "$pkg_include" = 'y' ] ; then
+		install_pkg || echo "can't install pkg"
+	else
+		echo "not installing pkg"
+	fi
+fi
+## pkg end
+
 rm -f /tmp/3builddistro_end_of_pinstall
 echo -e '\ntouch /tmp/3builddistro_end_of_pinstall' >> sandbox3/pinstall.sh
 chmod 755 sandbox3/pinstall.sh
@@ -343,7 +368,7 @@ for i in $(ls sandbox3/rootfs-complete/usr/share/doc); do
 		rm -rf sandbox3/rootfs-complete/usr/share/doc/$i
 	fi
 done
-for i in share/doc share/info share/man usr/share/info usr/share/man \
+for i in share/doc share/info share/man usr/share/info \
 	usr/share/gtk-doc usr/share/gnome/help usr/info usr/man usr/share/cups/doc-root/help
 do
 	if [ -d sandbox3/rootfs-complete/${i} ] ; then
