fix up previous mistake in func file

diff --git a/woof-code/_00func b/woof-code/_00func
--- a/woof-code/_00func
+++ b/woof-code/_00func
@@ -95,6 +95,41 @@ function create_local_repos_dirs() {
 	fi
 }
 
+function set_layer_type() { # sets $LAYER_TYPE
+	LAYER_TYPE='aufs'
+	modprobe aufs &>/dev/null
+	cat /proc/filesystems | grep -q 'aufs' && return
+	mount | grep ' / ' | grep -q 'aufs' && return
+	lsmod | grep -q '^aufs ' && return
+	#-
+	LAYER_TYPE='overlay'
+	modprobe overlay &>/dev/null
+	cat /proc/filesystems | grep -q 'overlay' && return
+	lsmod | grep -q '^overlay ' && return
+	#-
+	echo "ERROR: need aufs or overlay"
+	exit 1
+}
+
+function clean_out_whiteouts() { #dir
+	local dir="$@"
+	# aufs whiteouts
+	#find "$dir" -name '.wh*' -delete
+	find "$dir" -name '.wh.*' -exec rm -rf '{}' 2>/dev/null \;
+	# overlayfs whiteouts
+	if [ "$LAYER_TYPE" = 'overlay' ]; then
+		for ONE_CHAR_NODE in `find "$dir" -type c`
+		do
+			if [ "`stat -c '%t, %T' $ONE_CHAR_NODE`" = '0, 0' ]; then
+				# paranoid test, regular files are also '0, 0'
+				if [ "`stat -c '%F' $ONE_CHAR_NODE`" = 'character special file' ]; then
+					rm $ONE_CHAR_NODE
+				fi
+			fi
+		done
+	fi
+}
+
 function copy_pkgs_to_build() {
 	. ./DISTRO_SPECS
 	SFS_DIR=$2
