add frugalify support to ext4 images

diff --git a/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater b/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater
--- a/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater
+++ b/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater
@@ -186,6 +186,17 @@ if [ $UEFI -eq 1 ]; then
 			exit 1
 		fi
 	fi
+
+	if [ -e /mnt/root/frugalify ]; then
+		echo "Updating frugalify"
+		install -m 755 frugalify /mnt/root/frugalify
+		if [ $? -ne 0 ]; then
+			echo "Failed to update frugalify"
+			cd ..
+			[ "$1" = ask ] && read
+			exit 1
+		fi
+	fi
 else
 	echo "Updating the kernel"
 	mv -f vmlinuz ..
@@ -196,6 +207,12 @@ else
 	if [ -e ucode.cpio ]; then
 		echo "Updating microcode"
 		mv -f ucode.cpio ..
+	fi
+
+	if [ -e ../frugalify ]; then
+		echo "Updating frugalify"
+		mv -f frugalify ..
+		chmod 755 ../frugalify
 	fi
 fi
 
