do not try to update initrd.gz if not using it

diff --git a/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater b/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater
--- a/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater
+++ b/woof-code/rootfs-packages/simple_updater/usr/sbin/simple_updater
@@ -150,12 +150,14 @@ if [ -n "$ESP" ]; then
 		exit 1
 	fi
 
-	echo "Updating initrd"
-	cp -f initrd.gz /mnt/efi/EFI/BOOT/initrd.gz
-	if [ $? -ne 0 ]; then
-		echo "Failed to move initrd.gz to EFI partition"
-		[ "$1" = ask ] && read
-		exit 1
+	if [ -e /mnt/efi/EFI/BOOT/initrd.gz ]; then
+		echo "Updating initrd"
+		cp -f initrd.gz /mnt/efi/EFI/BOOT/initrd.gz
+		if [ $? -ne 0 ]; then
+			echo "Failed to move initrd.gz to EFI partition"
+			[ "$1" = ask ] && read
+			exit 1
+		fi
 	fi
 
 	rm -f /mnt/efi/EFI/BOOT/ucode.cpio
@@ -184,8 +186,10 @@ else
 	echo "Updating the kernel"
 	mv -f vmlinuz ..
 
-	echo "Updating initrd"
-	mv -f initrd.gz ..
+	if [ -e ../initrd.gz ]; then
+		echo "Updating initrd"
+		mv -f initrd.gz ..
+	fi
 
 	if [ -e ucode.cpio ]; then
 		echo "Updating microcode"
