cups_backend pdf-writer: use yad/gtkdialog, remember last directory

diff --git a/woof-code/rootfs-packages/cups_backend64/usr/lib64/cups/backend/pdf-writer b/woof-code/rootfs-packages/cups_backend64/usr/lib64/cups/backend/pdf-writer
--- a/woof-code/rootfs-packages/cups_backend64/usr/lib64/cups/backend/pdf-writer
+++ b/woof-code/rootfs-packages/cups_backend64/usr/lib64/cups/backend/pdf-writer
@@ -20,24 +20,38 @@ export LC_ALL="C"
 export XAUTHORITY=$USERHOME/.Xauthority
 
 PDFNAME=$3".pdf"
-[ ${PDFNAME:0:1} != "/" ] && PDFNAME=$USERHOME/$PDFNAME
-PDFNAME=$(Xdialog --stdout --title "Save As ..." --fselect "$PDFNAME" 0 0)
+
+if [ ${PDFNAME:0:1} != "/" ] ; then
+	PDFNAME=$USERHOME/$PDFNAME
+fi
+
+if [ -f "$USERHOME/.config/cups_pdf_dir" ] ; then
+	read LAST_DIR < "$USERHOME/.config/cups_pdf_dir"
+	PDFNAME="${LAST_DIR}/$(basename "$PDFNAME")"
+fi
+
+PDFNAME=$(yad --file --save --filename="$PDFNAME" \
+	--width=640 --height=480 --center --title="Save As..." \
+	--window-icon=gtk-save)
 
 [ $? -gt 0 ] && cat - > /dev/null && exit 0 	# to finish the job stream
 
 if [ -f "$PDFNAME" ]; then
-  Xdialog --title "CUPS-PDF" --yesno "$PDFNAME exists: Overwrite it?" 0 0
-  [ $? -gt 0 ] && cat - > /dev/null && exit 0 
+	/usr/lib/gtkdialog/box_yesno --yes-first "CUPS-PDF" "$PDFNAME exists: Overwrite it?"
+	[ $? -gt 0 ] && cat - > /dev/null && exit 0 
 fi
+
+LAST_DIR=$(dirname "$PDFNAME")
+echo "$LAST_DIR" > "$USERHOME/.config/cups_pdf_dir"
 	
 ps2pdf - "$PDFNAME"
 
 if [ $? -eq 0 ]; then
-  Xdialog --title "CUPS-PDF" --infobox "Created: $PDFNAME" 0 0 3000
-  chown $2:$2 "$PDFNAME"
+	/usr/lib/gtkdialog/box_ok "CUPS-PDF" info "Created: $PDFNAME"
+	chown $2:$2 "$PDFNAME"
 else
-  Xdialog --title "CUPS-PDF" --msgbox "Invalid filename: $PDFNAME" 0 0
-  cat - > /dev/null && exit 0 
+	/usr/lib/gtkdialog/box_ok "CUPS-PDF" error "Invalid filename: $PDFNAME"
+	cat - > /dev/null && exit 0 
 fi
 
 exit 0	# so CUPS knows that the job has completed
