rpi: Improve the labelling for raspberry saves
Now multiple saves are easily distinguished by the savefile name instead of the distro name. Also some improvements to 'raspi-version', including --quiet and --brief options.

diff --git a/woof-code/rootfs-skeleton/usr/bin/raspi-version b/woof-code/rootfs-skeleton/usr/bin/raspi-version
--- a/woof-code/rootfs-skeleton/usr/bin/raspi-version
+++ b/woof-code/rootfs-skeleton/usr/bin/raspi-version
@@ -1,7 +1,17 @@
 #!/bin/ash
 
-#https://elinux.org/RPi_HardwareHistory#Board_Revision_History
+# https://elinux.org/RPi_HardwareHistory#Board_Revision_History
 # better https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md
+
+case "$1" in
+	-h|--help)cat <<EOF
+usage:
+${0##*/} -q, --quiet: no output; exit status only
+${0##*/} -b, --brief: print model name and RAM in MB only
+${0##*/} -h, --help: show this message and exit
+EOF
+		exit 2 ;;
+esac
 
 cpuinfo=/proc/cpuinfo
 
@@ -57,12 +67,24 @@ while IFS=":" read field value ; do
 done < $cpuinfo
 
 if [ "$rev" ] ; then
+	case "$1" in
+		-q|--quiet) exit 0 ;;
+	esac
 	rev=${rev#1000}
 	info=$(echo "$raspi_versions" | grep "^${rev}|")
 	if [ "$info" ] ; then
-		IFS="|" read Revision Release_Date Model PCB_Revision Memory Notes <<EOF
+		IFS="|" \
+		read Revision Release_Date Model PCB_Revision Memory Notes <<EOF
 $info
 EOF
+		case "$1" in
+			-b|--brief)
+				[ ${Memory/[MG]B/} = 256 -o ${Memory/[MG]B/} = 512 ] \
+				&& Mem=${Memory/[MG]B/} || Mem=$((${Memory%% *} * 1024)) 
+				Mod=${Model/Raspberry Pi /}
+				echo "${Mod}|${Mem}"
+				exit 0;;
+		esac
 		echo "Model        : $Model"
 		echo "PCB Revision : $PCB_Revision"
 		echo "Revision     : $Revision"
@@ -78,7 +100,7 @@ EOF
 	fi
 	exit 0
 else
-	exit 1
+	exit 1 # not a pi
 fi
 
 ### END ###
