Add error message if xsane is not present in xsaneshell. (#3795)
* Add error message if xsane is not present.

* Update xsaneshell

* Update xsaneshell

diff --git a/woof-code/rootfs-skeleton/usr/bin/xsaneshell b/woof-code/rootfs-skeleton/usr/bin/xsaneshell
--- a/woof-code/rootfs-skeleton/usr/bin/xsaneshell
+++ b/woof-code/rootfs-skeleton/usr/bin/xsaneshell
@@ -1,6 +1,13 @@
 #!/bin/sh
 #8.06.11 rodin.s: i18n
 
+command -v xsane >/dev/null 2>&1
+if [ $? -gt 0 ]; then
+  /usr/lib/gtkdialog/box_splash -bg red -fg white -timeout 5 -close box -text "ERROR: xsane is not installed. Install xsane first."
+  echo "ERROR: xsane is not installed. Install xsane first."
+  exit 1
+fi
+
 export TEXTDOMAIN=xsaneshell #usr_sbin2
 export TEXTDOMAINDIR=/usr/share/locale
 export OUTPUT_CHARSET=UTF-8
