xwin: xorg specific / misc edits
now xwin only supports xorg.. thus it's easir to understand.

diff --git a/woof-code/rootfs-skeleton/usr/bin/xwin b/woof-code/rootfs-skeleton/usr/bin/xwin
--- a/woof-code/rootfs-skeleton/usr/bin/xwin
+++ b/woof-code/rootfs-skeleton/usr/bin/xwin
@@ -6,8 +6,6 @@
 #v3.98 forced reboot handling improved by pizzasgood.
 #v408 BK k2.6.25.16 serial mouse driver now a module 'sermouse'.
 #v411 rerwin: mouse improvements.
-#w001 fixes for woof, /usr/X11R7 not used.
-#w479 k2.6.18.8 need awful hack, Xorg, '-nolisten tcp' causes hang!
 #v424 bad hack to fix serial mouse.
 #100127 make sure xorg keyboard layout matches console setting (same code in xorgwizard).
 #100130 typo fix.
@@ -16,8 +14,6 @@
 #100520 attempt fix keyboard layout not getting updated.
 #100608 jemimah: added 1366x768.
 #20110328 for xorg, run xorgwizard-automatic instead of xorgwizard, for xorg 7.5.
-#110413 variable DISTRO_XORG_AUTO in /etc/DISTRO_SPECS, set in Woof '3builddistro'.
-#110622 fix handling of DISTRO_XORG_AUTO.
 #110721 o/p to /dev/null when modprobe modules that are builtin to kernel.
 #110804 /etc/profile has fix for double-login. need to output '# ' when exit xwin.
 #110807 revert 110804
@@ -31,6 +27,12 @@
 #130527 /etc/.XLOADED has been moved to /root, refer also remasterpup2.
 #130725 quiet if no /etc/oldmousedevice file.
 
+if ! which Xorg &>/dev/null ; then
+	echo -e "\\033[1;31m"$(gettext 'Xorg not found.. cannot continue.')"\\033[0;39m"
+	exit 1
+fi
+[ -z $DISPLAY ] || exit #v2.11 from GuestToo.
+
 export TEXTDOMAIN=xwin
 export OUTPUT_CHARSET=UTF-8
 eval_gettext () {
@@ -39,12 +41,6 @@ eval_gettext () {
 }
 export LANGORG=$LANG
 HOSTNAMEORIG=$HOSTNAME #120511
-
-#NUMXWINS=`pidof xwin | wc -w` #w478
-#[ $NUMXWINS -gt 1 ] && exit   #w478
-
-[ -z $DISPLAY ] || exit #v2.11 from GuestToo.
-#echo "This script will run X windows for you..."
 
 cd ~/   #v3.98 Ensure current directory is root, in case changed at command prompt, so rox icon and menu item open only at home directory. rerwin
 
@@ -70,11 +66,8 @@ fi
 
 #0.9.9 enables to start a specific w.m. from commandline...
 if [ $1 ];then
- echo -n "$1" > /etc/windowmanager
- #note, /root/.xinitrc uses this file.
+ echo -n "$1" > /etc/windowmanager #note, /root/.xinitrc uses this file.
 fi
-
-HAVEX="`readlink /usr/bin/X`"
 
 #v411 restored after removal in v407...
 #update xorg.conf if mouse has changed...
@@ -121,8 +114,7 @@ if [ ! -f /etc/mousebuttons ];then
 fi
 
 #v2.11 find out if xorg video drvr exists, else use xorg vesa...
-if [ -f /usr/bin/Xorg ];then
- if [ -f /etc/X11/xorg.conf ];then
+if [ -f /etc/X11/xorg.conf ];then
   #find location of video chip drivers...
   SPECVESA="`find /usr/lib /usr/X11R7/lib /usr/lib64 -noleaf -mount -type f -name vesa_drv.so 2>/dev/null | grep -v 'backup' | grep -m1 'vesa_drv.so'`" #1201031 bug fix.
   if [ "$SPECVESA" ];then
@@ -130,7 +122,6 @@ if [ -f /usr/bin/Xorg ];then
    #get current driver...
    DRVRCURR="`cat /etc/X11/xorg.conf | grep '#card0driver' | cut -f 2 -d '"'`" #'
    if [ "$DRVRCURR" ];then
-    #if [ ! -f $DRVRSPATH/${DRVRCURR}_drv.so ];then
     #one driver is mtx_drv.o hmmm, okay do it this way (pakt)...
     ls -1 $DRVRSPATH/* | grep $DRVRCURR >/dev/null
     if [ $? -ne 0 ];then
@@ -139,13 +130,10 @@ if [ -f /usr/bin/Xorg ];then
     fi
    fi
   fi
- fi
 fi
 
 #Puppy Xorg Video Wizard...
-if [ -f /usr/bin/Xorg ];then
- if [ -f /etc/X11/xorg.conf ];then
-  if [ "`readlink /usr/bin/X`" = "Xorg" ];then
+if [ -f /etc/X11/xorg.conf ];then
    if [ "`which ddcprobe`" = "" ];then  #120517
     #arm board, does not support ddcprobe (refer also /usr/sbin/xorgwizard-automatic)...
     HARDWAREPROFILE='armsystem'
@@ -175,16 +163,14 @@ if [ -f /usr/bin/Xorg ];then
     #if a previous profiled filename for new hardware, use that...
     [ -f /etc/X11/xorg.conf.${HARDWAREPROFILE} ] && cp -af /etc/X11/xorg.conf.${HARDWAREPROFILE} /etc/X11/xorg.conf
    fi
-  fi
- fi
- if [ ! -f /etc/X11/xorg.conf ];then
+fi
+if [ ! -f /etc/X11/xorg.conf ];then
   rm -f /root/.XLOADED 2> /dev/null #not necessary, precaution.
   if [ "$DISTRO_XORG_AUTO" = "yes" ];then #see /etc/DISTRO_SPECS.
    /usr/sbin/xorgwizard-automatic
   else
    /usr/sbin/xorgwizard
   fi
- fi
 fi
 
 #v1.0.7 J_Reys idea (see note further down)...
@@ -214,11 +200,6 @@ $(gettext 'If undecided, wait 30 seconds for normal startup of X...')" 0 0
  fi
 fi
 
-MOUSEBUTTONS=3
-if [ -e /etc/mousebuttons ];then
- MOUSEBUTTONS=`cat /etc/mousebuttons`
-fi
-
 #v424 bad hack, i somehow get /dev/mouse pointing to psaux when chose a serial mouse, don't know why...
 [ "`grep 'ttyS' /etc/mousedevice`" != "" ] && ln -snf $MOUSEDEV /dev/mouse
 
@@ -229,10 +210,8 @@ KEYMAPNOW="`cat /etc/keymap`"
 KEYMAPPREV="`cat /etc/keymap_previous`"
 if [ "$KEYMAPNOW" != "$KEYMAPPREV" ];then
  cp -f /etc/keymap /etc/keymap_previous
- #100520 bring this code back again...
  #100215 moved this code to /usr/sbin/input-wizard, avoid automatic overwriting of any user edit of xorg.conf...
  #100127 make sure xorg keyboard layout matches console setting (same code in xorgwizard)...
- if [ "$HAVEX" = "Xorg" ];then
   xCONSKEYMAP="`cat /etc/keymap | cut -c 1-2`"
   [ "$xCONSKEYMAP" = "" ] && xCONSKEYMAP="us"
   case $xCONSKEYMAP in
@@ -258,7 +237,6 @@ if [ "$KEYMAPNOW" != "$KEYMAPPREV" ];then
    skPATTERN="s%.*#xkeymap0%	Option      \"XkbLayout\" \"${XKEYMAP}\" #xkeymap0%"
    sed -i -e "${skPATTERN}" /etc/X11/xorg.conf #100130
   fi
- fi
 fi
 
 
@@ -266,28 +244,10 @@ fi
 #J_Rey had a good idea, flag XLOADED... and set to false on exit.
 #but if PC hangs, XLOADED will still be true, so will know it is broken.
 echo -n "true" > /root/.XLOADED
-#chmod 666 /root/.XLOADED #130609 precaution, if change to user 'fido' at X shutdown, need to be able to delete this at next boot.
-case $HAVEX in
- Xi810) #v1.0.7
-  echo "$(gettext 'Starting X with Xi810 Kdrive X server, mouse') $MOUSEDEV..."
-  #echo "(experimental, currently fixed to 1024x768x16x72 in /usr/bin/xwin)"
-   /usr/bin/xinit /root/.xinitrc -- -screen $VIDSCRN -mouse /dev/mouse,$MOUSEBUTTONS > /tmp/xerrs.log 2>&1
-  ;;
- Xorg)
-  echo "$(gettext 'Starting X, specs in /etc/X11/xorg.conf, startup apps /root/.xinitrc...')"
-  #v2.11 G2 suggested -br for black background instead of checked...
-  #w479 ***AWFUL HACK*** running pup 218, retro k2.6.18.8, my laptop, Xorg hangs
-  #     if have '-nolisten tcp'. until find out why, this workaround...
-  if [ "$KERNELVER" = "2.6.18.8" ];then
-   /usr/bin/xinit /root/.xinitrc -- -br > /tmp/xerrs.log 2>&1
-  else
-   /usr/bin/xinit /root/.xinitrc -- -br -nolisten tcp > /tmp/xerrs.log 2>&1
-  fi
-  ;;
- *)
-  /usr/bin/xinit /root/.xinitrc --  > /tmp/xerrs.log 2>&1
-  ;;
-esac
+echo "$(gettext 'Starting X, specs in /etc/X11/xorg.conf, startup apps /root/.xinitrc...')"
+#-----------------------------------------------------------------------
+/usr/bin/xinit /root/.xinitrc -- -br -nolisten tcp > /tmp/xerrs.log 2>&1
+#-----------------------------------------------------------------------
 echo -n "false" > /root/.XLOADED #see note above.
 #...if PC hung, run xorgwizard at next bootup (see further up).
 
@@ -297,23 +257,17 @@ load_consolefont #120301 seems have to do this on exit from X. (new script)
 #120224 ...console font is loaded in quicksetup if locale changed.
 echo ''$(gettext 'Exited from X. Type "xwin [fvwm95|jwm]" to restart X ([ ] mean optional).')''
 echo ''$(gettext '(To shutdown PC type "poweroff", to reboot PC type "reboot")')''
-if [ "$HAVEX" = "Xorg" ];then #v1.0.7
- echo -en "\\033[1;35m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
- echo -n ''$(gettext 'If X failed to start, type "xorgwizard" to setup X')''
- echo -e "\\033[0;39m"
-fi
+echo -en "\\033[1;35m" #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
+echo -n ''$(gettext 'If X failed to start, type "xorgwizard" to setup X')''
+echo -e "\\033[0;39m"
 
 #Shutdown menu calls wmreboot, wmpoweroff, wmexit or restartwm, which create this file...
 if [ -f /tmp/wmexitmode.txt ];then
  WMEXITMODE="`cat /tmp/wmexitmode.txt`"
  if [ "$WMEXITMODE" = "exit" ];then #see /usr/bin/wmexit.
-  #[ $NUMXWINS -eq 1 ] && rm -f /tmp/wmexitmode.txt #w477 hack, see above.
   rm -f /tmp/wmexitmode.txt #w478
-  #[ ! -f /tmp/xwin-firstexit ] && echo -n '# ' #110804 pretend prompt. 110807
-  #touch /tmp/xwin-firstexit #110804 110807
   exit
  fi
- #rm -f /tmp/wmexitmode.txt ...no, removed in rc.shutdown.
  [ "$WMEXITMODE" = "poweroff" ] && exec /sbin/poweroff #see /usr/bin/wmpoweroff
  [ "$WMEXITMODE" = "reboot" ] && exec /sbin/reboot #see /usr/bin/wmreboot
  #restart window manager...
