use release archive for update

diff --git a/woof-code/rootfs-packages/pm6_updater/usr/sbin/pm6_update b/woof-code/rootfs-packages/pm6_updater/usr/sbin/pm6_update
--- a/woof-code/rootfs-packages/pm6_updater/usr/sbin/pm6_update
+++ b/woof-code/rootfs-packages/pm6_updater/usr/sbin/pm6_update
@@ -69,53 +69,69 @@ RELEASE_ASSETS=`echo "$RELEASES" | jq -r ".[$RELEASE_CHOICE].assets"`
 COUNT=`echo "$RELEASE_ASSETS" | jq length`
 
 # download the kernel and every SFS in the release
-DOWNLOADED_ASSETS=""
+ASSET_CHOICE=-1
 for i in `seq 0 $(($COUNT - 1))`; do
     ASSET_NAME=`echo "$RELEASE_ASSETS" | jq -r ".[$i].name"`
 
-    case "$ASSET_NAME" in
-    *.sfs|vmlinuz) ;;
-    *) continue ;;
-    esac
-
-    # update only assets that have a symlink in the boot partition root
-    [ ! -e "/initrd/${ASSET_NAME}" ] && continue
-
-    ASSET_URL=`echo "$RELEASE_ASSETS" | jq -r ".[$i].url"`
-
-    echo "Downloading $ASSET_NAME"
-    wget -c --header "Accept: application/octet-stream" -O "/initrd/${RELEASE_TAG}/${ASSET_NAME}" "$ASSET_URL"
-    if [ $? -ne 0 ]; then
-        echo "Failed to download $ASSET_NAME"
-        rm -rf "/initrd/${RELEASE_TAG}"
-        exit 1
+    if [ "$ASSET_NAME" = "${DISTRO_FILE_PREFIX}-${DISTRO_VERSION}.tar" ]; then
+        ASSET_CHOICE=$i
+        break
     fi
-
-    DOWNLOADED_ASSETS="$DOWNLOADED_ASSETS $ASSET_NAME"
 done
 
-if [ -z "$DOWNLOADED_ASSETS" ]; then
-    echo "Failed to update to $RELEASE_TAG"
+if [ $ASSET_CHOICE -lt 0 ]; then
+    echo "No $RELEASE_CHANNEL update available"
     rm -rf "/initrd/${RELEASE_TAG}"
     exit 1
 fi
+
+cd "/initrd/${RELEASE_TAG}"
+
+echo "Downloading $ASSET_NAME"
+ASSET_URL=`echo "$RELEASE_ASSETS" | jq -r ".[$ASSET_CHOICE].url"`
+wget -c --header "Accept: application/octet-stream" "$ASSET_URL"
+if [ $? -ne 0 ]; then
+    echo "Failed to download $ASSET_NAME"
+    cd ..
+    rm -rf "${RELEASE_TAG}"
+    exit 1
+fi
+
+tar xf "${ASSET_NAME}"
+if [ $? -ne 0 ]; then
+    echo "Failed to update to $RELEASE_TAG"
+    cd ..
+    rm -rf "${RELEASE_TAG}"
+    exit 1
+fi
+
+rm -f "${ASSET_NAME}"
 
 # it's important to make sure all assets are flushed to disk
 echo "Flushing /initrd/${RELEASE_TAG} to disk"
 sync
 
-# replace the symlinks on the boot partition with symlinks that point to the
-# downloaded assets
-echo "Updating symlinks"
-for ASSET_NAME in $DOWNLOADED_ASSETS; do
-    rm -f "/initrd/${ASSET_NAME}"
-    ln -s "${RELEASE_TAG}/${ASSET_NAME}" "/initrd/${ASSET_NAME}"
+# update the SFS symlinks on the boot partition
+for NAME in *.sfs; do
+    echo "Updating $NAME"
+    rm -f "../${NAME}"
+    ln -s "${RELEASE_TAG}/${NAME}" "../${NAME}"
 done
 
-# if the symlinks are not flushed to disk, we're left in non-bootable state
-sync
+echo "Updating the kernel"
+if [ -e ../vmlinuz ]; then
+    ln -s "${RELEASE_TAG}/vmlinuz" ../vmlinuz
+else
+    # TODO: detect the partition instead of relying on a fixed UUID
+    dd if=vmlinux.kpart of=/dev/disk/by-partuuid/b361601a-103d-374c-ba2c-35b8533a199d
+    rm -f vmlinuz vmlinux.kpart
+fi
 
-# TODO: when using the Chrome OS partition layout, vmlinuz needs to be written
-# to the kernel partition using dd
+echo "Updating frugalify"
+mv -f init ../init
+chmod 755 ../init
+
+# if the files are not flushed to disk, we're left in non-bootable state
+sync
 
 # TODO: rc.update needs to be triggered in the first boot after update
