Fix pinstall.sh's ineffectiveness pinstall.sh is run before copying files by support/petbuilds.sh

diff --git a/woof-code/rootfs-petbuilds/conky-gtk_lua/usr/bin/conky-gtk b/woof-code/rootfs-petbuilds/conky-gtk_lua/usr/bin/conky-gtk
--- a/woof-code/rootfs-petbuilds/conky-gtk_lua/usr/bin/conky-gtk
+++ b/woof-code/rootfs-petbuilds/conky-gtk_lua/usr/bin/conky-gtk
@@ -10,6 +10,7 @@ CONKYRC=$HOME/.config/conky-gtk/conkyrc
 CONKYRC_BAK=$HOME/.config/conky-gtk/conkyrc.bak
 CONKYRC_SYMLINK=$HOME/.conkyrc # this will be symlink of $CONKYRC
 CONKY_STARTUP_SCRIPT=$HOME/Startup/conkystart
+CONKY_STARTUP_SCRIPT_FORMAT=$HOME/.config/conky-gtk/startup_script_format
 WEATHER_SAVED_LOCATION=$HOME/.config/conky-gtk/saved_weather
 WEATHER_FORMAT=$HOME/.config/conky-gtk/weather_format
 
@@ -27,10 +28,19 @@ if [ ! -f "$CONKYRC_SYMLINK" ]; then
     echo "success!"
 fi
 
-if [ ! -f "$WEATHER_FORMAT" ]; then
-    echo "$WEATHER_FORMAT not found.. please re-install conky-gtk."; echo "script failed.. exiting."
-    exit 1
+if [ ! -f "$CONKYRC_BAK" ]; then # happens when conky-gtk is run the first time
+    cp "$CONKYRC" "$CONKYRC_BAK" # conkyrc is already present - confirmed by previous if clause
 fi
+
+IFS=$'\n' # make newlines the only separator; in case the files have a space
+for FILE_TO_CHECK in $(printf "%s\n%s" "$CONKY_STARTUP_SCRIPT_FORMAT" "$WEATHER_FORMAT"); do
+    [ -z "$FILE_TO_CHECK" ] && continue
+    if [ ! -f "$FILE_TO_CHECK" ]; then
+        echo "$FILE_TO_CHECK not found.. please re-install conky-gtk."; echo "script failed.. exiting."
+        exit 1
+    fi
+done
+unset IFS
 
 touch "$WEATHER_SAVED_LOCATION"
 mkdir -p "$HOME"/Startup
@@ -42,6 +52,7 @@ gtk-update-icon-cache -f -i /usr/share/icons/hicolor 2>/dev/null
 export CONKYRC # required exporting since these variables are required inside GTKDIALOG
 export CONKYRC_BAK
 export CONKY_STARTUP_SCRIPT
+export CONKY_STARTUP_SCRIPT_FORMAT
 export WEATHER_SAVED_LOCATION
 export WEATHER_FORMAT
 #----------------------------------------------------------------------------------
@@ -81,22 +92,12 @@ restart_conky() {
     if [ -n "$(pidof conky 2>/dev/null)" ]; then
         killall conky &
     fi
-    sleep 1
-    wallp=$(cat "$HOME"/.config/wallpaper/bg_img)
-    conky -c "$CONKYRC" 2>/dev/null &
-    sleep 2
-    set_bg "$wallp" &
+    "$CONKY_STARTUP_SCRIPT_FORMAT"
 }
 export -f restart_conky
 
 gen_autostart_conky_script() {
-    echo '#!/bin/sh
-wallp=$(cat $HOME/.config/wallpaper/bg_img)
-sleep 1
-conky -c '"$CONKYRC"' 2>/dev/null &
-sleep 5
-set_bg "$wallp" &' > "$CONKY_STARTUP_SCRIPT"
-    chmod a+x "$CONKY_STARTUP_SCRIPT"
+    cp "$CONKY_STARTUP_SCRIPT_FORMAT" "$CONKY_STARTUP_SCRIPT" # script format file already chmod'ed with 'a+x' permissions
 }
 export -f gen_autostart_conky_script
 
@@ -279,7 +280,6 @@ export MAIN_DIALOG
 
 case $1 in
     -d | --dump) echo "$MAIN_DIALOG" ;;
-    --enable-autostart) gen_autostart_conky_script ;;
     *) $GTKDIALOG --program=MAIN_DIALOG ;;
 esac
 #----------------------------------------------------------------------------------
@@ -288,6 +288,7 @@ esac
 unset CONKYRC
 unset CONKYRC_BAK
 unset CONKY_STARTUP_SCRIPT
+unset CONKY_STARTUP_SCRIPT_FORMAT
 unset WEATHER_SAVED_LOCATION
 unset WEATHER_FORMAT
 #----------------------------------------------------------------------------------
