initrd init: improve savefile stuff
plus some other edits..

add debug messages
relocate code
add comments to explain a little more
support savefiles with any name, ex:
   stretchsave.4fs.BKP-17.01.01-10.13

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -1,5 +1,9 @@
 #!/bin/sh
 # see also /sbin scripts: usablefs, set_plang, wait4usb, switch
+#
+# _FN = _FILENAME
+# _MP = _MOUNTPOINT
+#
 
 #Aufs layers setup by this script...
 #aufs layers:            RW (top)      RO1             RO2              PUPMODE
@@ -54,6 +58,7 @@ L_DEBUG_SAVE="To save debug info to a partition, type 'debugsave'"
 L_PASSWORD="Password:"
 L_PASSWORD_MSG_1="NOTICE: As you type your password nothing will be displayed on the screen."
 L_PASSWORD_MSG_2="This is a security measure. Just type it in then press ENTER key..."
+L_SFFS_ERROR="ERROR: savefile filesystem is not ext2/3/4"
 
 ##############################################################
 
@@ -67,7 +72,7 @@ KERNELVER="$(uname -r)"
 VFAT_OUT_PARAM='shortname=mixed,quiet,utf8' #see also /sbin/set_plang
 . /DISTRO_SPECS #v412 has DISTRO_VERSION, DISTRO_FILE_PREFIX
 
-#precaution - if using a DISTRO_SPECS not processed by 3builddistro...
+#precaution - if DISTRO_SPECS was not processed by 3builddistro...
 [ ! "$DISTRO_ZDRVSFS" ] && DISTRO_ZDRVSFS="zdrv_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
 [ ! "$DISTRO_FDRVSFS" ] && DISTRO_FDRVSFS="fdrv_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
 [ ! "$DISTRO_ADRVSFS" ] && DISTRO_ADRVSFS="adrv_${DISTRO_FILE_PREFIX}_${DISTRO_VERSION}.sfs"
@@ -393,32 +398,6 @@ setup_onepupdrv() {
  return 0
 }
 
-resize_ext_file() {
- . $RESIZE_FN
- [ "$PUPSAVEFILEX" = "$SAVE_REL_FN" ] || return
- if [ ! -e /bin/e2fsck ];then
-  echo -en "\\033[1;31m" > /dev/console
-  echo -n "$(printf "${L_CANNOT_RESIZE_PUPSAVE}" "$PUPSAVEFILEX")" > /dev/console #31=red
-  echo -en "\\033[0;39m" > /dev/console
-  rm -f $RESIZE_FN
- else
-  SAVE_SZ_FN="$SAVE_FN"
-  rm -f $RESIZE_FN
-  echo > /dev/console
-  echo -n "$(printf "${L_INCREASING_PUPSAVE}" "$PUPSAVEFILEX" "$KILOBIG")" >/dev/console
-  dd if=/dev/zero bs=1024 count=$KILOBIG >> $SAVE_SZ_FN #131225 
-  sync
- fi
-}
-
-resize_ext_fs() {
- fsck_func ${1} ${2}
- resize2fs -pf ${1} #no size, will fill all of file.
- sync
- check_status 0 #note, e2fsck gives an error even though it works. v2.21 maybe okay now.
- echo -n "$(printf "${L_CONTINUING_LOADING}" "$PUPSAVEFILE")" > /dev/console
-}
-
 format_bytes() {
  [ $1 ] || return
  if [ $1 -gt 1073741824 ] ; then #GB
@@ -431,12 +410,33 @@ format_bytes() {
  echo ${SIZEX}
 }
 
-load_ext_file() {
+
+load_ext_file() { #ex: stretchsave.4fs
  SAVE_SZ_FN=""
  RESIZE_FN="$(dirname $SAVE_FN)/pupsaveresizenew.txt"
  #delete following line when resize file location is fixed
  [ -f "$RESIZE_FN" ] || RESIZE_FN="${SAVE_MP}/pupsaveresizenew.txt"
- [ -f "$RESIZE_FN" ] && resize_ext_file
+ #-- resize savefile?.. see /usr/sbin/resizepfile.sh
+ if [ -f "$RESIZE_FN" ] ; then
+   #(1) resize extX file. see below (2)
+   . $RESIZE_FN #$PUPSAVEFILEX $KILOBIG
+   if [ "$PUPSAVEFILEX" = "$SAVE_REL_FN" ] ; then
+    if [ ! -e /bin/resize2fs ];then
+     echo -en "\\033[1;31m" > /dev/console
+     echo -n "$(printf "${L_CANNOT_RESIZE_PUPSAVE}" "$PUPSAVEFILEX")" > /dev/console #31=red
+     echo -en "\\033[0;39m" > /dev/console
+     rm -f $RESIZE_FN
+    else
+     SAVE_SZ_FN="$SAVE_FN"
+     rm -f $RESIZE_FN
+     echo > /dev/console
+     echo -n "$(printf "${L_INCREASING_PUPSAVE}" "$PUPSAVEFILEX" "$KILOBIG")" >/dev/console
+     dd if=/dev/zero bs=1024 count=$KILOBIG >> $SAVE_SZ_FN
+     sync
+    fi
+   fi
+ fi
+ #--
  ONE_LOOP="$(losetup -f)"
  #-- is the ${DISTRO_FILE_PREFIX}save encrypted?...
  if echo "$SAVE_FN" | grep -q '_crypt' ;then
@@ -456,13 +456,45 @@ load_ext_file() {
  else
    losetup $ONE_LOOP $SAVE_FN
  fi
- SFFS='ext'$(echo -n "$SAVE_FN" | rev | cut -c 3)
- [ "$PFSCK" = "yes" ] && { echo "" > /dev/console; fsck_func "$ONE_LOOP" "$SFFS"; }
- [ "$SAVE_SZ_FN" ] && resize_ext_fs "$ONE_LOOP" "$SFFS"
+ #--
+ SFFS=$(busybox blkid "$SAVE_FN" | grep -o 'TYPE=".*' | cut -f 2 -d '"')
+ case $SFFS in #savefile filesystem
+   ext2|ext3|ext4) ok=1 ;;
+   *) # might be encrypted - unrecognizable..
+     case "$SAVE_FN" in #savefile can have any extension/name. but must one of these strings
+       *".2fs"*) SFFS=ext2 ;;
+       *".3fs"*) SFFS=ext3 ;;
+       *".4fs"*) SFFS=ext4 ;;
+       *) echo "$L_SFFS_ERROR" #debug
+          echo -e "\\033[1;31m${L_SFFS_ERROR}\\033[0;39m" >/dev/console #31=red
+          ;;
+     esac
+     ;;
+ esac
+ if [ "$PFSCK" = "yes" ] ; then
+   echo "" > /dev/console
+   fsck_func "$ONE_LOOP" "$SFFS"
+ fi
+ #--
+ if [ "$SAVE_SZ_FN" ] ; then
+   #(2) resize extX filesystem - fill extX file. see above (1)
+   fsck_func "$ONE_LOOP" "$SFFS"
+   resize2fs -pf "$ONE_LOOP" #no size, will fill all of file.
+   sync
+   check_status 0 #note, e2fsck gives an error even though it works. v2.21 maybe okay now.
+   echo -n "$(printf "${L_CONTINUING_LOADING}" "$PUPSAVEFILE")" > /dev/console
+ fi
+ #--
  [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
+ echo "mount -t $SFFS -o noatime $ONE_LOOP $SAVE_LAYER" #debug
  mount -t $SFFS -o noatime $ONE_LOOP $SAVE_LAYER
- [ $? -eq 0 ] || { PUPSAVE=""; losetup -d $ONE_LOOP; } 
+ if [ $? -ne 0 ] ; then
+   echo 'Warning: PUPSAVE=""' #debug
+   PUPSAVE=""
+   losetup -d $ONE_LOOP
+ fi
 }
+
 
 setup_save_file(){
  SAVE_REL_FN="$(echo "$PUPSAVE" | cut -f 3 -d ',')"
@@ -474,14 +506,16 @@ setup_save_file(){
  fi
  rm -r -f "$SAVE_LAYER"
  SAVE_FN="${SAVE_MP}${SAVE_REL_FN}"
- if [ -f "$SAVE_FN" ];then #savefile
+ if [ -f "$SAVE_FN" ];then #savefile. ex: stretchsave.4fs
+  echo "--SAVEFILE-- $SAVE_FN" #debug
   load_ext_file
  elif [ -d "$SAVE_FN" ];then #savefolder
+  echo "--SAVEFOLDER-- $SAVE_FN" #debug
   ln -sv "$SAVE_FN" "$SAVE_LAYER"
  else
   PUPSAVE=""
  fi
-#[ "$PUPSAVE" ] && decrypt directory at SAVE_LAYER
+ #[ "$PUPSAVE" ] && decrypt directory at SAVE_LAYER
  if [ "$PUPSAVE" ];then
   if [ ! -f "$SAVE_LAYER/initrd/DISTRO_SPECS" ];then
    PUPSAVE=""
@@ -541,7 +575,12 @@ setup_save_file(){
  else
   check_status 1
  fi
- [ "$PUPSAVE" ] || { PUPMODE=5; SAVE_MP=""; SAVE_LAYER=""; }
+ if [ ! "$PUPSAVE" ] ; then
+   echo "No pupsave. Setting PUPMODE 5" #debug
+   PUPMODE=5
+   SAVE_MP=""
+   SAVE_LAYER=""
+ fi
 }
 
 setup_save_part() {
@@ -1084,11 +1123,13 @@ if [ "${SAVE_MP}" != "" -a "$PRAMONLY" != "yes" ];then #have mounted save? parti
   else
    #have to find savefile/savefolder
    [ "$PUPSAVES" ] || find_save_file "${SAVE_MP}" "$SAVEPART" "$SAVE_FS"
+   echo "PUPSAVES=${PUPSAVES}" #debug
    if [ "$PUPSAVES" ];then
     NUMPUPSAVES=0
     for ONE_SAVE in $PUPSAVES;do
      NUMPUPSAVES=$(expr $NUMPUPSAVES + 1)
     done
+    echo "NUMPUPSAVES=${NUMPUPSAVES}" #debug
     if [ $NUMPUPSAVES -eq 1 ];then
      PUPSAVE="$(echo -n $PUPSAVES)"
     elif [ $NUMPUPSAVES -gt 1 ];then
@@ -1108,7 +1149,9 @@ if [ "${SAVE_MP}" != "" -a "$PRAMONLY" != "yes" ];then #have mounted save? parti
     fi
    fi
   fi
+  echo "PUPSAVE=${PUPSAVE}" #debug
   if [ "$PUPSAVE" ];then
+   echo "Setting PUPMODE 12" #debug
    PUPMODE=12
    ONE_PART="$(echo -n "$PUPSAVE" | cut -f 1 -d ',')"
    [ "$ONE_PART" != "$SAVEPART" ] && { SAVEPART="$ONE_PART"; ensure_save_mounted; }
@@ -1120,8 +1163,10 @@ SAVE_LAYER=""
 if [ "$PUPSAVE" ];then #refine pupmode
  if [ $PUPMODE -eq 6 -o $PUPMODE -eq 12 ];then
   SAVE_LAYER="/pup_rw"
+  echo "SAVE_LAYER=/pup_rw" #debug
   if [ "${PMEDIA:3}" = "flash" ];then
    PUPMODE=$(expr $PUPMODE + 1) #PUPMODE=7 PUPMODE=13
+   echo "Flash drive: setting PUPMODE $PUPMODE, SAVE_LAYER=/pup_ro1"  #debug
    SAVE_LAYER="/pup_ro1"
   fi
  fi
