initrd init: prevent kernel panic from happening if...
there is an error setting up the layered filesystem
or the /bin/busybox is not found (assume catastrophic situation)

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -287,10 +287,14 @@ mntfunc() {
  return $?
 }
 
-check_status()
+check_status() #args: [-critical] $RET_VAL "$ERROR_MSG"
 {
-  if [ $1 -eq 0 ]
-  then
+  ERROR_CRITICAL=""
+  [ "$1" = "-critical" ] && { ERROR_CRITICAL="yes" ; shift; }
+  RET_VAL=$1
+  shift
+  ERROR_MSG="$@"
+  if [ $RET_VAL -eq 0 ] ; then
     /bin/echo -en "\\033[74G" >/dev/console #move to column 72. 110426: 74
     /bin/echo -en "\\033[1;32m" >/dev/console
     /bin/echo -en "done" >/dev/console
@@ -314,8 +318,16 @@ check_status()
     /bin/echo -en "\\033[0;39m" >/dev/console
     #exit to initial ramdisk shell...
     [ "$RDSH" != "" ] && exec /bin/sh >/dev/console 2>&1
-    echo "Pausing for 60 seconds..." >/dev/console
-    sleep 60
+    if [ "$ERROR_CRITICAL" = "yes" ] ; then
+      echo -en "\\033[1;35m" >/dev/console #35=purple
+      [ "$ERROR_MSG" != "" ] && echo "*** $ERROR_MSG" >/dev/console
+      echo "*** Error is too critical, dropping out to console..." >/dev/console
+      echo -en "\\033[0;39m" >/dev/console
+      exec /bin/sh >/dev/console 2>&1
+    else
+      echo "Pausing for 60 seconds..." >/dev/console
+      sleep 60
+    fi
   fi
 }
 
@@ -1943,7 +1955,11 @@ fi
 
 #create the layered f.s.... ***THE BIG EVENT***
 mount -t aufs -o udba=reval,diropq=w,dirs=${UMNTRW}${UMNTRO0}${ALAYER}${YLAYER}${UMNTRO1}${FLAYER}${ZLAYER}${UMNTRO} unionfs /pup_new
-check_status $? #END STEP FIVE
+check_status -critical $? "Error setting up layered filesystem"
+if [ ! -f /pup_new/bin/busybox ] ; then
+  check_status -critical 1 "/bin/busybox not found.. assuming catastrophic situation"
+fi
+#END STEP FIVE
 #######################END SETUP UNIONFS LAYERED FILESYSTEM###################
 
 #101127 pakt: code adapted from bchafy's Xin
