fix mounting with large numbers or partitions bug

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -98,7 +98,7 @@ mntfunc() {
  MNT_O=""
  [ $4 ] && MNT_O="${4}" #ex: noatime
  MNT_DSK="${MNT_DEV:5:3}"
- if [ "$PTRIM" = "yes" -a "$(cat /sys/block/$MNT_DSK/queue/rotational)" = "0" ];then
+ if [ "$PTRIM" = "yes" -a "$MNT_DSK" != "" -a "$(cat /sys/block/$MNT_DSK/queue/rotational)" = "0" ];then
   if [ "$MNT_T" = "ext4" -o "$MNT_T" = "f2fs" ];then
    if [ "$MNT_O" = "" ];then
     MNT_O="discard"
@@ -224,11 +224,11 @@ ensure_mounted() {
 # "$2" - mountpoint - ex: /mnt/pdrv
  ONE_MP="$(mount | grep -m1 "/dev/${1} " | cut -f 3 -d ' ')"
  [ "$ONE_MP" ] && return
- ONE_FS="$(echo "$HAVE_PARTS" | grep "${1}" | cut -f 2 -d '|')"
+ ONE_FS="$(echo "$HAVE_PARTS" | grep -m1 "${1}" | cut -f 2 -d '|')"
  ONE_MP="${2}"
  [ -d "$ONE_MP" ] || mkdir -p $ONE_MP
  mntfunc $ONE_FS /dev/${1} $ONE_MP #-t $ONE_FS /dev/$ONE_PART $ONE_MP
- [ $? -eq 0 ] || { ONE_MP=""; echo "${1} on $ONE_MP as $ONE_FS mount failed."; }
+ [ $? -eq 0 ] || { echo "${1} on $ONE_MP as $ONE_FS mount failed."; ONE_MP=""; }
 }
 
 ensure_save_mounted() {
