integrate save processing int new environment

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -643,8 +643,8 @@ find_save_file() {
 # "$1" - mount point - ex:  /mnt/pdrv
 # "$2" - partition name - ex: sdb2
 # "$3" - file system type - ex: ext4
- if [ "$SAVE_BP_DIR" ];then
-  SAVE_DIR="$SAVE_BP_DIR"
+ if [ "$SAVE_REL_DIR" ];then
+  SAVE_DIR="$SAVE_REL_DIR"
  else
   SAVE_DIR="${PSUBDIR}/"
  fi
@@ -853,7 +853,7 @@ if [ -f /sbin/isoboot ] ; then
   . /sbin/isoboot # optional, can remove all occurrences of "isoboot" from this script
 fi
 
-[ "$PDEBUG" ] && echo "0: PMEDIA=$PMEDIA PDRV=$PDRV PSUBDIR=$PSUBDIR pfix=$pfix"
+[ "$PDEBUG" ] && echo "0: PMEDIA=$PMEDIA PDRV=$PDRV PSUBDIR=$PSUBDIR PSAVE=$PSAVE pfix=$pfix"
 
 #setup wireless
 [ "$PWIRELESS" ] && echo -e "SSID=${PWIRELESS%:*}\nPSWD=${PWIRELESS#*:}" > /tmp/wireless.conf
@@ -863,8 +863,6 @@ get_part_info
 PUP_SAVES=""
 KEEPMOUNTED=""
 FSCKDPARTS=""
-
-[ "$PDEBUG" ] && echo "1: PDRV=$PDRV P_BP_ID=$P_BP_ID P_BP_FN=$P_BP_FN"
 
 check_resize_part
 grep -v '^sr' /tmp/ALLDRVS0 > /tmp/ATADRIVES0
@@ -942,17 +940,20 @@ for ONE_DRV in $PREPEND_DRVS; do
   LOADMSG="${ONE_DRV}drv"
   process_one_sfs "$ONE_DRV" 'p'
 done
-ONE_DEF_FN=''
 
 #establish SAVEPART
 [ "$PSAVE" ] || PSAVE="$ISO_PSAVE"
-SAVE_BP_DIR=""
+ONE_DEF_FN=''
+SAVE_REL_DIR=''
 if [ "$PSAVE" ]; then
   interpret_spec "$PSAVE" 'sv'
-  SAVEPART="$ONE_PART"
-  PSAVEPART="$ONE_PART"
-  SAVE_BP_FN="$ONE_REL_FN"
-  [ "$SAVE_BP_FN" ] && [ "${SAVE_BP_FN:$((${#SAVE_BP_FN} - 1))}" = "/" ] && SAVE_BP_DIR="$SAVE_BP_FN" #last char
+  SAVEPART="$SPEC_PART"
+  SAVE_REL_FN="$SPEC_REL_FN"
+  if [ "$SAVE_REL_FN" ];then
+    case "$SAVE_REL_FN" in
+      */) SAVE_REL_DIR="$SAVE_REL_FN" ;; #specified a directory
+    esac
+  fi
 fi
 
 if [ "$P_PART" ];then
@@ -963,7 +964,7 @@ if [ "$P_PART" ];then
   if [ "$PSAVEMARK" -a "$BOOTDRV" ];then
    ONE_PART="${BOOTDRV}${PSAVEMARK}" #note, PSAVEMARK could also be a kernel boot param. ex: 2
    if [ "$(echo $HAVE_PARTS | grep "$ONE_PART")" ];then #partition exists
-    SAVEPART="$ONE_PART"; PSAVEPART="$ONE_PART"; SAVE_BP_DIR="${PSUBDIR}/"
+    SAVEPART="$ONE_PART"; SAVE_REL_DIR="${PSUBDIR}/"
     PSAVEMARK=''
    fi
   fi
@@ -981,12 +982,12 @@ if [ -f "/tmp/SAVESPEC" ];then
  rm /tmp/SAVESPEC
  if [ "$SS_ID" ];then
   decode_id "$SS_ID"
-  [ "$ONE_PART" ] && { SAVEPART="$ONE_PART"; PSAVEPART="$ONE_PART"; }
+  [ "$ONE_PART" ] && SAVEPART="$ONE_PART"
  fi
  if [ "$SS_DIR" ];then
-  SAVE_BP_DIR="${SS_DIR%/}/" #ensure trailing '/'
-  [ "${SAVE_BP_DIR:0:1}" = '/' ] || SAVE_BP_DIR="/$SAVE_BP_DIR" #ensure leading '/'
-  SAVE_BP_FN="$SAVE_BP_DIR"
+  SAVE_REL_DIR="/${SS_DIR#/}" #ensure leading '/'
+  SAVE_REL_DIR="${SAVE_REL_DIR%/}/" #ensure trailing '/'
+  SAVE_REL_FN="$SAVE_REL_DIR"
  fi
  [ "$SS_MEDIA" ] && PMEDIA="$SS_MEDIA"
 fi
@@ -1002,15 +1003,14 @@ fi
 [ "$SAVEPART" ] || SAVEPART="$P_PART"
 
 #ensure that save partition is mounted
-#if SAVEPART is not the same as P_PART
 #moved up here to ensure config files are available
 [ "$SAVEPART" ] && ensure_save_mounted
 
 #support initmodules.txt
 if [ "$PIMOD" = "" ]; then
   PIMOD_DIR=""
-  case $SAVE_BP_FN in
-    */*) PIMOD_DIR="${SAVE_BP_FN%/*}" ;;
+  case $SAVE_REL_FN in
+    */*) PIMOD_DIR="${SAVE_REL_FN%/*}" ;;
     *) PIMOD_DIR="${PSUBDIR}" ;;
   esac
   PIMOD_FN="${SAVE_MP}${PIMOD_DIR}/${DISTRO_FILE_PREFIX}initmodules.txt"
@@ -1081,16 +1081,16 @@ if [ "${SAVE_MP}" != "" -a "$PRAMONLY" != "yes" ];then #have mounted save? parti
  #not sorted yet, may be pupmode=12
  if [ $PUPMODE -eq 5 ];then
   #check boot spec
-  if [ "$SAVE_BP_FN" -a "$SAVE_BP_DIR" = "" ];then
-   if [ -d "${SAVE_MP}${SAVE_BP_FN}" ];then
-    [ "$ONE_FS_IS_LINUX" = "yes" ] && PUPSAVE="$SAVEPART,$SAVE_FS,$SAVE_BP_FN"
+  if [ "$SAVE_REL_FN" -a "$SAVE_REL_DIR" = "" ];then
+   if [ -d "${SAVE_MP}${SAVE_REL_FN}" ];then
+    [ "$ONE_FS_IS_LINUX" = "yes" ] && PUPSAVE="$SAVEPART,$SAVE_FS,$SAVE_REL_FN"
    else
-    [ -s "${SAVE_MP}${SAVE_BP_FN}" ] && PUPSAVE="$SAVEPART,$SAVE_FS,$SAVE_BP_FN"
+    [ -s "${SAVE_MP}${SAVE_REL_FN}" ] && PUPSAVE="$SAVEPART,$SAVE_FS,$SAVE_REL_FN"
    fi
-   [ "$PUPSAVE" ] || echo "$SAVEPART, $SAVE_BP_FN file not found."
+   [ "$PUPSAVE" ] || echo "$SAVEPART, $SAVE_REL_FN file not found."
   else
    #have to find savefile/savefolder
-   [ "$PUP_SAVES" ] || find_save_file "${SAVE_MP}" "$SAVEPART" "$SAVE_FS"
+   [ "$PUP_SAVES" ] || find_save_file "$SAVE_MP" "$SAVEPART" "$SAVE_FS"
    echo "PUP_SAVES=${PUP_SAVES}" #debug
    if [ "$PUP_SAVES" ];then
     NUMPUP_SAVES=0
@@ -1251,8 +1251,8 @@ echo "PUP_HOME='${SAVE_MP}'"
 echo '#(in /initrd) ...note, /mnt/home is a link to it.'
 echo '#Partition no. override on boot drive to which session is (or will be) saved...'
 echo "PSAVEMARK='$PSAVEMARK'"
-echo "PSAVEPART='$PSAVEPART'"
-echo "PSAVEDIR='$SAVE_BP_DIR'"
+echo "PSAVEPART='$SAVEPART'"
+echo "PSAVEDIR='$SAVE_REL_DIR'"
 echo "PSUBDIR='$PSUBDIR'"
 echo "PUNIONFS='aufs'"
 echo "DOIMODS='yes'"
