fixes for pupmodes 7 & 13
also make pmedia=<usbhd|usbflash|usb*> work in atahd drives .. less bug reports

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -84,7 +84,7 @@ fsck_func() {
   vfat|msdos) fsck_app='fsck.fat' ;;
   *) return ;;
  esac
- which "${fsck_app}" ] || echo "WARNING: '${fsck_app}' not found / ${fsck_app} -y ${1}"
+ which "${fsck_app}" || echo "WARNING: '${fsck_app}' not found / ${fsck_app} -y ${1}"
  if [ "$(echo "$FSCKDPARTS" | grep "${1}|")" = "" ];then
   ${fsck_app} -y ${1} > /dev/console 2>&1
   FSCKDPARTS="${FSCKDPARTS}${1}|"
@@ -608,10 +608,11 @@ copy_folders() {
 
 prepend_dir() {
  dir="$1"
+ mode="$2"
  rm -rf ${dir}/tmp #in case last boot was pupmode=12
  #adjust stack
- echo "mount -o remount,add:1:${dir}=ro+wh /pup_new" #debug
- mount -o remount,add:1:${dir}=ro+wh /pup_new
+ echo "mount -o remount,add:1:${dir}=${mode} /pup_new" #debug
+ mount -o remount,add:1:${dir}=${mode} /pup_new
  if [ $? -eq 0 ];then
   KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
   [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
@@ -860,7 +861,11 @@ if [ "$LOOK_PUP" -o "$LOOK_SAVE" ];then #something to search for
   wait_for_usb
   USBDRVS="$(find /sys/block -maxdepth 1 -name 'sd*' -o -name 'sr*' | xargs -n 1 readlink 2>/dev/null | grep '/usb[0-9]' | rev | cut -f 1 -d '/' | rev | tr '\n' '|')"
   [ "$PDEBUG" ] && echo "2: USBDRVS=$USBDRVS -> ${USBDRVS%|}"
-  [ "$USBDRVS" ] && search_func "${USBDRVS%|}"
+  if [ "$USBDRVS" ] ; then
+    search_func "${USBDRVS%|}"
+  else
+    search_func
+  fi
  fi
 fi
 [ "$P_BP_ID" ] && { log_part_id "$P_BP_ID"; ONE_PART="$P_BP_ID"; }
@@ -1092,12 +1097,12 @@ fi
 case $PUPMODE in
  77) #load folders
   copy_folders /pup_ro1
-  prepend_dir /mnt/tmpfs/pup_ro1
+  prepend_dir /mnt/tmpfs/pup_ro1 ro+wh #wh = Readonly branch and it has/might have whiteouts on it
   SAVE_LAYER=/pup_rw
  ;;
  13) #prepend ro1
   setup_save_file
-  [ "$PUPSAVE" ] && prepend_dir ${SAVE_LAYER}
+  [ "$PUPSAVE" ] && prepend_dir ${SAVE_LAYER} rw #read write
  ;;
  12) #replace rw
   setup_save_file
@@ -1105,7 +1110,7 @@ case $PUPMODE in
  ;;
  7) #prepend ro1
   setup_save_part
-  prepend_dir ${SAVE_LAYER}
+  prepend_dir ${SAVE_LAYER} rw #read write
  ;;
  6) #replace rw
   setup_save_part
