init: merge load_ext_file() into setup_psave()

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -386,32 +386,6 @@ setup_onepupdrv() {
  return 0
 }
 
-
-load_ext_file() { #ex: stretchsave.4fs
- if [ -f /sbin/load_ext_file ] ; then
-   /sbin/load_ext_file "$SAVE_FN" "$SAVE_MP"
-   if [ -f /tmp/savefile_loop ] ; then
-     . /tmp/savefile_loop # $SAVEFILE_LOOP $SFFS
-   else
-     FLAG_NO_TIMEOUT=1
-     PUPSAVE=""
-     return
-   fi
- else
-   SAVEFILE_LOOP="$(losetup -f)"
-   losetup $SAVEFILE_LOOP $SAVE_FN
-   SFFS=$(blkid "$SAVE_FN" | grep -o ' TYPE=".*' | cut -f 2 -d '"')
- fi
- #--
- [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
- echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER" #debug
- mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER
- if [ $? -ne 0 ] ; then
-   echo 'Warning: setting PUPSAVE=""' #debug
-   PUPSAVE=""
- fi
-}
-
 # setup savefile or savefolder
 setup_psave(){
  SAVE_REL_FN="$(echo "$PUPSAVE" | cut -f 3 -d ',')"
@@ -425,7 +399,17 @@ setup_psave(){
  SAVE_FN="${SAVE_MP}${SAVE_REL_FN}"
  if [ -f "$SAVE_FN" ];then #savefile. ex: stretchsave.4fs
   echo "--SAVEFILE-- $SAVE_FN" #debug
-  load_ext_file
+  /sbin/load_ext_file "$SAVE_FN" "$SAVE_MP" #reads $PFSCK
+  if [ -f /tmp/savefile_loop ] ; then
+    . /tmp/savefile_loop # $SAVEFILE_LOOP $SFFS
+    [ -d "$SAVE_LAYER" ] || mkdir $SAVE_LAYER
+    echo "mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER" #debug
+    mount -t $SFFS -o noatime $SAVEFILE_LOOP $SAVE_LAYER
+    [ $? -ne 0 ] && PUPSAVE=""
+  else # load_ext_file failed
+    FLAG_NO_TIMEOUT=1
+    PUPSAVE=""
+  fi
  elif [ -d "$SAVE_FN" ];then #savefolder
   echo "--SAVEFOLDER-- $SAVE_FN" #debug
   ln -sv "$SAVE_FN" "$SAVE_LAYER"
