initrd init: localization support

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -1,5 +1,45 @@
 #!/bin/sh
 
+######################## localization ########################
+#ex: /locale/<locale>/init.mo
+L_WINDOWS_HIBERNATED="ERROR: Windows NTFS hibernated partition, cannot mount"
+L_DONE='done'
+L_FAILED='failed'
+L_DUMPING_BOOTINIT_LOG="Dumping last lines of /tmp/bootinit.log..."
+L_DUMPING_KERNEL_LOG="Dumping last lines of kernel log..."
+L_ERROR_IS_TOO_CRITICAL="Error is too critical, dropping out to console..."
+L_PAUSING_60_SECONDS="Pausing for 60 seconds..."
+L_LOADING_FILE='Loading the \"$ONE_BASENAME\" $LOADMSG file...' #eval
+L_CANNOT_RESIZE_PUPSAVE='SORRY, cannot resize $PUPSAVEFILEX' #eval
+L_INCREASING_PUPSAVE='Increasing $PUPSAVEFILEX by $KILOBIG Kbytes, please wait...' #eval
+L_LOADING_PUPSAVE='Loading personal storage $SAVE_REL_FN - $SAVEPART...' #eval
+L_UPGRADE_MSG_1='This personal storage was last used with version $OLDDISTRO_VERSION of Puppy.' #eval
+L_UPGRADE_MSG_2="Hit the ENTER key only if it is okay to upgrade this file, or to not use it and boot up in RAM only type any other printable character."
+L_UPGRADE_MSG_3="ENTER only to upgrade: "
+L_UPGRADE_NO="Backing off, not using personal storage, booting in RAM only, PUPMODE=5..."
+L_LOADING_FROM_CD='Loading folder $ONEFOLDER from CD/DVD...' #eval
+L_RAM_DISK_FULL='RAM disk full, copy failed at $ONEFOLDER' #eval
+L_ADDING_SAVE_LAYER_FAILED='adding $SAVE_LAYER to aufs stack failed.' #eval
+L_WAITING_FOR_USB="Waiting for USB storage."
+L_LOADING_KEYBOARD_LAYOUT='Loading \"$PKEYS\" keyboard layout...' #eval
+L_COPY_MESSAGE="copying to ram"
+L_LOAD_MESSAGE="main"
+L_PRE_MESSAGE="Loading puppy main sfs file."
+L_ERR_PDRV_INCOMPLETE='$PDRV information is incomplete.' #eval
+L_ERR_ONEPART_NOT_MOUNTED='$ONE_PART is not mounted.' #eval
+L_ERR_ONEPART_NOT_OK='$ONE_PART $ONE_REL_FN is not Ok.' #eval
+L_ERR_ONEPART_MOUNT_SFS_FAILED='$ONE_PART $ONE_REL_FN mount of sfs failed.' #eval
+L_ERR_AUFS_SFS_FAILED='aufs mount of $ONE_LAYER failed.' #eval
+L_ERR_TYPE_PUPSAVE="Type a number to choose which personal file to use:"
+L_DROPPED_TO_INITRD_SHELL="Dropped to initramfs shell. Type 'exec switch' to continue booting Puppy."
+L_SWITCH_ROOT="Performing a 'switch_root' to the layered filesystem..."
+L_CONTINUING_LOADING='...continuing with loading $PUPSAVEFILE...' #eval
+L_FOLDER_MARKED_BAD='Folder $ONEFOLDER marked bad.' #eval
+L_0_NONE="0  none"
+L_ERROR_FAILED_AUFS_STACK='Failed to create empty aufs stack'
+L_ADDING_MODULE='Adding module $CURMOD' #eval
+##############################################################
+
 if [ "$(ls /proc)" = "" ]; then
  mount -t proc none /proc
  mount -t sysfs none /sys
@@ -69,7 +109,7 @@ mntfunc() {
    [ $ntfsRETVAL -eq 0 ] && return 0
    if [ $ntfsRETVAL -eq 14 ];then
     echo -e "\\033[1;31m" >/dev/console #31=red
-    echo -n "ERROR: Windows NTFS hibernated partition, cannot mount" > /dev/console
+    echo -n "${L_WINDOWS_HIBERNATED}" > /dev/console
     echo -e "\\033[0;39m" >/dev/console
     return 14
    else
@@ -99,37 +139,37 @@ check_status() #args: [-critical] $RET_VAL "$ERROR_MSG"
   shift
   ERROR_MSG="$@"
   if [ $RET_VAL -eq 0 ] ; then
-    /bin/echo -en "\\033[74G" >/dev/console #move to column 72. 110426: 74
-    /bin/echo -en "\\033[1;32m" >/dev/console
-    /bin/echo -en "done" >/dev/console
-    /bin/echo -e "\\033[0;39m" >/dev/console
+    echo -en "\\033[74G" >/dev/console #move to column 72. 110426: 74
+    echo -en "\\033[1;32m" >/dev/console
+    echo -en "${L_DONE}" >/dev/console
+    echo -e "\\033[0;39m" >/dev/console
   else
-    /bin/echo -en "\\033[72G" >/dev/console #110426 move to column 72.
-    /bin/echo -en "\\033[1;31m" >/dev/console
-    /bin/echo -en "failed" >/dev/console
-    /bin/echo -e "\\033[0;39m" >/dev/console
+    echo -en "\\033[72G" >/dev/console #110426 move to column 72.
+    echo -en "\\033[1;31m" >/dev/console
+    echo -en "${L_FAILED}" >/dev/console
+    echo -e "\\033[0;39m" >/dev/console
     echo -en "\\033[1;35m" >/dev/console #35=purple
-    echo -n "Dumping last lines of /tmp/bootinit.log..." >/dev/console
-    /bin/echo -e "\\033[0;39m" >/dev/console
+    echo -n "${L_DUMPING_BOOTINIT_LOG}" >/dev/console
+    echo -e "\\033[0;39m" >/dev/console
     echo -en "\\033[1;31m" >/dev/console #31=red
     cat /tmp/bootinit.log | tail -n 4 >/dev/console
-    /bin/echo -en "\\033[0;39m" >/dev/console
+    echo -en "\\033[0;39m" >/dev/console
     echo -en "\\033[1;35m" >/dev/console #35=purple
-    echo -n "Dumping last lines of kernel log..." >/dev/console
-    /bin/echo -e "\\033[0;39m" >/dev/console
+    echo -n "${L_DUMPING_KERNEL_LOG}" >/dev/console
+    echo -e "\\033[0;39m" >/dev/console
     echo -en "\\033[1;31m" >/dev/console #31=red
     dmesg | tail -n 4 >/dev/console
-    /bin/echo -en "\\033[0;39m" >/dev/console
+    echo -en "\\033[0;39m" >/dev/console
     #exit to initial ramdisk shell...
     [ "$RDSH" != "" ] && exec /bin/sh >/dev/console 2>&1
     if [ "$ERROR_CRITICAL" = "yes" ] ; then
       echo -en "\\033[1;35m" >/dev/console #35=purple
       [ "$ERROR_MSG" != "" ] && echo "*** $ERROR_MSG" >/dev/console
-      echo "*** Error is too critical, dropping out to console..." >/dev/console
+      echo "*** ${L_ERROR_IS_TOO_CRITICAL}" >/dev/console
       echo -en "\\033[0;39m" >/dev/console
       exec /bin/sh >/dev/console 2>&1
     else
-      echo "Pausing for 60 seconds..." >/dev/console
+      echo "${L_PAUSING_60_SECONDS}" >/dev/console
       sleep 60
     fi
   fi
@@ -233,7 +273,7 @@ setup_loop_sfs() {
 }
 
 load_sfs_file() {
- [ "$LOADMSG" ] && echo -n "Loading the '${ONE_BASENAME}' ${LOADMSG} file..." > /dev/console
+ [ "$LOADMSG" ] && eval echo -n "${L_LOADING_FILE}" > /dev/console
  if [ "$COPY2RAM" = "" ];then
   COPY2RAM="no"
   #if there's heaps of ram, copy puppy.sfs to a tmpfs...
@@ -321,13 +361,15 @@ resize_ext_file() {
  . $RESIZE_FN
  [ "$PUPSAVEFILEX" = "$SAVE_REL_FN" ] || return
  if [ ! -e /bin/e2fsck ];then
-  echo -e -n "\\033[1;31m SORRY, cannot resize ${PUPSAVEFILEX} \\033[0;39m" > /dev/console #31=red
+  echo -en "\\033[1;31m" > /dev/console
+  eval echo -n "${L_CANNOT_RESIZE_PUPSAVE}" > /dev/console #31=red
+  echo -en "\\033[0;39m" > /dev/console
   rm -f $RESIZE_FN
  else
   SAVE_SZ_FN="$SAVE_FN"
   rm -f $RESIZE_FN
   echo > /dev/console
-  echo -n "Increasing $PUPSAVEFILEX by $KILOBIG Kbytes, please wait..." >/dev/console
+  eval echo -n "${L_INCREASING_PUPSAVE}" >/dev/console
   dd if=/dev/zero bs=1024 count=$KILOBIG >> $SAVE_SZ_FN #131225 
   sync
  fi
@@ -338,7 +380,7 @@ resize_ext_fs() {
  resize2fs -pf ${1} #no size, will fill all of file.
  sync
  check_status 0 #note, e2fsck gives an error even though it works. v2.21 maybe okay now.
- echo -n "...continuing with loading $PUPSAVEFILE..." > /dev/console
+ eval echo -n "${L_CONTINUING_LOADING}" > /dev/console
 }
 
 load_ext_file() {
@@ -359,7 +401,7 @@ load_ext_file() {
 
 setup_save_file(){
  SAVE_REL_FN="$(echo "$PUPSAVE" | cut -f 3 -d ',')"
- echo -n "Loading personal storage $SAVE_REL_FN ($SAVEPART)..." > /dev/console 
+ eval echo -n "${L_LOADING_PUPSAVE}" > /dev/console
  rm -r -f "$SAVE_LAYER"
  SAVE_FN="${SAVE_MP}${SAVE_REL_FN}"
  if [ -f "$SAVE_FN" ];then #savefile
@@ -376,14 +418,14 @@ setup_save_file(){
   OLDDISTRO_VERSION="$(grep '^DISTRO_VERSION' $SAVE_LAYER/etc/DISTRO_SPECS | cut -f 2 -d '=' | cut -f 2 -d "'" | cut -f 2 -d '"' | cut -f 1 -d ' ')"
   if [ "$DISTRO_VERSION" != "$OLDDISTRO_VERSION" ]; then
    echo -en "\\033[1;36m" >/dev/console #36=aquablue
-   echo "This personal storage was last used with version $OLDDISTRO_VERSION of Puppy." >/dev/console
-   echo "Hit the ENTER key only if it is okay to upgrade this file, or to not use it and boot up in RAM only type any other printable character."  >/dev/console
-   echo -n "ENTER only to upgrade: "  >/dev/console
+   eval echo "${L_UPGRADE_MSG_1}" >/dev/console
+   echo "${L_UPGRADE_MSG_2}"  >/dev/console
+   echo -n "${L_UPGRADE_MSG_3}"  >/dev/console
    echo -en "\\033[0;39m" >/dev/console
    read noupgradesf
    if [ "$noupgradesf" != "" ];then
     echo -en "\\033[1;35m" >/dev/console #35=purple
-    echo "Backing off, not using personal storage, booting in RAM only, PUPMODE=5..." >/dev/console
+    echo "${L_UPGRADE_NO}" >/dev/console
     echo -en "\\033[0;39m" >/dev/console
     PUPSAVE=""
    #else
@@ -429,10 +471,10 @@ copy_folders() {
  BKFOLDERS="$(echo -n "$BKFOLDERS" | tr "\n" " ")"
  for ONEFOLDER in $BKFOLDERS;do
   if [ ! "$(echo -n "$BKBADLIST" | grep "$ONEFOLDER")" = "" ];then
-   echo "Folder $ONEFOLDER marked bad." >/dev/console
+   eval echo "${L_FOLDER_MARKED_BAD}" >/dev/console
    continue #ignore bad folder.
   fi
-  echo -n "Loading folder $ONEFOLDER from CD/DVD..." >/dev/console
+  eval echo -n "${L_LOADING_FROM_CD}" >/dev/console
   #need to be careful not to overfill the ramdisk...
   FREERAMDISK=$(df 2>/dev/null | grep /mnt/tmpfs | head -n 1 | tr -s " " | cut -f 4 -d " ")
   SIZEFOLDER=$(du -k -s ${SAVE_MP}/${ONEFOLDER} | cut -f 1)
@@ -471,7 +513,7 @@ copy_folders() {
    done
    check_status 0 #display 'done' for each folder loaded.
   else
-   echo "RAM disk full, copy failed at $ONEFOLDER"
+   eval echo "${L_RAM_DISK_FULL}"
    check_status 1
    break
   fi
@@ -487,6 +529,7 @@ prepend_dir() {
   KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
   [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
  else
+  eval echo "${L_ADDING_SAVE_LAYER_FAILED}"
   echo "adding $SAVE_LAYER to aufs stack failed."
  fi
 }
@@ -503,6 +546,7 @@ replace_dir() {
   KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
   [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
  else
+  eval echo "${L_ADDING_SAVE_LAYER_FAILED}"
   echo "adding $SAVE_LAYER to aufs stack failed."
  fi
 }
@@ -567,7 +611,7 @@ get_part_info() {
 
 wait_for_usb() {
  [ -e /tmp/flag-usb-ready ] && return
- echo -n "Waiting for USB storage." > /dev/console 
+ echo -n "${L_WAITING_FOR_USB}" > /dev/console 
  /sbin/wait4usb
  get_part_info
  BLKIDOUT=""
@@ -586,7 +630,7 @@ fatal_error() {
 # "$2" - pre-status-message - ex: Finding puppy
  KEEPMOUNTED=""
  umount_unneeded
- [ "${2}" ] && echo -n "${2}" > /dev/console
+ [ "${2}" ] && eval echo -n "${2}" > /dev/console
  check_status -critical 1 "$1"
 }
 
@@ -594,6 +638,9 @@ clear #clear the screen.
 [ ! "$LOGLEVEL" ] && exec 1>/tmp/bootinit.log 2>&1 #remove o/p from console. v2.22 loglevel added.
 
 [ $plang ] && PLANG=$plang #boot parameter
+[ "`echo -n "$PLANG" | grep '_'`" = "" ] && PLANG="" #PLANG must be complete, ex: de_DE.UTF-8.
+[ ! "$PLANG" ] && [ -s /PUPPYLANG ] && PLANG=`cat /PUPPYLANG` #so Woof can specify a default lang.
+
 [ $pkeys ] && PKEYS=$pkeys #boot parameter, keyboard layout w476
 #pmedia= usbflash|usbhd|usbcd|ataflash|atahd|atacd|atazip|scsihd|scsicd|cd
 [ $pmedia ] && PMEDIA=$pmedia #boot parameter, broad category of boot media. ex: cd.
@@ -640,11 +687,11 @@ if [ "$pfix" ];then
 fi
 
 export TZ='XXX-20'
-/bin/hwclock -l -s
+hwclock -l -s
 
 #120216 /PUPPYKEYMAP inserted in initrd by quicksetup (in future, by Woof too)...
 FONTMAP=""
-[ -f /PUPPYKEYMAP ] && [ ! "$PKEYS" ] && PKEYS="`cat /PUPPYKEYMAP`" #allow kernel boot param to override.
+[ ! "$PKEYS" ] && [ -s /PUPPYKEYMAP ] && PKEYS="`cat /PUPPYKEYMAP`" #allow kernel boot param to override.
 if [ "$PLANG" ];then
  if [ ! "$PKEYS" ];then
   #try to set PKEYS to match the language. first 2 letters of PLANG...
@@ -669,6 +716,11 @@ if [ "$PLANG" ];then
    FONTMAP='LatGrkCyr-8x16.psfu'
   ;;
  esac
+ if [ -f /locale/${PLANG%.*}/init.mo ];then
+   . /locale/${PLANG%.*}/init.mo
+ elif [ -f /locale/${PLANG%_*}/init.mo ];then
+   . /locale/${PLANG%_*}/init.mo
+ fi
 fi
 
 #091122 load keyboard layout if PKEYS boot param...
@@ -681,7 +733,7 @@ if [ "$PKEYS" ];then
   PKEYS="`ls -1 /lib/keymaps/${PKEYS}*.gz | head -n 1 | rev | cut -f 1 -d '/' | cut -f 2 -d '.' | rev`"
  fi
  if [ -f /lib/keymaps/${PKEYS}.gz ];then
-  echo "Loading '${PKEYS}' keyboard layout..." >/dev/console
+  eval echo "${L_LOADING_KEYBOARD_LAYOUT}" >/dev/console
   KMAP="$PKEYS"
   zcat /lib/keymaps/${PKEYS}.gz | loadkmap ; STATUS=$(($STATUS + $?))
   case $PKEYS in #note, same code in /etc/rc.d/rc.country, /usr/sbin/input-wizard and init.
@@ -793,23 +845,23 @@ RAMSIZE=$(free | grep -o 'Mem: .*' | tr -s ' ' | cut -f 2 -d ' ') #total physica
 mount -t tmpfs tmpfs /mnt/tmpfs
 [ -d "/mnt/tmpfs/pup_rw" ] || mkdir /mnt/tmpfs/pup_rw
 mount -t aufs -o udba=reval,diropq=w,br=/mnt/tmpfs/pup_rw=rw,xino=/mnt/tmpfs/.aufs.xino unionfs /pup_new 
-[ $? -eq 0 ] || fatal_error "Failed to create empty aufs stack"
+[ $? -eq 0 ] || fatal_error "${L_ERROR_FAILED_AUFS_STACK}"
 
 NEWUNIONRECORD=""
 COPY2RAM=""
 
-COPYMSG='copying to ram' #purple
-LOADMSG="main"
+COPYMSG="${L_COPY_MESSAGE}" #purple
+LOADMSG="${L_LOAD_MESSAGE}"
 setup_onepupdrv "$PDRV" "p"
 STATUS=$?
 if [ $STATUS -gt 0 ];then
- P_PRE_MSG="Loading puppy main sfs file."
+ P_PRE_MSG="${L_PRE_MESSAGE}"
  case $STATUS in
-  1) fatal_error "$PDRV information is incomplete." "$P_PRE_MSG" ;;
-  2) fatal_error "$ONE_PART is not mounted." "$P_PRE_MSG" ;;
-  3) fatal_error "$ONE_PART $ONE_REL_FN is not Ok." "$P_PRE_MSG" ;;
-  4) fatal_error "$ONE_PART $ONE_REL_FN mount of sfs failed." "$P_PRE_MSG" ;;
-  5) fatal_error "aufs mount of $ONE_LAYER failed." "$P_PRE_MSG" ;;
+  1) fatal_error "${L_ERR_PDRV_INCOMPLETE}" "$P_PRE_MSG" ;;
+  2) fatal_error "${L_ERR_ONEPART_NOT_MOUNTED}" "$P_PRE_MSG" ;;
+  3) fatal_error "${L_ERR_ONEPART_NOT_OK}" "$P_PRE_MSG" ;;
+  4) fatal_error "${L_ERR_ONEPART_MOUNT_SFS_FAILED}" "$P_PRE_MSG" ;;
+  5) fatal_error "${L_ERR_AUFS_SFS_FAILED}" "$P_PRE_MSG" ;;
  esac
 fi
 PUP_LAYER="$SFS_MP"
@@ -870,7 +922,7 @@ if [ "$PIMOD" != "" ];then
    [ -f "${MODSPATH}/${CURMOD}" ] || CURMOD=""
   fi
   if [ "$CURMOD" != "" ];then
-   echo -n "Adding module $CURMOD" > /dev/console
+   eval echo -n "${L_ADDING_MODULE}" > /dev/console
    insmod "${MODSPATH}/${CURMOD}" > /dev/console 2>&1
    check_status $?
   fi
@@ -926,8 +978,8 @@ if [ "$SAVE_MP" -a "$PRAMONLY" != "yes" ];then #have mounted save? partition
     elif [ $NUMPUPSAVES -gt 1 ];then
      CNTSAVE=1
      echo -e "\\033[1;36m" >/dev/console #36=aquablue
-     echo "Type a number to choose which personal file to use:" > /dev/console
-     echo "0  none" > /dev/console
+     echo "${L_ERR_TYPE_PUPSAVE}" > /dev/console
+     echo "${L_0_NONE}" > /dev/console
      for ONETRY in $PUPSAVES;do
       ONE_PART="$(echo -n "$ONETRY" | cut -f 1 -d ',')"
       ONE_FILE="$(echo -n "$ONETRY" | cut -f 3 -d ',')"
@@ -1027,7 +1079,7 @@ else
  echo "LASTUNIONRECORD=''" >> /pup_new/etc/rc.d/BOOTCONFIG
 fi
 
-echo -n "Performing a 'switch_root' to the layered filesystem..." > /dev/console
+echo -n "${L_SWITCH_ROOT}" > /dev/console
 
 rm -r -f "/pup_new/initrd${SAVE_LAYER}"
 for ONEMNT in $(mount | cut -f 3 -d ' ' | grep -v 'pup_new' | grep '^/pup_' | tr '\n' ' ');do
@@ -1076,7 +1128,7 @@ fi
 
 if [ "$RDSH" = "yes" ];then
  echo > /dev/console
- echo "Dropped to initramfs shell. Type 'exec switch' to continue booting Puppy." > /dev/console
+ echo "${L_DROPPED_TO_INITRD_SHELL}" > /dev/console
  exec /bin/sh >/dev/console 2>&1
 fi
 
