init: move prepend_dir() & replace_dir() to where they belong..

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -377,8 +377,7 @@ setup_onepupdrv() {
  return 0
 }
 
-# setup savefile or savefolder
-setup_psave(){
+setup_psave(){ # setup savefile or savefolder
  SAVE_REL_FN="$(echo "$PUPSAVE" | cut -f 3 -d ',')"
  if [ -f "${SAVE_MP}${SAVE_REL_FN}" ];then #savefile
   PUPSAVE_SIZE="$(fx_format_bytes $(stat -c %s "${SAVE_MP}${SAVE_REL_FN}"))"
@@ -544,34 +543,6 @@ copy_folders() { #SAVE_LAYER=/pup_ro1
  done
  sync
  echo -e "--------------------\n" # debug
-}
-
-prepend_dir() { #SAVE_LAYER=/pup_ro1
- rm -rf ${SAVE_LAYER}/tmp #in case last boot was pupmode=12
- #adjust stack
- echo "mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new" #debug
- mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new #ro+wh = Readonly branch and it has/might have whiteouts on it
- if [ $? -eq 0 ];then
-  [ $PUPMODE -ne 77 ] && KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
-  [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
- else
-  printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
- fi
-}
-
-replace_dir() { #SAVE_LAYER=/pup_rw
- #setup empty /tmp on tmpfs for in stack
- rm -rf ${SAVE_LAYER}/tmp
- #adjust stack
- echo "mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new" #debug
- mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new
- if [ $? -eq 0 ];then
-  rm -rf /mnt/tmpfs/pup_rw
-  KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
-  [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
- else
-  printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
- fi
 }
 
 set_fs_linux() {
@@ -1045,17 +1016,40 @@ fi
 
 #load savefile if required, then setup stack
 case $PUPMODE in
- 77) #load folders
-  copy_folders #to /pup_ro1 (part of the tmpfs)
-  prepend_dir  #prepend ro1
- ;;
- 13) #prepend ro1
-  setup_psave
-  [ "$PUPSAVE" ] && prepend_dir
+ 77|13)
+  [ $PUPMODE -eq 77 ] && copy_folders #to /pup_ro1 (part of the tmpfs)
+  [ $PUPMODE -eq 13 ] && setup_psave
+  if [ "$PUPSAVE" ] ; then
+    #prepend ro1 - #SAVE_LAYER=/pup_ro1
+    rm -rf ${SAVE_LAYER}/tmp #in case last boot was pupmode=12
+    #adjust stack
+    echo "mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new" #debug
+    mount -o remount,add:1:${SAVE_LAYER}=ro+wh /pup_new #ro+wh = Readonly branch and it has/might have whiteouts on it
+    if [ $? -eq 0 ];then
+      [ $PUPMODE -ne 77 ] && KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
+      [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
+    else
+      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
+    fi
+  fi
  ;;
  12) #replace rw
   setup_psave
-  [ "$PUPSAVE" ] && replace_dir
+  if [ "$PUPSAVE" ] ; then
+    #SAVE_LAYER=/pup_rw
+    #setup empty /tmp on tmpfs for in stack
+    rm -rf ${SAVE_LAYER}/tmp
+    #adjust stack
+    echo "mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new" #debug
+    mount -o remount,prepend:${SAVE_LAYER}=rw,mod:/mnt/tmpfs/pup_rw=ro,del:/mnt/tmpfs/pup_rw /pup_new
+    if [ $? -eq 0 ];then
+      rm -rf /mnt/tmpfs/pup_rw
+      KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
+      [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
+    else
+      printf "${L_ADDING_SAVE_LAYER_FAILED}\n" "$SAVE_LAYER"
+    fi
+  fi
  ;;
  5)
   SAVE_MP=""
