initrd init: add a warning to log if $fsck_app is missing

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -91,6 +91,7 @@ fsck_func() {
   vfat|msdos) fsck_app='fsck.fat' ;;
   *) return ;;
  esac
+ which "${fsck_app}" ] || echo "WARNING: '${fsck_app}' not found / ${fsck_app} -y ${1}"
  if [ "$(echo "$FSCKDPARTS" | grep "${1}|")" = "" ];then
   ${fsck_app} -y ${1} > /dev/console 2>&1
   FSCKDPARTS="${FSCKDPARTS}${1}|"
