improve handling of a file taht is not found

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -459,12 +459,19 @@ process_one_sfs() {
       ONE_SFS_SPEC="rootfs:/${ONE_DEF_FN}"
     elif [ -e "${P_MP}${PSUBDIR}/$ONE_DEF_FN" ]; then
       ONE_SFS_SPEC=":${ONE_DEF_FN}"
+    else
+      echo "${ONE_DEF_FN}, file not found"
+      return 3
     fi
   fi
   if [ "$ONE_SFS_SPEC" ]; then
     interpret_spec "$ONE_SFS_SPEC" "$1"
-    find_drv_file "$SPEC_MP" "${SPEC_REL_FN}"
-    [ "$ONE_FN" ] || return 3
+    [ "$SPEC_PART" ] || return 3
+    find_drv_file "$SPEC_MP" "$SPEC_REL_FN"
+    if [ "$ONE_FN" = "" ];then
+      echo "${SPEC_REL_FN##*/}, file not found"
+      return 3
+    fi
     SPEC_REL_FN="$ONE_FN"
     setup_onepupdrv "${1}" "${2}"
     STATUS=$?
