standard output is already redirected to /tmp/bootinit.log

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -171,7 +171,7 @@ decode_other_ids() {
 
 log_part_id() {
 # "$1" - partition id - ex: Work or sdc4
- echo "Partition ${1} not found." >> /tmp/bootinit.log
+ echo "Partition ${1} not found."
 }
 
 ensure_mounted() {
@@ -183,7 +183,7 @@ ensure_mounted() {
  ONE_MP="${2}"
  [ -d "$ONE_MP" ] || mkdir -p $ONE_MP
  mntfunc $ONE_FS /dev/${1} $ONE_MP #-t $ONE_FS /dev/$ONE_PART $ONE_MP
- [ $? -eq 0 ] || { ONE_MP=""; echo "${1} on $ONE_MP as $ONE_FS mount failed." >> /tmp/bootinit.log; }
+ [ $? -eq 0 ] || { ONE_MP=""; echo "${1} on $ONE_MP as $ONE_FS mount failed."; }
 }
 
 ensure_save_mounted() {
@@ -222,7 +222,7 @@ find_onepupdrv() {
  ensure_mounted "$ONE_PART" "/mnt/${4}drv"
  [ "$ONE_MP" ] || return
  find_drv_file "${2}" "${3}"
- [ "$ONE_FN" = "" -a "${2}" ] && echo "$ONE_PART, $ONE_TRY_FN file not found." >> /tmp/bootinit.log
+ [ "$ONE_FN" = "" -a "${2}" ] && echo "$ONE_PART, $ONE_TRY_FN file not found."
 }
 
 setup_loop_sfs() {
@@ -471,7 +471,7 @@ copy_folders() {
    done
    check_status 0 #display 'done' for each folder loaded.
   else
-   echo -n "RAM disk full, copy failed at $ONEFOLDER" >> /tmp/bootinit.log
+   echo "RAM disk full, copy failed at $ONEFOLDER"
    check_status 1
    break
   fi
@@ -487,7 +487,7 @@ prepend_dir() {
   KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
   [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
  else
-  echo "adding $SAVE_LAYER to aufs stack failed." >> /tmp/bootinit.log
+  echo "adding $SAVE_LAYER to aufs stack failed."
  fi
 }
 
@@ -503,7 +503,7 @@ replace_dir() {
   KEEPMOUNTED="${KEEPMOUNTED}${SAVEPART} "
   [ "$SAVE_NAME" ] && NEWUNIONRECORD="$SAVE_NAME $NEWUNIONRECORD"
  else
-  echo "adding $SAVE_LAYER to aufs stack failed." >> /tmp/bootinit.log
+  echo "adding $SAVE_LAYER to aufs stack failed."
  fi
 }
 
@@ -917,7 +917,7 @@ if [ "$SAVE_MP" -a "$PRAMONLY" != "yes" ];then #have mounted save? partition
    else
     [ -s "${SAVE_MP}${SAVE_BP_FN}" ] && PUPSAVE="$SAVEPART,$SAVE_FS,$SAVE_BP_FN"
    fi
-   [ "$PUPSAVE" ] || echo "$SAVEPART, $SAVE_BP_FN file not found." >> /tmp/bootinit.log
+   [ "$PUPSAVE" ] || echo "$SAVEPART, $SAVE_BP_FN file not found."
   else
    #have to find savefile/savefolder
    [ "$PUPSAVES" ] || find_save_file "$SAVE_MP" "$SAVEPART" "$SAVE_FS"
