initrd init: retry after 3 seconds if mounting a partition fails
this idea comes from the old init

this happened to me twice at least and it did work

however, the waiting time in the old init was 5, not it's only 3

this is an interesting comment...
usb optical drive showing as /sys/block/sr0, but won't mount, needs more delay...

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -224,7 +224,11 @@ ensure_mounted() {
  ONE_MP="${2}"
  [ -d "$ONE_MP" ] || mkdir -p $ONE_MP
  mntfunc $ONE_FS /dev/${1} $ONE_MP #-t $ONE_FS /dev/$ONE_PART $ONE_MP
- [ $? -eq 0 ] || { echo "${1} on $ONE_MP as $ONE_FS mount failed."; ONE_MP=""; }
+ if [ $? -ne 0 ] ; then
+  sleep 3 # usb optical drive showing as /sys/block/sr0, but won't mount, needs more delay...
+  mntfunc $ONE_FS /dev/${1} $ONE_MP
+  [ $? -ne 0 ] && { echo "${1} on $ONE_MP as $ONE_FS mount failed."; ONE_MP=""; return 1; }
+ fi
 }
 
 ensure_save_mounted() {
