init: merge load_sfs_file() into setup_onepupdrv()

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -285,65 +285,11 @@ find_onepupdrv() {
  [ "$ONE_FN" = "" -a "${2}" ] && echo "$ONE_PART, $ONE_TRY_FN file not found."
 }
 
-load_sfs_file() {
- [ "$LOADMSG" ] && echo -n "$(printf "${L_LOADING_FILE}" "$ONE_BASENAME" "$LOADMSG")" > /dev/console
- #- handle pfix=copy pfix=ram pfix=nocopy
- if [ "$PCOPY" = "yes" -o "$PRAMONLY" = "yes" ] ; then
-   COPY2RAM="yes"
- elif [ "$PNOCOPY" = "yes" ] ; then
-   COPY2RAM="no"
- fi
- #-
- if [ "$COPY2RAM" = "" ];then
-  COPY2RAM="no"
-  #if there's heaps of ram, copy puppy.sfs to a tmpfs...
-  #v405 fast media plus more than 256MB ram then definitely worth copying to ram...
-  SIZESFSK=$(du -k $ONE_FN | cut -f 1)
-  SIZESFSK=$(($SIZESFSK + 1000)) #some slack.
-  MINRAM2CPY=$(($SIZESFSK * 2)) #100222 technosaurus: in case of very big puppies.
-  #decide whether to copy .sfs's to ram
-  if [ $RAMSIZE -gt 1048576 ] ; then
-   [ $RAMSIZE -gt $MINRAM2CPY ] && COPY2RAM="yes"
-  fi
- fi
- ONE_LOOP="$(losetup -f)"
- if [ "$COPY2RAM" = "yes" ];then
-  SIZEZK=$(du -k $ONE_FN | cut -f 1)
-  TFREEK=$(df | grep -m1 ' /mnt/tmpfs' | tr -s ' ' | cut -f 4 -d ' ')
-  if [ $TFREEK -gt $SIZEZK ];then
-   if [ "$ONE_MP" = "" ];then #101101 humongous initrd.
-    mv -f $ONE_FN /mnt/tmpfs/
-   else
-    [ "$LOADMSG" ] && [ "$COPYMSG" ] && echo -en " \\033[1;35m${COPYMSG}\\033[0;39m" > /dev/console #purple.
-    TOTAL_SIZEK_SFS_RAM=$(($TOTAL_SIZEK_SFS_RAM + $SIZEZK))
-    cp -af $ONE_FN /mnt/tmpfs/
-   fi
-   sync
-   losetup -r $ONE_LOOP /mnt/tmpfs/$ONE_BASENAME
-  else
-   losetup -r $ONE_LOOP $ONE_FN
-   [ "$ONE_PART" != "rootfs" ] && KEEPMOUNTED="${KEEPMOUNTED}${ONE_PART} "
-  fi
- else
-  losetup -r $ONE_LOOP $ONE_FN
-  [ "$ONE_PART" != "rootfs" ] && KEEPMOUNTED="${KEEPMOUNTED}${ONE_PART} "
- fi
- SFS_MP="/pup_${ONE_SFX}"
- [ "$ONE_SFX" = "p" ] && SFS_MP="/pup_ro2"
- [ -d "$SFS_MP" ] || mkdir $SFS_MP
- mount -r -t squashfs -o noatime $ONE_LOOP $SFS_MP > /dev/console 2>&1
- STATUS=$?
- [ $STATUS -eq 0 ] && ONE_LAYER="$SFS_MP=rr"
- [ "$LOADMSG" ] && check_status $STATUS
-}
-
 setup_onepupdrv() {
 # "$1" - sfs spec - ex: sdb2,ext4,/pup/mydrv-1.2.3.sfs
 # "$2" - suffix for "pup_" branch directory - ex: a
 # "$3" - prepend after rw layer indicator - ex: p
  ONE_LAYER=""
- [ "$1" ] || return 1
- [ "$2" ] || return 1
  ONE_PART="$(echo "${1}" | cut -f 1 -d ',')"
  [ "$ONE_PART" ] || return 1
  ONE_REL_FN="$(echo "${1}" | cut -f 3 -d ',')"
@@ -363,10 +309,61 @@ setup_onepupdrv() {
  fi
  ONE_FN="${ONE_MP}${ONE_REL_FN}"
  ONE_BASENAME="$(basename $ONE_REL_FN)"
- #validate sfs here
- [ -s "$ONE_FN" ] || return 3 #sfs not Ok
- load_sfs_file
- [ "$ONE_LAYER" ] || return 4 #sfs mount failed
+ if ! [ -s "$ONE_FN" ] ; then
+   return 3 #sfs not Ok - empty file
+ fi
+ # ======= load_sfs_file()
+ echo -n "$(printf "${L_LOADING_FILE}" "$ONE_BASENAME" "$LOADMSG")" > /dev/console
+ #- handle pfix=copy pfix=ram pfix=nocopy
+ if [ "$PCOPY" = "yes" -o "$PRAMONLY" = "yes" ] ; then
+   COPY2RAM="yes"
+ elif [ "$PNOCOPY" = "yes" ] ; then
+   COPY2RAM="no"
+ fi
+ #-
+ if [ "$COPY2RAM" = "" ];then
+  COPY2RAM="no"
+  #if there's heaps of ram, copy puppy.sfs to a tmpfs...
+  SIZESFSK=$(du -k $ONE_FN | cut -f 1)
+  SIZESFSK=$(($SIZESFSK + 1000)) #some slack.
+  MINRAM2CPY=$(($SIZESFSK * 2)) #100222 technosaurus: in case of very big puppies.
+  #decide whether to copy .sfs's to ram
+  if [ $RAMSIZE -gt 1048576 ] ; then
+   [ $RAMSIZE -gt $MINRAM2CPY ] && COPY2RAM="yes"
+  fi
+ fi
+ ONE_LOOP="$(losetup -f)"
+ if [ "$COPY2RAM" = "yes" ];then
+  SIZEZK=$(du -k $ONE_FN | cut -f 1)
+  TFREEK=$(df | grep -m1 ' /mnt/tmpfs' | tr -s ' ' | cut -f 4 -d ' ')
+  if [ $TFREEK -gt $SIZEZK ];then
+   if [ "$ONE_MP" = "" ];then #101101 humongous initrd.
+    mv -f $ONE_FN /mnt/tmpfs/
+   else
+    echo -en " \\033[1;35m${L_COPY_MESSAGE}\\033[0;39m" > /dev/console #purple.
+    TOTAL_SIZEK_SFS_RAM=$(($TOTAL_SIZEK_SFS_RAM + $SIZEZK))
+    cp -af $ONE_FN /mnt/tmpfs/
+   fi
+   sync
+   losetup -r $ONE_LOOP /mnt/tmpfs/$ONE_BASENAME
+  else
+   losetup -r $ONE_LOOP $ONE_FN
+   [ "$ONE_PART" != "rootfs" ] && KEEPMOUNTED="${KEEPMOUNTED}${ONE_PART} "
+  fi
+ else
+  losetup -r $ONE_LOOP $ONE_FN
+  [ "$ONE_PART" != "rootfs" ] && KEEPMOUNTED="${KEEPMOUNTED}${ONE_PART} "
+ fi
+ SFS_MP="/pup_${ONE_SFX}"
+ [ "$ONE_SFX" = "p" ] && SFS_MP="/pup_ro2"
+ [ -d "$SFS_MP" ] || mkdir $SFS_MP
+ mount -r -t squashfs -o noatime $ONE_LOOP $SFS_MP > /dev/console 2>&1
+ STATUS=$? ; check_status $STATUS
+ [ $STATUS -eq 0 ] && ONE_LAYER="$SFS_MP=rr"
+ # ======= end of load_sfs_file()
+ if ! [ "$ONE_LAYER" ] ; then
+   return 4 #sfs mount failed
+ fi
  if [ "$ONE_PREP" ];then
   echo "mount -o remount,add:1:$ONE_LAYER /pup_new" #debug
   mount -o remount,add:1:$ONE_LAYER /pup_new
@@ -861,7 +858,6 @@ mount -t aufs -o udba=reval,diropq=w,br=/mnt/tmpfs/pup_rw=rw,xino=/mnt/tmpfs/.au
 NEWUNIONRECORD=""
 COPY2RAM=""
 
-COPYMSG="${L_COPY_MESSAGE}" #purple
 LOADMSG="${L_LOAD_MESSAGE}"
 setup_onepupdrv "$PDRV" "p"
 STATUS=$?
