improve handling of failed partition id decoding

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -195,9 +195,13 @@ wait_for_blkid() {
   sleep 1
   echo -en "\\033[1;33m.\\033[0;39m" >/dev/console #yellow dot
  done
- [ "$PART" ] && BLKID_PART="$PART"
+ if [ "$PART" ];then
+  BLKID_PART="$PART"
+ else
+  echo "Partition ${1} not found."
+ fi
+ get_part_info
  if [ "$DIDMSG" ];then
-  get_part_info
   if [ "$PART" ];then
    check_status 0
   else
@@ -215,12 +219,6 @@ decode_id() {
  fi
  wait_for_blkid "$1" 'id'
  ONE_PART="$BLKID_PART"
- [ "$ONE_PART" ] || log_part_id "$1"
-}
-
-log_part_id() {
-# "$1" - partition id - ex: Work or sdc4
- echo "Partition ${1} not found."
 }
 
 ensure_mounted() {
@@ -311,6 +309,7 @@ interpret_spec() {
   fi
   if [ "$PART" ]; then
     decode_id "$PART"
+    [ "$ONE_PART" ] || return
     PART="$ONE_PART"
   else
     PART="$P_PART"
