sync with initrd_progs repo
commits:

 dialog 1.3-20181107
 e2fsprogs 1.44.5
 fuse-exfat 1.3.0
 config.sub 2019-01-01
 busybox 1.30.0
 busybox: add some patches from alpine linux
 busybox 1.30.1
 dialog  20190211
 update z_compile_cc
 cross compilers 2019-04-24
    binutils-2.27
    gcc-6.4.0
    gmp-6.1.1
    linux-4.4.10
    make-cc.sh
    mpc-1.0.3
    mpfr-3.1.4
    musl-1.1.22

diff --git a/initrd-progs/z_compile_cc b/initrd-progs/z_compile_cc
--- a/initrd-progs/z_compile_cc
+++ b/initrd-progs/z_compile_cc
@@ -166,13 +166,15 @@ do
 	cd musl-cross-make-master
 
 	INSTALL_DIR=$(pwd)/${CC_DIR}
+	rm -rf $INSTALL_DIR
 	mkdir -p $INSTALL_DIR
 
-	export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"
-
 	make clean
+
+	cat > make-cc.sh <<EOF
+	export MAKEFLAGS="-j \$(grep -c ^processor /proc/cpuinfo)"
 	make OUTPUT="$INSTALL_DIR" TARGET="$TG" install
-	if [ $? -eq 0 ] ; then
+	if [ \$? -eq 0 ] ; then
 		(
 			date "+%Y-%m-%d"
 			echo
@@ -189,6 +191,14 @@ do
 	mv -fv "$CC_PKG" ../0sources
 
 	echo "Done !"
+	exit 0
+EOF
+
+	sh make-cc.sh
+	if [ $? -ne 0 ] ; then
+		echo "Failed to build cross-compiler, exiting"
+		exit 1
+	fi
 
 done
 
