pgprs-3.0: Upgrade with connect log restored and code refinements

diff --git a/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs b/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs
--- a/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs
+++ b/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs
@@ -1,103 +1,25 @@
 #! /bin/bash
+# shellcheck disable=SC1091 #Skip sourced checks.
 # PGPRS 2.x: Common interface to Puppy Generic GPRS Modem Utility
 
-#set -x; test -f /tmp/xerrs.log && exec 1>&2 || exec &>/tmp/debug.log #send feedback and trace to xerrs.log or debug.log
+#200622 (v3.0) Offer to disconnect existing connection; become current manager after setup; remove lock usage; move version & help options out of main loop; move etc gprs.conf; complete internationalization; resolve shellcheck warnings.
+
+export VERSION='3.0'  #UPDATE this with each release!
 
 export TEXTDOMAIN=pgprs
 export OUTPUT_CHARSET=UTF-8
 . gettext.sh
 
-export VERSION='2.0.2'  #UPDATE this with each release!
-
-[ -f /root/.config/gprs.conf ] \
- || echo -e "GPRSDEV=\nGPRSAPN=\nGPRSNBR=\nGPRSPIN=\nGPRSUSER=\nGPRSPAPONLY=" > /root/.config/gprs.conf
-mkdir -p /var/lock/gprs
-mkdir -p /tmp/.pgprs
-ICONLIB=/usr/local/lib/X11/pixmaps
-[ -f /usr/share/pixmaps/pgprs.svg ] \
- && export PGPRSICON=/usr/share/pixmaps/pgprs.svg \
- || export PGPRSICON=/usr/share/pixmaps/pgprs.png
-
-#Lock management - for unblocked locking only.
-eval $(grep '^GPRS_SETUP_LOCK_FD=' /etc/ppp/gprs.conf)
-eval $(grep '^GPRS_CONNECT_LOCK_FD=' /etc/ppp/gprs.conf)
-[ "$GPRS_SETUP_LOCK_FD" -a "$GPRS_CONNECT_LOCK_FD" ] || exit 1 
-eval exec "$GPRS_SETUP_LOCK_FD>/var/lock/gprs/setup"
-eval exec "$GPRS_CONNECT_LOCK_FD>/var/lock/gprs/connect"
-
-function disconnect_gprs {
- local PPPDPID=$(cat /var/run/ppp-gprs.pid)
- local CONNECTEDDEV
- [ "$PPPDPID" ] \
-  && CONNECTEDDEV="$(ps -p $PPPDPID | grep 'pppd' | grep -v 'grep' | grep -o '/dev/[a-z][^ ]*')"
- if [ "$CONNECTEDDEV" ];then
-  kill $PPPDPID
-  rm -f /var/run/ppp-gprs.pid
-  gtkdialog-splash -timeout 10 -placement center -bg orange -text "$(eval_gettext "Modem device \\\$CONNECTEDDEV disconnected")"
- fi
-}
-
 OPTION="$1"
 case $(basename "$0") in
- pgprs-shell) OPTION="--setup" ;;
- pgprs-connect) OPTION="--connect" ;;
- pgprs) [ -z "$OPTION" ] && OPTION="--setup" ;;
+    pgprs-shell) OPTION="--setup" ;;
+    pgprs-connect) OPTION="--connect" ;;
+    pgprs) [ -z "$OPTION" ] && OPTION="--setup" ;;
 esac
-
-while [ "$OPTION" ]; do
- OPT=$OPTION; OPTION=''
- case "$OPT" in
-  -s|--setup)
-   if [ -z "$(busybox pidof pgprs-connect)" ] \
-     && flock --exclusive --nonblock $GPRS_SETUP_LOCK_FD; then #lock setup
-    /usr/local/pgprs/pgprs-setup
-    [ $? -eq 2 -a -z "$(busybox pidof pgprs-connect)" ] \
-     && OPTION='--connect'
-    flock --unlock $GPRS_SETUP_LOCK_FD #unlock setup
-   else
-    if [ -n "$(busybox pidof pgprs-setup)" -o -n "$(busybox pidof pgprs-connect)" ]; then
-     Xdialog --center --wmclass pgprs --title "Pgprs $(gettext 'GPRS Setup')" --icon $ICONLIB/error.xpm --msgbox "\n$(gettext 'PGPRS cannot start now because it is already active.')\n\n$(gettext 'Please use the active PGPRS session.')\n" 0 70
-    elif [ -n "$(busybox pidof frisbee-main)" ]; then
-     Xdialog --center --wmclass pgprs --title "Pgprs $(gettext 'GPRS Setup')" --icon $ICONLIB/error.xpm --ok-label "OK" --cancel-label $(gettext 'Retry') --yesno "\n$(gettext 'PGPRS cannot start now because the Frisbee network manager is active.')\n\n$(gettext 'If you terminate Frisbee, you can Retry PGPRS.')\n" 0 70
-     [ $? -eq 1 ] && OPTION='--setup' #1 = retry
-    else #stale lock - delete, recreate and retry
-     rm -f /var/lock/gprs/setup
-     eval exec "$GPRS_SETUP_LOCK_FD>/var/lock/gprs/setup"
-     echo "basename $0: Stale 'setup' lock detected and replaced" 1>&2
-     OPTION='--setup'
-    fi
-   fi
-   ;;
-  -c|--connect)
-   #If no setup in place, do it now...
-   . /root/.config/gprs.conf
-   if [ "$GPRSDEV" -a "$GPRSNBR" -a "$GPRSAPN" ]; then
-    if flock --exclusive --nonblock $GPRS_CONNECT_LOCK_FD; then #lock if no dialog active
-     /usr/local/pgprs/pgprs-connect
-     [ $? -eq 0 -a -z "$(busybox pidof pgprs-setup)" ] \
-      && OPTION='--setup'
-     flock --unlock $GPRS_CONNECT_LOCK_FD #unlock connect
-    elif [ -n "$(busybox pidof pgprs-connect)" -o -n "$(busybox pidof frisbee-gprs-connect)" ]; then
-     Xdialog --center --wmclass pgprs --title "Pgprs $(gettext 'GPRS Connect')" --icon $ICONLIB/info.xpm --msgbox "\n$(eval_gettext "Modem device '\$GPRSDEV' connection window is active.")\n\n$(gettext 'Please go to the active GPRS Connection Log window.')\n" 0 70
-    else #stale lock - delete, recreate and retry
-     rm -f /var/lock/gprs/connect
-     eval exec "$GPRS_CONNECT_LOCK_FD>/var/lock/gprs/connect"
-     echo "basename $0: Stale 'connect' lock detected and replaced" 1>&2
-     OPTION='--connect'
-    fi
-   else
-    OPTION='--setup'
-   fi
-   ;;
-  -d|--disconnect)
-   if [ -s /var/run/ppp-gprs.pid ];then
-    disconnect_gprs
-   fi
-   ;;
-  -v|--version)
-		echo "$VERSION"
-		;;
- *) echo "$(gettext 'Usage: pgprs [option]')
+case "$OPTION" in
+    -s|--setup|-c|--connect|-d|--disconnect) ;;
+    -v|--version) echo "$VERSION"; exit ;;
+    *) echo "$(gettext 'Usage: pgprs [option]')
  
 $(gettext 'Manage 3G/GPRS network connections')
 
@@ -107,8 +29,61 @@ $(gettext 'Options'):
   -d, --disconnect  $(gettext 'Disconnect from active GPRS network')
   -v, --version     $(gettext 'Display pgprs version')
   -h, --help        $(gettext 'Display this help and exit')
-"
-   ;;
- esac
+"; exit ;;
+esac
+
+[ -f /root/.config/gprs.conf ] \
+  || echo -e "GPRSDEV=\nGPRSAPN=\nGPRSNBR=\nGPRSPIN=\nGPRSUSER=\nGPRSPAPONLY=" > /root/.config/gprs.conf
+mkdir -p /tmp/.pgprs
+export ICONLIB=/usr/local/lib/X11/pixmaps
+if [ -f /usr/share/pixmaps/pgprs.svg ]; then
+    export PGPRSICON=/usr/share/pixmaps/pgprs.svg
+else
+    export PGPRSICON=/usr/share/pixmaps/pgprs.png
+fi
+
+function disconnect_gprs {
+    local GPRS_PPPD_PID
+    local CONNECTED_DEVICE
+    GPRS_PPPD_PID="$(cat /var/run/ppp-gprs.pid 2>/dev/null)"
+    if [ -n "$GPRS_PPPD_PID" ]; then
+# shellcheck disable=SC2034 # Variable used in gettext message
+        CONNECTED_DEVICE="$(pgrep -ax 'pppd' | grep -w "^$GPRS_PPPD_PID" | grep -o '/dev/[^ ]*')"
+        kill "$GPRS_PPPD_PID"
+        sleep 0.1 #200607
+        rm -f /var/run/ppp-gprs.pid
+        gtkdialog-splash -timeout 10 -placement center -bg orange -text "$(eval_gettext "Modem device \$CONNECTED_DEVICE disconnected")"
+    fi
+}
+
+while [ "$OPTION" ]; do
+    OPT=$OPTION; OPTION=''
+    case "$OPT" in
+      -s|--setup)
+        if pgrep -x 'pgprs' | grep -qwv "$$"; then #200622...
+            Xdialog --center --wmclass pgprs --title "$(gettext 'Pgprs GPRS Setup')" --icon $ICONLIB/error.xpm --ok-label "$(gettext 'OK')" --msgbox "\n$(gettext 'PGPRS cannot start now because it is already active.')\n\n$(gettext 'Please use the active PGPRS session.')\n" 0 70
+            exit
+        fi
+        /usr/local/pgprs/pgprs-setup
+        STATUS=$? #200611...
+        [ $STATUS -eq 2 ] && OPTION='--connect'
+        [ $STATUS -eq 0 ] || [ $STATUS -eq 2 ] && which connectwizard_exec >/dev/null 2>&1 \
+          && connectwizard_exec pgprs
+        ;;
+      -c|--connect)
+        #If no setup in place, do it now...
+        . /root/.config/gprs.conf
+        if [ "$GPRSDEV" ] && [ "$GPRSNBR" ] && [ "$GPRSAPN" ]; then
+            /usr/local/pgprs/pgprs-connect && OPTION='--setup' #0 = configure, 1 = done, 255 = abort
+        else
+            OPTION='--setup'
+        fi
+        ;;
+      -d|--disconnect)
+        if [ -s /var/run/ppp-gprs.pid ]; then
+            disconnect_gprs
+        fi
+        ;;
+    esac
 done
 exit 0
diff --git a/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs-connect b/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs-connect
--- a/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs-connect
+++ b/woof-code/rootfs-packages/pgprs/usr/local/pgprs/pgprs-connect
@@ -1,10 +1,12 @@
-#!/bin/sh
+#!/bin/bash
+# shellcheck disable=SC1091 # Skip sourced checks.
 #120131 rodin.s: internationalized.
 #130505 rerwin: ensure network_tray icon shows wireless modem
 #130812 rerwin: Modification as version 1.5 for Puppy integration
 #151222 rerwin: Add device name to 'not detected' message
 #160116 rerwin: restore display of current connection; disconnect network if resolveconf absent.
 #180720 Revert 130505 -- network_tray ignores.
+#200607 (v3.0) Correct display of connect log to work around Xdialog regression; correct not-connected logic; make pppd detach after connection; specify busybox microcom because full version interprets -t as "work in telnet mode" instead of timeout; add version to window title; prevent running if pgprs or frisbee connect window active; replace pidof with ps -C; complete internationalization; accommodate busybox 'tail'; resolve shellcheck warnings.
 
 . /root/.config/gprs.conf #130812...
 
@@ -14,100 +16,151 @@ export TEXTDOMAIN=pgprs
 export OUTPUT_CHARSET=UTF-8
 . gettext.sh
 
+CONNECTLOG=/tmp/.gprs_connect.log #200607
+
 # connect
 function connect_func () {
-	export TEXTDOMAIN=pgprs
-	export OUTPUT_CHARSET=UTF-8
-	. gettext.sh
-	echo -e "$(eval_gettext "Attempting connection through \$GPRSDEV to APN \$GPRSAPN...\n")" #130812
-	if [ ! -x /usr/sbin/resolvconf ];then #160116...
-	 if [ -x /usr/sbin/networkdisconnect ];then #but not ppp interface.
-	  /usr/sbin/networkdisconnect
-	 else 
-	  [ -n "$(busybox pidof wpa_supplicant)" ] \
-	   && wpa_cli terminate #kills any running wpa_supplicant
-	  if [ -x /etc/rc.d/rc.network ];then 
-	   /etc/rc.d/rc.network stop
-	  else
-	   dhcpcd -k
-	  fi
-	 fi
-	fi
-	[ -e /dev/ppp ] || mknod /dev/ppp c 108 0
-	# Start PPP daemon...
-	# For sanity, keep a lock on the serial line (lock).
-	logger "pgprs: $(eval_gettext "Starting PPP daemon for \$GPRSDEV")"
-	/usr/sbin/pppd $GPRSDEV \
-	 call gprs-generated \
-	 connect "chat -v -T $GPRSNBR -f /etc/ppp/chatscripts/gprs-connect-chat" \
-	 disconnect "chat -v -s -S -f /etc/ppp/chatscripts/gprs-disconnect-chat" \
-	 linkname gprs \
-	 nodetach \
-	 lock
-	local STATUS=$?
-	echo "$(eval_gettext "Exit status is \$STATUS")" #130812
-	echo "$(gettext 'DISCONNECTED')"
-	logger "pgprs: $(eval_gettext "pppd exit status for \$GPRSDEV is \$STATUS")"
-	exit $STATUS
+    export TEXTDOMAIN=pgprs
+    export OUTPUT_CHARSET=UTF-8
+    . gettext.sh
+    echo -e "$(eval_gettext "Attempting connection through \$GPRSDEV to APN \$GPRSAPN...")\n" >> $CONNECTLOG #130812 200607
+    if [ ! -x /usr/sbin/resolvconf ]; then #160116...
+        if [ -x /usr/sbin/networkdisconnect ]; then #but not ppp interface.
+            /usr/sbin/networkdisconnect
+        else
+            ps -C wpa_supplicant >/dev/null \
+              && wpa_cli terminate #kills any running wpa_supplicant #200607
+            if [ -x /etc/rc.d/rc.network ]; then
+                /etc/rc.d/rc.network stop
+            else
+                dhcpcd -k
+            fi
+        fi
+    fi
+    [ -e /dev/ppp ] || mknod /dev/ppp c 108 0
+    # Start PPP daemon...
+    # For sanity, keep a lock on the serial line (lock).
+    logger "pgprs: $(eval_gettext "Starting PPP daemon for \$GPRSDEV")"
+    /usr/sbin/pppd "$GPRSDEV" \
+      call gprs-generated \
+      connect "chat -v -T $GPRSNBR -f /etc/ppp/chatscripts/gprs-connect-chat" \
+      disconnect "chat -v -s -S -f /etc/ppp/chatscripts/gprs-disconnect-chat" \
+      linkname gprs \
+      updetach \
+      lock \
+      >> $CONNECTLOG 2>&1 #200607
+    local STATUS=$?
+# shellcheck disable=SC2005 # echo needed for newline.
+    echo "$(eval_gettext "Exit status is \$STATUS")" >> $CONNECTLOG #130812 200607
+    logger "pgprs: $(eval_gettext "pppd exit status for \$GPRSDEV is \$STATUS")"
+    if [ -s /var/run/ppp-gprs.pid ]; then #200607...
+# shellcheck disable=SC2005 # echo needed for newline.
+        echo "$(gettext 'CONNECTED')" >> $CONNECTLOG
+    else
+# shellcheck disable=SC2005 # echo needed for newline.
+        echo "$(gettext 'NOT CONNECTED')" >> $CONNECTLOG
+    fi
+    sleep 2 #Let connection_dialog_func show the entire log before stopping the feed.
+    TAILPID="$(pgrep -f "tail -f $CONNECTLOG")"
+    [ -n "$TAILPID" ] && kill "$TAILPID"
+    exit $STATUS
 }
 export -f connect_func
 
 #160116 connect dialog...
 function connection_dialog_func () {
-	local DISCSTOP="$(gettext 'DISCONNECT')"
-	Xdialog --center --wmclass pgprs --title "Pgprs $(gettext 'GPRS Connection Log')" --backtitle "$(eval_gettext "NOTICE: If log shows a failure to connect, click '\$DISCSTOP', to exit.")" --ok-label "$DISCSTOP or stop trying" --cancel-label "$(gettext 'CLOSE window but stay online')" --fixed-font --tailbox /tmp/.gprs_connect.log 25 82
-	local STATUS=$?
-	if [ $STATUS -eq 0 -a -s /var/run/ppp-gprs.pid ];then
-		PPPDPID=$(cat /var/run/ppp-gprs.pid)
-		if [ "$PPPDPID" ];then
-			kill $PPPDPID
-			rm -f /var/run/ppp-gprs.pid
-			gtkdialog-splash -timeout 15 -placement center -bg orange -text "$(eval_gettext "Mobile device \$GPRSDEV disconnected")"
-		fi
-	fi
-	return $STATUS
+    local READLOG='cat' #200607...
+    local TAIL_PATH
+    TAIL_PATH="$(which tail)"
+    if [ -n "$CONNECT_PID" ] && [ -n "$TAIL_PATH" ]; then
+        if [ -L "$TAIL_PATH" ]; then #busybox tail, cannot follow (-f)
+            gtkdialog-splash -timeout 10 -placement center -bg orange -text "$(eval_gettext "Attempting connection to APN \$GPRSAPN.")  $(gettext 'Please wait.')" &
+            sleep 10
+        else
+            READLOG="tail -f"
+        fi
+    fi
+    $READLOG $CONNECTLOG | \
+      Xdialog --center --wmclass pgprs --title "$(eval_gettext "Pgprs \$VERSION - GPRS Connection Log")" --backtitle "$(gettext 'NOTICE: If log shows a failure to connect, click DISCONNECT to exit.')" --ok-label "$(gettext 'DISCONNECT or stop trying')" --cancel-label "$(gettext 'CLOSE window but stay online')" --logbox - 25 82
+    local STATUS=$? #0 = disconnect/stop, 1 = close but stay connected, 255 = abort
+    if [ $STATUS -eq 0 ] && [ -s /var/run/ppp-gprs.pid ]; then #200607 end
+        local GPRS_PPPD_PID=$(cat /var/run/ppp-gprs.pid)
+        if [ -n "$GPRS_PPPD_PID" ]; then
+            kill "$GPRS_PPPD_PID"
+            sleep 0.1 #200607
+            rm -f /var/run/ppp-gprs.pid
+            gtkdialog-splash -timeout 15 -placement center -bg orange -text "$(eval_gettext "Mobile device \$GPRSDEV disconnected")"
+        fi
+    fi
+    # Return 0 = configure/setup, 1 = done, 255 = abort #200607...
+    [ $STATUS -ne 0 ] && return $STATUS
+    Xdialog --center --wmclass pgprs --title "$(gettext 'Pgprs GPRS Connect')" --icon "$ICONLIB/info.xpm" --ok-label "$(gettext 'Yes')" --cancel-label "$(gettext 'No')" --yesno "\n$(gettext 'Not connected.')\n\n$(gettext 'Return to configuration setup window?')\n" 10 60
+    return $?
 }
 
+while true; do #200607...
+    if pgrep -f 'pgprs --connect' | grep -qwv "$PPID"; then
+        Xdialog --center --wmclass pgprs --title "$(gettext 'Pgprs GPRS Connect')" --icon "$ICONLIB/error.xpm" --ok-label "$(gettext 'Configure')" --cancel-label "$(gettext 'Retry')" --yesno "\n$(gettext 'PGPRS cannot start now because a Pgprs Connection window is already active.')\n\n$(gettext 'If you terminate the connection, you can Retry connecting.')\n\n$(gettext "Otherwise, you can go to Setup or use 'X' to exit.")\n" 0 70
+        STATUS=$? #0 = configure, 1 = retry, 255 = abort
+        [ $STATUS -eq 1 ] && continue || exit $STATUS
+    elif pgrep -f 'frisbee --connect-gprs' >/dev/null; then
+        Xdialog --center --wmclass pgprs --title "$(gettext 'Pgprs GPRS Connect')" --icon "$ICONLIB/error.xpm" --ok-label "$(gettext 'OK')" --cancel-label "$(gettext 'Retry')" --yesno "\n$(gettext 'PGPRS cannot start now because Frisbee mobile wireless (GPRS) is active.')\n\n$(gettext 'If you terminate the Frisbee connection, you can Retry connecting.')\n" 0 70
+        STATUS=$? #0 = configure, 1 = retry, 255 = abort
+        [ $STATUS -eq 1 ] && continue
+        [ $STATUS -eq 0 ] && exit 1 || exit $STATUS
+    else break
+    fi
+done
+
 #160116...
-if [ -f /var/run/ppp-gprs.pid ];then
-	connection_dialog_func
-	exit $? #0 = disonnect/stop, 1 = close but stay connected, 255 = abort
+if [ -s /var/run/ppp-gprs.pid ]; then
+    GPRS_PPPD_PID="$(grep -ow '[0-9]*' /var/run/ppp-gprs.pid)" #200607...
+    #Kill connection if not for current device.
+    if pgrep -ax 'pppd' | grep -w "^$GPRS_PPPD_PID" | grep -qv "$GPRSDEV"; then
+        kill "$GPRS_PPPD_PID"
+        rm -f /var/run/ppp-gprs.pid
+    fi
+    CONNECT_PID=''
+    connection_dialog_func
+    exit $? #0 = configure/setup, 1 = done, 255 = abort
 fi #160116 end
 
 echo "#Generated by pgprs-connect" > /etc/ppp/peers/gprs-generated
 echo "call gprs-editable" >> /etc/ppp/peers/gprs-generated
-if [ "$GPRSUSER" ];then #130812
-	echo -e "auth\nuser $GPRSUSER" >> /etc/ppp/peers/gprs-generated
-	[ "$GPRSPAPONLY" = "true" ] \
-	 && echo "require-pap" >> /etc/ppp/peers/gprs-generated
+if [ "$GPRSUSER" ]; then #130812
+    echo -e "auth\nuser $GPRSUSER" >> /etc/ppp/peers/gprs-generated
+    [ "$GPRSPAPONLY" = "true" ] \
+     && echo "require-pap" >> /etc/ppp/peers/gprs-generated
 else
-	echo "noauth" >> /etc/ppp/peers/gprs-generated
+    echo "noauth" >> /etc/ppp/peers/gprs-generated
 fi
 
-[ "${GPRSPIN}" != "" -a "${GPRSPIN}" != "gprspin" ] \
- && SAVEVAL="AT+CPIN=\"$GPRSPIN\"" \
- || SAVEVAL="AT"
-[ "$SAVEVAL" != "$(cat /etc/ppp/chatscripts/gprs-cpin_command 2>/dev/null | grep -v ^\')" ] \
+[ -n "${GPRSPIN}" ] && [ "${GPRSPIN}" != "gprspin" ] \
+  && SAVEVAL="AT+CPIN=\"$GPRSPIN\"" \
+  || SAVEVAL="AT"
+[ "$SAVEVAL" != "$(grep -v "^'" < /etc/ppp/chatscripts/gprs-cpin_command)" ] \
  && echo "$SAVEVAL" > /etc/ppp/chatscripts/gprs-cpin_command #130812 end
 SAVEVAL="AT+CGDCONT=1,\"IP\",\"$GPRSAPN\""
-[ "$SAVEVAL" != "$(cat /etc/ppp/chatscripts/gprs-cgdcont_command 2>/dev/null | grep -v ^\')" ] \
- && echo "$SAVEVAL" > /etc/ppp/chatscripts/gprs-cgdcont_command
-SAVEVAL="ATD$GPRSNBR"
-[ "$SAVEVAL" != "$(cat /etc/ppp/chatscripts/gprs-dial_command 2>/dev/null | grep -v ^\')" ] \
- && echo "$SAVEVAL" > /etc/ppp/chatscripts/gprs-dial_command
+[ "$SAVEVAL" != "$(grep -v "^'" < /etc/ppp/chatscripts/gprs-cgdcont_command)" ] \
+  && echo "$SAVEVAL" > /etc/ppp/chatscripts/gprs-cgdcont_command
 
-if [ -c $GPRSDEV ] \
- && echo ATZ | microcom -t 200 $GPRSDEV 2>/dev/null | grep -q 'ATZ'; then #130812 151224 160104
-	echo -n > /tmp/.gprs_connect.log
-	connect_func 2>&1 > /tmp/.gprs_connect.log &
-	if [ $? -eq 0 ];then
-		connection_dialog_func #160116
-		exit $? #0 = disonnect/stop, 1 = close but stay connected, 255 = abort
-	else
-		Xdialog --center --wmclass pgprs --title "Pgprs $(gettext 'GPRS Connection Log')" --backtitle "\n$(gettext 'The attempt to connect was unsuccessful:')\n" --ok-label "$(gettext 'Configure')" --cancel-label $(gettext 'Close') --fixed-font --tailbox /tmp/.gprs_connect.log 25 82
-	fi
+if [ -c "$GPRSDEV" ] \
+  && echo ATZ | busybox microcom -t 200 "$GPRSDEV" 2>/dev/null | grep -q 'ATZ'; then #130812 151224 160104
+    echo -n > $CONNECTLOG
+    connect_func & #200607
+# shellcheck disable=SC2181 # status test necessary due to '&' above.
+    if [ $? -eq 0 ]; then
+        CONNECT_PID=$! #200607
+        connection_dialog_func #160116
+        # Returns 0 = configure/setup, 1 = done, 255 = abort #200607...
+        STATUS=$? #200607
+    else
+        Xdialog --center --wmclass pgprs --title "$(gettext 'Pgprs GPRS Connect')" --backtitle "\n$(gettext 'The attempt to connect was unsuccessful:')\n" --ok-label "$(gettext 'Configure')" --cancel-label "$(gettext 'Close')" --logbox $CONNECTLOG 25 82
+        STATUS=$? #200607
+    fi
 else
-	Xdialog --center --wmclass pgprs --title "Pgprs $(gettext 'GPRS Connect')" --icon $ICONLIB/error.xpm --ok-label "$(gettext 'Configure')" --cancel-label $(gettext 'Close') --yesno "\n$(gettext 'Cannot connect.')\n\n$(eval_gettext "Modem device '\$GPRSDEV' is not accessable")\n$(gettext 'It might not be plugged in.')\n" 10 60
+    Xdialog --center --wmclass pgprs --title "$(gettext 'Pgprs GPRS Connect')" --icon "$ICONLIB/error.xpm" --ok-label "$(gettext 'Configure')" --cancel-label "$(gettext 'Close')" --yesno "\n$(gettext 'Cannot connect.')\n\n$(eval_gettext "Modem device '\$GPRSDEV' is not accessable")\n$(gettext 'It might not be plugged in.')\n" 10 60
+    STATUS=$? #200607
 fi
-STATUS=$?
-exit $STATUS #0 = Configure, 1 = Cancel, 255 = abort
+#STATUS: #0 = configure/setup, 1 = done, 255 = abort #200607
+exit $STATUS
