drive_all: move rox stuff to frontend_rox_funcs

diff --git a/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_rox_funcs b/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_rox_funcs
--- a/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_rox_funcs
+++ b/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_rox_funcs
@@ -13,6 +13,21 @@ export TEXTDOMAIN=pup_event_frontend_d
 export OUTPUT_CHARSET=UTF-8
 . gettext.sh
 
+#===================================================================
+# precaution
+
+if [ -z "$DISPLAY" ] ; then
+	[ -f /var/local/shared/x_display ] && . /var/local/shared/x_display
+	export DISPLAY
+fi
+
+if [ "$USER_ID" = "" ] ; then
+	[ -f /tmp/services/user_info ] && . /tmp/services/user_info
+	export PATH HOME LANG USER
+fi
+
+#===================================================================
+
 roxfiler_R() {
 	if [ "$USER" = "root" -o "$USER" = "" ] ; then
 		roxfiler -R
@@ -35,18 +50,9 @@ EOF
 	chmod +x /tmp/pup_event_frontend/drive_${dev}/AppRun
 }
 
-# precaution
-if [ -z "$DISPLAY" ] ; then
-	[ -f /var/local/shared/x_display ] && . /var/local/shared/x_display
-	export DISPLAY
-fi
-if [ "$USER_ID" = "" ] ; then
-	[ -f /tmp/services/user_info ] && . /tmp/services/user_info
-	export PATH HOME LANG USER
-fi
-
-#------------------------------------------------------------
+#===================================================================
 #v403 change desktop icon to unmounted status, called from pup_event_frontend_d, pmount...
+
 rox_icon_unmounted_func() {
  [ "$ROX_DESKTOP" != "yes" ] && return
  #passed params: drivename category  ex: sda usbdrv
@@ -395,7 +401,7 @@ rox_mount() {
   [ -e /tmp/pup_event_frontend/drive_${DEVNAME} ] && DRVNAME="$DEVNAME" #icon for each partition.
   if [ -e /tmp/pup_event_frontend/drive_${DRVNAME} ];then
     DRV_CATEGORY="`probedisk /dev/${xDRVNAME} | cut -f 2 -d '|'`"
-    rox_icon_mounted_func $DRVNAME $DRV_CATEGORY #see frontend_rox_funcs
+    rox_icon_mounted_func $DRVNAME $DRV_CATEGORY #see frontend_funcs
   fi
  fi
 }
@@ -415,10 +421,10 @@ rox_umount() {
    if [ "`mount-FULL -v | tr -s ' ' | cut -f 1,3 -d ' ' | grep "$drvPATTERN" | grep -v ' /initrd/' | grep -v ' /$'`" = "" ];then
     if [ "`mount-FULL -v | tr -s ' ' | cut -f 1,3 -d ' ' | grep "$drvPATTERN" | grep -E ' /initrd/| /$'`" != "" ];then
      #only a partition left mntd that is in use by puppy, change green->yellow...
-     rox_icon_mounted_func $DRVNAME $DRV_CATEGORY #see frontend_rox_funcs
+     rox_icon_mounted_func $DRVNAME $DRV_CATEGORY #see frontend_funcs
     else
      #redraw icon without "MNTD" text...
-     rox_icon_unmounted_func $DRVNAME $DRV_CATEGORY #see frontend_rox_funcs
+     rox_icon_unmounted_func $DRVNAME $DRV_CATEGORY #see frontend_funcs
     fi
    fi
   fi
@@ -436,7 +442,7 @@ rox_mount_luks() {
   [ -e /tmp/pup_event_frontend/drive_${DEVNAME} ] && DRVNAME="$DEVNAME" #icon for each partition.
   if [ -e /tmp/pup_event_frontend/drive_${DRVNAME} ];then
     DRV_CATEGORY="`probedisk "/dev/${xDRVNAME} " | cut -f 2 -d '|'`"
-    rox_icon_mounted_func $DRVNAME $DRV_CATEGORY crypto_LUKS #see frontend_rox_funcs
+    rox_icon_mounted_func $DRVNAME $DRV_CATEGORY crypto_LUKS #see frontend_funcs
   fi
  fi
 }
@@ -464,6 +470,161 @@ rox_umount_luks() {
    fi
   fi
 }
+
+
+
+
+#===================================================================
+#            DRIVE_ALL (see /usr/local/bin/drive_all)
+#===================================================================
+
+unmount_func() {
+	sync
+	while [ 1 ]
+	do
+		umount.crypto_LUKS "$MNTPT" || umount "$MNTPT"
+		umVAL=$?
+		#fix zombie process prevents partition unmount, invisible to fuser...
+		if [ $umVAL -ne 0 ];then
+			#120129 karl godt: fix ZOMBIES, see http://murga-linux.com/puppy/viewtopic.php?t=71767&start=420 ...
+			ZOMBIES="`ps -H -A | grep '<defunct>' | sed 's/^[[:blank:]]*//;s/  /|/g' | grep -v '|||' | cut -f 1 -d ' ' | tr '\n' ' '`"
+			for ONEZOMBIE in $ZOMBIES
+			do
+				echo "Killing parentless zombie process $ONEZOMBIE"
+				kill $ONEZOMBIE
+			done
+			umount $MNTPT ; umVAL=$?
+		fi
+		#rare ocassion, partition got unmounted before umount runs above...
+		mount | grep -q "${MNTPT} " || umVAL=0 #not mounted
+		if [ $umVAL -ne 0 ];then
+			EXTRAMSG0="`fuser -v -m $MNTPT`"  
+			if [ "$EXTRAMSG0" = "" ];then
+				/usr/lib/gtkdialog/box_ok "$(gettext 'Puppy drive manager')" error  "$(gettext 'FAILURE! In the case of removable media, the most
+common reason is the media is not currently inserted.
+If so, please remedy.')"
+			else
+				xmessage -bg "#ff99ff" -title "$(gettext 'Puppy drive manager: FAIL')" -center -buttons "$(gettext 'KILL')":10,"$(gettext 'EXIT')":20 "$(gettext 'FAILURE!')
+$(gettext 'One or more processes (programs) are currently
+using the partition. Here they are:')
+${EXTRAMSG0}
+
+$(gettext "If you press the 'KILL' button, Puppy will attempt to
+kill the offending programs for you. Only do this as a
+last resort.")
+$(gettext "Firstly you should try to close the programs
+manually, so do not press 'KILL'.")
+$(gettext "PLEASE PRESS THE 'EXIT' BUTTON!")"
+				if [ $? -eq 10 ];then
+					fuser -k -m $MNTPT
+					continue
+				fi
+			fi
+		else
+			[ "$DRV_CATEGORY" = "optical" ]  && eject /dev/$ONEDRVNAME
+		fi
+		break
+	done
+}
+
+#
+# drive_all
+#
+rox_desktop_icon_clicked() {
+	ONEDRVNAME="$1" # /tmp/pup_event_frontend/drive_<ONEDRVNAME>/AppRun
+	PARAM1="$2"
+	FSTYPE="$3"
+	#--------------------------------------------------------------------
+	#   detect if have clicked on a close-box of mounted partition...
+	#--------------------------------------------------------------------
+	#when left-click desktop icon, param1 passed this script: drive|card|floppy|optical|usbdrv
+	# and param2 has the fs type...
+	case $PARAM1 in drive|card|floppy|optical|usbdrv)
+	  MNTPT="`mount | grep -m1 -E "^/dev/${ONEDRVNAME} |^/dev/mapper/lukspartition_${ONEDRVNAME} " | tr -s ' ' | cut -f 3 -d ' '`"
+	  if [ "$MNTPT" ];then
+	   read CURPOSX CURPOSY <<< `getcurpos`
+	   #get coords of desktop icon...
+	   drPTN=">/tmp/pup_event_frontend/drive_${ONEDRVNAME}<"
+	   PPENTRY="`grep "$drPTN" /root/Choices/ROX-Filer/PuppyPin`"
+	   if [ "$PPENTRY" ];then
+		xleft="`echo -n "$PPENTRY" | grep -o ' x="[0-9]*"' | cut -f 2 -d '"'`" #'geany
+		ytop="`echo -n "$PPENTRY" | grep -o ' y="[0-9]*"' | cut -f 2 -d '"'`" #'geany
+		#hmmm, have to apply correction to cursor position...
+		CURPOSX=$(($CURPOSX + 24))
+		CURPOSY=$(($CURPOSY + 32))
+		xcloseleft=$(($xleft + 35)) #close-box is 13x13 pixels, want bigger pickup area.
+		xcloseright=$(($xleft + 53))
+		yclosetop=$(($ytop - 5))
+		yclosebottom=$(($ytop + 13))
+		if [ $CURPOSX -ge $xcloseleft ];then
+		 if [ $CURPOSX -le $xcloseright ];then
+		  if [ $CURPOSY -ge $yclosetop ];then
+		   if [ $CURPOSY -le $yclosebottom ];then
+		    PARAM1="unmount"
+		   fi
+		  fi
+		 fi
+		fi
+	   fi
+	  fi
+	 ;;
+	esac
+
+	# rox right-clik menu items...
+	case "${PARAM1}" in
+		unmount)
+			# "Unmount drive [if currently mounted]"
+			MNTPT="`mount | grep -m1 -E "^/dev/${ONEDRVNAME} |^/dev/mapper/lukspartition_${ONEDRVNAME} " | tr -s ' ' | cut -f 3 -d ' '`"
+			if [ -e /sys/block/${ONEDRVNAME}  ] ; then
+				DRV_CATEGORY=$(probedisk $ONEDRVNAME | cut -d'|' -f 2)
+				[ "$MNTPT" = "" -a "$DRV_CATEGORY" = "optical" ] && eject /dev/$ONEDRVNAME
+			fi
+			[ "$MNTPT" = "" ] && exit #precaution.
+			if [ "$MNTPT" = "/" -o "`echo "$MNTPT" | grep '/initrd/'`" != "" ];then
+				/usr/lib/gtkdialog/box_ok "$(gettext 'Puppy drive manager')" error  "$(eval_gettext "/dev/\${ONEDRVNAME} mounted on \${MNTPT}
+is in use by Puppy. You cannot unmount it.")"
+				exit
+			fi
+			unmount_func
+			exit
+			;;
+		pmount_*)
+			# "Run Pmount Puppy Drive Mounter"
+			DRV_CATEGORY="`echo -n "${PARAM1}" | cut -f 2 -d '_'`"
+			if [ "`pidof gtkdialog_pmount`" != "" ];then #if pmount running, kill it.
+				killall gtkdialog_pmount 2>/dev/null
+				sleep 0.1
+			fi
+			exec pmount $ONEDRVNAME
+			exit
+			;;
+		unmountall)
+			# "Unmount ALL mounted partitions"
+			for MNTPT in `mount | grep '^/dev/' | grep -vE '^/dev/loop|^/dev/ram' | cut -f 3 -d ' ' | grep -v '^/initrd/' | grep -v '^/$' | tr '\n' ' '`
+			do
+				unmount_func
+			done
+			exit
+			;;
+		eventmanager)
+			# "Run Desktop Drive Icon Manager"
+			exec eventmanager desktop
+			exit
+			;;
+	esac
+
+	#see /etc/eventmanager
+	# ICONPARTITIONS=false - ICONDESK=false
+	if [ "$ONEDRVNAME" = "drives" ];then
+		if [ "`pidof gtkdialog_pmount`" != "" ];then #if pmount running, kill it.
+			killall gtkdialog_pmount 2>/dev/null
+			sleep 0.1
+		fi
+		exec pmount
+	fi
+}
+
+#===================================================================
 
 if [ "$1" ] ; then
 	$@
