frontend_change: only exit with error code if probepart or probedisk fails

diff --git a/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_change b/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_change
--- a/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_change
+++ b/woof-code/rootfs-skeleton/usr/local/pup_event/frontend_change
@@ -13,6 +13,7 @@
 if [ "$FCDEBUG" = "1" ] ; then
 	exec &>>/tmp/${0##*/}.log
 	echo -e "\n================ $(date) ===================\n"
+	echo -e "$0 $@\n"
 	set -x ; env #debug
 fi
 
@@ -28,7 +29,7 @@ fi
 
 . /etc/eventmanager #has RAMSAVEINTERVAL, HOTPLUGNOISY, BACKENDON, POWERTIMEOUT
 if [ "$HOTPLUGON" != "true" -o "$BACKENDON" != "true" -o "$ICONDESK" != "true" ] ; then
-	exit 1
+	exit
 fi
 
 #==========================================================
@@ -39,7 +40,7 @@ fi
 . /var/shared/x_display
 if [ -z "$DISPLAY" -o -z "$PATH" ] ; then
 	echo "${0}: ERROR: empty "'$DISPLAY or $PATH'
-	exit 1
+	exit 3
 fi
 
 #---------------------------------
@@ -48,10 +49,14 @@ export DISPLAY PATH HOME LANG USER
 
 if fx_drv_is_optical ${DEV_NAME} ; then
 	FC_OPTICAL_DRV=1
-	[ "$ACTION" = "add" -a ! -e /sys/block/${DEV_NAME} ] && exit 1
+	if [ "$ACTION" = "add" -a ! -e /sys/block/${DEV_NAME} ] ; then
+		exit
+	fi
 else
 	case $ACTION in add|change)
-		[ ! -e /sys/block/${DEV_NAME} ] && exit 1 ;;
+		if [ ! -e /sys/block/${DEV_NAME} ] ; then
+			exit
+		fi ;;
 	esac
 fi
 
@@ -105,11 +110,18 @@ case $ACTION in
 		fi
 
 		PROBEDISK="$(probedisk -plus-size $DRV_NAME)"
+		if [ -z "$PROBEDISK" ] ; then
+			logger -s "PROBEDISK FAILED"
+			exit 1
+		fi
+
 		IFS="|" read -r DEV DRV_CATEGORY DRV_DESCRIPTION DRV_SIZE zz <<< "$PROBEDISK"
 
 		if [ "$ICONPARTITIONS" = "true" ] ; then
 			PROBEPART="`probepart -k -extra-info zzFRONTEND_CHANGE "${DRV_NAME}*"`"
-			[ -z "$PROBEPART" ] && exit 1
+			if [ -z "$PROBEPART" ] ; then
+				exit 2
+			fi
 		fi
 
 		#'startup' param just prevents func from running 'probepart'...
@@ -129,7 +141,11 @@ case $ACTION in
 		;;
 
 	remove)
-		[ ! -e /tmp/pup_event_frontend/drive_${DEV_NAME} ] && exit #desktop icon (and partitions) already removed.
+
+		if [ ! -e /tmp/pup_event_frontend/drive_${DEV_NAME} ] ; then
+			exit #desktop icon (and partitions) already removed.
+		fi
+
 		if [ "`pidof gtkdialog_pmount`" != "" ];then #if pmount running, refresh it.
 			killall gtkdialog_pmount 2>/dev/null
 			sleep 0.1
@@ -139,5 +155,7 @@ case $ACTION in
 		rm -rf /tmp/pup_event_frontend/drive_${DEV_NAME}* 2>/dev/null
 		;;
 esac
+
+exit 0
 
 ### END ###
