99-notify: misc edits

diff --git a/woof-code/rootfs-skeleton/lib/dhcpcd/dhcpcd-hooks/99-notify b/woof-code/rootfs-skeleton/lib/dhcpcd/dhcpcd-hooks/99-notify
--- a/woof-code/rootfs-skeleton/lib/dhcpcd/dhcpcd-hooks/99-notify
+++ b/woof-code/rootfs-skeleton/lib/dhcpcd/dhcpcd-hooks/99-notify
@@ -1,48 +1,49 @@
 #Notify user of interface state changes
 
+case "$reason" in
+	BOUND|REBOOT|STATIC|CARRIER|RELEASE|NOCARRIER|IPV4LL|TIMEOUT|FAIL) ok=1;;
+	*) exit ;;
+esac
+
+[ -f /etc/dhcpcd_state_notify ] || exit
+
 pidof X || exit
 
-display_notice()
-{
-	export DISPLAY=:0
-	export TEXTDOMAIN=dhcpcd_notify
-	export OUTPUT_CHARSET=UTF-8
-	. gettext.sh
-	case "$reason" in
+export DISPLAY=:0
+export TEXTDOMAIN=dhcpcd_notify
+export OUTPUT_CHARSET=UTF-8
+
+case "$reason" in
 	BOUND|REBOOT|STATIC) #up
 		PLACEMENT="bottom"
 		BG="green"
-		MSG="`eval_gettext \"\\\$new_ip_address acquired on \\\$interface\"`"
+		MSG="$(printf "$(gettext '%s acquired on %s')" "$new_ip_address" "$interface")"
 		;;
 	CARRIER) #ifup
 		ssid="$(wpa_cli -i $interface status 2>/dev/null | grep ^ssid | cut -f 2 -d =)"
 		PLACEMENT="bottom-left"
 		BG="orange"
-		MSG="`eval_gettext \"Requesting IP address for \\\$interface \\\$ssid\"`"
+		MSG="$(printf "$(gettext 'Requesting IP address for %s %s')" "$interface" "$ssid")"
 		;;
 	RELEASE) #release
 		PLACEMENT=bottom
 		BG=orange
-		MSG="`eval_gettext \"Releasing \\\$interface\"`"
+		MSG="$(printf "$(gettext 'Releasing %s')" "$interface")"
 		;;
 	NOCARRIER) #down
 		PLACEMENT="bottom"
 		BG="hotpink"
-		MSG="`eval_gettext \"\\\$interface is down\"`"
+		MSG="$(printf "$(gettext '%s is down')" "$interface")"
 		;;
 	IPV4LL|TIMEOUT|FAIL) #timeout
 		PLACEMENT="bottom"
 		BG="red"
-		MSG= "`eval_gettext \"IP address request failed on \\\$interface\"`"
+		MSG="$(printf "$(gettext 'IP address request failed on %s')" "$interface")"
 		;;
-	esac
-
-	if [ "$MSG" ] ; then
-		gtkdialog-splash -placement $PLACEMENT -timeout 4 -bg $BG -text "$MSG"
-	fi
-}
-
-case "$reason" in BOUND|REBOOT|STATIC|CARRIER|RELEASE|NOCARRIER|IPV4LL|TIMEOUT|FAIL)
-	[ -f /etc/dhcpcd_state_notify ] && display_notice ;;
 esac
 
+if [ "$MSG" ] ; then
+	gtkdialog-splash -placement $PLACEMENT -timeout 4 -bg $BG -text "$MSG"
+fi
+
+### END ###
