Pupdial: To version 2.1; rc.shutdown: conditional modemdisconnect

diff --git a/woof-code/rootfs-packages/pupdial/usr/local/pupdial/modem_functions b/woof-code/rootfs-packages/pupdial/usr/local/pupdial/modem_functions
--- a/woof-code/rootfs-packages/pupdial/usr/local/pupdial/modem_functions
+++ b/woof-code/rootfs-packages/pupdial/usr/local/pupdial/modem_functions
@@ -9,10 +9,14 @@ chat_with_modem() {
 	local COMMAND=$1 DEVICE=$2
 	rm -f $ANSWERFILE
 	if which microcom &>/dev/null; then
-		if [ -f "/var/lock/LCK..${DEVICE##*/}" ] ; then
-			rm -f "/var/lock/LCK..${DEVICE##*/}"
+		local MCTIMEOUT=200 #v2.0.1...
+		[ -f "/var/lock/LCK..${DEVICE##*/}" ] \
+		 && rm -f "/var/lock/LCK..${DEVICE##*/}"
+		if ! echo -e "${COMMAND}\r" | microcom -t $MCTIMEOUT $DEVICE > $ANSWERFILE; then
+			#When microcom fails, waiting and retrying succeeds.
+			usleep 10
+			echo -e "${COMMAND}\r" | microcom -t $MCTIMEOUT $DEVICE > $ANSWERFILE
 		fi
-		echo -e "${COMMAND}\r" | microcom -t 200 $DEVICE > $ANSWERFILE 2>/dev/null
 		[ -s $ANSWERFILE ] && grep -q '^OK' $ANSWERFILE && return 0
 	fi
 	if which modem-stats &>/dev/null \
@@ -27,26 +31,18 @@ chat_with_modem() {
 		done
 		kill $MSPID 2>/dev/null
 	elif which microcom &>/dev/null; then
-		if [ -f "/var/lock/LCK..${DEVICE##*/}" ] ; then
-			rm -f "/var/lock/LCK..${DEVICE##*/}"
-		fi
-		#Determine time needed to get response + 0.1 sec.
+		[ -f "/var/lock/LCK..${DEVICE##*/}" ] \
+		 && rm -f "/var/lock/LCK..${DEVICE##*/}" #v2.0.1
 		for MCTIMEOUT in 2000 5000 7000; do
-			if echo -e "${COMMAND}\r" | microcom -t $MCTIMEOUT $DEVICE > $ANSWERFILE 2>/dev/null; then
-				if grep -q '^OK' $ANSWERFILE; then
-					MCTIMEOUT=$(($MCTIMEOUT + 100))
-					break
-				fi
-			else
-				unset MCTIMEOUT
-				break
-			fi
+			echo -e "${COMMAND}\r" | microcom -t $MCTIMEOUT $DEVICE > $ANSWERFILE \
+			 && grep -q '^OK' $ANSWERFILE \
+			 && break #v2.0.1
 		done
 	fi
 	[ -s $ANSWERFILE ] && grep -q '^OK' $ANSWERFILE
 	return $?
 }
-export function chat_with_modem
+export -f chat_with_modem
 
 #Set default initialization strings
 #Used by modemtest & modemprobe_erase.
@@ -70,4 +66,4 @@ reset_to_default_func() {
  done
  mv -f /tmp/wvdial.conf-reset /etc/wvdial.conf
 }
-export function reset_to_default_func
+export -f reset_to_default_func
